import type { Metadata } from "next";
import Link from "next/link";
import { guides } from "@/lib/guides";

export const metadata: Metadata = {title:"Mohammad Qasim — Founder and Editor",description:"About Mohammad Qasim, the founder and editor responsible for SolvePilot's Pakistan-focused calculators and guides.",alternates:{canonical:"/author/mohammad-qasim/"}};

export default function AuthorPage(){
  const jsonLd={"@context":"https://schema.org","@type":"Person",name:"Mohammad Qasim",jobTitle:"Founder and Editor",worksFor:{"@type":"Organization",name:"SolvePilot"},url:"https://solvepilot.xyz/author/mohammad-qasim/"};
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><div className="shell prose-page author-page"><div className="author-profile"><span>MQ</span><div><span className="eyebrow">Founder and editor</span><h1>Mohammad Qasim</h1><p>Karachi, Pakistan</p></div></div><p>Mohammad Qasim created SolvePilot to make everyday calculations easier to understand, particularly when Pakistan-specific assumptions, units and costs are involved. He plans the tools, reviews their user experience and maintains the site's content and calculation standards.</p><p>His work combines web development with practical research. Calculator pages are designed to show the formula, editable inputs, worked examples and limitations instead of presenting an unexplained number as fact.</p><h2>Review approach</h2><p>For topics that can change—such as taxes, electricity tariffs, banking terms and device registration—official authorities and other primary sources are preferred. Dates and limitations are displayed so readers know when an estimate needs independent confirmation.</p><p>AI may assist with drafting, code and research organisation, but it is not treated as an authority. Pages are checked for usefulness, formula consistency, understandable wording and honest limitations before publication.</p><h2>Published guides</h2><div className="author-guides">{guides.map(guide=><Link href={`/guides/${guide.slug}/`} key={guide.slug}><span>{guide.icon}</span><b>{guide.title}</b></Link>)}</div><h2>Corrections</h2><p>If you find a reproducible formula, source or content issue, include the page URL and the inputs used when contacting us. Confirmed material errors are corrected and the review date is updated.</p><div className="author-actions"><Link className="primary-button" href="/guides/">Read the guides <span>→</span></Link><Link className="secondary-button" href="/contact/">Report an issue</Link></div></div></>;
}
