import type {Metadata} from "next";
import Link from "next/link";
import {generatorTools} from "@/lib/generator-tools";
import {productivityTools} from "@/lib/productivity-tools";
import {creatorTools} from "@/lib/creator-tools";

const allTools=[...generatorTools,...productivityTools,...creatorTools];
export const metadata:Metadata={title:"Free Online Generators for Work, Study and Creators",description:"Use 48 free tools for QR codes, documents, careers, study and social content. Private browser processing with no signup or external AI request.",alternates:{canonical:"/generator-tools/"},openGraph:{title:"Free Online Generators for Work, Study and Creators",description:"Use 48 free browser generators without signup or server-side storage.",url:"/generator-tools/",type:"website",images:[{url:"/og-image.png",width:1732,height:909,alt:"SolvePilot generator tools"}]}};
export default function GeneratorToolsPage(){
 const groups=["QR & Barcode","Business Documents","Career Tools","Student & Office","Social & Creator"] as const;
 const schema={"@context":"https://schema.org","@type":"CollectionPage",name:"Free Online Generators for Work, Study and Creators",description:"Private browser-based generators for codes, documents, career tasks, study, office and social content.",url:"https://solvepilot.xyz/generator-tools/",mainEntity:{"@type":"ItemList",itemListElement:allTools.map((t,i)=>({"@type":"ListItem",position:i+1,name:t.title,url:"https://solvepilot.xyz/generator-tools/"+t.slug+"/"}))}};
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="shell pdf-directory"><span className="eyebrow">Phase 6 · Everyday generators</span><h1>Free generators for work, study and creators</h1><p className="pdf-lead">Create scannable codes, practical PDFs, career drafts, office materials and social-content ideas without registration. Supported processing happens inside your browser, so entered information stays on your device.</p><div className="pdf-trust-row"><span>🔒 Private processing</span><span>✓ No signup</span><span>✓ No external AI request</span><span>✓ 48 focused tools</span></div>{groups.map(group=><section key={group}><h2>{group}</h2><div className="pdf-card-grid">{allTools.filter(t=>t.category===group).map(t=><Link href={"/generator-tools/"+t.slug+"/"} key={t.slug}><span>{t.icon}</span><div><h3>{t.shortTitle}</h3><p>{t.description}</p><small>{"kind" in t?(t.kind==="document"?"Create PDF":"Create or scan code"):"Create result"}</small></div></Link>)}</div></section>)}<section className="pdf-seo-copy"><h2>Useful generators without an account</h2><p>These tools cover common needs across QR codes, barcodes, business records, job applications, study, office administration and content creation. Each generator has a dedicated URL, clear instructions, privacy notes and practical limitations.</p><h2>Review before professional or public use</h2><p>Test codes, proofread documents, confirm calculations and verify content claims before sharing. Generated material is a practical starting point and does not replace legal, accounting, employment, academic or advertising guidance.</p><div className="accuracy-note"><b>Privacy note:</b> Form values, selected images and content ideas are processed in your browser and are not submitted to SolvePilot servers.</div></section></div></>
}
