"use client";
import {useState} from "react";
import type {ArchiveTool as Tool} from "@/lib/archive-tools";
const zipUrl="https://cdn.jsdelivr.net/npm/@zip.js/zip.js@2.7.57/+esm";
const archiveUrl="https://cdn.jsdelivr.net/npm/libarchive.js@2.0.2/main.js";
const save=(blob:Blob,name:string)=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)};
const flatten=(value:any,prefix="",out:{name:string;file:File|Blob}[]=[]):{name:string;file:File|Blob}[]=>{if(value instanceof File||value instanceof Blob)out.push({name:prefix||("file"+(value instanceof File?"-"+value.name:"")),file:value});else if(value&&typeof value==="object")for(const [key,item] of Object.entries(value))flatten(item,prefix?prefix+"/"+key:key,out);return out};
export function ArchiveTool({tool}:{tool:Tool}){const multi=/create|password/.test(tool.slug),[files,setFiles]=useState<File[]>([]),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[level,setLevel]=useState(6),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[message,setMessage]=useState(""),[entries,setEntries]=useState<string[]>([]);
 const makeZip=async(items:{name:string;file:File|Blob}[],encrypted=false)=>{const zip:any=await import(/* webpackIgnore: true */ zipUrl),writer=new zip.ZipWriter(new zip.BlobWriter("application/zip"),encrypted?{password,encryptionStrength:3}:{});let i=0;for(const item of items){await writer.add(item.name,new zip.BlobReader(item.file),{level,password:encrypted?password:undefined,encryptionStrength:encrypted?3:undefined});setProgress(Math.round(++i/items.length*90))}return writer.close() as Promise<Blob>};
 const run=async()=>{setBusy(true);setProgress(2);setMessage("");setEntries([]);try{if(!files.length)throw new Error("Choose the required file or files first.");if(files.some(f=>f.size>100*1024*1024))throw new Error("For reliable browser processing, use files below 100 MB each.");
  if(tool.slug==="create-zip-file"||tool.slug==="password-protect-zip-file"){if(tool.slug.includes("password")){if(password.length<8)throw new Error("Use a password containing at least 8 characters.");if(password!==confirm)throw new Error("The password confirmation does not match.")}const blob=await makeZip(files.map(f=>({name:(f as any).webkitRelativePath||f.name,file:f})),tool.slug.includes("password"));save(blob,tool.slug.includes("password")?"protected-files.zip":"created-files.zip");setProgress(100);setMessage("Done — the ZIP file was created and downloaded locally.");return}
  if(tool.slug==="extract-zip-file"){const zip:any=await import(/* webpackIgnore: true */ zipUrl),reader=new zip.ZipReader(new zip.BlobReader(files[0]),password?{password}:{}),found=await reader.getEntries();setEntries(found.filter((x:any)=>!x.directory).map((x:any)=>x.filename));const extracted:{name:string;file:Blob}[]=[];for(const entry of found)if(!entry.directory)extracted.push({name:entry.filename,file:await entry.getData(new zip.BlobWriter(),password?{password}:undefined)});await reader.close();if(!extracted.length)throw new Error("No extractable files were found in this ZIP.");save(await makeZip(extracted),"extracted-files.zip");setProgress(100);setMessage("Done — contents were extracted and downloaded in a new ZIP.");return}
  const mod:any=await import(/* webpackIgnore: true */ archiveUrl),Archive=mod.Archive||mod.default?.Archive||mod.default;if(!Archive)throw new Error("The archive engine could not start in this browser.");Archive.init?.({workerUrl:"https://cdn.jsdelivr.net/npm/libarchive.js@2.0.2/dist/worker-bundle.js"});const archive=await Archive.open(files[0]),tree=await archive.extractFiles(),found=flatten(tree);if(!found.length)throw new Error("No supported files could be extracted from this archive.");setEntries(found.map(x=>x.name));save(await makeZip(found),tool.slug==="tar-gz-extractor"?"tar-gz-extracted.zip":tool.slug.startsWith("rar")?"converted-rar.zip":"converted-7z.zip");setProgress(100);setMessage("Done — supported contents were packaged as ZIP and downloaded.");
 }catch(e){setMessage(e instanceof Error?e.message:"The archive could not be processed.")}finally{setBusy(false)}};
 return <section className="document-workbench"><div className="privacy-pill">🔒 Archive stays on this device</div><div className="wasm-note"><b>Local processing:</b> large or highly compressed archives can use several times their file size in browser memory. Keep the original and use desktop software for unsupported archives.</div><label className="document-drop"><input type="file" accept={tool.accept} multiple={multi} {...(multi?({webkitdirectory:undefined} as any):{})} onChange={e=>setFiles(Array.from(e.target.files||[]))}/><b>{files.length?files.length+" file(s) selected":"Choose "+(multi?"files":"an archive")}</b><span>{files.length?files.map(f=>f.name).join(", "):"Tap to browse · recommended maximum 100 MB per file"}</span></label>{/create|password/.test(tool.slug)&&<label className="document-field"><span>Compression level: {level}</span><input type="range" min="0" max="9" value={level} onChange={e=>setLevel(+e.target.value)}/><small>0 is fastest; 9 aims for a smaller archive.</small></label>}{/password|extract-zip/.test(tool.slug)&&<label className="document-field"><span>{tool.slug.includes("extract")?"Password, if required":"Password"}</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label>}{tool.slug.includes("password")&&<label className="document-field"><span>Confirm password</span><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label>}<button className="pdf-action" disabled={busy||!files.length} onClick={run}>{busy?"Processing on your device… "+progress+"%":tool.shortTitle}</button>{busy&&<div className="media-progress"><span style={{width:progress+"%"}}/></div>}{message&&<p className={"pdf-message "+(message.startsWith("Done")?"success":"")} role="status">{message}</p>}{entries.length>0&&<div className="document-preview"><b>{entries.length} extracted entries</b><ul>{entries.slice(0,30).map(x=><li key={x}>{x}</li>)}</ul>{entries.length>30&&<p>And {entries.length-30} more…</p>}</div>}<small className="pdf-legal">Only process files you own or are authorized to access. This tool does not discover or bypass unknown passwords.</small></section>}
