"use client";
import { useMemo, useState } from "react";

const n = (value: string) => Math.max(0, Number(value) || 0);
const money = (value: number) => new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", maximumFractionDigits: 0 }).format(value);

type Result = { label: string; value: string; note?: string };

function Field({ label, value, onChange, suffix }: { label: string; value: string; onChange: (v: string) => void; suffix?: string }) {
  return <label className="field"><span>{label}</span><div><input inputMode="decimal" value={value} onChange={(e)=>onChange(e.target.value)} aria-label={label}/>{suffix && <b>{suffix}</b>}</div></label>;
}

export function Calculator({ slug }: { slug: string }) {
  const defaults: Record<string,[string,string,string,string?]> = {
    "electricity-bill-calculator-pakistan":["250","18","12"], "solar-system-calculator-pakistan":["600","5.2","580"],
    "salary-tax-calculator-pakistan":["150000","0","0"], "pta-tax-calculator-pakistan":["500","278","15"],
    "ev-vs-petrol-calculator-pakistan":["50","40","265"], "daraz-profit-calculator-pakistan":["3000","1500","12"],
    "percentage-calculator":["20","5000","0"], "cgpa-percentage-calculator-pakistan":["3.2","25","0"],
    "loan-emi-calculator-pakistan":["1000000","18","5"], "fuel-cost-calculator-pakistan":["450","13","265"],
    "battery-backup-calculator-pakistan":["300","150","12"], "inverter-load-calculator-pakistan":["800","25","0.8"],
    "profit-margin-calculator":["2000","1400","0"], "discount-calculator-pakistan":["8000","25","0"],
    "attendance-percentage-calculator":["36","50","75"], "marks-percentage-calculator-pakistan":["735","1100","40"],
    "freelance-hourly-rate-calculator-pakistan":["200000","100","30000"], "paint-quantity-calculator-pakistan":["1000","2","120"],
    "appliance-electricity-cost-calculator-pakistan":["1200","6","55"], "generator-fuel-cost-calculator-pakistan":["4","1.5","280"],
    "ac-tonnage-calculator-pakistan":["180","10","65"], "water-tank-volume-calculator-pakistan":["6","4","4"],
    "tile-quantity-calculator-pakistan":["200","24","24"], "concrete-volume-calculator-pakistan":["5","4","10"],
    "download-time-calculator":["20","50","90"], "mobile-data-usage-calculator-pakistan":["1","0.7","8"],
    "compound-interest-calculator-pakistan":["500000","10","5"], "savings-goal-calculator-pakistan":["600000","120000","24"],
    "monthly-investment-calculator-pakistan":["20000","10","5"], "loan-affordability-calculator-pakistan":["50000","18","5"],
    "credit-card-payoff-calculator-pakistan":["200000","15000","30"], "emergency-fund-calculator-pakistan":["90000","6","150000"],
    "salary-increment-calculator-pakistan":["100000","12","0"], "business-break-even-calculator-pakistan":["300000","2000","1200"],
    "solar-battery-size-calculator-pakistan":["600","4","24"], "solar-panel-output-calculator-pakistan":["5","5.2","80"],
    "solar-payback-calculator-pakistan":["1200000","30000","20000"], "ac-electricity-cost-calculator-pakistan":["1500","8","55"],
    "battery-charging-time-calculator-pakistan":["150","20","20"], "watts-amps-volts-calculator":["1000","230","0.9"],
    "rent-affordability-calculator-pakistan":["150000","75000","30"], "debt-to-income-calculator-pakistan":["200000","55000","0"],
    "freelance-project-quote-calculator-pakistan":["40","2500","20"], "sales-commission-calculator-pakistan":["800000","3","10000"],
    "50-30-20-budget-calculator-pakistan":["120000","50","20"], "salary-to-hourly-rate-calculator-pakistan":["100000","26","8"],
    "solar-ac-calculator-pakistan":["1500","6","5.2"], "ups-charging-cost-calculator-pakistan":["150","12","80","55"],
    "generator-size-calculator-pakistan":["3000","1500","25"], "solar-panel-series-parallel-calculator":["49","11","6","2"],
    "solar-roof-area-calculator-pakistan":["1000","28","580"], "solar-load-calculator-pakistan":["80","6","8"],
  };
  const initial = defaults[slug] || ["20","5000","0"];
  const [a,setA]=useState(initial[0]);
  const [b,setB]=useState(initial[1]);
  const [c,setC]=useState(initial[2]);
  const [d,setD]=useState(initial[3] || "0");
  const [calculated,setCalculated]=useState(true);

  const config = useMemo(() => {
    if(slug==="electricity-bill-calculator-pakistan") return { labels:["Monthly units","Average energy rate","Taxes & surcharges"], suffix:["units","PKR/unit","%"], calculate:()=>{const base=n(a)*n(b);const tax=base*n(c)/100;return [{label:"Estimated monthly bill",value:money(base+tax),note:"Planning estimate"},{label:"Energy charges",value:money(base)},{label:"Taxes & surcharges",value:money(tax)}]}};
    if(slug==="solar-system-calculator-pakistan") return { labels:["Monthly electricity usage","Peak sun hours per day","Panel wattage"], suffix:["units","hours","W"], calculate:()=>{const kw=(n(a)/30)/(n(b)*.8||1);const panels=Math.ceil(kw*1000/(n(c)||580));const generation=kw*n(b)*30*.8;return [{label:"Recommended system",value:`${kw.toFixed(1)} kW`,note:`About ${panels} × ${n(c)}W panels`},{label:"Estimated generation",value:`${Math.round(generation)} units/mo`},{label:"Roof area guide",value:`${Math.ceil(panels*28)} sq ft`} ]}};
    if(slug==="salary-tax-calculator-pakistan") return { labels:["Gross monthly salary","Monthly allowances","Other monthly deduction"], suffix:["PKR","PKR","PKR"], calculate:()=>{const annual=(n(a)+n(b))*12;let tax=0;if(annual>600000) tax=(Math.min(annual,1200000)-600000)*.01;if(annual>1200000) tax=6000+(Math.min(annual,2200000)-1200000)*.11;if(annual>2200000) tax=116000+(Math.min(annual,3200000)-2200000)*.23;if(annual>3200000) tax=346000+(Math.min(annual,4100000)-3200000)*.30;if(annual>4100000) tax=616000+(annual-4100000)*.35;const monthly=tax/12;const effective=annual?tax/annual*100:0;return [{label:"Estimated take-home",value:money(n(a)+n(b)-monthly-n(c)),note:`Annual gross ${money(annual)} · effective tax ${effective.toFixed(2)}%`},{label:"Estimated monthly tax",value:money(monthly)},{label:"Estimated annual tax",value:money(tax)}]}};
    if(slug.includes("pta")) return { labels:["Phone value","USD to PKR rate","Estimated duty rate"], suffix:["USD","PKR","%"], calculate:()=>{const value=n(a)*n(b);const duty=value*n(c)/100;return [{label:"Estimated PTA duty",value:money(duty),note:"Confirm through official DIRBS assessment"},{label:"Declared PKR value",value:money(value)},{label:"Total after duty",value:money(value+duty)}]}};
    if(slug.includes("ev-")) return { labels:["Daily travel","Petrol vehicle mileage","Petrol price"], suffix:["km","km/l","PKR/l"], calculate:()=>{const distance=n(a)*30;const petrol=distance/(n(b)||1)*n(c);const ev=distance*.035*55;const save=petrol-ev;return [{label:"Estimated monthly saving",value:money(save),note:"EV assumption: 0.035 kWh/km at PKR 55/unit"},{label:"Petrol energy cost",value:money(petrol)},{label:"EV charging cost",value:money(ev)}]}};
    if(slug.includes("daraz")) return { labels:["Selling price","Product cost","Commission rate"], suffix:["PKR","PKR","%"], calculate:()=>{const commission=n(a)*n(c)/100;const profit=n(a)-n(b)-commission;return [{label:"Estimated profit",value:money(profit),note:`${n(a)?(profit/n(a)*100).toFixed(1):0}% net margin before other fees`},{label:"Commission",value:money(commission)},{label:"Break-even price",value:money(n(b)/(1-n(c)/100||1))}]}};
    if(slug.includes("cgpa")) return { labels:["Your CGPA","Institution multiplier","Unused"], suffix:["CGPA","×",""], calculate:()=>[{label:"Estimated percentage",value:`${Math.min(100,n(a)*n(b)).toFixed(2)}%`,note:"Confirm your institution’s official conversion"},{label:"CGPA entered",value:n(a).toFixed(2)},{label:"Multiplier",value:`× ${n(b)}`}]};
    if(slug.includes("loan-emi")) return { labels:["Loan amount","Annual rate","Repayment term"], suffix:["PKR","%","years"], calculate:()=>{const principal=n(a);const months=Math.max(1,Math.round(n(c)*12));const rate=n(b)/1200;const payment=rate?principal*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1):principal/months;const total=payment*months;return [{label:"Estimated monthly instalment",value:money(payment),note:`${months} equal monthly payments`},{label:"Total repayment",value:money(total)},{label:"Financing cost",value:money(total-principal)}]}};
    if(slug==="fuel-cost-calculator-pakistan") return { labels:["Travel distance","Average mileage","Fuel price"], suffix:["km","km/l","PKR/l"], calculate:()=>{const litres=n(a)/(n(b)||1);const cost=litres*n(c);return [{label:"Estimated fuel cost",value:money(cost),note:`About ${litres.toFixed(1)} litres required`},{label:"Fuel required",value:`${litres.toFixed(1)} litres`},{label:"Cost per kilometre",value:money(cost/(n(a)||1))}]}};
    if(slug.includes("battery-backup")) return { labels:["Connected load","Battery capacity","Battery bank voltage"], suffix:["W","Ah","V"], calculate:()=>{const energy=n(b)*n(c);const usable=energy*.8;const hours=usable/(n(a)||1);return [{label:"Estimated backup time",value:`${hours.toFixed(1)} hours`,note:"Uses an 80% combined usable-energy allowance"},{label:"Nominal energy",value:`${Math.round(energy)} Wh`},{label:"Usable estimate",value:`${Math.round(usable)} Wh`}]}};
    if(slug.includes("inverter-load")) return { labels:["Connected running load","Safety headroom","Power factor"], suffix:["W","%","PF"], calculate:()=>{const watts=n(a)*(1+n(b)/100);const va=watts/(n(c)||1);const suggested=Math.ceil(va/250)*250;return [{label:"Suggested minimum inverter",value:`${suggested.toLocaleString("en-PK")} VA`,note:"Verify startup surge before purchase"},{label:"Calculated requirement",value:`${Math.round(va).toLocaleString("en-PK")} VA`},{label:"Load with headroom",value:`${Math.round(watts).toLocaleString("en-PK")} W`}]}};
    if(slug.includes("profit-margin")) return { labels:["Sales revenue","Total direct cost","Unused"], suffix:["PKR","PKR",""], calculate:()=>{const profit=n(a)-n(b);const margin=n(a)?profit/n(a)*100:0;const markup=n(b)?profit/n(b)*100:0;return [{label:"Gross profit",value:money(profit),note:`${margin.toFixed(1)}% gross margin`},{label:"Profit margin",value:`${margin.toFixed(1)}%`},{label:"Markup on cost",value:`${markup.toFixed(1)}%`}]}};
    if(slug.includes("discount")) return { labels:["Original price","Discount rate","Tax or service rate"], suffix:["PKR","%","%"], calculate:()=>{const saved=n(a)*n(b)/100;const sale=n(a)-saved;const final=sale*(1+n(c)/100);return [{label:"Final price",value:money(final),note:n(c)?"After discount and additional rate":"After discount"},{label:"You save",value:money(saved)},{label:"Sale price before extras",value:money(sale)}]}};
    if(slug.includes("attendance")) return { labels:["Classes attended","Total classes held","Target attendance"], suffix:["classes","classes","%"], calculate:()=>{const attended=Math.min(n(a),n(b));const held=n(b);const target=Math.min(99.9,n(c))/100;const current=held?attended/held*100:0;const needed=current>=target*100?0:Math.ceil((target*held-attended)/(1-target));return [{label:"Current attendance",value:`${current.toFixed(2)}%`,note:needed?`Attend the next ${needed} classes to reach ${n(c)}%`:"Target already reached"},{label:"Classes needed",value:needed.toLocaleString("en-PK")},{label:"Classes missed",value:Math.max(0,held-attended).toLocaleString("en-PK")}]}};
    if(slug.includes("marks-percentage")) return { labels:["Marks obtained","Total marks","Passing percentage"], suffix:["marks","marks","%"], calculate:()=>{const percent=n(b)?n(a)/n(b)*100:0;const pass=n(b)*n(c)/100;return [{label:"Percentage score",value:`${percent.toFixed(2)}%`,note:n(a)>=pass?"At or above the entered pass threshold":"Below the entered pass threshold"},{label:"Minimum passing marks",value:Math.ceil(pass).toLocaleString("en-PK")},{label:"Difference from pass",value:`${n(a)>=pass?"+":""}${Math.round(n(a)-pass).toLocaleString("en-PK")}`}]}};
    if(slug.includes("freelance-hourly")) return { labels:["Monthly income target","Monthly billable hours","Monthly business costs"], suffix:["PKR","hours","PKR"], calculate:()=>{const required=n(a)+n(c);const rate=required/(n(b)||1);return [{label:"Required hourly rate",value:money(rate),note:"Before tax and platform/payment fees"},{label:"Monthly revenue needed",value:money(required)},{label:"Daily billable target",value:`${(n(b)/20).toFixed(1)} hours`}]}};
    if(slug.includes("paint-quantity")) return { labels:["Net paintable area","Number of coats","Coverage per litre"], suffix:["sq ft","coats","sq ft/L"], calculate:()=>{const base=n(a)*n(b)/(n(c)||1);const withWaste=base*1.1;return [{label:"Paint to purchase",value:`${Math.ceil(withWaste)} litres`,note:"Includes a 10% allowance"},{label:"Base requirement",value:`${base.toFixed(1)} litres`},{label:"Allowance",value:`${(withWaste-base).toFixed(1)} litres`}]}};
    if(slug.includes("appliance-electricity")) return { labels:["Appliance power","Daily runtime","Effective unit rate"], suffix:["W","hours","PKR/unit"], calculate:()=>{const units=n(a)/1000*n(b)*30;const cost=units*n(c);return [{label:"Estimated monthly cost",value:money(cost),note:`About ${units.toFixed(1)} electricity units`},{label:"Monthly consumption",value:`${units.toFixed(1)} kWh`},{label:"Daily energy",value:`${(n(a)/1000*n(b)).toFixed(2)} kWh`}]}};
    if(slug.includes("generator-fuel")) return { labels:["Daily operating time","Fuel consumption","Fuel price"], suffix:["hours","litres/hour","PKR/litre"], calculate:()=>{const litres=n(a)*n(b);const daily=litres*n(c);return [{label:"Estimated monthly fuel cost",value:money(daily*30),note:"30-day projection before maintenance"},{label:"Daily fuel",value:`${litres.toFixed(1)} litres`},{label:"Daily fuel cost",value:money(daily)}]}};
    if(slug.includes("ac-tonnage")) return { labels:["Room floor area","Ceiling height","Heat-load factor"], suffix:["sq ft","ft","BTU/sq ft"], calculate:()=>{const adjusted=n(a)*(n(b)/9||1);const btu=adjusted*n(c);const tons=btu/12000;const practical=Math.ceil(tons*4)/4;return [{label:"Suggested starting size",value:`${practical.toFixed(2)} ton`,note:"Arrange a professional heat-load check"},{label:"Estimated cooling load",value:`${Math.round(btu).toLocaleString("en-PK")} BTU/h`},{label:"Raw tonnage",value:`${tons.toFixed(2)} ton`}]}};
    if(slug.includes("water-tank")) return { labels:["Internal length","Internal width","Usable depth"], suffix:["ft","ft","ft"], calculate:()=>{const cubic=n(a)*n(b)*n(c);const litres=cubic*28.3168;return [{label:"Estimated tank capacity",value:`${Math.round(litres).toLocaleString("en-PK")} litres`,note:"Rectangular tank using internal dimensions"},{label:"Volume",value:`${cubic.toFixed(1)} cu ft`},{label:"US gallons",value:`${Math.round(litres/3.785).toLocaleString("en-PK")}`}]}};
    if(slug.includes("tile-quantity")) return { labels:["Net surface area","Tile length","Tile width"], suffix:["sq ft","inches","inches"], calculate:()=>{const tileSqFt=n(b)*n(c)/144;const base=n(a)/(tileSqFt||1);const total=Math.ceil(base*1.1);return [{label:"Tiles to purchase",value:total.toLocaleString("en-PK"),note:"Includes a 10% cutting and breakage allowance"},{label:"Base tile count",value:Math.ceil(base).toLocaleString("en-PK")},{label:"Allowance tiles",value:Math.max(0,total-Math.ceil(base)).toLocaleString("en-PK")}]}};
    if(slug.includes("concrete-volume")) return { labels:["Slab length","Slab width","Thickness"], suffix:["metres","metres","cm"], calculate:()=>{const base=n(a)*n(b)*(n(c)/100);const order=base*1.07;return [{label:"Concrete to order",value:`${order.toFixed(2)} m³`,note:"Includes a 7% site allowance"},{label:"Geometric volume",value:`${base.toFixed(2)} m³`},{label:"Allowance",value:`${(order-base).toFixed(2)} m³`}]}};
    if(slug.includes("download-time")) return { labels:["File size","Connection speed","Practical efficiency"], suffix:["GB","Mbps","%"], calculate:()=>{const seconds=n(a)*8000/(n(b)||1)/(n(c)/100||1);const hours=Math.floor(seconds/3600);const minutes=Math.ceil((seconds%3600)/60);return [{label:"Estimated download time",value:hours?`${hours}h ${minutes}m`:`${minutes} minutes`,note:"Assumes a steady average connection"},{label:"Data transferred",value:`${n(a).toFixed(1)} GB`},{label:"Effective speed",value:`${(n(b)*n(c)/100).toFixed(1)} Mbps`}]}};
    if(slug.includes("mobile-data-usage")) return { labels:["Daily streaming time","Streaming data rate","Other monthly usage"], suffix:["hours","GB/hour","GB"], calculate:()=>{const streaming=n(a)*n(b)*30;const total=streaming+n(c);return [{label:"Suggested monthly data",value:`${Math.ceil(total)} GB`,note:"Round up to the next suitable package"},{label:"Streaming data",value:`${streaming.toFixed(1)} GB`},{label:"Other allowance",value:`${n(c).toFixed(1)} GB`}]}};
    if(slug.includes("compound-interest")) return { labels:["Starting investment","Assumed annual return","Investment period"], suffix:["PKR","%","years"], calculate:()=>{const months=Math.round(n(c)*12);const future=n(a)*Math.pow(1+n(b)/1200,months);return [{label:"Projected future value",value:money(future),note:"Monthly compounding before tax, fees and inflation"},{label:"Projected growth",value:money(future-n(a))},{label:"Total return",value:`${n(a)?((future/n(a)-1)*100).toFixed(1):0}%`}]}};
    if(slug.includes("savings-goal")) return { labels:["Savings target","Already saved","Months remaining"], suffix:["PKR","PKR","months"], calculate:()=>{const gap=Math.max(0,n(a)-n(b));const monthly=gap/(n(c)||1);return [{label:"Required monthly saving",value:money(monthly),note:gap?"Assumes equal monthly contributions":"Goal already funded"},{label:"Remaining gap",value:money(gap)},{label:"Progress so far",value:`${n(a)?Math.min(100,n(b)/n(a)*100).toFixed(1):0}%`}]}};
    if(slug.includes("monthly-investment")) return { labels:["Monthly contribution","Assumed annual return","Investment period"], suffix:["PKR","%","years"], calculate:()=>{const months=Math.max(0,Math.round(n(c)*12));const rate=n(b)/1200;const future=rate?n(a)*(Math.pow(1+rate,months)-1)/rate:n(a)*months;const contributed=n(a)*months;return [{label:"Projected future value",value:money(future),note:"End-of-month contributions; not a guaranteed return"},{label:"Total contributed",value:money(contributed)},{label:"Projected growth",value:money(future-contributed)}]}};
    if(slug.includes("loan-affordability")) return { labels:["Affordable monthly payment","Annual reducing rate","Repayment term"], suffix:["PKR","%","years"], calculate:()=>{const months=Math.max(1,Math.round(n(c)*12));const rate=n(b)/1200;const principal=rate?n(a)*(Math.pow(1+rate,months)-1)/(rate*Math.pow(1+rate,months)):n(a)*months;return [{label:"Estimated affordable principal",value:money(principal),note:"Before lender eligibility, fees and insurance"},{label:"Total scheduled payments",value:money(n(a)*months)},{label:"Number of payments",value:months.toLocaleString("en-PK")}]}};
    if(slug.includes("credit-card-payoff")) return { labels:["Current card balance","Fixed monthly payment","Annual finance rate"], suffix:["PKR","PKR","%"], calculate:()=>{const rate=n(c)/1200;const interest=n(a)*rate;if(n(b)<=interest)return [{label:"Payment is too low",value:"Balance will not reduce",note:`First-month interest is about ${money(interest)}`},{label:"Minimum to reduce balance",value:money(interest+1)},{label:"Current payment",value:money(n(b))}];const months=rate?Math.ceil(-Math.log(1-rate*n(a)/n(b))/Math.log(1+rate)):Math.ceil(n(a)/(n(b)||1));const total=n(b)*months;return [{label:"Estimated payoff time",value:`${months} months`,note:"Assumes no new purchases or fees"},{label:"Estimated total paid",value:money(total)},{label:"Estimated finance cost",value:money(Math.max(0,total-n(a)))}]}};
    if(slug.includes("emergency-fund")) return { labels:["Essential monthly expenses","Coverage period","Already reserved"], suffix:["PKR","months","PKR"], calculate:()=>{const target=n(a)*n(b);const gap=Math.max(0,target-n(c));return [{label:"Emergency-fund target",value:money(target),note:`Covers ${n(b)} months of entered expenses`},{label:"Remaining gap",value:money(gap)},{label:"Current coverage",value:`${(n(c)/(n(a)||1)).toFixed(1)} months`}]}};
    if(slug.includes("salary-increment")) return { labels:["Current monthly salary","Increment rate","New monthly allowance"], suffix:["PKR","%","PKR"], calculate:()=>{const increase=n(a)*n(b)/100;const revised=n(a)+increase+n(c);return [{label:"New gross monthly salary",value:money(revised),note:"Before tax and payroll deductions"},{label:"Monthly gross increase",value:money(increase+n(c))},{label:"Annual gross increase",value:money((increase+n(c))*12)}]}};
    if(slug.includes("business-break-even")) return { labels:["Monthly fixed costs","Selling price per unit","Variable cost per unit"], suffix:["PKR","PKR","PKR"], calculate:()=>{const contribution=n(b)-n(c);if(contribution<=0)return [{label:"No break-even point",value:"Price must exceed variable cost",note:"Contribution per unit is zero or negative"},{label:"Current contribution",value:money(contribution)},{label:"Price",value:money(n(b))}];const units=Math.ceil(n(a)/contribution);return [{label:"Break-even sales volume",value:`${units.toLocaleString("en-PK")} units`,note:"Units needed to cover entered fixed costs"},{label:"Break-even revenue",value:money(units*n(b))},{label:"Contribution per unit",value:money(contribution)}]}};
    if(slug.includes("solar-battery-size")) return { labels:["Essential backup load","Required backup time","Battery-bank voltage"], suffix:["W","hours","V"], calculate:()=>{const usable=n(a)*n(b);const nominal=usable/.8;const ah=nominal/(n(c)||1);return [{label:"Estimated battery capacity",value:`${Math.ceil(ah)} Ah`,note:"Uses an 80% combined usable-energy allowance"},{label:"Nominal bank energy",value:`${Math.ceil(nominal)} Wh`},{label:"Usable energy needed",value:`${Math.ceil(usable)} Wh`}]}};
    if(slug.includes("solar-panel-output")) return { labels:["Solar system capacity","Peak sun hours","System efficiency"], suffix:["kW","hours/day","%"], calculate:()=>{const daily=n(a)*n(b)*n(c)/100;return [{label:"Estimated monthly generation",value:`${Math.round(daily*30)} units`,note:"30-day planning estimate"},{label:"Estimated daily generation",value:`${daily.toFixed(1)} units`},{label:"Annualised estimate",value:`${Math.round(daily*365).toLocaleString("en-PK")} units`}]}};
    if(slug.includes("solar-payback")) return { labels:["Total installed cost","Average monthly saving","Annual maintenance"], suffix:["PKR","PKR","PKR/year"], calculate:()=>{const annual=n(b)*12-n(c);const years=annual>0?n(a)/annual:Infinity;return [{label:"Simple payback period",value:Number.isFinite(years)?`${years.toFixed(1)} years`:"No payback",note:"Excludes financing, degradation and replacements"},{label:"Net annual saving",value:money(Math.max(0,annual))},{label:"Five-year net saving",value:money(Math.max(0,annual*5))}]}};
    if(slug.includes("ac-electricity-cost")) return { labels:["Rated electrical input","Daily runtime","Effective unit rate"], suffix:["W","hours","PKR/unit"], calculate:()=>{const units=n(a)/1000*n(b)*30*.7;return [{label:"Estimated monthly AC cost",value:money(units*n(c)),note:"Uses a 70% average-load factor"},{label:"Estimated monthly units",value:`${units.toFixed(1)} kWh`},{label:"Full-load equivalent",value:`${(n(b)*.7).toFixed(1)} hours/day`}]}};
    if(slug.includes("battery-charging-time")) return { labels:["Battery capacity","Charger current","Loss and finish allowance"], suffix:["Ah","A","%"], calculate:()=>{const base=n(a)/(n(b)||1);const total=base*(1+n(c)/100);return [{label:"Estimated charging time",value:`${total.toFixed(1)} hours`,note:"Confirm the battery's safe charging current"},{label:"Ideal base time",value:`${base.toFixed(1)} hours`},{label:"Added allowance",value:`${(total-base).toFixed(1)} hours`}]}};
    if(slug.includes("watts-amps-volts")) return { labels:["Real power","Operating voltage","Efficiency / power factor"], suffix:["W","V","factor"], calculate:()=>{const amps=n(a)/((n(b)||1)*(n(c)||1));return [{label:"Estimated current",value:`${amps.toFixed(2)} A`,note:"Basic single-phase or DC planning estimate"},{label:"Apparent power",value:`${(n(a)/(n(c)||1)).toFixed(0)} VA`},{label:"Ideal unity current",value:`${(n(a)/(n(b)||1)).toFixed(2)} A`}]}};
    if(slug.includes("rent-affordability")) return { labels:["Monthly take-home income","Essential non-rent expenses","Rent guideline"], suffix:["PKR","PKR","%"], calculate:()=>{const percentage=n(a)*n(c)/100;const cash=Math.max(0,n(a)-n(b)-n(a)*.1);const suggested=Math.min(percentage,cash);return [{label:"Suggested maximum rent",value:money(suggested),note:"Uses the lower limit and keeps a 10% income buffer"},{label:"Percentage guideline",value:money(percentage)},{label:"Cash-flow limit",value:money(cash)}]}};
    if(slug.includes("debt-to-income")) return { labels:["Gross monthly income","Monthly debt payments","Unused"], suffix:["PKR","PKR",""], calculate:()=>{const ratio=n(a)?n(b)/n(a)*100:0;return [{label:"Debt-to-income ratio",value:`${ratio.toFixed(1)}%`,note:"A lender may calculate this differently"},{label:"Gross income after debt",value:money(Math.max(0,n(a)-n(b)))},{label:"Annual debt payments",value:money(n(b)*12)}]}};
    if(slug.includes("freelance-project-quote")) return { labels:["Estimated project hours","Hourly value","Scope-risk buffer"], suffix:["hours","PKR/hour","%"], calculate:()=>{const base=n(a)*n(b);const buffer=base*n(c)/100;return [{label:"Recommended project quote",value:money(base+buffer),note:"Before external costs, platform fees and tax"},{label:"Base labour value",value:money(base)},{label:"Risk buffer",value:money(buffer)}]}};
    if(slug.includes("sales-commission")) return { labels:["Eligible net sales","Commission rate","Fixed performance bonus"], suffix:["PKR","%","PKR"], calculate:()=>{const commission=n(a)*n(b)/100;return [{label:"Total incentive",value:money(commission+n(c)),note:"Commission plus entered fixed bonus"},{label:"Percentage commission",value:money(commission)},{label:"Effective incentive rate",value:`${n(a)?((commission+n(c))/n(a)*100).toFixed(2):0}%`}]}};
    if(slug.includes("50-30-20")) return { labels:["Monthly take-home income","Needs allocation","Savings / debt priority"], suffix:["PKR","%","%"], calculate:()=>{const needs=n(a)*n(b)/100;const savings=n(a)*n(c)/100;const wants=Math.max(0,n(a)-needs-savings);return [{label:"Needs budget",value:money(needs),note:`${n(b)}% for essential expenses`},{label:"Wants budget",value:money(wants)},{label:"Savings / debt",value:money(savings)}]}};
    if(slug.includes("salary-to-hourly")) return { labels:["Gross monthly salary","Paid working days","Paid hours per day"], suffix:["PKR","days","hours"], calculate:()=>{const daily=n(a)/(n(b)||1);const hourly=n(a)/((n(b)||1)*(n(c)||1));return [{label:"Gross hourly rate",value:money(hourly),note:"Before deductions and excluding benefits"},{label:"Gross daily rate",value:money(daily)},{label:"Paid monthly hours",value:(n(b)*n(c)).toLocaleString("en-PK")}]}};
    if(slug.includes("solar-ac")) return { labels:["AC electrical input","Daily runtime","Peak sun hours"], suffix:["W","hours","hours/day"], calculate:()=>{const daily=n(a)/1000*n(b);const kw=daily/((n(c)||1)*.8);const panels=Math.ceil(kw*1000/580);return [{label:"Estimated solar array",value:`${kw.toFixed(2)} kW`,note:"Energy-only sizing at 80% system efficiency"},{label:"580 W panels",value:panels.toLocaleString("en-PK")},{label:"Daily AC energy",value:`${daily.toFixed(1)} kWh`}]}};
    if(slug.includes("ups-charging-cost")) return { labels:["Battery capacity","Battery voltage","Capacity to recharge","Electricity unit rate"], suffix:["Ah","V","%","PKR/unit"], calculate:()=>{const stored=n(a)*n(b)*n(c)/100/1000;const grid=stored/.8;return [{label:"Estimated recharge cost",value:money(grid*n(d)),note:"Uses an 80% charging-efficiency assumption"},{label:"Grid energy",value:`${grid.toFixed(2)} kWh`},{label:"Energy stored",value:`${stored.toFixed(2)} kWh`}]}};
    if(slug.includes("generator-size")) return { labels:["Total running load","Largest additional startup surge","Safety headroom"], suffix:["W","W","%"], calculate:()=>{const required=(n(a)+n(b))*(1+n(c)/100);const kva=required/1000/.8;return [{label:"Recommended generator size",value:`${kva.toFixed(1)} kVA`,note:"Uses a 0.8 power-factor assumption"},{label:"Required apparent power",value:`${Math.round(required/.8).toLocaleString("en-PK")} VA`},{label:"Load with headroom",value:`${Math.round(required).toLocaleString("en-PK")} W`}]}};
    if(slug.includes("solar-panel-series-parallel")) return { labels:["One panel voltage","One panel current","Panels in each series string","Parallel strings"], suffix:["V","A","panels","strings"], calculate:()=>{const voltage=n(a)*n(c);const current=n(b)*n(d);const count=n(c)*n(d);return [{label:"Estimated array output",value:`${voltage.toFixed(1)} V / ${current.toFixed(1)} A`,note:"Verify cold Voc and all inverter input limits"},{label:"Total panel count",value:count.toLocaleString("en-PK")},{label:"Approximate DC power",value:`${Math.round(voltage*current).toLocaleString("en-PK")} W`}]}};
    if(slug.includes("solar-roof-area")) return { labels:["Measured roof area","Panel footprint","Panel wattage"], suffix:["sq ft","sq ft","W"], calculate:()=>{const usable=n(a)*.75;const panels=Math.floor(usable/(n(b)||1));return [{label:"Estimated panels that fit",value:panels.toLocaleString("en-PK"),note:"Uses 75% of measured area for preliminary layout"},{label:"Possible array capacity",value:`${(panels*n(c)/1000).toFixed(1)} kW`},{label:"Layout area used",value:`${Math.round(panels*n(b)).toLocaleString("en-PK")} sq ft`}]}};
    if(slug.includes("solar-load")) return { labels:["Appliance power","Quantity","Daily operating time"], suffix:["W","items","hours"], calculate:()=>{const peak=n(a)*n(b);const wh=peak*n(c);return [{label:"Daily energy requirement",value:`${(wh/1000).toFixed(2)} kWh`,note:"Calculate each appliance group and combine totals"},{label:"Peak running load",value:`${Math.round(peak).toLocaleString("en-PK")} W`},{label:"Daily watt-hours",value:`${Math.round(wh).toLocaleString("en-PK")} Wh`}]}};
    return { labels:["Percentage","Value","Unused"], suffix:["%","",""], calculate:()=>[{label:`${n(a)}% of ${n(b)}`,value:(n(a)*n(b)/100).toLocaleString("en-PK"),note:"Instant percentage result"},{label:"Decimal equivalent",value:(n(a)/100).toFixed(4)},{label:"Remaining value",value:(n(b)-n(a)*n(b)/100).toLocaleString("en-PK")}]};
  },[slug,a,b,c,d]);
  const results: Result[] = config.calculate();
  return <section className="calculator-shell" aria-label="Calculator"><div className="calc-inputs"><div className="calc-title"><span>Interactive calculator</span><strong>Your values stay on this device</strong></div><Field label={config.labels[0]} value={a} onChange={setA} suffix={config.suffix[0]}/><Field label={config.labels[1]} value={b} onChange={setB} suffix={config.suffix[1]}/>{config.labels[2]!=="Unused"&&<Field label={config.labels[2]} value={c} onChange={setC} suffix={config.suffix[2]}/>} {config.labels[3]&&<Field label={config.labels[3]} value={d} onChange={setD} suffix={config.suffix[3]}/>}<button className="calculate-button" onClick={()=>{setCalculated(false);requestAnimationFrame(()=>setCalculated(true))}}>Calculate result <span>→</span></button></div><div className={`calc-results ${calculated?"show":""}`}><div className="result-badge">✓ Estimated result</div><p>{results[0].label}</p><h2>{results[0].value}</h2><small>{results[0].note}</small><div className="result-grid">{results.slice(1).map((result)=><div key={result.label}><span>{result.label}</span><strong>{result.value}</strong></div>)}</div><div className="result-meter"><i style={{width:"72%"}}/><span>Personalised from your inputs</span></div></div></section>;
}
