"use client";
import { useMemo, useState } from "react";

const n = (value: string) => Math.max(0, Number(value) || 0);
const money = (value: number) => new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", maximumFractionDigits: 0 }).format(value);

type Result = { label: string; value: string; note?: string };

function Field({ label, value, onChange, suffix }: { label: string; value: string; onChange: (v: string) => void; suffix?: string }) {
  return <label className="field"><span>{label}</span><div><input inputMode="decimal" value={value} onChange={(e)=>onChange(e.target.value)} aria-label={label}/>{suffix && <b>{suffix}</b>}</div></label>;
}

export function Calculator({ slug }: { slug: string }) {
  const defaults: Record<string,[string,string,string,string?]> = {
    "electricity-bill-calculator-pakistan":["250","18","12"], "solar-system-calculator-pakistan":["600","5.2","580"],
    "salary-tax-calculator-pakistan":["150000","0","0"], "pta-tax-calculator-pakistan":["500","278","15"],
    "ev-vs-petrol-calculator-pakistan":["50","40","265"], "daraz-profit-calculator-pakistan":["3000","1500","12"],
    "percentage-calculator":["20","5000","0"], "cgpa-percentage-calculator-pakistan":["3.2","25","0"],
    "loan-emi-calculator-pakistan":["1000000","18","5"], "fuel-cost-calculator-pakistan":["450","13","265"],
    "battery-backup-calculator-pakistan":["300","150","12"], "inverter-load-calculator-pakistan":["800","25","0.8"],
    "profit-margin-calculator":["2000","1400","0"], "discount-calculator-pakistan":["8000","25","0"],
    "attendance-percentage-calculator":["36","50","75"], "marks-percentage-calculator-pakistan":["735","1100","40"],
    "freelance-hourly-rate-calculator-pakistan":["200000","100","30000"], "paint-quantity-calculator-pakistan":["1000","2","120"],
    "appliance-electricity-cost-calculator-pakistan":["1200","6","55"], "generator-fuel-cost-calculator-pakistan":["4","1.5","280"],
    "ac-tonnage-calculator-pakistan":["180","10","65"], "water-tank-volume-calculator-pakistan":["6","4","4"],
    "tile-quantity-calculator-pakistan":["200","24","24"], "concrete-volume-calculator-pakistan":["5","4","10"],
    "download-time-calculator":["20","50","90"], "mobile-data-usage-calculator-pakistan":["1","0.7","8"],
    "compound-interest-calculator-pakistan":["500000","10","5"], "savings-goal-calculator-pakistan":["600000","120000","24"],
    "monthly-investment-calculator-pakistan":["20000","10","5"], "loan-affordability-calculator-pakistan":["50000","18","5"],
    "credit-card-payoff-calculator-pakistan":["200000","15000","30"], "emergency-fund-calculator-pakistan":["90000","6","150000"],
    "salary-increment-calculator-pakistan":["100000","12","0"], "business-break-even-calculator-pakistan":["300000","2000","1200"],
    "solar-battery-size-calculator-pakistan":["600","4","24"], "solar-panel-output-calculator-pakistan":["5","5.2","80"],
    "solar-payback-calculator-pakistan":["1200000","30000","20000"], "ac-electricity-cost-calculator-pakistan":["1500","8","55"],
    "battery-charging-time-calculator-pakistan":["150","20","20"], "watts-amps-volts-calculator":["1000","230","0.9"],
    "rent-affordability-calculator-pakistan":["150000","75000","30"], "debt-to-income-calculator-pakistan":["200000","55000","0"],
    "freelance-project-quote-calculator-pakistan":["40","2500","20"], "sales-commission-calculator-pakistan":["800000","3","10000"],
    "50-30-20-budget-calculator-pakistan":["120000","50","20"], "salary-to-hourly-rate-calculator-pakistan":["100000","26","8"],
    "solar-ac-calculator-pakistan":["1500","6","5.2"], "ups-charging-cost-calculator-pakistan":["150","12","80","55"],
    "generator-size-calculator-pakistan":["3000","1500","25"], "solar-panel-series-parallel-calculator":["49","11","6","2"],
    "solar-roof-area-calculator-pakistan":["1000","28","580"], "solar-load-calculator-pakistan":["80","6","8"],
    "phone-finder-pakistan":["60000","9","6","8"], "phone-comparison-score-calculator":["82","74","88"],
    "mobile-gaming-fps-estimator":["75","85","12"], "phone-value-score-calculator-pakistan":["50000","80","70"],
    "screen-ppi-calculator":["1080","2400","6.67"], "mobile-battery-life-estimator":["5000","600","90"],
    "mobile-charging-time-calculator":["5000","25","35"], "phone-storage-requirement-calculator":["55","35","30","20"],
    "used-phone-condition-score-pakistan":["85","80","100"],
    "annual-to-monthly-salary-calculator-pakistan":["1800000","312","8"], "job-offer-comparison-calculator-pakistan":["130000","140000","12000"],
    "overtime-pay-calculator-pakistan":["600","20","1.5"], "provident-fund-calculator-pakistan":["100000","8","10"],
    "gratuity-calculator-pakistan":["90000","5","30"], "bonus-tax-estimator-pakistan":["200000","20","0"],
    "salary-allowance-calculator-pakistan":["100000","25000","8000"], "freelancer-income-tax-estimator-pakistan":["3000000","600000","5"],
    "sole-proprietor-tax-estimator-pakistan":["5000000","3200000","10"], "withholding-tax-calculator-pakistan":["100000","8","0"],
    "property-tax-estimator-pakistan":["8000000","25","5"],"vehicle-token-tax-estimator-pakistan":["60000","10","2000"],"filer-vs-non-filer-calculator-pakistan":["2000000","2","6"],"capital-gains-tax-estimator-pakistan":["3000000","2200000","15"],
    "islamic-home-finance-calculator-pakistan":["8000000","14","15"],"car-financing-calculator-pakistan":["4000000","30","14","5"],"personal-loan-comparison-calculator-pakistan":["1000000","18","22","3"],"early-loan-payment-calculator-pakistan":["1000000","18","30000","10000"],
    "loan-refinancing-calculator-pakistan":["1000000","18","14","50000"],"credit-card-minimum-payment-calculator-pakistan":["100000","5","2000","0"],"savings-account-profit-calculator-pakistan":["500000","10","15"],"term-deposit-profit-calculator-pakistan":["1000000","11","2"],
    "inflation-calculator-pakistan":["100000","8","5"],"pkr-purchasing-power-calculator":["2000000","8","5"],"retirement-savings-calculator-pakistan":["500000","25000","10","20"],"education-savings-calculator-pakistan":["2000000","8","8","200000"],
    "wedding-budget-calculator-pakistan":["1000000","500000","10","18"],"household-budget-calculator-pakistan":["180000","100000","35000"],"debt-snowball-calculator-pakistan":["60000","15000","24"],"debt-avalanche-calculator-pakistan":["200000","30","15000"],
    "currency-conversion-fee-calculator-pakistan":["1000","280","2","1000"],"remittance-received-calculator-pakistan":["1000","10","280","500"],
    "electricity-slab-rate-calculator-pakistan":["300","100","20","35"],"lesco-bill-calculator-pakistan":["300","35","18"],"iesco-bill-calculator-pakistan":["300","35","18"],"fesco-bill-calculator-pakistan":["300","35","18"],"mepco-bill-calculator-pakistan":["300","35","18"],"gepco-bill-calculator-pakistan":["300","35","18"],"pesco-bill-calculator-pakistan":["300","35","18"],"hesco-bill-calculator-pakistan":["300","35","18"],"sepco-bill-calculator-pakistan":["300","35","18"],"k-electric-bill-calculator-pakistan":["300","38","18"],
    "net-metering-savings-calculator-pakistan":["300","200","55","22"],"solar-export-credit-calculator-pakistan":["500","250","55","22"],"solar-inverter-size-calculator-pakistan":["3000","1500","25","0.8"],"solar-cable-size-estimator-pakistan":["15","20","48","2"],"solar-panel-tilt-angle-calculator-pakistan":["31","15","0"],"solar-generation-by-city-pakistan":["5","5.2","80"],
    "load-shedding-battery-calculator-pakistan":["500","4","24","80"],"lithium-vs-lead-acid-battery-calculator":["5","80","3000","500000"],"ups-runtime-multiple-appliances-calculator":["600","200","24","80"],"electricity-bill-appliance-share-calculator":["1500","4","30","600"],"inverter-vs-non-inverter-ac-savings-calculator-pakistan":["1500","1000","8","55"],"refrigerator-electricity-cost-calculator-pakistan":["180","40","55"],"electric-geyser-cost-calculator-pakistan":["2000","1.5","55"],"ev-charging-cost-calculator-pakistan":["40","90","55","300"],
    "shopify-profit-calculator-pakistan":["5000","2200","3","700"],"amazon-pakistan-seller-profit-calculator":["9000","3800","15","1200"],"foodpanda-restaurant-commission-calculator-pakistan":["2000","25","150","100"],"marketplace-fee-comparison-calculator-pakistan":["4000","12","16","100"],
    "cod-order-profit-calculator-pakistan":["3500","1700","250","100"],"cod-return-loss-calculator-pakistan":["100","20","900","450"],"product-pricing-calculator-pakistan":["1500","30","10"],"wholesale-retail-markup-calculator-pakistan":["1000","40","0"],
    "sales-tax-calculator-pakistan":["10000","18","0"],"inventory-reorder-point-calculator-pakistan":["10","14","50"],"inventory-turnover-calculator-pakistan":["12000000","1800000","2200000"],"import-landed-cost-calculator-pakistan":["5000","280","200000","20"],
    "customs-duty-calculator-pakistan":["1000000","20","18"],"courier-cost-comparison-calculator-pakistan":["100","250","300","40"],"freelancer-platform-fee-calculator-pakistan":["1000","10","15"],"payoneer-withdrawal-calculator-pakistan":["1000","280","3","500"],
    "international-payment-fee-comparison-pakistan":["1000","272","268","500"],"small-business-cash-flow-calculator-pakistan":["300000","800000","650000","50000"],"employee-cost-to-company-calculator-pakistan":["100000","12000","5000","3000"],
  };
  const initial = defaults[slug] || ["20","5000","0"];
  const [a,setA]=useState(initial[0]);
  const [b,setB]=useState(initial[1]);
  const [c,setC]=useState(initial[2]);
  const [d,setD]=useState(initial[3] || "0");
  const [calculated,setCalculated]=useState(true);

  const config = useMemo(() => {
    if(slug==="electricity-bill-calculator-pakistan") return { labels:["Monthly units","Average energy rate","Taxes & surcharges"], suffix:["units","PKR/unit","%"], calculate:()=>{const base=n(a)*n(b);const tax=base*n(c)/100;return [{label:"Estimated monthly bill",value:money(base+tax),note:"Planning estimate"},{label:"Energy charges",value:money(base)},{label:"Taxes & surcharges",value:money(tax)}]}};
    if(slug==="solar-system-calculator-pakistan") return { labels:["Monthly electricity usage","Peak sun hours per day","Panel wattage"], suffix:["units","hours","W"], calculate:()=>{const kw=(n(a)/30)/(n(b)*.8||1);const panels=Math.ceil(kw*1000/(n(c)||580));const generation=kw*n(b)*30*.8;return [{label:"Recommended system",value:`${kw.toFixed(1)} kW`,note:`About ${panels} × ${n(c)}W panels`},{label:"Estimated generation",value:`${Math.round(generation)} units/mo`},{label:"Roof area guide",value:`${Math.ceil(panels*28)} sq ft`} ]}};
    if(slug==="salary-tax-calculator-pakistan") return { labels:["Gross monthly salary","Monthly allowances","Other monthly deduction"], suffix:["PKR","PKR","PKR"], calculate:()=>{const annual=(n(a)+n(b))*12;let tax=0;if(annual>600000) tax=(Math.min(annual,1200000)-600000)*.01;if(annual>1200000) tax=6000+(Math.min(annual,2200000)-1200000)*.11;if(annual>2200000) tax=116000+(Math.min(annual,3200000)-2200000)*.23;if(annual>3200000) tax=346000+(Math.min(annual,4100000)-3200000)*.30;if(annual>4100000) tax=616000+(annual-4100000)*.35;const monthly=tax/12;const effective=annual?tax/annual*100:0;return [{label:"Estimated take-home",value:money(n(a)+n(b)-monthly-n(c)),note:`Annual gross ${money(annual)} · effective tax ${effective.toFixed(2)}%`},{label:"Estimated monthly tax",value:money(monthly)},{label:"Estimated annual tax",value:money(tax)}]}};
    if(slug.includes("pta")) return { labels:["Phone value","USD to PKR rate","Estimated duty rate"], suffix:["USD","PKR","%"], calculate:()=>{const value=n(a)*n(b);const duty=value*n(c)/100;return [{label:"Estimated PTA duty",value:money(duty),note:"Confirm through official DIRBS assessment"},{label:"Declared PKR value",value:money(value)},{label:"Total after duty",value:money(value+duty)}]}};
    if(slug.includes("ev-")) return { labels:["Daily travel","Petrol vehicle mileage","Petrol price"], suffix:["km","km/l","PKR/l"], calculate:()=>{const distance=n(a)*30;const petrol=distance/(n(b)||1)*n(c);const ev=distance*.035*55;const save=petrol-ev;return [{label:"Estimated monthly saving",value:money(save),note:"EV assumption: 0.035 kWh/km at PKR 55/unit"},{label:"Petrol energy cost",value:money(petrol)},{label:"EV charging cost",value:money(ev)}]}};
    if(slug.includes("daraz")) return { labels:["Selling price","Product cost","Commission rate"], suffix:["PKR","PKR","%"], calculate:()=>{const commission=n(a)*n(c)/100;const profit=n(a)-n(b)-commission;return [{label:"Estimated profit",value:money(profit),note:`${n(a)?(profit/n(a)*100).toFixed(1):0}% net margin before other fees`},{label:"Commission",value:money(commission)},{label:"Break-even price",value:money(n(b)/(1-n(c)/100||1))}]}};
    if(slug.includes("cgpa")) return { labels:["Your CGPA","Institution multiplier","Unused"], suffix:["CGPA","×",""], calculate:()=>[{label:"Estimated percentage",value:`${Math.min(100,n(a)*n(b)).toFixed(2)}%`,note:"Confirm your institution’s official conversion"},{label:"CGPA entered",value:n(a).toFixed(2)},{label:"Multiplier",value:`× ${n(b)}`}]};
    if(slug.includes("loan-emi")) return { labels:["Loan amount","Annual rate","Repayment term"], suffix:["PKR","%","years"], calculate:()=>{const principal=n(a);const months=Math.max(1,Math.round(n(c)*12));const rate=n(b)/1200;const payment=rate?principal*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1):principal/months;const total=payment*months;return [{label:"Estimated monthly instalment",value:money(payment),note:`${months} equal monthly payments`},{label:"Total repayment",value:money(total)},{label:"Financing cost",value:money(total-principal)}]}};
    if(slug==="fuel-cost-calculator-pakistan") return { labels:["Travel distance","Average mileage","Fuel price"], suffix:["km","km/l","PKR/l"], calculate:()=>{const litres=n(a)/(n(b)||1);const cost=litres*n(c);return [{label:"Estimated fuel cost",value:money(cost),note:`About ${litres.toFixed(1)} litres required`},{label:"Fuel required",value:`${litres.toFixed(1)} litres`},{label:"Cost per kilometre",value:money(cost/(n(a)||1))}]}};
    if(slug.includes("battery-backup")) return { labels:["Connected load","Battery capacity","Battery bank voltage"], suffix:["W","Ah","V"], calculate:()=>{const energy=n(b)*n(c);const usable=energy*.8;const hours=usable/(n(a)||1);return [{label:"Estimated backup time",value:`${hours.toFixed(1)} hours`,note:"Uses an 80% combined usable-energy allowance"},{label:"Nominal energy",value:`${Math.round(energy)} Wh`},{label:"Usable estimate",value:`${Math.round(usable)} Wh`}]}};
    if(slug.includes("inverter-load")) return { labels:["Connected running load","Safety headroom","Power factor"], suffix:["W","%","PF"], calculate:()=>{const watts=n(a)*(1+n(b)/100);const va=watts/(n(c)||1);const suggested=Math.ceil(va/250)*250;return [{label:"Suggested minimum inverter",value:`${suggested.toLocaleString("en-PK")} VA`,note:"Verify startup surge before purchase"},{label:"Calculated requirement",value:`${Math.round(va).toLocaleString("en-PK")} VA`},{label:"Load with headroom",value:`${Math.round(watts).toLocaleString("en-PK")} W`}]}};
    if(slug.includes("profit-margin")) return { labels:["Sales revenue","Total direct cost","Unused"], suffix:["PKR","PKR",""], calculate:()=>{const profit=n(a)-n(b);const margin=n(a)?profit/n(a)*100:0;const markup=n(b)?profit/n(b)*100:0;return [{label:"Gross profit",value:money(profit),note:`${margin.toFixed(1)}% gross margin`},{label:"Profit margin",value:`${margin.toFixed(1)}%`},{label:"Markup on cost",value:`${markup.toFixed(1)}%`}]}};
    if(slug.includes("discount")) return { labels:["Original price","Discount rate","Tax or service rate"], suffix:["PKR","%","%"], calculate:()=>{const saved=n(a)*n(b)/100;const sale=n(a)-saved;const final=sale*(1+n(c)/100);return [{label:"Final price",value:money(final),note:n(c)?"After discount and additional rate":"After discount"},{label:"You save",value:money(saved)},{label:"Sale price before extras",value:money(sale)}]}};
    if(slug.includes("attendance")) return { labels:["Classes attended","Total classes held","Target attendance"], suffix:["classes","classes","%"], calculate:()=>{const attended=Math.min(n(a),n(b));const held=n(b);const target=Math.min(99.9,n(c))/100;const current=held?attended/held*100:0;const needed=current>=target*100?0:Math.ceil((target*held-attended)/(1-target));return [{label:"Current attendance",value:`${current.toFixed(2)}%`,note:needed?`Attend the next ${needed} classes to reach ${n(c)}%`:"Target already reached"},{label:"Classes needed",value:needed.toLocaleString("en-PK")},{label:"Classes missed",value:Math.max(0,held-attended).toLocaleString("en-PK")}]}};
    if(slug.includes("marks-percentage")) return { labels:["Marks obtained","Total marks","Passing percentage"], suffix:["marks","marks","%"], calculate:()=>{const percent=n(b)?n(a)/n(b)*100:0;const pass=n(b)*n(c)/100;return [{label:"Percentage score",value:`${percent.toFixed(2)}%`,note:n(a)>=pass?"At or above the entered pass threshold":"Below the entered pass threshold"},{label:"Minimum passing marks",value:Math.ceil(pass).toLocaleString("en-PK")},{label:"Difference from pass",value:`${n(a)>=pass?"+":""}${Math.round(n(a)-pass).toLocaleString("en-PK")}`}]}};
    if(slug.includes("freelance-hourly")) return { labels:["Monthly income target","Monthly billable hours","Monthly business costs"], suffix:["PKR","hours","PKR"], calculate:()=>{const required=n(a)+n(c);const rate=required/(n(b)||1);return [{label:"Required hourly rate",value:money(rate),note:"Before tax and platform/payment fees"},{label:"Monthly revenue needed",value:money(required)},{label:"Daily billable target",value:`${(n(b)/20).toFixed(1)} hours`}]}};
    if(slug.includes("paint-quantity")) return { labels:["Net paintable area","Number of coats","Coverage per litre"], suffix:["sq ft","coats","sq ft/L"], calculate:()=>{const base=n(a)*n(b)/(n(c)||1);const withWaste=base*1.1;return [{label:"Paint to purchase",value:`${Math.ceil(withWaste)} litres`,note:"Includes a 10% allowance"},{label:"Base requirement",value:`${base.toFixed(1)} litres`},{label:"Allowance",value:`${(withWaste-base).toFixed(1)} litres`}]}};
    if(slug.includes("appliance-electricity")) return { labels:["Appliance power","Daily runtime","Effective unit rate"], suffix:["W","hours","PKR/unit"], calculate:()=>{const units=n(a)/1000*n(b)*30;const cost=units*n(c);return [{label:"Estimated monthly cost",value:money(cost),note:`About ${units.toFixed(1)} electricity units`},{label:"Monthly consumption",value:`${units.toFixed(1)} kWh`},{label:"Daily energy",value:`${(n(a)/1000*n(b)).toFixed(2)} kWh`}]}};
    if(slug.includes("generator-fuel")) return { labels:["Daily operating time","Fuel consumption","Fuel price"], suffix:["hours","litres/hour","PKR/litre"], calculate:()=>{const litres=n(a)*n(b);const daily=litres*n(c);return [{label:"Estimated monthly fuel cost",value:money(daily*30),note:"30-day projection before maintenance"},{label:"Daily fuel",value:`${litres.toFixed(1)} litres`},{label:"Daily fuel cost",value:money(daily)}]}};
    if(slug.includes("ac-tonnage")) return { labels:["Room floor area","Ceiling height","Heat-load factor"], suffix:["sq ft","ft","BTU/sq ft"], calculate:()=>{const adjusted=n(a)*(n(b)/9||1);const btu=adjusted*n(c);const tons=btu/12000;const practical=Math.ceil(tons*4)/4;return [{label:"Suggested starting size",value:`${practical.toFixed(2)} ton`,note:"Arrange a professional heat-load check"},{label:"Estimated cooling load",value:`${Math.round(btu).toLocaleString("en-PK")} BTU/h`},{label:"Raw tonnage",value:`${tons.toFixed(2)} ton`}]}};
    if(slug.includes("water-tank")) return { labels:["Internal length","Internal width","Usable depth"], suffix:["ft","ft","ft"], calculate:()=>{const cubic=n(a)*n(b)*n(c);const litres=cubic*28.3168;return [{label:"Estimated tank capacity",value:`${Math.round(litres).toLocaleString("en-PK")} litres`,note:"Rectangular tank using internal dimensions"},{label:"Volume",value:`${cubic.toFixed(1)} cu ft`},{label:"US gallons",value:`${Math.round(litres/3.785).toLocaleString("en-PK")}`}]}};
    if(slug.includes("tile-quantity")) return { labels:["Net surface area","Tile length","Tile width"], suffix:["sq ft","inches","inches"], calculate:()=>{const tileSqFt=n(b)*n(c)/144;const base=n(a)/(tileSqFt||1);const total=Math.ceil(base*1.1);return [{label:"Tiles to purchase",value:total.toLocaleString("en-PK"),note:"Includes a 10% cutting and breakage allowance"},{label:"Base tile count",value:Math.ceil(base).toLocaleString("en-PK")},{label:"Allowance tiles",value:Math.max(0,total-Math.ceil(base)).toLocaleString("en-PK")}]}};
    if(slug.includes("concrete-volume")) return { labels:["Slab length","Slab width","Thickness"], suffix:["metres","metres","cm"], calculate:()=>{const base=n(a)*n(b)*(n(c)/100);const order=base*1.07;return [{label:"Concrete to order",value:`${order.toFixed(2)} m³`,note:"Includes a 7% site allowance"},{label:"Geometric volume",value:`${base.toFixed(2)} m³`},{label:"Allowance",value:`${(order-base).toFixed(2)} m³`}]}};
    if(slug.includes("download-time")) return { labels:["File size","Connection speed","Practical efficiency"], suffix:["GB","Mbps","%"], calculate:()=>{const seconds=n(a)*8000/(n(b)||1)/(n(c)/100||1);const hours=Math.floor(seconds/3600);const minutes=Math.ceil((seconds%3600)/60);return [{label:"Estimated download time",value:hours?`${hours}h ${minutes}m`:`${minutes} minutes`,note:"Assumes a steady average connection"},{label:"Data transferred",value:`${n(a).toFixed(1)} GB`},{label:"Effective speed",value:`${(n(b)*n(c)/100).toFixed(1)} Mbps`}]}};
    if(slug.includes("mobile-data-usage")) return { labels:["Daily streaming time","Streaming data rate","Other monthly usage"], suffix:["hours","GB/hour","GB"], calculate:()=>{const streaming=n(a)*n(b)*30;const total=streaming+n(c);return [{label:"Suggested monthly data",value:`${Math.ceil(total)} GB`,note:"Round up to the next suitable package"},{label:"Streaming data",value:`${streaming.toFixed(1)} GB`},{label:"Other allowance",value:`${n(c).toFixed(1)} GB`}]}};
    if(slug.includes("compound-interest")) return { labels:["Starting investment","Assumed annual return","Investment period"], suffix:["PKR","%","years"], calculate:()=>{const months=Math.round(n(c)*12);const future=n(a)*Math.pow(1+n(b)/1200,months);return [{label:"Projected future value",value:money(future),note:"Monthly compounding before tax, fees and inflation"},{label:"Projected growth",value:money(future-n(a))},{label:"Total return",value:`${n(a)?((future/n(a)-1)*100).toFixed(1):0}%`}]}};
    if(slug.includes("savings-goal")) return { labels:["Savings target","Already saved","Months remaining"], suffix:["PKR","PKR","months"], calculate:()=>{const gap=Math.max(0,n(a)-n(b));const monthly=gap/(n(c)||1);return [{label:"Required monthly saving",value:money(monthly),note:gap?"Assumes equal monthly contributions":"Goal already funded"},{label:"Remaining gap",value:money(gap)},{label:"Progress so far",value:`${n(a)?Math.min(100,n(b)/n(a)*100).toFixed(1):0}%`}]}};
    if(slug.includes("monthly-investment")) return { labels:["Monthly contribution","Assumed annual return","Investment period"], suffix:["PKR","%","years"], calculate:()=>{const months=Math.max(0,Math.round(n(c)*12));const rate=n(b)/1200;const future=rate?n(a)*(Math.pow(1+rate,months)-1)/rate:n(a)*months;const contributed=n(a)*months;return [{label:"Projected future value",value:money(future),note:"End-of-month contributions; not a guaranteed return"},{label:"Total contributed",value:money(contributed)},{label:"Projected growth",value:money(future-contributed)}]}};
    if(slug.includes("loan-affordability")) return { labels:["Affordable monthly payment","Annual reducing rate","Repayment term"], suffix:["PKR","%","years"], calculate:()=>{const months=Math.max(1,Math.round(n(c)*12));const rate=n(b)/1200;const principal=rate?n(a)*(Math.pow(1+rate,months)-1)/(rate*Math.pow(1+rate,months)):n(a)*months;return [{label:"Estimated affordable principal",value:money(principal),note:"Before lender eligibility, fees and insurance"},{label:"Total scheduled payments",value:money(n(a)*months)},{label:"Number of payments",value:months.toLocaleString("en-PK")}]}};
    if(slug.includes("credit-card-payoff")) return { labels:["Current card balance","Fixed monthly payment","Annual finance rate"], suffix:["PKR","PKR","%"], calculate:()=>{const rate=n(c)/1200;const interest=n(a)*rate;if(n(b)<=interest)return [{label:"Payment is too low",value:"Balance will not reduce",note:`First-month interest is about ${money(interest)}`},{label:"Minimum to reduce balance",value:money(interest+1)},{label:"Current payment",value:money(n(b))}];const months=rate?Math.ceil(-Math.log(1-rate*n(a)/n(b))/Math.log(1+rate)):Math.ceil(n(a)/(n(b)||1));const total=n(b)*months;return [{label:"Estimated payoff time",value:`${months} months`,note:"Assumes no new purchases or fees"},{label:"Estimated total paid",value:money(total)},{label:"Estimated finance cost",value:money(Math.max(0,total-n(a)))}]}};
    if(slug.includes("emergency-fund")) return { labels:["Essential monthly expenses","Coverage period","Already reserved"], suffix:["PKR","months","PKR"], calculate:()=>{const target=n(a)*n(b);const gap=Math.max(0,target-n(c));return [{label:"Emergency-fund target",value:money(target),note:`Covers ${n(b)} months of entered expenses`},{label:"Remaining gap",value:money(gap)},{label:"Current coverage",value:`${(n(c)/(n(a)||1)).toFixed(1)} months`}]}};
    if(slug.includes("salary-increment")) return { labels:["Current monthly salary","Increment rate","New monthly allowance"], suffix:["PKR","%","PKR"], calculate:()=>{const increase=n(a)*n(b)/100;const revised=n(a)+increase+n(c);return [{label:"New gross monthly salary",value:money(revised),note:"Before tax and payroll deductions"},{label:"Monthly gross increase",value:money(increase+n(c))},{label:"Annual gross increase",value:money((increase+n(c))*12)}]}};
    if(slug.includes("business-break-even")) return { labels:["Monthly fixed costs","Selling price per unit","Variable cost per unit"], suffix:["PKR","PKR","PKR"], calculate:()=>{const contribution=n(b)-n(c);if(contribution<=0)return [{label:"No break-even point",value:"Price must exceed variable cost",note:"Contribution per unit is zero or negative"},{label:"Current contribution",value:money(contribution)},{label:"Price",value:money(n(b))}];const units=Math.ceil(n(a)/contribution);return [{label:"Break-even sales volume",value:`${units.toLocaleString("en-PK")} units`,note:"Units needed to cover entered fixed costs"},{label:"Break-even revenue",value:money(units*n(b))},{label:"Contribution per unit",value:money(contribution)}]}};
    if(slug.includes("solar-battery-size")) return { labels:["Essential backup load","Required backup time","Battery-bank voltage"], suffix:["W","hours","V"], calculate:()=>{const usable=n(a)*n(b);const nominal=usable/.8;const ah=nominal/(n(c)||1);return [{label:"Estimated battery capacity",value:`${Math.ceil(ah)} Ah`,note:"Uses an 80% combined usable-energy allowance"},{label:"Nominal bank energy",value:`${Math.ceil(nominal)} Wh`},{label:"Usable energy needed",value:`${Math.ceil(usable)} Wh`}]}};
    if(slug.includes("solar-panel-output")) return { labels:["Solar system capacity","Peak sun hours","System efficiency"], suffix:["kW","hours/day","%"], calculate:()=>{const daily=n(a)*n(b)*n(c)/100;return [{label:"Estimated monthly generation",value:`${Math.round(daily*30)} units`,note:"30-day planning estimate"},{label:"Estimated daily generation",value:`${daily.toFixed(1)} units`},{label:"Annualised estimate",value:`${Math.round(daily*365).toLocaleString("en-PK")} units`}]}};
    if(slug.includes("solar-payback")) return { labels:["Total installed cost","Average monthly saving","Annual maintenance"], suffix:["PKR","PKR","PKR/year"], calculate:()=>{const annual=n(b)*12-n(c);const years=annual>0?n(a)/annual:Infinity;return [{label:"Simple payback period",value:Number.isFinite(years)?`${years.toFixed(1)} years`:"No payback",note:"Excludes financing, degradation and replacements"},{label:"Net annual saving",value:money(Math.max(0,annual))},{label:"Five-year net saving",value:money(Math.max(0,annual*5))}]}};
    if(slug.includes("ac-electricity-cost")) return { labels:["Rated electrical input","Daily runtime","Effective unit rate"], suffix:["W","hours","PKR/unit"], calculate:()=>{const units=n(a)/1000*n(b)*30*.7;return [{label:"Estimated monthly AC cost",value:money(units*n(c)),note:"Uses a 70% average-load factor"},{label:"Estimated monthly units",value:`${units.toFixed(1)} kWh`},{label:"Full-load equivalent",value:`${(n(b)*.7).toFixed(1)} hours/day`}]}};
    if(slug.includes("battery-charging-time")) return { labels:["Battery capacity","Charger current","Loss and finish allowance"], suffix:["Ah","A","%"], calculate:()=>{const base=n(a)/(n(b)||1);const total=base*(1+n(c)/100);return [{label:"Estimated charging time",value:`${total.toFixed(1)} hours`,note:"Confirm the battery's safe charging current"},{label:"Ideal base time",value:`${base.toFixed(1)} hours`},{label:"Added allowance",value:`${(total-base).toFixed(1)} hours`}]}};
    if(slug.includes("watts-amps-volts")) return { labels:["Real power","Operating voltage","Efficiency / power factor"], suffix:["W","V","factor"], calculate:()=>{const amps=n(a)/((n(b)||1)*(n(c)||1));return [{label:"Estimated current",value:`${amps.toFixed(2)} A`,note:"Basic single-phase or DC planning estimate"},{label:"Apparent power",value:`${(n(a)/(n(c)||1)).toFixed(0)} VA`},{label:"Ideal unity current",value:`${(n(a)/(n(b)||1)).toFixed(2)} A`}]}};
    if(slug.includes("rent-affordability")) return { labels:["Monthly take-home income","Essential non-rent expenses","Rent guideline"], suffix:["PKR","PKR","%"], calculate:()=>{const percentage=n(a)*n(c)/100;const cash=Math.max(0,n(a)-n(b)-n(a)*.1);const suggested=Math.min(percentage,cash);return [{label:"Suggested maximum rent",value:money(suggested),note:"Uses the lower limit and keeps a 10% income buffer"},{label:"Percentage guideline",value:money(percentage)},{label:"Cash-flow limit",value:money(cash)}]}};
    if(slug.includes("debt-to-income")) return { labels:["Gross monthly income","Monthly debt payments","Unused"], suffix:["PKR","PKR",""], calculate:()=>{const ratio=n(a)?n(b)/n(a)*100:0;return [{label:"Debt-to-income ratio",value:`${ratio.toFixed(1)}%`,note:"A lender may calculate this differently"},{label:"Gross income after debt",value:money(Math.max(0,n(a)-n(b)))},{label:"Annual debt payments",value:money(n(b)*12)}]}};
    if(slug.includes("freelance-project-quote")) return { labels:["Estimated project hours","Hourly value","Scope-risk buffer"], suffix:["hours","PKR/hour","%"], calculate:()=>{const base=n(a)*n(b);const buffer=base*n(c)/100;return [{label:"Recommended project quote",value:money(base+buffer),note:"Before external costs, platform fees and tax"},{label:"Base labour value",value:money(base)},{label:"Risk buffer",value:money(buffer)}]}};
    if(slug.includes("sales-commission")) return { labels:["Eligible net sales","Commission rate","Fixed performance bonus"], suffix:["PKR","%","PKR"], calculate:()=>{const commission=n(a)*n(b)/100;return [{label:"Total incentive",value:money(commission+n(c)),note:"Commission plus entered fixed bonus"},{label:"Percentage commission",value:money(commission)},{label:"Effective incentive rate",value:`${n(a)?((commission+n(c))/n(a)*100).toFixed(2):0}%`}]}};
    if(slug.includes("50-30-20")) return { labels:["Monthly take-home income","Needs allocation","Savings / debt priority"], suffix:["PKR","%","%"], calculate:()=>{const needs=n(a)*n(b)/100;const savings=n(a)*n(c)/100;const wants=Math.max(0,n(a)-needs-savings);return [{label:"Needs budget",value:money(needs),note:`${n(b)}% for essential expenses`},{label:"Wants budget",value:money(wants)},{label:"Savings / debt",value:money(savings)}]}};
    if(slug.includes("salary-to-hourly")) return { labels:["Gross monthly salary","Paid working days","Paid hours per day"], suffix:["PKR","days","hours"], calculate:()=>{const daily=n(a)/(n(b)||1);const hourly=n(a)/((n(b)||1)*(n(c)||1));return [{label:"Gross hourly rate",value:money(hourly),note:"Before deductions and excluding benefits"},{label:"Gross daily rate",value:money(daily)},{label:"Paid monthly hours",value:(n(b)*n(c)).toLocaleString("en-PK")}]}};
    if(slug.includes("solar-ac")) return { labels:["AC electrical input","Daily runtime","Peak sun hours"], suffix:["W","hours","hours/day"], calculate:()=>{const daily=n(a)/1000*n(b);const kw=daily/((n(c)||1)*.8);const panels=Math.ceil(kw*1000/580);return [{label:"Estimated solar array",value:`${kw.toFixed(2)} kW`,note:"Energy-only sizing at 80% system efficiency"},{label:"580 W panels",value:panels.toLocaleString("en-PK")},{label:"Daily AC energy",value:`${daily.toFixed(1)} kWh`}]}};
    if(slug.includes("ups-charging-cost")) return { labels:["Battery capacity","Battery voltage","Capacity to recharge","Electricity unit rate"], suffix:["Ah","V","%","PKR/unit"], calculate:()=>{const stored=n(a)*n(b)*n(c)/100/1000;const grid=stored/.8;return [{label:"Estimated recharge cost",value:money(grid*n(d)),note:"Uses an 80% charging-efficiency assumption"},{label:"Grid energy",value:`${grid.toFixed(2)} kWh`},{label:"Energy stored",value:`${stored.toFixed(2)} kWh`}]}};
    if(slug.includes("generator-size")) return { labels:["Total running load","Largest additional startup surge","Safety headroom"], suffix:["W","W","%"], calculate:()=>{const required=(n(a)+n(b))*(1+n(c)/100);const kva=required/1000/.8;return [{label:"Recommended generator size",value:`${kva.toFixed(1)} kVA`,note:"Uses a 0.8 power-factor assumption"},{label:"Required apparent power",value:`${Math.round(required/.8).toLocaleString("en-PK")} VA`},{label:"Load with headroom",value:`${Math.round(required).toLocaleString("en-PK")} W`}]}};
    if(slug.includes("solar-panel-series-parallel")) return { labels:["One panel voltage","One panel current","Panels in each series string","Parallel strings"], suffix:["V","A","panels","strings"], calculate:()=>{const voltage=n(a)*n(c);const current=n(b)*n(d);const count=n(c)*n(d);return [{label:"Estimated array output",value:`${voltage.toFixed(1)} V / ${current.toFixed(1)} A`,note:"Verify cold Voc and all inverter input limits"},{label:"Total panel count",value:count.toLocaleString("en-PK")},{label:"Approximate DC power",value:`${Math.round(voltage*current).toLocaleString("en-PK")} W`}]}};
    if(slug.includes("solar-roof-area")) return { labels:["Measured roof area","Panel footprint","Panel wattage"], suffix:["sq ft","sq ft","W"], calculate:()=>{const usable=n(a)*.75;const panels=Math.floor(usable/(n(b)||1));return [{label:"Estimated panels that fit",value:panels.toLocaleString("en-PK"),note:"Uses 75% of measured area for preliminary layout"},{label:"Possible array capacity",value:`${(panels*n(c)/1000).toFixed(1)} kW`},{label:"Layout area used",value:`${Math.round(panels*n(b)).toLocaleString("en-PK")} sq ft`}]}};
    if(slug.includes("solar-load")) return { labels:["Appliance power","Quantity","Daily operating time"], suffix:["W","items","hours"], calculate:()=>{const peak=n(a)*n(b);const wh=peak*n(c);return [{label:"Daily energy requirement",value:`${(wh/1000).toFixed(2)} kWh`,note:"Calculate each appliance group and combine totals"},{label:"Peak running load",value:`${Math.round(peak).toLocaleString("en-PK")} W`},{label:"Daily watt-hours",value:`${Math.round(wh).toLocaleString("en-PK")} Wh`}]}};
    if(slug==="phone-finder-pakistan") return { labels:["Total mobile budget","Gaming priority","Camera priority","Battery priority"], suffix:["PKR","0–10","0–10","0–10"], calculate:()=>{const priorities=[{name:"Gaming",score:n(b),detail:"chipset, cooling and sustained performance"},{name:"Camera",score:n(c),detail:"verified photo and video quality"},{name:"Battery",score:n(d),detail:"endurance, efficiency and charging"}].sort((x,y)=>y.score-x.score);const phone=n(a)*.95;const storage=n(a)>=80000?256:n(a)>=35000?128:64;return [{label:"Your main buying focus",value:priorities[0].name,note:`Prioritise ${priorities[0].detail}`},{label:"Target phone price",value:money(phone)},{label:"Minimum storage guide",value:`${storage} GB`}]} };
    if(slug==="phone-comparison-score-calculator") return { labels:["Performance rating","Camera rating","Battery rating"], suffix:["0–100","0–100","0–100"], calculate:()=>{const performance=Math.min(100,n(a));const camera=Math.min(100,n(b));const battery=Math.min(100,n(c));const score=performance*.4+camera*.3+battery*.3;return [{label:"Weighted comparison score",value:`${score.toFixed(1)} / 100`,note:"Use the same testing methodology for every phone"},{label:"Performance contribution",value:`${(performance*.4).toFixed(1)} points`},{label:"Camera + battery",value:`${(camera*.3+battery*.3).toFixed(1)} points`}]} };
    if(slug==="mobile-gaming-fps-estimator") return { labels:["Sustained benchmark index","Game demand index","Thermal performance loss"], suffix:["index","index","%"], calculate:()=>{const raw=n(a)/(n(b)||1)*60;const fps=Math.min(120,raw*(1-Math.min(90,n(c))/100));const low=Math.max(1,fps*.9);return [{label:"Estimated sustained frame rate",value:`${Math.round(low)}–${Math.round(fps)} FPS`,note:"Indicative range before game or device caps"},{label:"No-throttle estimate",value:`${Math.min(120,raw).toFixed(0)} FPS`},{label:"Estimated thermal loss",value:`${Math.max(0,raw-fps).toFixed(1)} FPS`}]} };
    if(slug==="phone-value-score-calculator-pakistan") return { labels:["Current phone price","Performance rating","Camera rating"], suffix:["PKR","0–100","0–100"], calculate:()=>{const quality=(Math.min(100,n(b))+Math.min(100,n(c)))/2;const index=quality/(n(a)/10000||1);return [{label:"Price-to-quality value index",value:index.toFixed(1),note:"Points per PKR 10,000; compare like-for-like phones"},{label:"Combined quality rating",value:`${quality.toFixed(1)} / 100`},{label:"Price per quality point",value:money(n(a)/(quality||1))}]} };
    if(slug==="screen-ppi-calculator") return { labels:["Horizontal resolution","Vertical resolution","Screen diagonal"], suffix:["pixels","pixels","inches"], calculate:()=>{const diagonalPixels=Math.hypot(n(a),n(b));const ppi=diagonalPixels/(n(c)||1);return [{label:"Calculated pixel density",value:`${Math.round(ppi)} PPI`,note:"Geometric density from stated resolution and diagonal"},{label:"Diagonal resolution",value:`${Math.round(diagonalPixels).toLocaleString("en-PK")} pixels`},{label:"Megapixels per frame",value:`${(n(a)*n(b)/1000000).toFixed(2)} MP`}]} };
    if(slug==="mobile-battery-life-estimator") return { labels:["Battery capacity","Average current draw","Usable capacity"], suffix:["mAh","mA","%"], calculate:()=>{const usable=n(a)*Math.min(100,n(c))/100;const hours=usable/(n(b)||1);return [{label:"Estimated equivalent active use",value:`${hours.toFixed(1)} hours`,note:"Runtime changes substantially with workload and signal"},{label:"Usable capacity assumption",value:`${Math.round(usable).toLocaleString("en-PK")} mAh`},{label:"Estimated capacity used hourly",value:`${n(b).toLocaleString("en-PK")} mAh`}]} };
    if(slug==="mobile-charging-time-calculator") return { labels:["Battery capacity","Effective charging power","Loss and taper allowance"], suffix:["mAh","W","%"], calculate:()=>{const energy=n(a)/1000*3.85;const ideal=energy/(n(b)||1);const total=ideal*(1+n(c)/100);return [{label:"Estimated full-charge time",value:`${Math.floor(total)}h ${Math.round(total%1*60)}m`,note:"Uses effective average power, not peak adapter rating"},{label:"Nominal battery energy",value:`${energy.toFixed(1)} Wh`},{label:"Ideal constant-power time",value:`${Math.round(ideal*60)} minutes`}]} };
    if(slug==="phone-storage-requirement-calculator") return { labels:["Apps and games","Photos, files and music","Downloaded or recorded video","Free-space reserve"], suffix:["GB","GB","GB","%"], calculate:()=>{const used=n(a)+n(b)+n(c);const required=used/(1-Math.min(80,n(d))/100||1);const tiers=[64,128,256,512,1024];const tier=tiers.find(x=>x>=required)||Math.ceil(required/512)*512;return [{label:"Recommended storage tier",value:`${tier} GB`,note:`Keeps approximately ${Math.min(80,n(d))}% capacity in reserve`},{label:"Estimated content requirement",value:`${used.toFixed(0)} GB`},{label:"Capacity needed with reserve",value:`${required.toFixed(0)} GB`}]} };
    if(slug==="used-phone-condition-score-pakistan") return { labels:["Battery health","Physical condition","Verification completeness"], suffix:["0–100","0–100","0–100"], calculate:()=>{const battery=Math.min(100,n(a));const physical=Math.min(100,n(b));const verification=Math.min(100,n(c));const score=battery*.3+physical*.25+verification*.45;const resultLabel=score>=90?"Strong inspection result":score>=75?"Further checks recommended":"High-risk inspection result";return [{label:resultLabel,value:`${score.toFixed(0)} / 100`,note:"A score cannot reveal hidden repairs or prove ownership"},{label:"Verification contribution",value:`${(verification*.45).toFixed(1)} points`},{label:"Condition contribution",value:`${(battery*.3+physical*.25).toFixed(1)} points`}]} };
    if(slug==="annual-to-monthly-salary-calculator-pakistan") return {labels:["Annual gross compensation","Annual working days","Paid hours per day"],suffix:["PKR","days","hours"],calculate:()=>{const monthly=n(a)/12;const daily=n(a)/(n(b)||1);return [{label:"Gross monthly equivalent",value:money(monthly),note:"Before deductions and excluding unlisted benefits"},{label:"Gross daily equivalent",value:money(daily)},{label:"Gross hourly equivalent",value:money(daily/(n(c)||1))}]}};
    if(slug==="job-offer-comparison-calculator-pakistan") return {labels:["Current / first monthly salary","Second monthly salary","Second offer net adjustment"],suffix:["PKR","PKR","PKR"],calculate:()=>{const second=n(b)+n(c);const difference=second-n(a);return [{label:difference>=0?"Second offer monthly advantage":"First offer monthly advantage",value:money(Math.abs(difference)),note:"Adjustment should include recurring benefits minus extra work costs"},{label:"Adjusted second-offer value",value:money(second)},{label:"Annual value difference",value:money(Math.abs(difference)*12)}]}};
    if(slug==="overtime-pay-calculator-pakistan") return {labels:["Base hourly pay","Overtime hours","Overtime multiplier"],suffix:["PKR/hour","hours","×"],calculate:()=>{const base=n(a)*n(b);const total=base*n(c);return [{label:"Estimated gross overtime pay",value:money(total),note:"Confirm eligibility and multiplier independently"},{label:"Base value of extra hours",value:money(base)},{label:"Overtime premium",value:money(Math.max(0,total-base))}]}};
    if(slug==="provident-fund-calculator-pakistan") return {labels:["Monthly contributory salary","Each side contribution rate","Projection period"],suffix:["PKR","%","years"],calculate:()=>{const monthly=n(a)*n(b)/100*2;const months=Math.round(n(c)*12);const rate=.08/12;const future=monthly*(Math.pow(1+rate,months)-1)/rate;const contributed=monthly*months;return [{label:"Projected provident-fund balance",value:money(future),note:"Assumes equal matching and an illustrative 8% annual return"},{label:"Combined monthly contribution",value:money(monthly)},{label:"Total cash contributed",value:money(contributed)}]}};
    if(slug==="gratuity-calculator-pakistan") return {labels:["Last monthly salary basis","Completed service years","Paid days per service year"],suffix:["PKR","years","days"],calculate:()=>{const daily=n(a)/30;const gratuity=daily*n(b)*n(c);return [{label:"Estimated service gratuity",value:money(gratuity),note:"Eligibility and formula require independent verification"},{label:"Entered daily salary basis",value:money(daily)},{label:"Gratuity per service year",value:money(daily*n(c))}]}};
    if(slug==="bonus-tax-estimator-pakistan") return {labels:["Gross annual or performance bonus","Marginal withholding rate","Other bonus deductions"],suffix:["PKR","%","PKR"],calculate:()=>{const tax=n(a)*n(b)/100;const net=Math.max(0,n(a)-tax-n(c));return [{label:"Estimated net bonus",value:money(net),note:"Payroll may recompute tax using total annual income"},{label:"Estimated bonus withholding",value:money(tax)},{label:"Total entered deductions",value:money(tax+n(c))}]}};
    if(slug==="salary-allowance-calculator-pakistan") return {labels:["Monthly base salary","Taxable monthly allowances","Non-taxable reimbursements"],suffix:["PKR","PKR","PKR"],calculate:()=>{const taxable=n(a)+n(b);const gross=taxable+n(c);return [{label:"Gross monthly cash package",value:money(gross),note:"Uses the tax classification entered by you"},{label:"Amount marked taxable",value:money(taxable)},{label:"Annual cash package",value:money(gross*12)}]}};
    if(slug==="freelancer-income-tax-estimator-pakistan") return {labels:["Annual gross freelance receipts","Documented business expenses","Effective tax reserve rate"],suffix:["PKR","PKR","%"],calculate:()=>{const profit=Math.max(0,n(a)-n(b));const reserve=profit*n(c)/100;return [{label:"Suggested tax reserve",value:money(reserve),note:"Not a determination of the applicable tax regime"},{label:"Planning profit",value:money(profit)},{label:"Profit after reserve",value:money(profit-reserve)}]}};
    if(slug==="sole-proprietor-tax-estimator-pakistan") return {labels:["Annual business revenue","Allowable business expenses","Effective tax reserve rate"],suffix:["PKR","PKR","%"],calculate:()=>{const profit=Math.max(0,n(a)-n(b));const reserve=profit*n(c)/100;return [{label:"Estimated business tax reserve",value:money(reserve),note:"Flat-rate planning estimate, not a return calculation"},{label:"Estimated taxable profit",value:money(profit)},{label:"Net after entered expenses and reserve",value:money(profit-reserve)}]}};
    if(slug==="withholding-tax-calculator-pakistan") return {labels:["Gross invoice or payment","Applicable withholding rate","Unused"],suffix:["PKR","%",""],calculate:()=>{const withheld=n(a)*n(b)/100;const net=n(a)-withheld;const grossUp=net/(1-n(b)/100||1);return [{label:"Expected net receipt",value:money(net),note:"Confirm the correct transaction rate and tax treatment"},{label:"Amount withheld",value:money(withheld)},{label:"Gross-up for same net",value:money(grossUp)}]}};
    if(slug==="property-tax-estimator-pakistan")return{labels:["Assessed property value","Taxable proportion","Local tax rate"],suffix:["PKR","%","%"],calculate:()=>{const v=n(a)*n(b)/100,t=v*n(c)/100;return[{label:"Estimated annual property tax",value:money(t),note:"Verify provincial valuation and rate"},{label:"Taxable value",value:money(v)},{label:"Monthly reserve",value:money(t/12)}]}};
    if(slug==="vehicle-token-tax-estimator-pakistan")return{labels:["Official taxable basis","Applied rate","Fixed charge"],suffix:["PKR","%","PKR"],calculate:()=>{const t=n(a)*n(b)/100+n(c);return[{label:"Estimated annual token tax",value:money(t),note:"Verify with the registered province"},{label:"Percentage charge",value:money(n(a)*n(b)/100)},{label:"Fixed charge",value:money(n(c))}]}};
    if(slug==="filer-vs-non-filer-calculator-pakistan")return{labels:["Transaction amount","Filer rate","Non-filer rate"],suffix:["PKR","%","%"],calculate:()=>{const f=n(a)*n(b)/100,nf=n(a)*n(c)/100;return[{label:"Additional non-filer withholding",value:money(nf-f),note:"Withholding may not equal final tax"},{label:"Filer withholding",value:money(f)},{label:"Non-filer withholding",value:money(nf)}]}};
    if(slug==="capital-gains-tax-estimator-pakistan")return{labels:["Sale proceeds","Adjusted cost basis","Planning tax rate"],suffix:["PKR","PKR","%"],calculate:()=>{const g=Math.max(0,n(a)-n(b)),t=g*n(c)/100;return[{label:"Estimated tax reserve",value:money(t),note:"Asset rules and exemptions vary"},{label:"Calculated gain",value:money(g)},{label:"Gain after reserve",value:money(g-t)}]}};
    if(slug.includes("inflation-calculator"))return{labels:["Current cost","Annual inflation rate","Years"],suffix:["PKR","%","years"],calculate:()=>{const f=n(a)*Math.pow(1+n(b)/100,n(c));return[{label:"Estimated future cost",value:money(f),note:"Constant-rate scenario"},{label:"Price increase",value:money(f-n(a))},{label:"Total increase",value:`${n(a)?((f/n(a)-1)*100).toFixed(1):0}%`}]}};
    if(slug.includes("purchasing-power"))return{labels:["Future nominal amount","Annual inflation rate","Years"],suffix:["PKR","%","years"],calculate:()=>{const p=n(a)/Math.pow(1+n(b)/100,n(c));return[{label:"Value in today's purchasing power",value:money(p),note:"Constant inflation assumption"},{label:"Purchasing power lost",value:money(n(a)-p)},{label:"Retained power",value:`${n(a)?(p/n(a)*100).toFixed(1):0}%`}]}};
    if(slug.includes("currency-conversion"))return{labels:["Foreign amount","Market PKR rate","Provider spread","Fixed PKR fee"],suffix:["foreign","PKR","%","PKR"],calculate:()=>{const gross=n(a)*n(b),net=gross*(1-n(c)/100)-n(d);return[{label:"Estimated PKR received",value:money(net),note:"Use the provider's executable rate"},{label:"Market conversion",value:money(gross)},{label:"Total conversion cost",value:money(gross-net)}]}};
    if(slug.includes("remittance-received"))return{labels:["Foreign amount","Foreign sending fee","PKR exchange rate","Local PKR charge"],suffix:["foreign","foreign","PKR","PKR"],calculate:()=>{const net=Math.max(0,n(a)-n(b))*n(c)-n(d);return[{label:"Estimated PKR received",value:money(net),note:"Before unlisted intermediary charges"},{label:"Converted after sending fee",value:money(Math.max(0,n(a)-n(b))*n(c))},{label:"Local charge",value:money(n(d))}]}};
    if(slug.includes("household-budget"))return{labels:["Monthly household income","Essential spending","Flexible spending"],suffix:["PKR","PKR","PKR"],calculate:()=>{const s=n(a)-n(b)-n(c);return[{label:s>=0?"Monthly surplus":"Monthly shortfall",value:money(Math.abs(s)),note:"Add irregular annual costs separately"},{label:"Savings rate",value:`${n(a)?(s/n(a)*100).toFixed(1):0}%`},{label:"Total spending",value:money(n(b)+n(c))}]}};
    if(slug.includes("savings-account"))return{labels:["Average account balance","Annual profit rate","Deduction rate"],suffix:["PKR","%","%"],calculate:()=>{const g=n(a)*n(b)/100,net=g*(1-n(c)/100);return[{label:"Estimated net annual profit",value:money(net),note:"Bank calculation methods vary"},{label:"Gross annual profit",value:money(g)},{label:"Entered deduction",value:money(g-net)}]}};
    if(slug.includes("term-deposit"))return{labels:["Deposit principal","Annual return","Term"],suffix:["PKR","%","years"],calculate:()=>{const m=Math.round(n(c)*12),v=n(a)*Math.pow(1+n(b)/1200,m);return[{label:"Projected maturity value",value:money(v),note:"Monthly-compounding comparison"},{label:"Projected profit",value:money(v-n(a))},{label:"Term",value:`${m} months`}]}};
    if(slug.includes("wedding-budget"))return{labels:["Venue and catering","Other planned costs","Contingency","Months to save"],suffix:["PKR","PKR","%","months"],calculate:()=>{const target=(n(a)+n(b))*(1+n(c)/100);return[{label:"Target wedding budget",value:money(target),note:"Includes entered contingency"},{label:"Required monthly saving",value:money(target/(n(d)||1))},{label:"Contingency amount",value:money(target-n(a)-n(b))}]}};
    if(slug.includes("credit-card-minimum"))return{labels:["Statement balance","Minimum percentage","Fixed payment floor","Finance charges"],suffix:["PKR","%","PKR","PKR"],calculate:()=>{const p=Math.max(n(a)*n(b)/100,n(c))+n(d);return[{label:"Estimated minimum payment",value:money(p),note:"Issuer method may differ"},{label:"Percentage component",value:money(n(a)*n(b)/100)},{label:"Balance after payment",value:money(Math.max(0,n(a)-p))}]}};
    if(slug.includes("debt-snowball"))return{labels:["Smallest debt balance","Monthly payment to target","Annual rate"],suffix:["PKR","PKR","%"],calculate:()=>{const interest=n(a)*n(c)/1200,months=Math.ceil(n(a)/Math.max(1,n(b)-interest));return[{label:"Approximate first-target payoff",value:`${months} months`,note:"Simplified first-debt estimate"},{label:"First-month interest",value:money(interest)},{label:"First-month principal",value:money(Math.max(0,n(b)-interest))}]}};
    if(slug.includes("debt-avalanche"))return{labels:["Highest-rate debt balance","Annual rate","Monthly payment"],suffix:["PKR","%","PKR"],calculate:()=>{const r=n(b)/1200,months=r&&n(c)>n(a)*r?Math.ceil(-Math.log(1-r*n(a)/n(c))/Math.log(1+r)):Math.ceil(n(a)/(n(c)||1));return[{label:"Estimated target payoff",value:`${months} months`,note:"Assumes fixed rate and no new debt"},{label:"Scheduled payments",value:money(months*n(c))},{label:"Estimated finance cost",value:money(Math.max(0,months*n(c)-n(a)))}]}};
    if(slug.includes("education-savings"))return{labels:["Education cost today","Education inflation","Years away","Already saved"],suffix:["PKR","%","years","PKR"],calculate:()=>{const future=n(a)*Math.pow(1+n(b)/100,n(c)),gap=Math.max(0,future-n(d));return[{label:"Required monthly saving",value:money(gap/(n(c)*12||1)),note:"Excludes investment return"},{label:"Inflation-adjusted target",value:money(future)},{label:"Remaining funding gap",value:money(gap)}]}};
    if(slug.includes("retirement-savings"))return{labels:["Current retirement savings","Monthly contribution","Annual return","Years"],suffix:["PKR","PKR","%","years"],calculate:()=>{const months=Math.round(n(d)*12),r=n(c)/1200,fv=n(a)*Math.pow(1+r,months)+(r?n(b)*(Math.pow(1+r,months)-1)/r:n(b)*months);return[{label:"Projected retirement balance",value:money(fv),note:"Return is not guaranteed"},{label:"Total contributed",value:money(n(a)+n(b)*months)},{label:"Projected growth",value:money(fv-n(a)-n(b)*months)}]}};
    if(["islamic-home-finance-calculator-pakistan","car-financing-calculator-pakistan","personal-loan-comparison-calculator-pakistan","early-loan-payment-calculator-pakistan","loan-refinancing-calculator-pakistan"].includes(slug))return{labels:["Amount or balance","Primary rate / down payment","Term or comparison rate","Extra payment / fees"],suffix:["PKR","%","years / %","PKR / years"],calculate:()=>{const principal=slug.includes("car-financing")?n(a)*(1-n(b)/100):n(a),rate=(slug.includes("car-financing")?14:n(b))/1200,months=Math.max(1,Math.round((slug.includes("personal-loan")?n(d):n(c))*12)),p=rate?principal*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1):principal/months;return[{label:"Estimated monthly payment",value:money(p),note:"Comparison model; verify product structure"},{label:"Financed principal",value:money(principal)},{label:"Estimated scheduled total",value:money(p*months)}]}};
    if(slug==="electricity-slab-rate-calculator-pakistan")return{labels:["Monthly units","Lower slab threshold","Lower rate","Upper rate"],suffix:["units","units","PKR/unit","PKR/unit"],calculate:()=>{const low=Math.min(n(a),n(b)),high=Math.max(0,n(a)-n(b)),cost=low*n(c)+high*n(d);return[{label:"Estimated slab energy charge",value:money(cost),note:"Before taxes and adjustments"},{label:"Lower-slab charge",value:money(low*n(c))},{label:"Upper-slab charge",value:money(high*n(d))}]}};
    if(/^(lesco|iesco|fesco|mepco|gepco|pesco|hesco|sepco|k-electric)-bill/.test(slug))return{labels:["Monthly units","Effective energy rate","Additional charges"],suffix:["units","PKR/unit","%"],calculate:()=>{const base=n(a)*n(b),extra=base*n(c)/100;return[{label:"Estimated provider bill",value:money(base+extra),note:"Use current values from your bill"},{label:"Energy estimate",value:money(base)},{label:"Additional charges",value:money(extra)}]}};
    if(slug==="net-metering-savings-calculator-pakistan")return{labels:["Self-used solar units","Exported solar units","Import rate","Export rate"],suffix:["units","units","PKR/unit","PKR/unit"],calculate:()=>{const self=n(a)*n(c),exported=n(b)*n(d);return[{label:"Estimated monthly solar value",value:money(self+exported),note:"Self-use and exports valued separately"},{label:"Self-consumption value",value:money(self)},{label:"Export value",value:money(exported)}]}};
    if(slug==="solar-export-credit-calculator-pakistan")return{labels:["Imported grid units","Exported solar units","Import rate","Export rate"],suffix:["units","units","PKR/unit","PKR/unit"],calculate:()=>{const bill=n(a)*n(c),credit=n(b)*n(d);return[{label:"Estimated net energy amount",value:money(Math.max(0,bill-credit)),note:"Before fixed charges and taxes"},{label:"Import energy charge",value:money(bill)},{label:"Export credit",value:money(credit)}]}};
    if(slug==="solar-inverter-size-calculator-pakistan")return{labels:["Running load","Largest surge addition","Headroom","Power factor"],suffix:["W","W","%","PF"],calculate:()=>{const watts=(n(a)+n(b))*(1+n(c)/100),va=watts/(n(d)||1);return[{label:"Suggested inverter capacity",value:`${(va/1000).toFixed(1)} kVA`,note:"Verify manufacturer surge limits"},{label:"Load with headroom",value:`${Math.round(watts)} W`},{label:"Apparent power",value:`${Math.round(va)} VA`}]}};
    if(slug==="solar-cable-size-estimator-pakistan")return{labels:["Circuit current","One-way cable length","System voltage","Allowed voltage drop"],suffix:["A","m","V","%"],calculate:()=>{const drop=n(c)*n(d)/100,area=2*n(b)*n(a)*.0175/(drop||1);return[{label:"Calculated copper area",value:`${area.toFixed(2)} mm²`,note:"Select the next compliant standard size"},{label:"Allowed voltage drop",value:`${drop.toFixed(2)} V`},{label:"Round-trip length",value:`${n(b)*2} m`}]}};
    if(slug==="solar-panel-tilt-angle-calculator-pakistan")return{labels:["Location latitude","Seasonal adjustment","Unused"],suffix:["degrees","degrees",""],calculate:()=>[{label:"Annual starting tilt",value:`${n(a).toFixed(1)}°`,note:"Site-specific shade and roof limits still matter"},{label:"Winter-oriented tilt",value:`${Math.min(90,n(a)+n(b)).toFixed(1)}°`},{label:"Summer-oriented tilt",value:`${Math.max(0,n(a)-n(b)).toFixed(1)}°`}]};
    if(slug==="solar-generation-by-city-pakistan")return{labels:["Solar system size","Local peak sun hours","System efficiency"],suffix:["kW","hours/day","%"],calculate:()=>{const daily=n(a)*n(b)*n(c)/100;return[{label:"Estimated monthly generation",value:`${Math.round(daily*30)} units`,note:"Use representative city sun-hours"},{label:"Daily generation",value:`${daily.toFixed(1)} units`},{label:"Annualised generation",value:`${Math.round(daily*365)} units`}]}};
    if(slug==="load-shedding-battery-calculator-pakistan")return{labels:["Essential load","Total outage hours daily","Battery-bank voltage","Usable capacity"],suffix:["W","hours","V","%"],calculate:()=>{const wh=n(a)*n(b),ah=wh/(n(c)||1)/(n(d)/100||1);return[{label:"Estimated battery requirement",value:`${Math.ceil(ah)} Ah`,note:"Daily energy requirement before ageing margin"},{label:"Usable energy needed",value:`${Math.round(wh)} Wh`},{label:"Nominal energy needed",value:`${Math.round(wh/(n(d)/100||1))} Wh`}]}};
    if(slug==="lithium-vs-lead-acid-battery-calculator")return{labels:["Nominal battery energy","Usable depth","Expected cycles","Purchase price"],suffix:["kWh","%","cycles","PKR"],calculate:()=>{const usable=n(a)*n(b)/100,cost=n(d)/(n(c)||1);return[{label:"Usable energy per cycle",value:`${usable.toFixed(2)} kWh`,note:"Run separately for each chemistry"},{label:"Purchase cost per cycle",value:money(cost)},{label:"Lifetime delivered energy",value:`${Math.round(usable*n(c))} kWh`}]}};
    if(slug==="ups-runtime-multiple-appliances-calculator")return{labels:["Combined appliance load","Battery capacity","Battery-bank voltage","Usable energy"],suffix:["W","Ah","V","%"],calculate:()=>{const wh=n(b)*n(c)*n(d)/100,h=wh/(n(a)||1);return[{label:"Estimated combined-load runtime",value:`${h.toFixed(1)} hours`,note:"Surge and battery ageing not modelled"},{label:"Usable battery energy",value:`${Math.round(wh)} Wh`},{label:"Combined load",value:`${n(a)} W`}]}};
    if(slug==="electricity-bill-appliance-share-calculator")return{labels:["Appliance power","Daily runtime","Days used","Total monthly units"],suffix:["W","hours","days","units"],calculate:()=>{const units=n(a)/1000*n(b)*n(c),share=units/(n(d)||1)*100;return[{label:"Appliance share of consumption",value:`${share.toFixed(1)}%`,note:"Compare with measured appliance power"},{label:"Appliance monthly units",value:`${units.toFixed(1)} kWh`},{label:"Other household units",value:`${Math.max(0,n(d)-units).toFixed(1)} kWh`}]}};
    if(slug==="inverter-vs-non-inverter-ac-savings-calculator-pakistan")return{labels:["Standard AC average input","Inverter AC average input","Daily runtime","Unit rate"],suffix:["W","W","hours","PKR/unit"],calculate:()=>{const units=Math.max(0,n(a)-n(b))/1000*n(c)*30;return[{label:"Estimated monthly saving",value:money(units*n(d)),note:"Based on entered average inputs"},{label:"Monthly units saved",value:`${units.toFixed(1)} kWh`},{label:"Annualised saving",value:money(units*n(d)*12)}]}};
    if(slug==="refrigerator-electricity-cost-calculator-pakistan")return{labels:["Rated running power","Average duty cycle","Unit rate"],suffix:["W","%","PKR/unit"],calculate:()=>{const units=n(a)/1000*n(b)/100*24*30;return[{label:"Estimated monthly refrigerator cost",value:money(units*n(c)),note:"Duty cycle changes with heat and use"},{label:"Monthly consumption",value:`${units.toFixed(1)} kWh`},{label:"Daily consumption",value:`${(units/30).toFixed(2)} kWh`}]}};
    if(slug==="electric-geyser-cost-calculator-pakistan")return{labels:["Heater power","Daily heating time","Unit rate"],suffix:["W","hours","PKR/unit"],calculate:()=>{const units=n(a)/1000*n(b)*30;return[{label:"Estimated monthly geyser cost",value:money(units*n(c)),note:"Thermostat cycling can change usage"},{label:"Monthly consumption",value:`${units.toFixed(1)} kWh`},{label:"Daily cost",value:money(units*n(c)/30)}]}};
    if(slug==="ev-charging-cost-calculator-pakistan")return{labels:["Battery energy added","Charging efficiency","Electricity unit rate","Driving range gained"],suffix:["kWh","%","PKR/unit","km"],calculate:()=>{const grid=n(a)/(n(b)/100||1),cost=grid*n(c);return[{label:"Estimated charging cost",value:money(cost),note:"Includes entered charging loss"},{label:"Grid energy required",value:`${grid.toFixed(1)} kWh`},{label:"Charging cost per kilometre",value:money(cost/(n(d)||1))}]}};
    if(slug==="shopify-profit-calculator-pakistan")return{labels:["Selling price","Product cost","Payment fee rate","Ads and fulfilment"],suffix:["PKR","PKR","%","PKR"],calculate:()=>{const fee=n(a)*n(c)/100,p=n(a)-n(b)-fee-n(d);return[{label:"Estimated profit per order",value:money(p),note:"Before tax and unlisted app costs"},{label:"Net margin",value:`${n(a)?(p/n(a)*100).toFixed(1):0}%`},{label:"Payment fee",value:money(fee)}]}};
    if(slug==="amazon-pakistan-seller-profit-calculator")return{labels:["Selling price in PKR","Landed product cost","Referral fee rate","Fulfilment and ads"],suffix:["PKR","PKR","%","PKR"],calculate:()=>{const referral=n(a)*n(c)/100,p=n(a)-n(b)-referral-n(d);return[{label:"Estimated profit per unit",value:money(p),note:"Use fees for the exact marketplace and category"},{label:"Profit margin",value:`${n(a)?(p/n(a)*100).toFixed(1):0}%`},{label:"Referral fee",value:money(referral)}]}};
    if(slug==="foodpanda-restaurant-commission-calculator-pakistan")return{labels:["Customer order value","Platform commission","Seller-funded discount","Packaging cost"],suffix:["PKR","%","PKR","PKR"],calculate:()=>{const fee=n(a)*n(b)/100,net=n(a)-fee-n(c)-n(d);return[{label:"Estimated restaurant proceeds",value:money(net),note:"Before food cost, tax and other adjustments"},{label:"Platform commission",value:money(fee)},{label:"Total entered deductions",value:money(fee+n(c)+n(d))}]}};
    if(slug==="marketplace-fee-comparison-calculator-pakistan")return{labels:["Sale value","Marketplace A fee","Marketplace B fee","Fixed fee per order"],suffix:["PKR","%","%","PKR"],calculate:()=>{const first=n(a)*(1-n(b)/100)-n(d),second=n(a)*(1-n(c)/100)-n(d);return[{label:"Better net proceeds",value:money(Math.max(first,second)),note:first===second?"Both entered structures are equal":first>second?"Marketplace A yields more":"Marketplace B yields more"},{label:"Marketplace A net",value:money(first)},{label:"Marketplace B net",value:money(second)}]}};
    if(slug==="cod-order-profit-calculator-pakistan")return{labels:["COD selling price","Product cost","Courier and COD charges","Packaging and handling"],suffix:["PKR","PKR","PKR","PKR"],calculate:()=>{const cost=n(b)+n(c)+n(d),p=n(a)-cost;return[{label:"Delivered-order profit",value:money(p),note:"Return risk is not included on this page"},{label:"Profit margin",value:`${n(a)?(p/n(a)*100).toFixed(1):0}%`},{label:"Total order cost",value:money(cost)}]}};
    if(slug==="cod-return-loss-calculator-pakistan")return{labels:["Orders shipped","Expected return rate","Profit per delivered order","Loss per returned order"],suffix:["orders","%","PKR","PKR"],calculate:()=>{const returns=n(a)*n(b)/100,delivered=n(a)-returns,profit=delivered*n(c)-returns*n(d);return[{label:"Expected batch profit",value:money(profit),note:"Uses the entered return-rate scenario"},{label:"Expected delivered orders",value:Math.round(delivered).toLocaleString("en-PK")},{label:"Expected return loss",value:money(returns*n(d))}]}};
    if(slug==="product-pricing-calculator-pakistan")return{labels:["Total cost per unit","Target profit margin","Selling fee rate"],suffix:["PKR","%","%"],calculate:()=>{const combined=(n(b)+n(c))/100,price=n(a)/(Math.max(.01,1-combined));return[{label:"Suggested minimum selling price",value:money(price),note:"Margin is measured against the selling price"},{label:"Target profit amount",value:money(price*n(b)/100)},{label:"Estimated selling fee",value:money(price*n(c)/100)}]}};
    if(slug==="wholesale-retail-markup-calculator-pakistan")return{labels:["Wholesale unit cost","Markup on cost","Unused"],suffix:["PKR","%",""],calculate:()=>{const profit=n(a)*n(b)/100,price=n(a)+profit;return[{label:"Calculated retail price",value:money(price),note:"Before tax and selling fees"},{label:"Gross profit",value:money(profit)},{label:"Gross margin",value:`${price?(profit/price*100).toFixed(1):0}%`}]}};
    if(slug==="sales-tax-calculator-pakistan")return{labels:["Tax-exclusive amount","Sales tax rate","Unused"],suffix:["PKR","%",""],calculate:()=>{const tax=n(a)*n(b)/100;return[{label:"Tax-inclusive amount",value:money(n(a)+tax),note:"Confirm the applicable rate and registration treatment"},{label:"Sales tax component",value:money(tax)},{label:"Net amount",value:money(n(a))}]}};
    if(slug==="inventory-reorder-point-calculator-pakistan")return{labels:["Average units sold daily","Supplier lead time","Safety stock"],suffix:["units/day","days","units"],calculate:()=>{const demand=n(a)*n(b),point=demand+n(c);return[{label:"Inventory reorder point",value:`${Math.ceil(point).toLocaleString("en-PK")} units`,note:"Reorder when available stock reaches this level"},{label:"Lead-time demand",value:`${Math.ceil(demand)} units`},{label:"Safety stock",value:`${Math.ceil(n(c))} units`}]}};
    if(slug==="inventory-turnover-calculator-pakistan")return{labels:["Annual cost of goods sold","Opening inventory","Closing inventory"],suffix:["PKR","PKR","PKR"],calculate:()=>{const avg=(n(b)+n(c))/2,turns=n(a)/(avg||1);return[{label:"Inventory turnover",value:`${turns.toFixed(2)} times/year`,note:"Compare within a similar industry and period"},{label:"Average inventory",value:money(avg)},{label:"Approximate days held",value:`${turns?(365/turns).toFixed(0):0} days`}]}};
    if(slug==="import-landed-cost-calculator-pakistan")return{labels:["Foreign invoice value","PKR exchange rate","Freight and local charges","Duty rate"],suffix:["foreign","PKR","PKR","%"],calculate:()=>{const converted=n(a)*n(b),duty=converted*n(d)/100,total=converted+n(c)+duty;return[{label:"Estimated landed cost",value:money(total),note:"Simplified estimate before unlisted taxes and classification effects"},{label:"Converted invoice",value:money(converted)},{label:"Estimated duty",value:money(duty)}]}};
    if(slug==="customs-duty-calculator-pakistan")return{labels:["Assessable import value","Customs duty rate","Other import-tax rate"],suffix:["PKR","%","%"],calculate:()=>{const duty=n(a)*n(b)/100,other=n(a)*n(c)/100;return[{label:"Estimated import charges",value:money(duty+other),note:"Actual tax bases can be sequential and classification-specific"},{label:"Customs duty",value:money(duty)},{label:"Other entered taxes",value:money(other)}]}};
    if(slug==="courier-cost-comparison-calculator-pakistan")return{labels:["Monthly shipments","Courier A rate","Courier B rate","Common COD fee per parcel"],suffix:["shipments","PKR","PKR","PKR"],calculate:()=>{const first=n(a)*(n(b)+n(d)),second=n(a)*(n(c)+n(d));return[{label:"Lower monthly courier cost",value:money(Math.min(first,second)),note:first===second?"Both entered quotations are equal":first<second?"Courier A is lower":"Courier B is lower"},{label:"Courier A monthly",value:money(first)},{label:"Courier B monthly",value:money(second)}]}};
    if(slug==="freelancer-platform-fee-calculator-pakistan")return{labels:["Contract value","Platform fee rate","Withdrawal fee"],suffix:["foreign","%","foreign"],calculate:()=>{const fee=n(a)*n(b)/100,net=n(a)-fee-n(c);return[{label:"Estimated net earnings",value:net.toLocaleString("en-PK",{maximumFractionDigits:2}),note:"Shown in the same currency as the contract value"},{label:"Platform fee",value:fee.toLocaleString("en-PK",{maximumFractionDigits:2})},{label:"Total deductions",value:(fee+n(c)).toLocaleString("en-PK",{maximumFractionDigits:2})}]}};
    if(slug==="payoneer-withdrawal-calculator-pakistan")return{labels:["Foreign balance","Market PKR rate","Combined spread and fee","Fixed PKR charge"],suffix:["foreign","PKR","%","PKR"],calculate:()=>{const gross=n(a)*n(b),net=gross*(1-n(c)/100)-n(d);return[{label:"Estimated PKR received",value:money(net),note:"Compare against the provider's live offered rate"},{label:"Market-rate value",value:money(gross)},{label:"Estimated conversion cost",value:money(gross-net)}]}};
    if(slug==="international-payment-fee-comparison-pakistan")return{labels:["Foreign payment amount","Provider A net PKR rate","Provider B net PKR rate","Fixed charge"],suffix:["foreign","PKR","PKR","PKR"],calculate:()=>{const first=n(a)*n(b)-n(d),second=n(a)*n(c)-n(d);return[{label:"Higher estimated receipt",value:money(Math.max(first,second)),note:first===second?"Both offers are equal":first>second?"Provider A pays more":"Provider B pays more"},{label:"Provider A receipt",value:money(first)},{label:"Provider B receipt",value:money(second)}]}};
    if(slug==="small-business-cash-flow-calculator-pakistan")return{labels:["Opening cash balance","Cash receipts","Operating payments","Owner withdrawals"],suffix:["PKR","PKR","PKR","PKR"],calculate:()=>{const closing=n(a)+n(b)-n(c)-n(d),flow=n(b)-n(c)-n(d);return[{label:closing>=0?"Projected closing cash":"Projected cash shortfall",value:money(Math.abs(closing)),note:"Timing inside the period can still create a temporary shortfall"},{label:"Net cash movement",value:money(flow)},{label:"Total cash outflow",value:money(n(c)+n(d))}]}};
    if(slug==="employee-cost-to-company-calculator-pakistan")return{labels:["Monthly gross salary","Employer benefits","Employer contributions","Allocated overhead"],suffix:["PKR","PKR","PKR","PKR"],calculate:()=>{const monthly=n(a)+n(b)+n(c)+n(d);return[{label:"Estimated monthly employer cost",value:money(monthly),note:"Recruitment and termination costs are not included"},{label:"Estimated annual CTC",value:money(monthly*12)},{label:"Cost above gross salary",value:money(monthly-n(a))}]}};
    return { labels:["Percentage","Value","Unused"], suffix:["%","",""], calculate:()=>[{label:`${n(a)}% of ${n(b)}`,value:(n(a)*n(b)/100).toLocaleString("en-PK"),note:"Instant percentage result"},{label:"Decimal equivalent",value:(n(a)/100).toFixed(4)},{label:"Remaining value",value:(n(b)-n(a)*n(b)/100).toLocaleString("en-PK")}]};
  },[slug,a,b,c,d]);
  const results: Result[] = config.calculate();
  return <section className="calculator-shell" aria-label="Calculator"><div className="calc-inputs"><div className="calc-title"><span>Interactive calculator</span><strong>Your values stay on this device</strong></div><Field label={config.labels[0]} value={a} onChange={setA} suffix={config.suffix[0]}/><Field label={config.labels[1]} value={b} onChange={setB} suffix={config.suffix[1]}/>{config.labels[2]!=="Unused"&&<Field label={config.labels[2]} value={c} onChange={setC} suffix={config.suffix[2]}/>} {config.labels[3]&&<Field label={config.labels[3]} value={d} onChange={setD} suffix={config.suffix[3]}/>}<button className="calculate-button" onClick={()=>{setCalculated(false);requestAnimationFrame(()=>setCalculated(true))}}>Calculate result <span>→</span></button></div><div className={`calc-results ${calculated?"show":""}`}><div className="result-badge">✓ Estimated result</div><p>{results[0].label}</p><h2>{results[0].value}</h2><small>{results[0].note}</small><div className="result-grid">{results.slice(1).map((result)=><div key={result.label}><span>{result.label}</span><strong>{result.value}</strong></div>)}</div><div className="result-meter"><i style={{width:"72%"}}/><span>Personalised from your inputs</span></div></div></section>;
}
