"use client";
import {useState} from "react";
import type {CreatorTool as CreatorToolData} from "@/lib/creator-tools";

const clean=(value:string)=>value.trim().replace(/\s+/g," ");
const words=(value:string)=>clean(value).split(" ").filter(Boolean);
const hashtag=(value:string)=>"#"+value.replace(/[^a-zA-Z0-9]/g,"");
export function CreatorTool({tool}:{tool:CreatorToolData}){const[topic,setTopic]=useState(""),[audience,setAudience]=useState(""),[detail,setDetail]=useState(""),[tone,setTone]=useState("Practical"),[output,setOutput]=useState("");
 const generate=()=>{const t=clean(topic),a=clean(audience)||"your audience",d=clean(detail);if(!t){setOutput("Enter a topic or seed phrase first.");return}const key=d||t;let result="";
  if(tool.mode==="youtube-title")result=[`${t}: A Practical Guide for ${a}`,`How to ${t} — Step-by-Step ${tone} Guide`,`${t} Explained: What ${a} Should Know`,`${key}: Common Mistakes and Better Steps`,`${t} vs the Alternatives: An Honest Comparison`,`${t} in Practice — A Clear Beginner Walkthrough`, `Before You Try ${t}, Watch This`].join("\n");
  if(tool.mode==="youtube-description")result=`Learn about ${t} in this ${tone.toLowerCase()} video created for ${a}. We explain ${key} with clear steps, realistic examples and the important limitations to consider.\n\nIn this video:\n• What ${t} means and when it is useful\n• A step-by-step approach\n• Common mistakes to avoid\n• How to verify the final result\n\nUse the guidance as a starting point and confirm details for your own situation.\n\nQuestion for viewers: What part of ${t} should we cover next?\n\n#${hashtag(t).slice(1)} #Tutorial #HowTo`;
  if(tool.mode==="youtube-tags")result=Array.from(new Set([t,key,`${t} tutorial`,`${t} guide`,`${t} for beginners`,`${t} explained`,`${tone.toLowerCase()} ${t}`,`${t} tips`,`${t} mistakes`,`${t} step by step`,`${t} ${a}`])).join(", ");
  if(tool.mode==="youtube-timestamps"){const lines=detail.split("\n").map(x=>x.trim()).filter(Boolean);result=(lines.length?lines:["00:00 Introduction","00:30 What you need","02:00 Step-by-step process","05:00 Common mistakes","07:00 Final checks"]).map((x,i)=>/^\d{1,2}:\d{2}/.test(x)?x:`${i<10?"0":""}${i}:00 ${x}`).join("\n")}
  if(tool.mode==="instagram-caption")result=[`${t} — explained for ${a}.`,`Here is the ${tone.toLowerCase()} lesson: ${key}.`,`Save this for the next time you work on ${t}. What would you add?`,``,`${hashtag(t)} ${hashtag(key)} #Tips #Learn`].join("\n\n");
  if(tool.mode==="hashtags"){const seeds=[...words(t),...words(d),...words(a),t,`${t} tips`,`${t} guide`,`${t} community`,`${t} beginner`];result=Array.from(new Set(seeds.map(hashtag).filter(x=>x.length>1))).slice(0,18).join(" ")}
  if(tool.mode==="social-bio")result=[`${t} for ${a} | ${key}`,`Helping ${a} with ${t} • ${key}`,`${tone} ${t} resources for ${a} ↓`,`${t} | Clear ideas, honest examples and ${key}`].join("\n\n");
  if(tool.mode==="username"){const base=t.toLowerCase().replace(/[^a-z0-9]/g,""),extra=(d||a).toLowerCase().replace(/[^a-z0-9]/g,"");result=Array.from(new Set([base,`${base}hq`,`${base}lab`,`${base}daily`,`${base}guide`,`${base}${extra}`,`${extra}${base}`,`the${base}`,`${base}studio`,`${base}works`,`${base}online`,`${base}pk`])).join("\n")}
  if(tool.mode==="content-ideas")result=[`Beginner guide to ${t} for ${a}`,`7 common ${t} mistakes and how to fix them`,`A real-world ${t} workflow from start to finish`,`${t}: myth versus evidence`,`How to choose the right ${t} approach`,`What changed in ${t} and why it matters`,`${t} checklist: ${key}`,`Compare two popular ways to handle ${t}`,`Answer the five questions ${a} ask about ${t}`,`Case study: improving ${key} step by step`].join("\n");
  if(tool.mode==="hooks")result=[`If you are struggling with ${t}, start here.`,`Most ${a} miss this part of ${t}.`,`Before you try ${t}, check ${key}.`,`Here is the ${tone.toLowerCase()} way to approach ${t}.`,`What actually happens when you change ${key}?`,`Three ${t} mistakes that are easier to avoid than fix.`,`I tested a clearer way to handle ${t} — here is what changed.`,`This is why your ${t} result may not match your expectation.`].join("\n");setOutput(result)};
 const copy=async()=>{if(output)await navigator.clipboard.writeText(output)};
 return <section className="generator-workbench" aria-label={tool.shortTitle}><div className="productivity-fields"><label className="productivity-field"><span>{tool.fields.topic}</span><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder={`Enter ${tool.fields.topic.toLowerCase()}`}/></label><label className="productivity-field"><span>{tool.fields.audience}</span><input value={audience} onChange={e=>setAudience(e.target.value)} placeholder={`Enter ${tool.fields.audience.toLowerCase()}`}/></label><label className="productivity-field wide"><span>{tool.fields.detail}</span>{tool.mode==="youtube-timestamps"?<textarea rows={6} value={detail} onChange={e=>setDetail(e.target.value)} placeholder="00:00 Introduction&#10;01:25 First step&#10;04:10 Final checks"/>:<input value={detail} onChange={e=>setDetail(e.target.value)} placeholder={`Enter ${tool.fields.detail.toLowerCase()}`}/>}</label><label className="productivity-field"><span>Tone</span><select value={tone} onChange={e=>setTone(e.target.value)}><option>Practical</option><option>Professional</option><option>Friendly</option><option>Educational</option><option>Playful</option></select></label></div><div className="productivity-actions"><button onClick={generate}>Generate {tool.shortTitle.replace(" Generator","")}</button><button className="secondary" onClick={copy} disabled={!output}>Copy result</button><button className="secondary" onClick={()=>{setTopic("");setAudience("");setDetail("");setOutput("")}}>Clear</button></div><div className="productivity-output" aria-live="polite">{output}</div><p className="generator-privacy">🔒 Inputs stay in this browser. No account, upload or external AI request is used.</p></section>}

