"use client";
import {useState} from "react";
import type {DocumentTool as Tool} from "@/lib/document-tools";
declare global{interface Window{mammoth:any;pdfjsLib:any;XLSX:any;JSZip:any;jspdf:any;jsyaml:any}}
const cdn={mammoth:"https://cdn.jsdelivr.net/npm/mammoth@1.10.0/mammoth.browser.min.js",pdfjs:"https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js",xlsx:"https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js",zip:"https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js",jspdf:"https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js",yaml:"https://cdn.jsdelivr.net/npm/js-yaml@4.1.0/dist/js-yaml.min.js"};
const load=(src:string,key:string)=>new Promise<void>((ok,no)=>{if((window as any)[key])return ok();const old=document.querySelector('script[src="'+src+'"]');if(old){old.addEventListener("load",()=>ok());return}const s=document.createElement("script");s.src=src;s.onload=()=>ok();s.onerror=()=>no(new Error("A required browser library could not load. Check your connection."));document.head.appendChild(s)});
const save=(data:Blob|Uint8Array|string,name:string,type:string)=>{const blob=data instanceof Blob?data:new Blob([data as BlobPart],{type}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)};
const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
type Block={text:string;style?:"Title"|"Heading1"|"Heading2"|"ListParagraph"};
const markdownBlocks=(value:string):Block[]=>value.split(/\r?\n/).map(line=>{if(/^# /.test(line))return{text:line.slice(2),style:"Heading1"};if(/^## /.test(line))return{text:line.slice(3),style:"Heading2"};if(/^[-*] /.test(line))return{text:"• "+line.slice(2),style:"ListParagraph"};return{text:line.replace(/\*\*|__|`/g,"")}});
const textBlocks=(value:string,title:string):Block[]=>[...(title?[{text:title,style:"Title" as const}]:[]),...value.split(/\r?\n/).map(text=>({text}))];
const htmlBlocks=(html:string):Block[]=>{const doc=new DOMParser().parseFromString(html,"text/html");doc.querySelectorAll("script,style,iframe,object").forEach(x=>x.remove());const blocks:Block[]=[];doc.body.querySelectorAll("h1,h2,h3,p,li,blockquote,pre,td,th").forEach(el=>{const text=(el.textContent||"").trim();if(text)blocks.push({text:(el.tagName==="LI"?"• ":"")+text,style:el.tagName==="H1"?"Heading1":/^H[23]$/.test(el.tagName)?"Heading2":el.tagName==="LI"?"ListParagraph":undefined})});return blocks.length?blocks:textBlocks(doc.body.textContent||"","")};
const xmlNode=(node:Element):any=>{const result:any={};for(const attr of Array.from(node.attributes))result["@"+attr.name]=attr.value;const children=Array.from(node.children);if(!children.length){const text=(node.textContent||"").trim();return Object.keys(result).length?{...result,"#text":text}:text}for(const child of children){const value=xmlNode(child);if(result[child.tagName]===undefined)result[child.tagName]=value;else result[child.tagName]=Array.isArray(result[child.tagName])?[...result[child.tagName],value]:[result[child.tagName],value]}return result};
const safeXmlName=(name:string)=>{const value=name.replace(/[^A-Za-z0-9_.-]/g,"_");return /^[A-Za-z_]/.test(value)?value:"item_"+value};
const jsonXml=(name:string,value:any):string=>{const tag=safeXmlName(name);if(Array.isArray(value))return value.map(item=>jsonXml(tag,item)).join("");if(value&&typeof value==="object")return `<${tag}>${Object.entries(value).map(([k,v])=>jsonXml(k,v)).join("")}</${tag}>`;return `<${tag}>${esc(String(value??""))}</${tag}>`};
const makeDocx=async(blocks:Block[])=>{await load(cdn.zip,"JSZip");const zip=new window.JSZip(),paras=blocks.map(b=>'<w:p>'+(b.style?'<w:pPr><w:pStyle w:val="'+b.style+'"/></w:pPr>':'')+'<w:r><w:t xml:space="preserve">'+esc(b.text)+'</w:t></w:r></w:p>').join("");zip.file("[Content_Types].xml",'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>');zip.folder("_rels")!.file(".rels",'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.folder("word")!.file("document.xml",'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+paras+'<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1080" w:right="1080" w:bottom="1080" w:left="1080"/></w:sectPr></w:body></w:document>');zip.folder("word")!.file("styles.xml",'<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="38"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:rPr><w:b/><w:sz w:val="26"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="ListParagraph"><w:name w:val="List Paragraph"/></w:style></w:styles>');return zip.generateAsync({type:"blob",mimeType:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"})};
const makePdf=async(blocks:Block[],name:string)=>{await load(cdn.jspdf,"jspdf");const doc=new window.jspdf.jsPDF({unit:"pt",format:"a4"}),width=515;let y=58;for(const b of blocks){const heading=b.style?.startsWith("Heading")||b.style==="Title",size=b.style==="Title"?20:b.style==="Heading1"?17:b.style==="Heading2"?14:11;doc.setFont("helvetica",heading?"bold":"normal");doc.setFontSize(size);const lines=doc.splitTextToSize(b.text||" ",width);if(y+lines.length*(size+4)>790){doc.addPage();y=58}doc.text(lines,40,y);y+=lines.length*(size+4)+(heading?8:4)}doc.save(name)};
export function DocumentTool({tool}:{tool:Tool}){
 const pasteTool=/markdown|text-to|html-to|json-to|csv-to-json|xml-to-json|yaml-to-json/.test(tool.slug),multi=["merge-excel-files","compare-two-excel-files"].includes(tool.slug),[file,setFile]=useState<File|null>(null),[files,setFiles]=useState<File[]>([]),[value,setValue]=useState(""),[title,setTitle]=useState(""),[sheet,setSheet]=useState(""),[keyColumn,setKeyColumn]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[preview,setPreview]=useState(""),[stats,setStats]=useState<Record<string,string>|null>(null);
 const readInput=async()=>value.trim()?value:file?file.text():"";
 const run=async()=>{setBusy(true);setMessage("");setPreview("");setStats(null);try{
  if(!file&&!value.trim())throw new Error("Choose a file or paste content first.");
  if(["docx-viewer","docx-word-counter","word-to-pdf"].includes(tool.slug)){if(!file)throw new Error("Choose a DOCX file.");await load(cdn.mammoth,"mammoth");const buffer=await file.arrayBuffer();if(tool.slug==="docx-viewer"){const result=await window.mammoth.convertToHtml({arrayBuffer:buffer});setPreview(result.value);setMessage("Preview created locally.");return}const raw=(await window.mammoth.extractRawText({arrayBuffer:buffer})).value.trim();if(tool.slug==="docx-word-counter"){const words=raw?raw.split(/\s+/).length:0;setStats({Words:String(words),Characters:String(raw.length),"Characters without spaces":String(raw.replace(/\s/g,"").length),Paragraphs:String(raw.split(/\n+/).filter((x:string)=>x.trim()).length),"Reading time":Math.max(1,Math.ceil(words/200))+" min"});setMessage("Document statistics calculated locally.");return}await makePdf(textBlocks(raw,file.name.replace(/\.docx$/i,"")),"word-document.pdf");setMessage("Done — PDF downloaded.");return}
  if(tool.slug==="extract-images-from-docx"){if(!file)throw new Error("Choose a DOCX file.");await load(cdn.zip,"JSZip");const source=await window.JSZip.loadAsync(await file.arrayBuffer()),out=new window.JSZip();let count=0;for(const name of Object.keys(source.files)){if(name.startsWith("word/media/")&&!source.files[name].dir){out.file(name.split("/").pop(),await source.files[name].async("uint8array"));count++}}if(!count)throw new Error("No embedded images were found.");save(await out.generateAsync({type:"blob"}),"docx-images.zip","application/zip");setMessage("Done — "+count+" image(s) downloaded in a ZIP.");return}
  if(tool.slug==="pdf-to-word"){if(!file)throw new Error("Choose a PDF file.");await load(cdn.pdfjs,"pdfjsLib");window.pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js";const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,blocks:Block[]=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),content=await page.getTextContent();blocks.push({text:"Page "+n,style:"Heading2"},{text:content.items.map((x:any)=>x.str).join(" ")})}save(await makeDocx(blocks),"pdf-text.docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document");setMessage("Done — editable text downloaded as DOCX.");return}
  const spreadsheetTools=["csv-to-excel","excel-to-csv","json-to-excel","merge-excel-files","split-excel-sheets","remove-duplicate-excel-rows","compare-two-excel-files","excel-to-json","csv-to-json","json-to-csv"];
  if(spreadsheetTools.includes(tool.slug)){await load(cdn.xlsx,"XLSX");
   if(tool.slug==="merge-excel-files"){if(files.length<2)throw new Error("Choose at least two Excel files.");const out=window.XLSX.utils.book_new();for(const f of files){const book=window.XLSX.read(await f.arrayBuffer(),{type:"array"});for(const name of book.SheetNames){let target=(f.name.replace(/\.[^.]+$/,"-")+name).slice(0,31),n=2;while(out.SheetNames.includes(target))target=(target.slice(0,27)+"-"+n++).slice(0,31);window.XLSX.utils.book_append_sheet(out,book.Sheets[name],target)}}window.XLSX.writeFile(out,"merged-excel-files.xlsx");setStats({Workbooks:String(files.length),Worksheets:String(out.SheetNames.length)});setMessage("Done — merged Excel workbook downloaded.");return}
   if(tool.slug==="compare-two-excel-files"){
    if(files.length!==2)throw new Error("Choose exactly two Excel files.");
    const books:any[]=[];for(const f of files)books.push(window.XLSX.read(await f.arrayBuffer(),{type:"array"}));
    const rows:any[][]=books.map(b=>window.XLSX.utils.sheet_to_json(b.Sheets[sheet&&b.Sheets[sheet]?sheet:b.SheetNames[0]],{defval:""}));
    const key=(row:any)=>keyColumn?String(row[keyColumn]??""):JSON.stringify(row),oldMap=new Map<string,any>(rows[0].map((r:any)=>[key(r),r])),newMap=new Map<string,any>(rows[1].map((r:any)=>[key(r),r])),report:any[]=[];
    for(const [k,r] of oldMap)if(!newMap.has(k))report.push({status:"removed",key:k,...r});else if(JSON.stringify(r)!==JSON.stringify(newMap.get(k)))report.push({status:"changed",key:k,before:JSON.stringify(r),after:JSON.stringify(newMap.get(k))});
    for(const [k,r] of newMap)if(!oldMap.has(k))report.push({status:"added",key:k,...r});
    save(window.XLSX.utils.sheet_to_csv(window.XLSX.utils.json_to_sheet(report)),"excel-comparison.csv","text/csv;charset=utf-8");setPreview(JSON.stringify(report.slice(0,8),null,2));setStats({Differences:String(report.length)});setMessage("Done — comparison report downloaded.");return
   }
   if(!file&&!["csv-to-json","json-to-csv","csv-to-excel","json-to-excel"].includes(tool.slug))throw new Error("Choose an Excel file.");
   if(tool.slug==="split-excel-sheets"){await load(cdn.zip,"JSZip");const book=window.XLSX.read(await file!.arrayBuffer(),{type:"array"}),zip=new window.JSZip();for(const name of book.SheetNames){const out=window.XLSX.utils.book_new();window.XLSX.utils.book_append_sheet(out,book.Sheets[name],name.slice(0,31));zip.file(name.replace(/[^a-z0-9 _-]/gi,"_")+".xlsx",window.XLSX.write(out,{type:"array",bookType:"xlsx"}))}save(await zip.generateAsync({type:"blob"}),"split-excel-sheets.zip","application/zip");setStats({Worksheets:String(book.SheetNames.length)});setMessage("Done — separate worksheet files downloaded in a ZIP.");return}
   if(tool.slug==="remove-duplicate-excel-rows"){const book=window.XLSX.read(await file!.arrayBuffer(),{type:"array"}),name=sheet&&book.Sheets[sheet]?sheet:book.SheetNames[0],rows:any[]=window.XLSX.utils.sheet_to_json(book.Sheets[name],{defval:""}),seen=new Set(),clean=rows.filter(row=>{const k=keyColumn?JSON.stringify(row[keyColumn]):JSON.stringify(row);if(seen.has(k))return false;seen.add(k);return true}),out=window.XLSX.utils.book_new();window.XLSX.utils.book_append_sheet(out,window.XLSX.utils.json_to_sheet(clean),name.slice(0,31));window.XLSX.writeFile(out,"excel-without-duplicates.xlsx");setStats({"Original rows":String(rows.length),"Unique rows":String(clean.length),Removed:String(rows.length-clean.length)});setMessage("Done — cleaned workbook downloaded.");return}
   if(tool.slug==="excel-to-csv"||tool.slug==="excel-to-json"){const book=window.XLSX.read(await file!.arrayBuffer(),{type:"array"}),name=sheet&&book.Sheets[sheet]?sheet:book.SheetNames[0];if(tool.slug==="excel-to-csv")save(window.XLSX.utils.sheet_to_csv(book.Sheets[name]),"spreadsheet.csv","text/csv;charset=utf-8");else{const data=window.XLSX.utils.sheet_to_json(book.Sheets[name],{defval:""});setPreview(JSON.stringify(data.slice(0,8),null,2));save(JSON.stringify(data,null,2),"spreadsheet.json","application/json")}setMessage("Done — converted file downloaded.");return}
   const raw=await readInput();if(tool.slug==="csv-to-json"){const rows=window.XLSX.utils.sheet_to_json(window.XLSX.read(raw,{type:"string"}).Sheets.Sheet1,{defval:""});setPreview(JSON.stringify(rows.slice(0,8),null,2));save(JSON.stringify(rows,null,2),"csv-data.json","application/json");setMessage("Done — JSON downloaded.");return}if(tool.slug==="json-to-csv"){const parsed=JSON.parse(raw),rows=Array.isArray(parsed)?parsed:[parsed],csv=window.XLSX.utils.sheet_to_csv(window.XLSX.utils.json_to_sheet(rows));setPreview(csv.split(/\r?\n/).slice(0,8).join("\n"));save(csv,"json-data.csv","text/csv;charset=utf-8");setMessage("Done — CSV downloaded.");return}let ws;if(tool.slug==="json-to-excel"){const parsed=JSON.parse(raw),rows=Array.isArray(parsed)?parsed:[parsed];ws=window.XLSX.utils.json_to_sheet(rows);setPreview(JSON.stringify(rows.slice(0,5),null,2))}else{ws=window.XLSX.utils.csv_to_sheet(raw);setPreview(raw.split(/\r?\n/).slice(0,6).join("\n"))}const book=window.XLSX.utils.book_new();window.XLSX.utils.book_append_sheet(book,ws,"Data");window.XLSX.writeFile(book,tool.slug==="json-to-excel"?"json-data.xlsx":"csv-data.xlsx");setMessage("Done — Excel workbook downloaded.");return}
  if(["xml-to-json","json-to-xml","yaml-to-json","json-to-yaml"].includes(tool.slug)){const raw=await readInput();if(tool.slug==="xml-to-json"){const doc=new DOMParser().parseFromString(raw,"application/xml");if(doc.querySelector("parsererror"))throw new Error("The XML is not well formed.");const result={[doc.documentElement.tagName]:xmlNode(doc.documentElement)};setPreview(JSON.stringify(result,null,2));save(JSON.stringify(result,null,2),"converted-xml.json","application/json")}else if(tool.slug==="json-to-xml"){const parsed=JSON.parse(raw),xml='<?xml version="1.0" encoding="UTF-8"?>\n'+jsonXml(title||"root",parsed);setPreview(xml);save(xml,"converted-json.xml","application/xml")}else{await load(cdn.yaml,"jsyaml");if(tool.slug==="yaml-to-json"){const parsed=window.jsyaml.load(raw);setPreview(JSON.stringify(parsed,null,2));save(JSON.stringify(parsed,null,2),"converted-yaml.json","application/json")}else{const parsed=JSON.parse(raw),yaml=window.jsyaml.dump(parsed,{noRefs:true,lineWidth:100});setPreview(yaml);save(yaml,"converted-json.yaml","application/yaml")}}setMessage("Done — converted data file downloaded.");return}
  const raw=await readInput(),blocks=tool.slug.startsWith("markdown")?markdownBlocks(raw):tool.slug.startsWith("html")?htmlBlocks(raw):textBlocks(raw,title);setPreview(blocks.slice(0,30).map(x=>x.text).join("\n"));if(tool.slug.endsWith("docx"))save(await makeDocx(blocks),tool.slug+".docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document");else await makePdf(blocks,tool.slug+".pdf");setMessage("Done — converted file downloaded.");
 }catch(e){setMessage(e instanceof Error?e.message:"The file could not be processed.")}finally{setBusy(false)}};
 const accept=tool.input.includes("docx")?".docx":tool.input.includes("pdf")?".pdf":tool.input.includes("csv")?".csv":tool.input.includes("xlsx")||tool.input.includes("Excel")?".xlsx,.xls":tool.input.includes("json")||tool.input.includes("JSON")?".json":tool.input.includes("xml")||tool.input.includes("XML")?".xml":tool.input.includes("yaml")||tool.input.includes("YAML")?".yaml,.yml":tool.input.includes("html")?".html,.htm":tool.input.includes("md")?".md,.markdown":".txt";
 const selected=multi?files.length>0:!!file;
 return <section className="document-workbench"><div className="privacy-pill">🔒 Local browser processing</div><label className="document-drop"><input type="file" accept={accept} multiple={multi} onChange={async e=>{const list=Array.from(e.target.files||[]);setFiles(list);const f=list[0]||null;setFile(f);if(f&&pasteTool&&!/xlsx|docx|pdf/.test(accept))setValue(await f.text())}}/><b>{multi&&files.length?files.length+" files selected":file?file.name:"Choose "+tool.input+" file"}</b><span>{selected?"Ready to process":"Tap to browse · recommended maximum 25 MB"}</span></label>{pasteTool&&<label className="document-field"><span>Or paste structured text</span><textarea rows={10} value={value} onChange={e=>setValue(e.target.value)} placeholder="Paste content here…"/></label>}{(tool.slug.startsWith("text-to")||tool.slug==="json-to-xml")&&<label className="document-field"><span>{tool.slug==="json-to-xml"?"Root element name (optional)":"Optional title"}</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={tool.slug==="json-to-xml"?"root":"Document title"}/></label>}{/[Ee]xcel/.test(tool.title)&&!["merge-excel-files","split-excel-sheets"].includes(tool.slug)&&<label className="document-field"><span>Worksheet name (optional)</span><input value={sheet} onChange={e=>setSheet(e.target.value)} placeholder="Blank uses the first worksheet"/></label>}{["remove-duplicate-excel-rows","compare-two-excel-files"].includes(tool.slug)&&<label className="document-field"><span>Key column header (optional)</span><input value={keyColumn} onChange={e=>setKeyColumn(e.target.value)} placeholder="Blank compares complete rows"/></label>}<button className="pdf-action" disabled={busy||(!selected&&!value.trim())} onClick={run}>{busy?"Processing on your device…":tool.shortTitle}</button>{message&&<p className={"pdf-message "+(message.startsWith("Done")||message.includes("locally")||message.includes("Preview")?"success":"")} role="status">{message}</p>}{stats&&<dl className="metadata-grid">{Object.entries(stats).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}{preview&&(tool.slug==="docx-viewer"?<div className="document-preview" dangerouslySetInnerHTML={{__html:preview}}/>:<pre className="document-preview text-preview">{preview}</pre>)}<small className="pdf-legal">Review converted files before professional, legal or academic use. Advanced formatting and nested structures can vary.</small></section>
}
