"use client";
import {useState} from "react";
import type {DocumentTool as Tool} from "@/lib/document-tools";
declare global{interface Window{mammoth:any;pdfjsLib:any;XLSX:any;JSZip:any;jspdf:any}}
const cdn={mammoth:"https://cdn.jsdelivr.net/npm/mammoth@1.10.0/mammoth.browser.min.js",pdfjs:"https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js",xlsx:"https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js",zip:"https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js",jspdf:"https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js"};
const load=(src:string,key:string)=>new Promise<void>((ok,no)=>{if((window as any)[key])return ok();const old=document.querySelector('script[src="'+src+'"]');if(old){old.addEventListener("load",()=>ok());return}const s=document.createElement("script");s.src=src;s.onload=()=>ok();s.onerror=()=>no(new Error("A required browser library could not load. Check your connection."));document.head.appendChild(s)});
const save=(data:Blob|Uint8Array|string,name:string,type:string)=>{const blob=data instanceof Blob?data:new Blob([data as BlobPart],{type}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)};
const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
type Block={text:string;style?:"Title"|"Heading1"|"Heading2"|"ListParagraph"};
const markdownBlocks=(value:string):Block[]=>value.split(/\r?\n/).map(line=>{if(/^# /.test(line))return{text:line.slice(2),style:"Heading1"};if(/^## /.test(line))return{text:line.slice(3),style:"Heading2"};if(/^[-*] /.test(line))return{text:"• "+line.slice(2),style:"ListParagraph"};return{text:line.replace(/\*\*|__|`/g,"")}});
const textBlocks=(value:string,title:string):Block[]=>[...(title?[{text:title,style:"Title" as const}]:[]),...value.split(/\r?\n/).map(text=>({text}))];
const htmlBlocks=(html:string):Block[]=>{const doc=new DOMParser().parseFromString(html,"text/html");doc.querySelectorAll("script,style,iframe,object").forEach(x=>x.remove());const blocks:Block[]=[];doc.body.querySelectorAll("h1,h2,h3,p,li,blockquote,pre,td,th").forEach(el=>{const text=(el.textContent||"").trim();if(text)blocks.push({text:(el.tagName==="LI"?"• ":"")+text,style:el.tagName==="H1"?"Heading1":/^H[23]$/.test(el.tagName)?"Heading2":el.tagName==="LI"?"ListParagraph":undefined})});return blocks.length?blocks:textBlocks(doc.body.textContent||"","")};
const makeDocx=async(blocks:Block[])=>{await load(cdn.zip,"JSZip");const zip=new window.JSZip(),paras=blocks.map(b=>'<w:p>'+(b.style?'<w:pPr><w:pStyle w:val="'+b.style+'"/></w:pPr>':'')+'<w:r><w:t xml:space="preserve">'+esc(b.text)+'</w:t></w:r></w:p>').join("");zip.file("[Content_Types].xml",'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>');zip.folder("_rels")!.file(".rels",'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.folder("word")!.file("document.xml",'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+paras+'<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1080" w:right="1080" w:bottom="1080" w:left="1080"/></w:sectPr></w:body></w:document>');zip.folder("word")!.file("styles.xml",'<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="38"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:rPr><w:b/><w:sz w:val="26"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="ListParagraph"><w:name w:val="List Paragraph"/></w:style></w:styles>');return zip.generateAsync({type:"blob",mimeType:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"})};
const makePdf=async(blocks:Block[],name:string)=>{await load(cdn.jspdf,"jspdf");const doc=new window.jspdf.jsPDF({unit:"pt",format:"a4"}),width=515;let y=58;for(const b of blocks){const heading=b.style?.startsWith("Heading")||b.style==="Title",size=b.style==="Title"?20:b.style==="Heading1"?17:b.style==="Heading2"?14:11;doc.setFont("helvetica",heading?"bold":"normal");doc.setFontSize(size);const lines=doc.splitTextToSize(b.text||" ",width);if(y+lines.length*(size+4)>790){doc.addPage();y=58}doc.text(lines,40,y);y+=lines.length*(size+4)+(heading?8:4)}doc.save(name)};
export function DocumentTool({tool}:{tool:Tool}){
 const pasteTool=/markdown|text-to|html-to|json-to/.test(tool.slug),[file,setFile]=useState<File|null>(null),[value,setValue]=useState(""),[title,setTitle]=useState(""),[sheet,setSheet]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[preview,setPreview]=useState(""),[stats,setStats]=useState<Record<string,string>|null>(null);
 const readInput=async()=>value.trim()?value:file?file.text():"";
 const run=async()=>{setBusy(true);setMessage("");setPreview("");setStats(null);try{
  if(!file&&!value.trim())throw new Error("Choose a file or paste content first.");
  if(["docx-viewer","docx-word-counter","word-to-pdf"].includes(tool.slug)){if(!file)throw new Error("Choose a DOCX file.");await load(cdn.mammoth,"mammoth");const buffer=await file.arrayBuffer();if(tool.slug==="docx-viewer"){const result=await window.mammoth.convertToHtml({arrayBuffer:buffer});setPreview(result.value);setMessage("Preview created locally.");return}const raw=(await window.mammoth.extractRawText({arrayBuffer:buffer})).value.trim();if(tool.slug==="docx-word-counter"){const words=raw?raw.split(/\s+/).length:0;setStats({Words:String(words),Characters:String(raw.length),"Characters without spaces":String(raw.replace(/\s/g,"").length),Paragraphs:String(raw.split(/\n+/).filter((x:string)=>x.trim()).length),"Reading time":Math.max(1,Math.ceil(words/200))+" min"});setMessage("Document statistics calculated locally.");return}await makePdf(textBlocks(raw,file.name.replace(/\.docx$/i,"")),"word-document.pdf");setMessage("Done — PDF downloaded.");return}
  if(tool.slug==="extract-images-from-docx"){if(!file)throw new Error("Choose a DOCX file.");await load(cdn.zip,"JSZip");const source=await window.JSZip.loadAsync(await file.arrayBuffer()),out=new window.JSZip();let count=0;for(const name of Object.keys(source.files)){if(name.startsWith("word/media/")&&!source.files[name].dir){out.file(name.split("/").pop(),await source.files[name].async("uint8array"));count++}}if(!count)throw new Error("No embedded images were found.");save(await out.generateAsync({type:"blob"}),"docx-images.zip","application/zip");setMessage("Done — "+count+" image(s) downloaded in a ZIP.");return}
  if(tool.slug==="pdf-to-word"){if(!file)throw new Error("Choose a PDF file.");await load(cdn.pdfjs,"pdfjsLib");window.pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js";const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,blocks:Block[]=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),content=await page.getTextContent();blocks.push({text:"Page "+n,style:"Heading2"},{text:content.items.map((x:any)=>x.str).join(" ")})}save(await makeDocx(blocks),"pdf-text.docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document");setMessage("Done — editable text downloaded as DOCX.");return}
  if(["csv-to-excel","excel-to-csv","json-to-excel"].includes(tool.slug)){await load(cdn.xlsx,"XLSX");if(tool.slug==="excel-to-csv"){if(!file)throw new Error("Choose an Excel file.");const book=window.XLSX.read(await file.arrayBuffer(),{type:"array"}),name=sheet||book.SheetNames[0];if(!book.Sheets[name])throw new Error("Choose a valid worksheet.");save(window.XLSX.utils.sheet_to_csv(book.Sheets[name]),"spreadsheet.csv","text/csv;charset=utf-8");setMessage("Done — CSV downloaded.");return}const raw=await readInput();let ws;if(tool.slug==="json-to-excel"){const parsed=JSON.parse(raw),rows=Array.isArray(parsed)?parsed:[parsed];ws=window.XLSX.utils.json_to_sheet(rows);setPreview(JSON.stringify(rows.slice(0,5),null,2))}else{ws=window.XLSX.utils.csv_to_sheet(raw);setPreview(raw.split(/\r?\n/).slice(0,6).join("\n"))}const book=window.XLSX.utils.book_new();window.XLSX.utils.book_append_sheet(book,ws,"Data");window.XLSX.writeFile(book,tool.slug==="json-to-excel"?"json-data.xlsx":"csv-data.xlsx");setMessage("Done — Excel workbook downloaded.");return}
  const raw=await readInput(),blocks=tool.slug.startsWith("markdown")?markdownBlocks(raw):tool.slug.startsWith("html")?htmlBlocks(raw):textBlocks(raw,title);setPreview(blocks.slice(0,30).map(x=>x.text).join("\n"));if(tool.slug.endsWith("docx"))save(await makeDocx(blocks),tool.slug+".docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document");else await makePdf(blocks,tool.slug+".pdf");setMessage("Done — converted file downloaded.");
 }catch(e){setMessage(e instanceof Error?e.message:"The file could not be processed.")}finally{setBusy(false)}};
 const accept=tool.input.includes("docx")?".docx":tool.input.includes("pdf")?".pdf":tool.input.includes("csv")?".csv":tool.input.includes("xlsx")?".xlsx,.xls":tool.input.includes("json")?".json":tool.input.includes("html")?".html,.htm":tool.input.includes("md")?".md,.markdown":".txt";
 return <section className="document-workbench"><div className="privacy-pill">🔒 Local browser processing</div><label className="document-drop"><input type="file" accept={accept} onChange={async e=>{const f=e.target.files?.[0]||null;setFile(f);if(f&&pasteTool&&!/xlsx|docx|pdf/.test(accept))setValue(await f.text())}}/><b>{file?file.name:"Choose "+tool.input+" file"}</b><span>{file?"Ready to process":"Tap to browse · recommended maximum 25 MB"}</span></label>{pasteTool&&<label className="document-field"><span>Or paste {tool.input.includes("html")?"HTML":tool.input.includes("json")?"JSON":tool.input.includes("markdown")?"Markdown":"text"}</span><textarea rows={10} value={value} onChange={e=>setValue(e.target.value)} placeholder="Paste content here…"/></label>}{tool.slug.startsWith("text-to")&&<label className="document-field"><span>Optional title</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Document title"/></label>}{tool.slug==="excel-to-csv"&&<label className="document-field"><span>Worksheet name (optional)</span><input value={sheet} onChange={e=>setSheet(e.target.value)} placeholder="Blank uses the first worksheet"/></label>}<button className="pdf-action" disabled={busy||(!file&&!value.trim())} onClick={run}>{busy?"Processing on your device…":tool.shortTitle}</button>{message&&<p className={"pdf-message "+(message.startsWith("Done")||message.includes("locally")||message.includes("Preview")?"success":"")} role="status">{message}</p>}{stats&&<dl className="metadata-grid">{Object.entries(stats).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}{preview&&(tool.slug==="docx-viewer"?<div className="document-preview" dangerouslySetInnerHTML={{__html:preview}}/>:<pre className="document-preview text-preview">{preview}</pre>)}<small className="pdf-legal">Review converted files before professional, legal or academic use. Advanced formatting can vary.</small></section>
}
