"use client";
import {useMemo,useRef,useState} from "react";
import type {GeneratorTool as Tool} from "@/lib/generator-tools";

declare global{interface Window{QRCode:any;JsBarcode:any;jspdf:any;BarcodeDetector:any}}
const scripts={qr:"https://cdn.jsdelivr.net/npm/qrcode@1.5.4/build/qrcode.min.js",barcode:"https://cdn.jsdelivr.net/npm/jsbarcode@3.12.1/dist/JsBarcode.all.min.js",pdf:"https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js"};
const load=(src:string,key:string)=>new Promise<void>((ok,no)=>{if((window as any)[key])return ok();const old=document.querySelector('script[src="'+src+'"]');if(old){old.addEventListener("load",()=>ok(),{once:true});return}const s=document.createElement("script");s.src=src;s.onload=()=>ok();s.onerror=()=>no(new Error("A required browser library could not load. Check your connection and try again."));document.head.appendChild(s)});
const download=(url:string,name:string)=>{const a=document.createElement("a");a.href=url;a.download=name;a.click()};
const cleanPhone=(value:string)=>value.replace(/[^0-9+]/g,"").replace(/^\+/,"");
const escapeWifi=(value:string)=>value.replace(/([\\;,:"])/g,"\\$1");

export function GeneratorTool({tool}:{tool:Tool}){
 const initial=useMemo(()=>Object.fromEntries(tool.fields.map(x=>[x.name,x.type==="date"?new Date().toISOString().slice(0,10):""])),[tool.fields]);
 const[values,setValues]=useState<Record<string,string>>(initial),[size,setSize]=useState("360"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[result,setResult]=useState(""),[scanFile,setScanFile]=useState<File|null>(null);const svgRef=useRef<SVGSVGElement>(null);
 const set=(name:string,value:string)=>setValues(v=>({...v,[name]:value}));
 const payload=()=>{switch(tool.preset){case"wifi":return `WIFI:T:${escapeWifi(values.security||"WPA")};S:${escapeWifi(values.ssid||"")};P:${escapeWifi(values.password||"")};H:${String(values.hidden).toLowerCase()==="true"?"true":"false"};;`;case"whatsapp":return "https://wa.me/"+cleanPhone(values.phone||"")+(values.message?"?text="+encodeURIComponent(values.message):"");case"vcard":return `BEGIN:VCARD\nVERSION:3.0\nFN:${values.name||""}\nORG:${values.business||""}\nTEL:${values.phone||""}\nEMAIL:${values.email||""}\nEND:VCARD`;case"url":return values.url||"";case"email":return `mailto:${values.email||""}?subject=${encodeURIComponent(values.subject||"")}&body=${encodeURIComponent(values.message||"")}`;case"sms":return `SMSTO:${cleanPhone(values.phone||"")}:${values.message||""}`;default:return values.value||""}};
 const validate=()=>{for(const field of tool.fields)if(field.required&&!String(values[field.name]||"").trim())throw new Error("Complete the “"+field.label+"” field first.")};
 const makeQr=async()=>{validate();await load(scripts.qr,"QRCode");const data=payload();if(!data)throw new Error("Enter content to encode.");const url=await window.QRCode.toDataURL(data,{width:Number(size),margin:2,errorCorrectionLevel:"M",color:{dark:"#0b1b4b",light:"#ffffff"}});setResult(url);setMessage("QR code generated locally. Scan-test it before publishing.")};
 const makeBarcode=async()=>{validate();await load(scripts.barcode,"JsBarcode");if(!svgRef.current)throw new Error("Barcode preview is unavailable.");window.JsBarcode(svgRef.current,values.value,{format:"CODE128",displayValue:true,lineColor:"#0b1b4b",background:"#ffffff",height:92,margin:18,fontSize:17});const xml=new XMLSerializer().serializeToString(svgRef.current),url="data:image/svg+xml;base64,"+btoa(unescape(encodeURIComponent(xml)));setResult(url);setMessage("CODE128 barcode generated locally. Test it before printing.")};
 const scan=async()=>{if(!scanFile)throw new Error("Choose an image containing a code first.");if(!("BarcodeDetector" in window))throw new Error("This browser does not support image barcode detection. Try current Chrome or Edge on Android or desktop.");const formats=tool.preset==="qr"?["qr_code"]:["code_128","code_39","code_93","codabar","ean_13","ean_8","itf","upc_a","upc_e","qr_code"],bitmap=await createImageBitmap(scanFile),detector=new window.BarcodeDetector({formats}),codes=await detector.detect(bitmap);bitmap.close();if(!codes.length)throw new Error("No readable code was found. Use a sharper, well-lit image with space around the code.");setResult(codes.map((x:any)=>`${x.format}: ${x.rawValue}`).join("\n"));setMessage("Code decoded locally from the selected image.")};
 const makeDocument=async()=>{validate();await load(scripts.pdf,"jspdf");const doc=new window.jspdf.jsPDF({unit:"pt",format:"a4"}),w=595,h=842,blue=[11,27,75],accent=[35,108,255],muted=[99,112,146],title=tool.preset||tool.shortTitle;doc.setFillColor(...blue);doc.rect(0,0,w,tool.preset==="Letterhead"?105:125,"F");doc.setTextColor(255,255,255);doc.setFont("helvetica","bold");doc.setFontSize(tool.preset==="Business Card"?25:22);doc.text(values.business||title,42,52);doc.setFont("helvetica","normal");doc.setFontSize(10);if(tool.preset!=="Business Card")doc.text(title.toUpperCase(),42,82);doc.setTextColor(...blue);let y=165;
  if(tool.preset==="Business Card"){doc.setFillColor(246,249,255);doc.roundedRect(72,210,451,255,18,18,"F");doc.setFont("helvetica","bold");doc.setFontSize(28);doc.text(values.customer,105,275);doc.setTextColor(...accent);doc.setFontSize(14);doc.text(values.details||"",105,307);doc.setTextColor(...blue);doc.setFontSize(16);doc.text(values.business||"",105,350);doc.setFont("helvetica","normal");doc.setFontSize(11);[values.phone,values.email,values.notes].filter(Boolean).forEach((v,i)=>doc.text(String(v),105,391+i*24));}
  else if(tool.preset==="Letterhead"){doc.setFontSize(11);doc.setTextColor(...muted);const contact=[values.details,values.phone,values.email,values.notes].filter(Boolean).join("  •  ");doc.text(doc.splitTextToSize(contact,510),42,132);doc.setDrawColor(220,228,242);doc.line(42,165,553,165);doc.setTextColor(...muted);doc.text("Your letter content begins here.",42,205);doc.line(42,740,553,740);doc.setFontSize(9);doc.text(values.notes||values.business,42,765);}
  else{const pairs=[["Document number",values.number],["Issue date",values.date],[tool.preset==="Payslip"?"Employee":"Customer / recipient",values.customer]];pairs.forEach(([k,v])=>{doc.setFont("helvetica","bold");doc.setFontSize(9);doc.setTextColor(...muted);doc.text(String(k).toUpperCase(),42,y);doc.setFont("helvetica","normal");doc.setFontSize(12);doc.setTextColor(...blue);doc.text(String(v||"—"),42,y+19);y+=54});doc.setDrawColor(221,229,243);doc.line(42,y,553,y);y+=35;doc.setFont("helvetica","bold");doc.setFontSize(10);doc.setTextColor(...muted);doc.text(tool.preset==="Timesheet"?"WORK SUMMARY":"DETAILS",42,y);y+=22;doc.setFont("helvetica","normal");doc.setFontSize(11);doc.setTextColor(...blue);doc.text(doc.splitTextToSize(values.details||"",510),42,y);y+=Math.max(55,doc.splitTextToSize(values.details||"",510).length*15+22);doc.setFillColor(241,247,255);doc.roundedRect(338,y,215,64,10,10,"F");doc.setFont("helvetica","bold");doc.setFontSize(10);doc.setTextColor(...muted);doc.text(tool.preset==="Timesheet"?"TOTAL HOURS":"TOTAL AMOUNT",356,y+23);doc.setFontSize(18);doc.setTextColor(...accent);doc.text(String(values.amount||"0"),356,y+49);y+=95;if(values.notes){doc.setFontSize(10);doc.setTextColor(...muted);doc.text("NOTES",42,y);doc.setFont("helvetica","normal");doc.setTextColor(...blue);doc.text(doc.splitTextToSize(values.notes,510),42,y+20)}}doc.setFont("helvetica","normal");doc.setFontSize(8);doc.setTextColor(...muted);doc.text("Generated with SolvePilot · Review all details before use",42,h-34);doc.save(tool.slug+".pdf");setMessage(title+" PDF generated and downloaded. Review it before sharing.")};
 const run=async()=>{setBusy(true);setMessage("");try{if(tool.kind==="qr")await makeQr();else if(tool.kind==="barcode")await makeBarcode();else if(tool.kind==="scanner")await scan();else await makeDocument()}catch(e){setMessage(e instanceof Error?e.message:"The result could not be created.")}finally{setBusy(false)}};
 const success=/generated|decoded|downloaded/i.test(message);
 return <section className="generator-workbench"><div className="privacy-pill">🔒 Private browser processing</div>{tool.kind==="scanner"?<label className="generator-upload"><input type="file" accept="image/*" onChange={e=>setScanFile(e.target.files?.[0]||null)}/><b>{scanFile?scanFile.name:"Choose a QR or barcode image"}</b><span>Use a sharp image with good contrast and space around the code.</span></label>:<div className="generator-fields">{tool.fields.map(field=><label className={field.type==="textarea"?"wide":""} key={field.name}><span>{field.label}{!field.required&&<small> Optional</small>}</span>{field.type==="textarea"?<textarea rows={4} value={values[field.name]||""} placeholder={field.placeholder} onChange={e=>set(field.name,e.target.value)}/>:<input type={field.type||"text"} value={values[field.name]||""} placeholder={field.placeholder} onChange={e=>set(field.name,e.target.value)}/>}</label>)}{tool.kind==="qr"&&<label><span>Image size</span><select value={size} onChange={e=>setSize(e.target.value)}><option value="240">240 × 240</option><option value="360">360 × 360</option><option value="600">600 × 600</option><option value="900">900 × 900</option></select></label>}</div>}<button className="pdf-action" disabled={busy} onClick={run}>{busy?"Working on your device…":tool.kind==="scanner"?"Scan image":tool.kind==="document"?"Generate and download PDF":"Generate "+tool.shortTitle}</button>{message&&<p className={"pdf-message "+(success?"success":"")} role="status">{message}</p>}{tool.kind==="barcode"&&<div className="code-preview"><svg ref={svgRef}/>{result&&<button onClick={()=>download(result,tool.slug+".svg")}>Download SVG</button>}</div>}{tool.kind==="qr"&&result&&<div className="code-preview"><img src={result} alt="Generated QR code preview"/><button onClick={()=>download(result,tool.slug+".png")}>Download PNG</button></div>}{tool.kind==="scanner"&&result&&<pre className="scan-result">{result}</pre>}<small className="pdf-legal">Generated output is not stored by SolvePilot. Keep your own copy and verify it before professional, financial or public use.</small></section>
}
