"use client";
import {useState} from 'react';
import {generateSphere,sphereCsv,type SphereModel} from '@/lib/minecraft-sphere';
export function MinecraftSphereTool(){
 const [diameter,setDiameter]=useState('16'),[mode,setMode]=useState<'solid'|'hollow'>('hollow'),[model,setModel]=useState<SphereModel|null>(null),[layer,setLayer]=useState(0),[error,setError]=useState('');
 const changed=model&&(diameter!==String(model.diameter)||mode!==model.mode);
 const calculate=()=>{try{if(!diameter.trim())throw Error('Enter an integer diameter from 1–64.');const next=generateSphere(Number(diameter),mode);setModel(next);setLayer(Math.floor(next.diameter/2));setError('');}catch(e){setError(e instanceof Error?e.message:'Check inputs.');}};
 const download=()=>{if(!model)return;const url=URL.createObjectURL(new Blob([sphereCsv(model)],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`sphere-${model.diameter}-${model.mode}.csv`;anchor.click();URL.revokeObjectURL(url);};
 return <section className="calculator-shell" aria-label="Minecraft sphere generator"><div className="calc-inputs"><div className="calc-title"><span>Sphere layer planner</span><strong>Your values stay on this device</strong></div><label className="field"><span>Sphere diameter in blocks</span><div><input aria-label="Sphere diameter in blocks" value={diameter} inputMode="numeric" onChange={e=>setDiameter(e.target.value)}/></div></label><label className="field"><span>Sphere mode</span><div><select aria-label="Sphere mode" value={mode} onChange={e=>setMode(e.target.value as 'solid'|'hollow')}><option value="hollow">Hollow six-neighbor shell</option><option value="solid">Solid sphere</option></select></div></label><button className="calculate-button" onClick={calculate}>Calculate sphere <span>→</span></button><p>Diameter is 1–64 whole blocks. Output uses a center-distance voxel rule, not official Minecraft commands.</p></div><div className="calc-results show" aria-live="polite"><div className="result-badge">{!model?'Ready to calculate':changed?'Inputs changed — click Calculate to update':'✓ Calculated sphere'}</div>{error&&<p role="alert">{error}</p>}{model?<><p>{model.mode==='solid'?'Solid sphere':'Hollow sphere'} block count</p><h2>{model.blocks.toLocaleString('en-US')}</h2><label className="field"><span>View generated Y layer</span><div><select aria-label="View generated Y layer" value={layer} onChange={e=>setLayer(Number(e.target.value))}>{model.layers.map((_,y)=><option key={y} value={y}>Y = {y} ({model.layers[y].length} blocks)</option>)}</select></div></label><svg role="img" aria-label={`Generated layer Y ${layer}: ${model.layers[layer].length} filled blocks; X left to right, Z top to bottom`} viewBox={`0 0 ${model.diameter} ${model.diameter}`} style={{width:'100%',maxWidth:480,background:'#f1f5f9',border:'1px solid #94a3b8'}}>{model.layers[layer].map(([x,z])=><rect key={`${x}-${z}`} x={x} y={z} width={1} height={1} fill="#2563eb" stroke="#f1f5f9" strokeWidth={.06}/>)}</svg><p>Blue cells are blocks. X increases left to right; Z increases top to bottom. Coordinates are zero-based, with Y counting upward.</p><button type="button" className="calculate-button" onClick={download}>Download generated coordinates (CSV)</button></>:<><p>Your result</p><h2>Click Calculate</h2><small>Generate the layers before viewing or exporting coordinates.</small></>}</div></section>;
}
