"use client";
import {useState} from "react";
import type {PdfTool as Tool} from "@/lib/pdf-tools";
declare global{interface Window{PDFLib:any;pdfjsLib:any;JSZip:any}}
const urls={pdf:"https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js",pdfjs:"https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js",zip:"https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js"};
const load=(src:string,key:string)=>new Promise<void>((ok,no)=>{if((window as any)[key])return ok();const s=document.createElement("script");s.src=src;s.onload=()=>ok();s.onerror=()=>no(new Error("A processing library could not load. Check your connection."));document.head.appendChild(s)});
const download=(data:Uint8Array|Blob,name:string,type="application/pdf")=>{const b=data instanceof Blob?data:new Blob([data as BlobPart],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)};
const range=(value:string,total:number)=>{const found:number[]=[];for(const part of value.split(",").map(x=>x.trim()).filter(Boolean)){const m=part.match(/^(\d+)(?:-(\d+))?$/);if(!m)throw new Error("Invalid page range: "+part);const a=+m[1],b=+(m[2]||m[1]);if(a<1||b<a||b>total)throw new Error("Pages must stay between 1 and "+total+".");for(let n=a;n<=b;n++)if(!found.includes(n-1))found.push(n-1)}if(!found.length)throw new Error("Enter at least one page.");return found};
export function PdfTool({tool}:{tool:Tool}){
 const [files,setFiles]=useState<File[]>([]),[pages,setPages]=useState(""),[text,setText]=useState("CONFIDENTIAL"),[option,setOption]=useState("90"),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[metadata,setMetadata]=useState<Record<string,string>|null>(null);
 const multi=["merge-pdf","images-to-pdf"].includes(tool.slug),images=tool.slug==="images-to-pdf";
 const run=async()=>{if(!files.length)return;setBusy(true);setMessage("");setMetadata(null);try{
  if(["protect-pdf-password","unlock-pdf"].includes(tool.slug)){if(!password)throw new Error("Enter the PDF password.");const url="https://cdn.jsdelivr.net/npm/qpdf-wasm-esm-embedded@1.1.1/+esm";const pkg=await import(/* webpackIgnore: true */ url);const qpdf=await (pkg as any).default({noInitialRun:true});qpdf.FS.writeFile("/input.pdf",new Uint8Array(await files[0].arrayBuffer()));qpdf.callMain(tool.slug==="protect-pdf-password"?["--encrypt",password,password,"256","--","/input.pdf","/output.pdf"]:["--password="+password,"--decrypt","/input.pdf","/output.pdf"]);download(qpdf.FS.readFile("/output.pdf"),tool.slug==="protect-pdf-password"?"protected.pdf":"unlocked.pdf");setMessage("Done — your PDF is ready.");return}
  await load(urls.pdf,"PDFLib");const {PDFDocument,degrees,rgb,StandardFonts}=window.PDFLib;
  if(tool.slug==="images-to-pdf"){const out=await PDFDocument.create();for(const file of files){const bytes=await file.arrayBuffer(),img=file.type==="image/png"?await out.embedPng(bytes):await out.embedJpg(bytes),scale=Math.min(1,595/img.width),page=out.addPage([img.width*scale,img.height*scale]);page.drawImage(img,{x:0,y:0,width:page.getWidth(),height:page.getHeight()})}download(await out.save(),"images.pdf");setMessage("Done — your images are now one PDF.");return}
  const source=await PDFDocument.load(await files[0].arrayBuffer(),{ignoreEncryption:true}),total=source.getPageCount();
  if(tool.slug==="pdf-metadata-viewer"){setMetadata({Pages:String(total),Title:source.getTitle()||"Not set",Author:source.getAuthor()||"Not set",Subject:source.getSubject()||"Not set",Keywords:source.getKeywords()||"Not set",Created:source.getCreationDate()?.toLocaleString()||"Not set",Modified:source.getModificationDate()?.toLocaleString()||"Not set"});setMessage("Metadata read locally. The PDF was not changed.");return}
  if(tool.slug==="pdf-to-images"){await load(urls.pdfjs,"pdfjsLib");await load(urls.zip,"JSZip");window.pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js";const doc=await window.pdfjsLib.getDocument({data:new Uint8Array(await files[0].arrayBuffer())}).promise,zip=new window.JSZip();for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n),view=page.getViewport({scale:option==="2"?2:1.4}),canvas=document.createElement("canvas");canvas.width=view.width;canvas.height=view.height;await page.render({canvasContext:canvas.getContext("2d"),viewport:view}).promise;const blob=await new Promise<Blob>(r=>canvas.toBlob(b=>r(b!),"image/png"));zip.file("page-"+n+".png",blob)}download(await zip.generateAsync({type:"blob"}),"pdf-images.zip","application/zip");setMessage("Done — PNG pages are in the ZIP.");return}
  let out=await PDFDocument.create();
  if(tool.slug==="merge-pdf"){for(const file of files){const doc=await PDFDocument.load(await file.arrayBuffer()),copied=await out.copyPages(doc,doc.getPageIndices());copied.forEach((p:any)=>out.addPage(p))}}
  else if(tool.slug==="split-pdf"){await load(urls.zip,"JSZip");const groups=pages?pages.split(";").filter(Boolean).map(x=>range(x,total)):source.getPageIndices().map((x:number)=>[x]),zip=new window.JSZip();for(let i=0;i<groups.length;i++){const doc=await PDFDocument.create(),copied=await doc.copyPages(source,groups[i]);copied.forEach((p:any)=>doc.addPage(p));zip.file("part-"+(i+1)+".pdf",await doc.save())}download(await zip.generateAsync({type:"blob"}),"split-pdf.zip","application/zip");setMessage("Done — split files are in the ZIP.");return}
  else if(["extract-pdf-pages","reorder-pdf-pages","delete-pdf-pages"].includes(tool.slug)){const chosen=range(pages,total),indices=tool.slug==="delete-pdf-pages"?source.getPageIndices().filter((x:number)=>!chosen.includes(x)):chosen;if(!indices.length)throw new Error("At least one page must remain.");const copied=await out.copyPages(source,indices);copied.forEach((p:any)=>out.addPage(p))}
  else{out=source;if(tool.slug==="rotate-pdf-pages"){const chosen=pages?range(pages,total):source.getPageIndices();chosen.forEach((i:number)=>{const p=out.getPage(i);p.setRotation(degrees((p.getRotation().angle+(+option))%360))})}if(tool.slug==="add-pdf-watermark"){const font=await out.embedFont(StandardFonts.HelveticaBold);out.getPages().forEach((p:any)=>{const size=Math.max(18,Math.min(42,p.getWidth()/12)),w=font.widthOfTextAtSize(text,size),pos=option==="top"?{x:(p.getWidth()-w)/2,y:p.getHeight()-55}:option==="bottom"?{x:(p.getWidth()-w)/2,y:35}:{x:(p.getWidth()-w)/2,y:p.getHeight()/2};p.drawText(text,{...pos,size,font,color:rgb(.35,.4,.5),opacity:.22,rotate:degrees(option==="center"?35:0)})})}if(tool.slug==="add-page-numbers-pdf"){const font=await out.embedFont(StandardFonts.Helvetica);out.getPages().forEach((p:any,i:number)=>{const label=String((+pages||1)+i),size=11,w=font.widthOfTextAtSize(label,size),x=option.includes("left")?36:option.includes("right")?p.getWidth()-w-36:(p.getWidth()-w)/2,y=option.includes("top")?p.getHeight()-36:28;p.drawText(label,{x,y,size,font,color:rgb(.25,.28,.34)})})}if(tool.slug==="remove-pdf-metadata"){out.setTitle("");out.setAuthor("");out.setSubject("");out.setKeywords([]);out.setProducer("SolvePilot private PDF tool");out.setCreator("")}}
  download(await out.save(),tool.slug+".pdf");setMessage("Done — your processed PDF is ready.");
 }catch(e){setMessage(e instanceof Error?e.message:"The PDF could not be processed.")}finally{setBusy(false)}};
 const pageField=["split-pdf","extract-pdf-pages","reorder-pdf-pages","rotate-pdf-pages","delete-pdf-pages"].includes(tool.slug),pass=["protect-pdf-password","unlock-pdf"].includes(tool.slug),opts=["rotate-pdf-pages","pdf-to-images","add-pdf-watermark","add-page-numbers-pdf"].includes(tool.slug);
 return <section className="pdf-workbench"><div className="privacy-pill">🔒 Files stay on this device</div><label className="pdf-drop"><input type="file" accept={images?"image/jpeg,image/png":"application/pdf"} multiple={multi} onChange={e=>setFiles(Array.from(e.target.files||[]))}/><b>{files.length?files.length+" file(s) selected":"Choose "+(images?"images":"PDF file"+(multi?"s":""))}</b><span>{files.length?files.map(f=>f.name).join(", "):"Tap to browse · recommended maximum 50 MB"}</span></label>{pageField&&<label className="pdf-field"><span>{tool.slug==="split-pdf"?"Ranges separated by semicolons (blank = every page)":"Pages or ranges"}</span><input value={pages} onChange={e=>setPages(e.target.value)} placeholder={tool.slug==="split-pdf"?"1-3; 4-6":"1-3,5,8-10"}/></label>}{tool.slug==="add-pdf-watermark"&&<label className="pdf-field"><span>Watermark text</span><input value={text} maxLength={80} onChange={e=>setText(e.target.value)}/></label>}{pass&&<label className="pdf-field"><span>{tool.slug==="unlock-pdf"?"Current password":"New password"}</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>}{opts&&<label className="pdf-field"><span>Option</span><select value={option} onChange={e=>setOption(e.target.value)}>{tool.slug==="rotate-pdf-pages"?<><option value="90">90° clockwise</option><option value="180">180°</option><option value="270">270°</option></>:tool.slug==="pdf-to-images"?<><option value="1">Normal resolution</option><option value="2">High resolution</option></>:tool.slug==="add-pdf-watermark"?<><option value="center">Diagonal centre</option><option value="top">Top centre</option><option value="bottom">Bottom centre</option></>:<><option value="bottom-center">Bottom centre</option><option value="bottom-left">Bottom left</option><option value="bottom-right">Bottom right</option><option value="top-center">Top centre</option><option value="top-left">Top left</option><option value="top-right">Top right</option></>}</select></label>}{tool.slug==="add-page-numbers-pdf"&&<label className="pdf-field"><span>Starting number</span><input type="number" min="0" value={pages||"1"} onChange={e=>setPages(e.target.value)}/></label>}<button className="pdf-action" disabled={busy||!files.length} onClick={run}>{busy?"Processing on your device…":tool.shortTitle}</button>{message&&<p className={"pdf-message "+(message.startsWith("Done")||message.includes("locally")?"success":"")} role="status">{message}</p>}{metadata&&<dl className="metadata-grid">{Object.entries(metadata).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}<small className="pdf-legal">Use only documents you own or are authorized to modify. Keep a backup of the original.</small></section>
}
