type EditorialTool={title:string;shortTitle:string;category:string;description:string;keywords:string[];features:string[]};

export function Phase6Editorial({tool}:{tool:EditorialTool}){
 const name=tool.shortTitle,primary=tool.keywords[0]||tool.shortTitle.toLowerCase(),secondary=tool.keywords[1]||primary,featureA=tool.features[0]||"browser-based output",featureB=tool.features[1]||"editable inputs",isCode=tool.category==="QR & Barcode",isBusiness=tool.category==="Business Documents",isCareer=tool.category==="Career Tools";
 const context=isCode?"encoded content, destination, format and intended print size":isBusiness?"names, dates, reference numbers, amounts and local record requirements":isCareer?"role, employer, experience, dates and evidence supporting each professional claim":"class, institution, participants, dates, source material and the required output format";
 const result=isCode?"scan the finished code with a second device and confirm that its decoded value is exact":isBusiness?"read the document from top to bottom, recalculate figures and confirm that every party can identify the transaction":isCareer?"compare the result with the vacancy and your real employment record, then rewrite any statement that sounds generic or unsupported":"compare the result with the original records and the receiving institution's instructions before printing or submitting it";
 const risk=isCode?"an incorrect link, weak contrast or unsuitable physical size":isBusiness?"an incorrect amount, identity, date, tax treatment or document sequence":isCareer?"an exaggerated claim, missing evidence, unclear date or wording that does not match the target role":"an incorrect name, score, citation, schedule, attendance record or formatting requirement";
 return <>
  <section><h2>Plan the information before using {name}</h2><p>A reliable {primary} begins with complete source information rather than guesses entered while creating the result. Collect the {context}. Decide who will receive the output, what they need to understand and whether an organisation has supplied a required format. This preparation reduces corrections and helps the generated result remain focused on its real purpose.</p><p>Separate confirmed facts from optional wording. Keep original records open while working and avoid relying on memory for dates, identifiers or numeric values. The {featureA.toLowerCase()} feature is useful for preparing a first result, but it cannot know whether the supplied facts are complete. If several people provide information, assign one person to verify the final version.</p></section>
  <section><h2>How to review the generated result</h2><p>After using {name}, pause before downloading, printing or publishing. First, {result}. Then compare spelling, capitalization, punctuation and number formatting with the source. Review the result at the size and on the device where it will actually be used. A technically generated file can still fail its practical purpose when important content is difficult to see or understand.</p><p>Use the {featureB.toLowerCase()} option to correct problems rather than editing around them later. Check whether the result answers the intended task without requiring hidden context. Ask another person to review high-impact material when possible. A second reader often notices ambiguous wording, transposed digits and missing information that the creator overlooks after repeatedly viewing the same draft.</p></section>
  <section><h2>Quality standards for {secondary}</h2><p>Quality depends on accuracy, clarity and fitness for purpose—not simply whether a file was created successfully. A strong result uses consistent terminology, presents essential information in a logical order and avoids claims that cannot be supported. Remove filler that distracts from the task, but retain limitations, instructions or identifiers the recipient needs to interpret the output correctly.</p><p>Search intent also matters for a public-facing tool page. People looking for {secondary} normally want an immediate working tool followed by concise instructions and dependable context. This page places the interactive tool first, explains its method and states what it cannot verify. That structure supports users without pretending that automated output replaces professional judgment or an organisation's official procedure.</p></section>
  <section><h2>Common mistakes and how to avoid them</h2><p>The most serious mistake is treating generated output as verified output. Watch especially for {risk}. Other frequent problems include copying stale information, leaving a placeholder unchanged, selecting the wrong unit or format and assuming requirements are identical everywhere. Reopen the inputs when something looks wrong instead of manually covering the visible symptom.</p><p>Do not add information merely to make the result appear more complete. Unknown values should be researched, requested from the responsible person or clearly left for later completion. Save an approved source copy when the result forms part of a business, employment or academic record. For public material, preview it on mobile and desktop and confirm that links, labels and downloadable files behave as expected.</p></section>
  <section><h2>Privacy, accessibility and responsible sharing</h2><p>{name} works in the browser so the values you enter are not intentionally submitted to SolvePilot. Browser processing still requires sensible device security. Avoid working on a shared device with sensitive personal data, close the page after use and store downloaded files in an appropriate location. Remove test copies and do not publish private identifiers simply because the tool allows them to be entered.</p><p>Make the result usable for its intended audience. Prefer readable language, sufficient contrast, meaningful labels and a logical order. Provide an accessible alternative when a visual code, complex table or printed document would exclude someone. Before sharing, confirm permission to use personal names, contact details, signatures, logos and third-party material. The creator remains responsible for the final content and distribution.</p></section>
  <section><h2>Keeping the output current</h2><p>A saved result represents the inputs and assumptions used at one moment. Review it when a price, role, schedule, policy, contact detail or official requirement changes. Do not keep distributing an old copy because it still opens correctly. Add a meaningful filename or internal date so collaborators can distinguish the current version from drafts without exposing unnecessary personal data.</p><p>Return to this {name} page when the underlying information changes and create a clean replacement. Keep supporting evidence separately because the generated output does not create an audit trail or prove that a fact was correct. For regulated, contractual, financial, employment or academic use, check the latest instructions from the responsible authority and obtain qualified advice where necessary.</p></section>
 </>
}

