'use client';
import {useState} from 'react';
import {redactText} from '../lib/text-redaction';
export function RedactedTextTool(){
 const [source,setSource]=useState('Contact Alex at alex@example.com about the draft.'),[phrases,setPhrases]=useState('alex@example.com\nAlex'),[ignoreCase,setIgnoreCase]=useState(true),[output,setOutput]=useState<{text:string;matches:number}|null>(null),[error,setError]=useState(''),[changed,setChanged]=useState(false);
 const generate=()=>{try{setOutput(redactText(source,phrases,ignoreCase));setError('');setChanged(false)}catch(e){setError(e instanceof Error?e.message:'Unable to generate text.')}};
 const download=()=>{if(!output)return;const url=URL.createObjectURL(new Blob([output.text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='redacted-text.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <section className="calculator-shell text-redaction-tool" aria-label="Redacted text generator"><div className="calc-inputs"><div className="calc-title"><span>Plain-text redaction</span><strong>Text is processed on this device</strong></div><label className="field"><span>Original plain text (maximum 100,000 characters)</span><textarea aria-label="Original plain text" rows={8} maxLength={100000} value={source} onChange={e=>{setSource(e.target.value);setChanged(true)}}/></label><label className="field"><span>Literal phrases to replace, one per line</span><textarea aria-label="Phrases to redact" rows={5} maxLength={50100} value={phrases} onChange={e=>{setPhrases(e.target.value);setChanged(true)}}/></label><label><input type="checkbox" checked={ignoreCase} onChange={e=>{setIgnoreCase(e.target.checked);setChanged(true)}}/> Match regardless of letter case</label><button className="calculate-button" onClick={generate}>Generate redacted text →</button><button className="clear-text-button" onClick={()=>{setSource('');setPhrases('');setOutput(null);setError('');setChanged(false)}}>Clear text and result</button>{error&&<p role="alert">{error}</p>}</div><div className="calc-results show" aria-live="polite"><p>{output?`${output.matches} matches replaced${changed?' — inputs changed; generate again':''}`:'Click Generate redacted text'}</p>{output&&<><textarea aria-label="Generated redacted text" readOnly rows={12} value={output.text}/><button className="calculate-button" onClick={download}>Download redacted TXT →</button><p>Review every line before sharing. Only this generated plain text is downloaded.</p></>}</div></section>
}
