export type ArchiveTool={slug:string;title:string;shortTitle:string;icon:string;description:string;keywords:string[];accept:string;output:string;intro:string;method:string;example:string;howTo:string[];features:string[];faqs:{question:string;answer:string}[]};
const common=(name:string)=>[
 {question:`Is ${name} free to use?`,answer:"Yes. The tool is free, needs no account and does not add branding to the archive or extracted files."},
 {question:"Are my archive files uploaded?",answer:"No. Supported archive processing runs in your browser. SolvePilot does not receive or store the selected files."},
 {question:"Can I use it on a phone?",answer:"Yes, for modest archives. A desktop browser is more reliable when an archive contains many files or needs substantial memory."},
 {question:"Will the original archive be changed?",answer:"No. The source remains untouched. The tool creates a separate archive or separate extracted-file download."},
 {question:"What happens with damaged archives?",answer:"Damaged, incomplete, unsupported or strongly encrypted archives may fail. Keep the source and verify every important output file."}
];
const make=(slug:string,title:string,shortTitle:string,icon:string,description:string,keywords:string[],accept:string,output:string,intro:string,method:string,example:string,howTo:string[],features:string[],extra?:{question:string;answer:string}):ArchiveTool=>({slug,title,shortTitle,icon,description,keywords,accept,output,intro,method,example,howTo,features,faqs:[...(extra?[extra]:[]),...common(shortTitle)].slice(0,5)});
export const archiveTools:ArchiveTool[]=[
make("create-zip-file","Create ZIP File Online","Create ZIP File","🗜️","Create a ZIP file online from multiple selected files with adjustable compression and private processing directly in your browser.",["create zip file online","make zip file","compress files to zip"],"*/*",".zip","Bundle related documents, images or project files into one portable ZIP download without sending the selected content to a server.","The browser reads each selected file, applies DEFLATE compression and writes a new standards-based ZIP container.","Select a 2 MB document and a 5 MB image, choose balanced compression and receive one ZIP containing both files in their selected order.",["Choose one or more files.","Select the compression level and review the file list.","Create and download the new ZIP archive."],["Multiple files","Original filenames","Compression control"]),
make("extract-zip-file","Extract ZIP File Online","Extract ZIP File","📦","Extract ZIP files online, preview contained paths and download selected contents privately without uploading the archive to a server.",["extract zip file online","unzip files online","open zip file"],".zip,application/zip","extracted files","Open an ordinary ZIP archive, inspect its folders and save the contained files on the current device.","The ZIP directory is read locally, each selected entry is decompressed and a new download is created. Folder-only records are ignored while file names are sanitized for downloads.","Choose backup.zip, inspect ten contained entries and download the required document, or package all extracted entries into a fresh ZIP for one convenient download.",["Choose a ZIP archive.","Review the detected files and folders.","Extract and download the contents."],["Entry preview","Local decompression","Batch download"],{question:"Can this extract password-protected ZIP files?",answer:"Yes, when the ZIP encryption method is supported and you enter the correct password. It cannot discover, guess or bypass an unknown password."}),
make("password-protect-zip-file","Password Protect ZIP File Online","Password Protect ZIP","🔐","Create a password-protected ZIP file online with AES encryption and private local processing for files you are authorized to secure.",["password protect zip file","encrypt zip online","create password protected zip"],"*/*","encrypted .zip","Protect authorized personal or business files by creating a new encrypted ZIP that requires the password you choose.","Files are compressed locally and written to a ZIP using AES encryption. The password is used only in the active browser session and is not transmitted to SolvePilot.","Select three statements, enter a strong unique passphrase and download encrypted-files.zip. Test it in the intended unzip application before deleting any original.",["Choose the files you are authorized to protect.","Enter and confirm a strong password.","Create, download and test the encrypted ZIP."],["AES encryption","Password confirmation","Local processing"],{question:"Can SolvePilot recover my ZIP password?",answer:"No. Keep the password securely. This tool does not store it and cannot recover or bypass an unknown password."}),
make("rar-to-zip-converter","RAR to ZIP Converter Online","RAR to ZIP","🔁","Convert RAR archives to ZIP online by extracting supported entries locally and repackaging them in a widely compatible ZIP file.",["rar to zip converter","convert rar to zip online","open rar as zip"],".rar,application/vnd.rar",".zip","Repackage an accessible RAR archive as ZIP for software and devices that do not conveniently open RAR files.","A browser archive engine decodes supported RAR entries in memory, then a ZIP writer packages the extracted file data without intentionally changing document contents.","Choose photos.rar containing six images and receive photos.zip with the same usable files and folder paths, subject to browser-engine compatibility.",["Choose an unencrypted or authorized RAR archive.","Wait while compatible entries are read locally.","Download the newly created ZIP and verify it."],["RAR extraction","ZIP repackaging","Folder preservation"],{question:"Does it support every RAR version?",answer:"No browser converter supports every archive variation. Multi-volume, damaged, newer encrypted or unusual compression archives may require desktop software."}),
make("7z-to-zip-converter","7Z to ZIP Converter Online","7Z to ZIP","🧰","Convert supported 7Z archives to ZIP online with private browser processing, preserved folders and a separate downloadable output archive.",["7z to zip converter","convert 7z to zip online","7zip to zip"],".7z,application/x-7z-compressed",".zip","Turn an accessible 7Z package into a broadly supported ZIP while keeping the source archive unchanged.","The browser archive engine expands supported 7Z entries in local memory. A separate ZIP writer then stores those bytes using standard ZIP compression.","Select records.7z, allow the browser to decode its folders, and download records.zip for a recipient whose software accepts ZIP but not 7Z.",["Choose a supported 7Z archive.","Allow local extraction and review any compatibility message.","Download and test the converted ZIP."],["7Z decoding","Standard ZIP output","No server upload"],{question:"Will ZIP be the same size as 7Z?",answer:"Usually not. 7Z and ZIP use different compression methods, so the ZIP may be larger even though the extracted file content is unchanged."}),
make("tar-gz-extractor","TAR.GZ Extractor Online","TAR.GZ Extractor","🗃️","Extract TAR.GZ and TGZ archives online with private browser processing, path preservation and a convenient ZIP download of the contents.",["tar.gz extractor online","extract tgz online","open tar gz file"],".tar.gz,.tgz,application/gzip","extracted files","Open compressed TAR packages commonly used for source code, Linux backups and downloaded data without uploading them.","The browser first decompresses the GZIP stream and then reads the TAR records. Regular files are collected with their relative paths and offered in a ZIP download.","Choose project.tar.gz, extract its source and documentation folders locally, then download project-extracted.zip and compare key files with the expected package.",["Choose a TAR.GZ or TGZ archive.","Wait for GZIP and TAR processing on your device.","Download the extracted contents and verify them."],["GZIP decompression","TAR path reading","ZIP batch download"])
];
export const getArchiveTool=(slug:string)=>archiveTools.find(t=>t.slug===slug);
