export type CreatorMode="youtube-title"|"youtube-description"|"youtube-tags"|"youtube-timestamps"|"instagram-caption"|"hashtags"|"social-bio"|"username"|"content-ideas"|"hooks";
export type CreatorTool={slug:string;title:string;shortTitle:string;icon:string;category:"Social & Creator";mode:CreatorMode;description:string;keywords:string[];intro:string;howTo:string[];features:string[];fields:{topic:string;audience:string;detail:string};sections:{heading:string;paragraphs:string[]}[];faqs:{question:string;answer:string}[]};
const faqs=(name:string,scope:string)=>[
 {question:`Is the ${name} free?`,answer:"Yes. It works without registration, payment or usage credits. The suggestions are created locally in your browser."},
 {question:"Does this tool send my ideas to an AI service?",answer:"No. It uses browser-based writing patterns and does not send your topic, draft, keywords or audience information to an external AI API."},
 {question:`Can I publish the ${scope} exactly as generated?`,answer:"You can, but editing is strongly recommended. Add accurate details, your natural voice and platform-specific context before publishing."},
 {question:"Will this guarantee views or followers?",answer:"No. A well-structured draft may improve clarity, but reach also depends on topic demand, content quality, retention, competition, timing and audience response."},
 {question:"Can I generate more than one version?",answer:"Yes. Change the topic, audience, tone or keywords and generate again. Compare several options instead of selecting the first result automatically."}
];
const make=(slug:string,title:string,shortTitle:string,icon:string,mode:CreatorMode,description:string,keywords:string[],intro:string,howTo:string[],features:string[],fields:CreatorTool["fields"],sections:CreatorTool["sections"],scope:string):CreatorTool=>({slug,title,shortTitle,icon,category:"Social & Creator",mode,description,keywords,intro,howTo,features,fields,sections,faqs:faqs(shortTitle,scope)});
export const creatorTools:CreatorTool[]=[
make("youtube-title-generator","YouTube Title Generator Online Free","YouTube Title Generator","▶️","youtube-title","Generate clear YouTube video title ideas from your topic, audience and primary keyword without signup or an external AI request.",["youtube title generator","video title ideas","youtube seo title maker"],"Turn a video topic into several concise title directions that communicate the subject and give viewers a truthful reason to click.",["Describe the exact video topic and intended viewer.","Add the main search phrase and choose a suitable tone.","Generate options, verify every promise and select the title that best matches the video."],["Multiple title patterns","Keyword placement","Character guidance"],{topic:"Video topic",audience:"Target viewer",detail:"Primary keyword"},[
 {heading:"How strong YouTube titles communicate value",paragraphs:["A useful YouTube title tells a potential viewer what the video is about before asking for attention. Put the recognizable subject close to the beginning, then add the specific benefit, comparison, result or constraint that makes this video different. A title about learning React becomes clearer when it identifies the level, project or time frame. This helps both searchers and recommendation viewers judge relevance quickly.","Treat curiosity as an information gap, not permission to hide the subject. Viewers should understand the category and receive the promised answer in the video. Misleading superlatives may attract an initial click but can weaken watch time, satisfaction and trust when the content does not support them."]},
 {heading:"Using search phrases naturally",paragraphs:["Use the phrase a real viewer would type, but do not repeat variations merely to insert more keywords. One clear primary phrase is normally enough for the title; supporting terms can appear in the description, spoken introduction and captions. Preserve normal grammar because a readable title serves people before algorithms.","Compare the wording on current results for the query. This is research for understanding intent, not an invitation to copy. If results are mostly tutorials, signal a tutorial. If they are comparisons, identify the compared options and the decision the viewer can make."]},
 {heading:"Match the title to the thumbnail",paragraphs:["The title and thumbnail should work as a pair. Avoid placing the same long sentence on both. Let the title explain the topic while the thumbnail supplies a short visual contrast, number, object or outcome. The combination should remain understandable on a small mobile screen.","Check that neither element introduces a promise missing from the video. Names, prices, dates and performance claims should be current and visible in the actual content. This alignment supports better viewer expectations and more meaningful clicks."]},
 {heading:"A practical title review checklist",paragraphs:["Read the title aloud and remove filler that does not change meaning. Confirm the subject is identifiable, the keyword fits naturally, the wording is specific and the claim is defensible. Check spelling, capitalization and platform display on mobile. Front-load important words because the end may be truncated.","Create three genuinely different angles: direct search answer, benefit-led explanation and comparison or question. Select the angle that reflects how the video opens, rather than choosing only the most dramatic version."]}
],"title"),
make("youtube-description-generator","YouTube Description Generator Online Free","YouTube Description Generator","📝","youtube-description","Create a structured YouTube video description draft with an opening summary, key points and editable call to action in your browser.",["youtube description generator","video description maker","youtube seo description"],"Build a readable description that explains the video, supports discovery and gives viewers useful links or next steps without keyword stuffing.",["Enter the video topic, audience and important points.","Generate a structured description draft.","Replace placeholders, verify claims and add only relevant links before publishing."],["Opening summary","Chapter-ready structure","Editable call to action"],{topic:"Video topic",audience:"Target audience",detail:"Key points or keywords"},[
 {heading:"What belongs near the beginning",paragraphs:["The first lines should summarize the video in plain language because they are often visible before a viewer expands the description. State the subject, who the video helps and the practical outcome. Do not begin with a wall of links or a generic welcome message that delays the useful information.","Use the main search concept naturally in this opening, then write for comprehension. The description can clarify context that would make the title too long, such as tools used, version tested, location, eligibility or the limits of a comparison."]},
 {heading:"Organizing details for viewers",paragraphs:["After the opening, group information into short sections: what viewers will learn, resources mentioned, chapters, disclosures and a relevant next step. Descriptive labels make a long block easier to scan. Add timestamps only when they correspond to the final uploaded edit.","Links should have a reason to exist. Identify what each resource contains and use secure, correct destinations. Test every URL after publication and remove expired offers. If a relationship is sponsored or affiliate-based, use the disclosure required by the platform and applicable law."]},
 {heading:"Description SEO without repetition",paragraphs:["A description helps the platform understand context, but repeating the same keyword dozens of times makes the copy difficult to read and does not repair weak content. Use related terms only where they explain a real section of the video. Captions, spoken words, title and viewer behavior provide additional context.","Avoid pasting the same generic paragraph under every upload. Reusable channel links are fine, while the opening and learning points should describe this exact video. Unique summaries also help viewers who arrive from search decide whether the content answers their question."]},
 {heading:"Final checks before publishing",paragraphs:["Confirm names, product versions, dates, prices and claims against reliable sources. Replace every placeholder and remove sections you do not use. Verify chapters begin with 00:00 when required, links open correctly and contact details are intentional.","Read the description on a phone as well as desktop. Short paragraphs and meaningful line breaks usually work better than decorative symbols everywhere. Keep the call to action relevant to the value already delivered in the video."]}
],"description"),
make("youtube-tag-generator","YouTube Tag Generator for Videos","YouTube Tag Generator","🏷️","youtube-tags","Generate relevant YouTube tag ideas from a video topic, audience and seed keyword with no signup, upload or external API request.",["youtube tag generator","youtube video tags","youtube keyword tag maker"],"Create a focused mix of exact-topic, broad-category and contextual tag suggestions while avoiding unrelated high-volume phrases.",["Enter the exact video topic and main keyword.","Add the intended audience or location when relevant.","Generate tags, remove weak suggestions and keep only terms that accurately describe the upload."],["Comma-separated tags","Topic variations","Copy-ready result"],{topic:"Exact video topic",audience:"Audience or location",detail:"Seed keywords"},[
 {heading:"What YouTube tags are for",paragraphs:["Tags provide supporting context and can help with common spelling variants, names or ambiguous subjects. They are not a substitute for a clear title, accurate description, captions and a video that satisfies viewers. Use them as descriptive metadata rather than a list of every popular phrase in the category.","Start with the exact subject, then include a few close variations and necessary context such as software version, model, language or location. A tutorial about one phone should not carry tags for unrelated phones simply because those models are popular."]},
 {heading:"Choosing useful tag variations",paragraphs:["Include the primary phrase, a natural reordered version, a broader category and specific subtopics genuinely covered. Add brand or creator names only when the video meaningfully discusses them. Misspellings may be useful for a commonly confused proper name, but large collections of errors make the list noisy.","Think about intent. A phrase such as review, setup, comparison or troubleshooting changes what the viewer expects. Select the modifier matching the format of your video, not the modifier with the biggest estimated volume."]},
 {heading:"Avoiding tag spam",paragraphs:["Unrelated tags can create the wrong audience match and make metadata misleading. Do not add celebrity names, viral events or competitor titles that never appear in the content. Repeating singular, plural and tiny word-order variations consumes space without adding much context.","Do not place a long tag block in the public description. Follow the platform fields and policies. Metadata should accurately represent the uploaded content and should never imply an endorsement, product test or result that did not occur."]},
 {heading:"Reviewing generated tags",paragraphs:["Read each suggestion and ask whether a viewer searching that phrase would be satisfied by this video. Delete any uncertain answer. Keep the strongest exact phrase first for your own organization, although tags alone do not determine ranking.","Review performance after publication using real query and audience data available in analytics. Future wording decisions should learn from qualified impressions, watch behavior and the questions viewers ask, not from tag count alone."]}
],"tag list"),
make("youtube-timestamp-generator","YouTube Timestamp and Chapter Generator","YouTube Timestamp Generator","⏱️","youtube-timestamps","Format YouTube timestamps and chapter labels from pasted time-and-topic lines, with validation and copy-ready output in your browser.",["youtube timestamp generator","youtube chapter generator","video chapters formatter"],"Convert rough notes into consistent clickable chapter lines and catch common time-order or formatting problems before publication.",["Paste one timestamp and chapter label per line.","Add the video subject for a useful introductory heading.","Generate, check the order against the final edit and paste the chapters into the description."],["Timestamp formatting","Chapter validation","Copy-ready chapters"],{topic:"Video subject",audience:"Video duration",detail:"Timestamps and chapter labels"},[
 {heading:"How YouTube chapters help viewers",paragraphs:["Chapters let viewers navigate a long video and understand its structure before committing time. Clear labels are more useful than vague wording such as next part or more information. Name the action, question or subject covered at that point.","The timestamp must match the final exported video, not an earlier script or editing timeline. An inserted intro, deleted pause or changed sponsor segment can shift every later marker, so chapter verification should happen after the upload is final."]},
 {heading:"Writing useful chapter labels",paragraphs:["Use short descriptive phrases that remain distinct from one another. A tutorial might use Installation, Project setup, First component and Common error fixes. Repeating the complete video title in every chapter wastes space and makes scanning harder.","Include a relevant term when it naturally identifies the segment, but do not turn every label into a keyword list. The main purpose is navigation. Consistent capitalization and parallel wording create a more professional outline."]},
 {heading:"Timing and ordering checks",paragraphs:["Begin with 00:00 when the platform requires it and arrange markers in ascending order. Do not create overlapping or duplicate times. Allow enough duration for each chapter to represent a meaningful section rather than every sentence or camera cut.","Play the video from each marker. Confirm the label describes what begins there, audio is understandable and the next chapter does not start too early. Check on the published watch page because processing or edits can affect the final result."]},
 {heading:"Using chapters responsibly",paragraphs:["Chapters should not conceal sponsorship, corrections or important safety context. If a tutorial has prerequisites or limitations, label those sections clearly instead of directing viewers only to the successful outcome.","Update timestamps when using the platform editor to trim a published video. Keep a source copy of your chapter list, but treat the live description as authoritative. This generator formats notes; it cannot inspect or synchronize with the video itself."]}
],"chapter list"),
make("instagram-caption-generator","Instagram Caption Generator Online Free","Instagram Caption Generator","📸","instagram-caption","Generate Instagram caption drafts for posts, reels or carousels using your topic, audience and tone without signup or an AI API.",["instagram caption generator","caption ideas for instagram","reel caption maker"],"Turn the context behind a post into a readable opening, supporting message and relevant call to action that you can personalize.",["Describe what the post actually shows or teaches.","Choose the audience and add the tone or important detail.","Generate alternatives, add your voice and verify every statement before posting."],["Caption variations","Tone control","Call-to-action ideas"],{topic:"Post or reel topic",audience:"Target audience",detail:"Tone and key detail"},[
 {heading:"Start with context, not filler",paragraphs:["The opening line should help someone understand why the post matters even if they encounter it outside your profile. Use a concrete observation, question or result connected to the image or reel. Generic hooks that could introduce any subject often attract less meaningful attention.","Continue with the information necessary to support the opening. For a product, explain the use or difference honestly. For educational content, deliver the promised tip. For a personal story, include the detail that makes the lesson credible without disclosing information you should keep private."]},
 {heading:"Tone and brand consistency",paragraphs:["Choose a tone your audience already associates with you: practical, conversational, expert, playful or reflective. Trendy vocabulary can feel forced when it does not match the creator, business or subject. Read the draft aloud and replace phrases you would never say.","Keep spelling, capitalization and terminology consistent across posts. A recognizable voice develops through repeated choices, not by pasting an identical template. The generated caption is a structure that should receive a personal example, opinion or accurate detail."]},
 {heading:"Calls to action with a purpose",paragraphs:["Ask for one reasonable next step connected to the post. A tutorial may invite a question; a carousel may ask readers to save a checklist; a business post may point to an exact product page. Multiple demands to like, share, comment, follow and buy can distract from the primary action.","Do not use false scarcity or engagement bait. If a deadline, stock count or result is mentioned, it should be real and verifiable. Honest expectations protect the relationship between creator and audience."]},
 {heading:"Caption accessibility and review",paragraphs:["Write the essential meaning in text instead of relying only on emoji. Add accurate alternative text through the platform when visual information matters. Use line breaks to improve scanning, but avoid excessive decorative spacing that makes screen-reader navigation longer.","Before posting, confirm names, tags, prices, links, dates, permissions and disclosures. Preview the caption with the media because a strong sentence can still create confusion when it contradicts the image or edited reel."]}
],"caption"),
make("hashtag-generator","Hashtag Generator for Instagram, TikTok and YouTube","Hashtag Generator","#️⃣","hashtags","Generate relevant hashtag ideas for Instagram, TikTok or YouTube from a topic, audience and niche using private browser processing.",["hashtag generator","instagram hashtag generator","tiktok hashtags for niche"],"Build a small, relevant hashtag set that describes the content instead of copying unrelated trending terms or repetitive blocks.",["Enter the exact content topic and target audience.","Add the niche, location or platform context.","Generate suggestions and keep only hashtags that accurately match the published content."],["Niche hashtags","Platform-ready format","One-click copy"],{topic:"Content topic",audience:"Target audience",detail:"Niche, location or seed terms"},[
 {heading:"Relevance is more useful than volume",paragraphs:["A hashtag groups content around a label, so every selected term should describe the post or the community it serves. A smaller relevant audience can be more valuable than impressions from people who expected a different subject. Broad tags may provide category context, while specific tags explain the exact topic, format, location or problem.","Do not assume a popular hashtag is safe or effective. Search it on the target platform, inspect the current results and confirm its meaning has not shifted. Communities sometimes use a familiar phrase for a purpose different from its literal wording."]},
 {heading:"Building a balanced hashtag set",paragraphs:["Start with one or two direct topic labels, then add a niche, audience, format and location when each is relevant. For example, a Karachi bakery tutorial may combine baking, cake decoration, small business and Karachi context without attaching unrelated food trends.","Avoid dozens of near-identical versions. Singular, plural and reordered phrases can look repetitive and provide little additional meaning. A concise set is easier to review, update and compare through analytics."]},
 {heading:"Platform rules and banned terms",paragraphs:["Platforms change hashtag display, search and recommendation behavior. Check current platform guidance and do not treat an old recommended count as a permanent rule. Some labels may be restricted because of spam or harmful content even when the words initially look harmless.","Never use tags that misrepresent protected identities, medical outcomes, financial results or affiliations. Hashtags are part of the public claim made by a post and should follow the same accuracy and disclosure standards as the caption."]},
 {heading:"Testing without chasing trends",paragraphs:["Keep the content quality and audience consistent when comparing hashtag groups. Measure qualified outcomes such as saves, watch time, profile visits or useful inquiries, not reach alone. One post cannot prove that a tag caused the result because timing and creative quality also changed.","Refresh the list for each post. Reusing a small branded label can help organization, while the descriptive portion should reflect the exact content. This generator supplies starting ideas and does not access live trend data."]}
],"hashtag set"),
make("social-media-bio-generator","Social Media Bio Generator Online Free","Social Media Bio Generator","👤","social-bio","Create concise bio drafts for Instagram, TikTok, X or other profiles from your role, audience and value proposition in your browser.",["social media bio generator","instagram bio maker","profile bio ideas"],"Summarize who you are, what you provide and why the intended audience should care within a compact editable profile draft.",["Enter your role, niche or business.","Describe the audience and the value you provide.","Generate options, confirm accuracy and adapt the strongest one to the platform limit."],["Value-focused bios","Multiple formats","Character-aware drafts"],{topic:"Role, brand or niche",audience:"People you help",detail:"Value, proof or call to action"},[
 {heading:"The three jobs of a profile bio",paragraphs:["A useful bio identifies the person or brand, explains the relevant value and offers a next step. Visitors often decide quickly whether a profile matches their interest, so concrete language is more helpful than a collection of broad labels such as dreamer, expert or entrepreneur.","State the category in words your audience recognizes. A developer might name React websites or MERN applications; a bakery might identify custom cakes and delivery area. The value statement should remain understandable to someone seeing the profile for the first time."]},
 {heading:"Proof without exaggerated claims",paragraphs:["Add a qualification, result or experience marker only when it is current and supportable. Avoid best, number one or guaranteed unless objective evidence and local advertising rules allow the claim. Honest specificity builds more trust than inflated authority language.","If space is limited, prioritize what affects the visitor's decision. A real location, service type or portfolio link may be more useful than several personality adjectives. Sensitive personal information should remain private unless there is a clear business reason to publish it."]},
 {heading:"Calls to action and profile links",paragraphs:["Use one clear next step such as view the portfolio, download the guide, book an appointment or browse the menu. Make sure the linked page continues the same promise and works well on mobile. Avoid link text that hides an unfamiliar or unsafe destination.","Update temporary calls to action when campaigns end. A profile is often discovered months after it was edited, so expired launches, old prices and unavailable services can create confusion."]},
 {heading:"Adapting one bio across platforms",paragraphs:["Do not paste the same bio blindly everywhere. Professional networks may need role and industry context, while visual platforms may benefit from niche, location and a concise benefit. Respect the visible character limit and check how line breaks appear on the actual profile.","Keep the core identity consistent so people recognize the same person or business. Adjust tone and call to action, then review usernames, profile image, link and bio together as one introduction."]}
],"bio"),
make("username-generator","Username Generator for Social Media and Gaming","Username Generator","✨","username","Generate memorable username ideas from your name, niche and style for social profiles, creator channels or gaming accounts without signup.",["username generator","social media username ideas","gaming name generator"],"Combine meaningful seed words into readable handle ideas while avoiding random personal data, copied identities and hard-to-type clutter.",["Enter a name, brand word or topic.","Add your niche and preferred style.","Generate options, check availability manually and investigate possible trademark or identity conflicts."],["Multiple username styles","Readable combinations","No account lookup"],{topic:"Name or seed word",audience:"Niche or community",detail:"Style or extra word"},[
 {heading:"What makes a username memorable",paragraphs:["Strong usernames are easy to read, say, type and recall. A short combination of a distinctive seed word and meaningful niche term is usually clearer than a long chain of numbers and punctuation. Consider how the handle sounds when mentioned in a video or conversation.","Keep spelling intentional. Creative alterations can make a name unique, but excessive substitutions force people to remember where each number or underscore belongs. Test the option in lowercase because many platforms display handles that way."]},
 {heading:"Privacy and personal information",paragraphs:["Do not automatically include a birth date, phone fragment, school, address or other information that could support account guessing or identity profiling. A public handle can appear in search results and may remain copied elsewhere after the original account is deleted.","Creators who want separation between personal and professional activity should choose a brand-oriented seed. Also review recovery email, two-factor authentication and public profile fields; the username alone does not protect the account."]},
 {heading:"Availability and identity checks",paragraphs:["This generator does not query social platforms, so an idea may already be taken. Search each intended platform manually and inspect similar accounts before deciding. Avoid a handle that could make viewers believe you are another person, official institution or established brand.","Check domain availability if the identity may become a website later. Search trademarks and local business records when the username will represent a commercial brand. Availability on one app does not create legal rights to a name."]},
 {heading:"Consistency without forcing an exact match",paragraphs:["Using the same handle across major profiles can improve recognition, but a readable platform-specific variation is better than an exact match filled with confusing characters. Keep profile name, image and bio consistent when handles differ.","Choose something that can survive a wider range of content. A highly specific trend reference may feel dated, while a name connected to your lasting niche or brand can grow with the account."]}
],"username"),
make("content-idea-generator","Content Idea Generator for Social Media","Content Idea Generator","💡","content-ideas","Generate practical content ideas for YouTube, Instagram, TikTok or blogs from a niche, audience and goal with no external AI request.",["content idea generator","social media content ideas","youtube video idea generator"],"Create a varied shortlist of educational, comparison, story, checklist and problem-solving topics tied to a real audience need.",["Enter the niche or central subject.","Describe the audience and the goal of the content.","Generate ideas, research demand and select only topics you can cover with useful firsthand value."],["Multiple content angles","Audience-focused prompts","Reusable planning list"],{topic:"Niche or main subject",audience:"Target audience",detail:"Goal, problem or keywords"},[
 {heading:"Begin with audience problems",paragraphs:["Content ideas become stronger when they start with a question, task or decision faced by a defined group. Instead of planning another general fitness post, identify whether the audience needs a beginner routine, equipment comparison, recovery explanation or budget meal plan. Specific problems create clearer titles and more useful content.","Collect questions from search suggestions, customer conversations, comments, support messages and communities. Treat these as evidence of language and concerns, not permission to copy another creator's work. Add your own process, test, example or analysis."]},
 {heading:"Use repeatable content angles",paragraphs:["One subject can support tutorials, mistakes, comparisons, checklists, case studies, myths, behind-the-scenes explanations and updates. Changing the angle should change the information, not only the headline. A comparison requires fair criteria; a case study requires real observations; a tutorial requires tested steps.","Balance evergreen topics with timely updates. Evergreen answers can remain useful for months, while news and platform changes may create short demand but require faster fact checking and visible dates."]},
 {heading:"Validate before producing",paragraphs:["Search the proposed topic and study what the current results answer well or leave unclear. Look for weak examples, outdated screenshots, missing local context or unanswered follow-up questions. The goal is not to duplicate the top result with different wording but to contribute a clearer or more specific resource.","Estimate production effort honestly. A topic needing expert testing, licensed footage or current statistics may not fit the available time. Select ideas where you can provide credible value and complete the promised format."]},
 {heading:"Turn ideas into a sustainable plan",paragraphs:["Group related topics into a series so research and audience learning carry forward. Define a purpose for each piece: attract a relevant search, answer a customer concern, demonstrate expertise or support an existing resource. Not every post needs to sell.","Track published date, format, target question, result and update requirement. Revisit successful topics with genuinely new evidence rather than reposting the same information. This generator offers starting angles and does not measure live search volume or competition."]}
],"idea list"),
make("social-media-hook-generator","Social Media Hook Generator Online","Hook Generator","🪝","hooks","Generate opening hook ideas for reels, shorts, videos and posts from a topic, audience and key result without signup or an AI API.",["hook generator","reel hook ideas","social media video hooks"],"Draft truthful opening lines that identify a problem, useful outcome, question or contrast and lead naturally into the actual content.",["Enter the content topic and intended viewer.","Add the result, problem or important constraint.","Generate hooks and choose one that the next seconds of content immediately support."],["Video and post hooks","Multiple hook patterns","Truth-focused prompts"],{topic:"Content topic",audience:"Intended viewer",detail:"Result, problem or surprising detail"},[
 {heading:"A hook is a promise about what follows",paragraphs:["The opening earns attention by making the relevance clear, not by being loud. It may name a familiar problem, show an outcome, ask a precise question or reveal a useful contrast. The next sentence or shot should immediately begin fulfilling that promise.","Avoid opening with background viewers do not need yet. Context can follow after the central reason to continue is understood. For search-led tutorials, repeating the exact task and showing the result quickly can be stronger than a mysterious statement."]},
 {heading:"Curiosity without deception",paragraphs:["A curiosity gap should withhold a detail while accurately identifying the subject. Do not imply danger, income, transformation or secret access that the content cannot demonstrate. False urgency may increase early attention but often damages retention and audience trust.","Numbers and deadlines need support. If a hook says three steps, deliver three recognizable steps. If it claims a test lasted thirty days, explain the method and limitations. Accurate specificity is compelling because it reduces uncertainty."]},
 {heading:"Hooks for different formats",paragraphs:["Short video hooks must work with the first visual and may need to be understood without sound through on-screen text. Carousel hooks should motivate the swipe while naming the topic. Long videos can establish more context, but the viewer still needs an early reason to believe the promised answer is coming.","Adapt the wording to the audience's knowledge. Beginners may need the category named directly; specialists may respond to a precise failure mode or tradeoff. Do not use technical jargon merely to sound authoritative."]},
 {heading:"Testing and improving openings",paragraphs:["Write several openings before recording and compare clarity, accuracy and transition into the main content. Read them aloud to find unnatural phrases. Ensure the chosen hook matches the title, thumbnail and caption so the viewer receives one coherent expectation.","Use retention data carefully after publication. A drop may reflect audio, visuals, pacing, audience mismatch or the hook itself. Test meaningful changes over multiple pieces rather than declaring a universal formula from one viral or unsuccessful post."]}
],"hook"),
];
export const getCreatorTool=(slug:string)=>creatorTools.find(t=>t.slug===slug);

