export type DocumentTool={slug:string;title:string;shortTitle:string;icon:string;description:string;keywords:string[];input:string;output:string;intro:string;howTo:string[];features:string[];faqs:{question:string;answer:string}[]};
const common=(name:string)=>[
 {question:"Is "+name+" free?",answer:"Yes. It is free to use, requires no account and does not add a watermark."},
 {question:"Are my files uploaded?",answer:"No. Files are processed in your browser and are not sent to SolvePilot servers."},
 {question:"Does it work on mobile?",answer:"Yes, in modern browsers. Desktop browsers are usually more comfortable for large documents and spreadsheets."},
 {question:"Is the output identical to the source?",answer:"Simple content converts reliably. Advanced layouts, fonts, formulas or embedded objects may need review after conversion."},
 {question:"What file size should I use?",answer:"For reliable browser processing, use files below 25 MB and keep a backup of the original."}
];
const make=(slug:string,title:string,shortTitle:string,icon:string,description:string,keywords:string[],input:string,output:string,intro:string,howTo:string[],features:string[],extra?:{question:string;answer:string}):DocumentTool=>({slug,title,shortTitle,icon,description,keywords,input,output,intro,howTo,features,faqs:[...(extra?[extra]:[]),...common(shortTitle)].slice(0,5)});
export const documentTools:DocumentTool[]=[
make("word-to-pdf","Convert Word to PDF Online","Word to PDF","📄","Convert DOCX Word documents to PDF online with private browser processing, readable formatting and no account or server upload.",["word to pdf online","convert docx to pdf","free word pdf converter"],".docx",".pdf","Create a shareable PDF from a Word document while keeping the source file on your device.",["Choose a DOCX file.","Review the extracted document preview.","Convert and download the PDF."],["Local DOCX reading","PDF download","Readable paragraphs"]),
make("pdf-to-word","Convert PDF to Word Online","PDF to Word","📝","Convert PDF text into an editable DOCX Word document online. Private browser processing requires no upload, signup or watermark.",["pdf to word online","pdf to docx","convert pdf text to word"],".pdf",".docx","Recover readable text from ordinary PDFs and place it into an editable Word document.",["Choose a text-based PDF.","Wait while each page is read locally.","Download the editable DOCX file."],["Page-by-page extraction","Editable DOCX output","No server upload"],{question:"Does PDF to Word support scanned PDFs?",answer:"Not yet. Scanned documents require OCR; this tool extracts text already embedded in the PDF."}),
make("docx-viewer","DOCX Viewer Online Free","DOCX Viewer","👁️","Open and preview DOCX Word documents online without Microsoft Word. Your file stays private and is rendered inside your browser.",["docx viewer online","open docx online","view word document"],".docx","preview","Read the main text, headings, lists and tables in a DOCX document without installing office software.",["Choose a DOCX document.","Wait for the private browser preview.","Read the rendered content on this page."],["Instant preview","Tables and headings","No download needed"]),
make("docx-word-counter","DOCX Word Counter Online","DOCX Word Counter","🔢","Count words, characters, paragraphs and estimated reading time in a DOCX file privately online without uploading the document.",["docx word counter","count words in word document","docx character count"],".docx","statistics","Measure document length for assignments, articles, applications or publishing requirements.",["Choose a DOCX file.","Let the browser extract its text.","Review word, character, paragraph and reading-time totals."],["Word count","Character count","Reading-time estimate"]),
make("extract-images-from-docx","Extract Images from DOCX Online","DOCX Image Extractor","🖼️","Extract embedded images from a DOCX Word file online and download them in a ZIP. Processing stays private in your browser.",["extract images from docx","download word document images","docx image extractor"],".docx",".zip","Recover pictures stored inside a Word document without copying them one at a time.",["Choose a DOCX file.","Scan its internal media folder.","Download all discovered images as a ZIP."],["Original image files","ZIP download","No quality conversion"]),
make("markdown-to-docx","Convert Markdown to DOCX Online","Markdown to DOCX","Ⓜ️","Convert Markdown text or an MD file into an editable DOCX document online with headings, lists and private browser processing.",["markdown to docx","md to word","convert markdown to word"],".md or text",".docx","Turn Markdown notes, documentation or AI-generated drafts into a Word-compatible file.",["Paste Markdown or choose an MD file.","Review the source text.","Convert and download DOCX."],["Headings and lists","Editable Word output","Paste or upload"]),
make("markdown-to-pdf","Convert Markdown to PDF Online","Markdown to PDF","📕","Convert Markdown text or MD files to a clean PDF online with headings and lists, using private processing entirely in your browser.",["markdown to pdf","md to pdf online","convert markdown document"],".md or text",".pdf","Create a portable PDF from Markdown content for sharing, printing or archiving.",["Paste Markdown or choose an MD file.","Confirm the generated preview.","Convert and download PDF."],["Heading support","List formatting","Private conversion"]),
make("text-to-docx","Convert Text to DOCX Online","Text to DOCX","✍️","Convert plain text or TXT files into an editable DOCX Word document online. Free browser processing keeps your content private.",["text to docx","txt to word","convert text file to docx"],".txt or text",".docx","Package plain text into a standard Word document that can be edited in Word, LibreOffice or compatible apps.",["Paste text or choose a TXT file.","Add an optional document title.","Convert and download DOCX."],["Editable output","Paragraph preservation","Optional title"]),
make("text-to-pdf","Convert Text to PDF Online","Text to PDF","📃","Convert plain text or TXT files into a clean PDF online with an optional title. Free private processing runs in your browser.",["text to pdf","txt to pdf online","convert plain text to pdf"],".txt or text",".pdf","Create a simple, portable and printable document from notes, drafts or exported plain text.",["Paste text or choose a TXT file.","Add an optional title.","Convert and download PDF."],["Automatic page wrapping","Optional title","No server upload"]),
make("html-to-docx","Convert HTML to DOCX Online","HTML to DOCX","🌐","Convert pasted HTML or an HTML file to editable DOCX online. Headings, paragraphs and lists are processed privately in-browser.",["html to docx","html to word","convert webpage html to docx"],".html or code",".docx","Turn clean HTML content into a Word document for editing, review or offline use.",["Paste HTML or choose an HTML file.","Review the plain rendered content.","Convert and download DOCX."],["Common HTML elements","Editable output","Script removal"]),
make("html-to-pdf","Convert HTML to PDF Online","HTML to PDF","📰","Convert pasted HTML or an HTML file to a readable PDF online with private browser processing and no server-side file upload.",["html to pdf online","convert html file to pdf","html code to pdf"],".html or code",".pdf","Create a PDF from clean HTML content such as an article, report, email or documentation page.",["Paste HTML or choose an HTML file.","Review the sanitized content.","Convert and download PDF."],["Readable layout","Automatic page wrapping","Script removal"]),
make("csv-to-excel","Convert CSV to Excel Online","CSV to Excel","📊","Convert CSV data into an Excel XLSX workbook online with automatic column detection and private processing in your browser.",["csv to excel","csv to xlsx online","convert csv spreadsheet"],".csv",".xlsx","Turn comma-separated data into a workbook that is easier to filter, format and share.",["Choose a CSV file.","Confirm the detected rows and columns.","Convert and download XLSX."],["Header detection","Worksheet creation","UTF-8 data"]),
make("excel-to-csv","Convert Excel to CSV Online","Excel to CSV","📈","Convert the first worksheet of an Excel XLSX file into CSV online. Free private processing keeps spreadsheet data local.",["excel to csv","xlsx to csv online","convert spreadsheet to csv"],".xlsx or .xls",".csv","Export the first worksheet as portable comma-separated values for databases, tools and imports.",["Choose an Excel workbook.","Select a worksheet when available.","Convert and download CSV."],["Worksheet selection","Quoted CSV output","Local processing"]),
make("json-to-excel","Convert JSON to Excel Online","JSON to Excel","🧾","Convert JSON arrays or objects into an Excel XLSX workbook online with private browser processing and automatic columns.",["json to excel","json to xlsx online","convert json data spreadsheet"],".json",".xlsx","Flatten common JSON records into spreadsheet rows and columns for analysis, reporting or sharing.",["Paste JSON or choose a JSON file.","Validate and preview the detected records.","Convert and download XLSX."],["JSON validation","Automatic columns","Object and array support"]),
make("merge-excel-files","Merge Excel Files Online","Merge Excel Files","🔗","Merge multiple Excel XLSX or XLS workbooks into one downloadable workbook with separate sheets and private browser processing.",["merge excel files online","combine excel workbooks","merge xlsx files"],".xlsx or .xls",".xlsx","Combine worksheets from several workbooks into one organized Excel file without copying data between files manually.",["Choose two or more Excel workbooks.","Review the selected file order and start the merge.","Download one workbook containing the copied sheets."],["Multiple workbooks","Unique sheet names","Formula preservation where supported"]),
make("split-excel-sheets","Split Excel Sheets Online","Split Excel Sheets","✂️","Split an Excel workbook into separate XLSX files for each worksheet and download them together in a ZIP using private browser processing.",["split excel sheets online","separate excel worksheets","extract sheets from xlsx"],".xlsx or .xls",".zip","Turn a multi-sheet workbook into individual files for sharing, importing or assigning each worksheet separately.",["Choose an Excel workbook with multiple worksheets.","Review the detected sheet names.","Split and download the worksheet files in a ZIP."],["One file per sheet","ZIP download","Sheet-name preservation"]),
make("remove-duplicate-excel-rows","Remove Duplicate Excel Rows Online","Remove Duplicate Rows","🧹","Remove duplicate rows from an Excel worksheet online using all columns or a selected column, with a preview and private processing.",["remove duplicate excel rows","excel duplicate remover online","deduplicate xlsx rows"],".xlsx or .xls",".xlsx","Clean repeated spreadsheet records while keeping the first matching row and preserving the original workbook as a backup.",["Choose an Excel workbook.","Select the worksheet and optional key column.","Remove duplicates, review counts and download the cleaned workbook."],["Whole-row matching","Column-key matching","Removed-row count"]),
make("compare-two-excel-files","Compare Two Excel Files Online","Compare Excel Files","⚖️","Compare two Excel worksheets online to find added, removed and changed rows using a selected key column with private browser processing.",["compare two excel files","excel comparison tool online","find differences between xlsx"],"two .xlsx or .xls","comparison report","Identify record-level differences between two spreadsheet versions without uploading confidential workbook data to SolvePilot.",["Choose the earlier and newer Excel workbooks.","Select a worksheet and key column or compare full rows.","Review and download the CSV difference report."],["Added rows","Removed rows","Changed values"]),
make("excel-to-json","Convert Excel to JSON Online","Excel to JSON","🔄","Convert an Excel worksheet to formatted JSON online with worksheet selection, header-based properties and private browser processing.",["excel to json converter","xlsx to json online","convert spreadsheet to json"],".xlsx or .xls",".json","Export tabular worksheet data as an array of JSON objects for APIs, development, migration or structured-data workflows.",["Choose an Excel workbook.","Select the worksheet to export.","Preview and download formatted JSON."],["Worksheet selection","Header properties","Formatted JSON"]),
make("csv-to-json","Convert CSV to JSON Online","CSV to JSON","🔃","Convert CSV rows to formatted JSON objects online with automatic header mapping, delimiter handling and private browser processing.",["csv to json converter","convert csv to json online","csv rows to json"],".csv or text",".json","Transform portable comma-separated records into a JSON array that is easier to use in web applications and APIs.",["Choose a CSV file or paste CSV text.","Check the detected header and sample rows.","Convert and download formatted JSON."],["Header mapping","Quoted values","JSON validation"]),
make("json-to-csv","Convert JSON to CSV Online","JSON to CSV","📑","Convert arrays of JSON objects to CSV online with automatic column discovery, correct value quoting and private browser processing.",["json to csv converter","convert json to csv online","json objects to spreadsheet"],".json or text",".csv","Flatten ordinary JSON records into portable comma-separated rows for spreadsheets, imports and reporting.",["Choose a JSON file or paste an array of objects.","Validate and preview the detected records.","Convert and download CSV."],["Automatic columns","CSV escaping","Array and object support"]),
make("xml-to-json","Convert XML to JSON Online","XML to JSON","🧩","Convert XML documents to readable JSON online while preserving attributes, text and repeated elements with private browser processing.",["xml to json converter","convert xml to json online","xml data to json"],".xml or text",".json","Represent an XML document as structured JSON for inspection, application development or data migration.",["Choose an XML file or paste XML text.","Validate the document and inspect parsing errors.","Convert and download formatted JSON."],["Attribute preservation","Repeated elements","Parser validation"]),
make("json-to-xml","Convert JSON to XML Online","JSON to XML","🔷","Convert valid JSON objects or arrays to well-formed XML online with safe element names, indentation and private browser processing.",["json to xml converter","convert json to xml online","json data to xml"],".json or text",".xml","Create an XML representation of JSON records for systems, feeds or integrations that require XML input.",["Choose a JSON file or paste valid JSON.","Set an optional root element name.","Convert, review and download XML."],["Configurable root","Escaped values","Indented XML"]),
make("yaml-to-json","Convert YAML to JSON Online","YAML to JSON","🟨","Convert common YAML mappings and lists to formatted JSON online with syntax checks and private browser processing on your device.",["yaml to json converter","convert yaml to json online","yml to json"],".yaml, .yml or text",".json","Turn configuration or structured YAML into JSON for applications, debugging and interoperability.",["Choose a YAML file or paste YAML text.","Parse supported mappings, arrays and scalar values.","Download formatted JSON after reviewing the preview."],["YAML mappings","List support","Scalar conversion"]),
make("json-to-yaml","Convert JSON to YAML Online","JSON to YAML","🟪","Convert JSON objects and arrays to readable YAML online with indentation, safe string handling and private browser processing.",["json to yaml converter","convert json to yaml online","json to yml"],".json or text",".yaml","Create human-readable YAML from valid JSON for configuration files, documentation or developer workflows.",["Choose a JSON file or paste valid JSON.","Validate and preview the parsed structure.","Convert and download YAML."],["Nested objects","Array formatting","Safe scalar output"])
];
export const getDocumentTool=(slug:string)=>documentTools.find(t=>t.slug===slug);
