export type DocumentTool={slug:string;title:string;shortTitle:string;icon:string;description:string;keywords:string[];input:string;output:string;intro:string;howTo:string[];features:string[];faqs:{question:string;answer:string}[]};
const common=(name:string)=>[
 {question:"Is "+name+" free?",answer:"Yes. It is free to use, requires no account and does not add a watermark."},
 {question:"Are my files uploaded?",answer:"No. Files are processed in your browser and are not sent to SolvePilot servers."},
 {question:"Does it work on mobile?",answer:"Yes, in modern browsers. Desktop browsers are usually more comfortable for large documents and spreadsheets."},
 {question:"Is the output identical to the source?",answer:"Simple content converts reliably. Advanced layouts, fonts, formulas or embedded objects may need review after conversion."},
 {question:"What file size should I use?",answer:"For reliable browser processing, use files below 25 MB and keep a backup of the original."}
];
const make=(slug:string,title:string,shortTitle:string,icon:string,description:string,keywords:string[],input:string,output:string,intro:string,howTo:string[],features:string[],extra?:{question:string;answer:string}):DocumentTool=>({slug,title,shortTitle,icon,description,keywords,input,output,intro,howTo,features,faqs:[...(extra?[extra]:[]),...common(shortTitle)].slice(0,5)});
export const documentTools:DocumentTool[]=[
make("word-to-pdf","Convert Word to PDF Online","Word to PDF","📄","Convert DOCX Word documents to PDF online with private browser processing, readable formatting and no account or server upload.",["word to pdf online","convert docx to pdf","free word pdf converter"],".docx",".pdf","Create a shareable PDF from a Word document while keeping the source file on your device.",["Choose a DOCX file.","Review the extracted document preview.","Convert and download the PDF."],["Local DOCX reading","PDF download","Readable paragraphs"]),
make("pdf-to-word","Convert PDF to Word Online","PDF to Word","📝","Convert PDF text into an editable DOCX Word document online. Private browser processing requires no upload, signup or watermark.",["pdf to word online","pdf to docx","convert pdf text to word"],".pdf",".docx","Recover readable text from ordinary PDFs and place it into an editable Word document.",["Choose a text-based PDF.","Wait while each page is read locally.","Download the editable DOCX file."],["Page-by-page extraction","Editable DOCX output","No server upload"],{question:"Does PDF to Word support scanned PDFs?",answer:"Not yet. Scanned documents require OCR; this tool extracts text already embedded in the PDF."}),
make("docx-viewer","DOCX Viewer Online Free","DOCX Viewer","👁️","Open and preview DOCX Word documents online without Microsoft Word. Your file stays private and is rendered inside your browser.",["docx viewer online","open docx online","view word document"],".docx","preview","Read the main text, headings, lists and tables in a DOCX document without installing office software.",["Choose a DOCX document.","Wait for the private browser preview.","Read the rendered content on this page."],["Instant preview","Tables and headings","No download needed"]),
make("docx-word-counter","DOCX Word Counter Online","DOCX Word Counter","🔢","Count words, characters, paragraphs and estimated reading time in a DOCX file privately online without uploading the document.",["docx word counter","count words in word document","docx character count"],".docx","statistics","Measure document length for assignments, articles, applications or publishing requirements.",["Choose a DOCX file.","Let the browser extract its text.","Review word, character, paragraph and reading-time totals."],["Word count","Character count","Reading-time estimate"]),
make("extract-images-from-docx","Extract Images from DOCX Online","DOCX Image Extractor","🖼️","Extract embedded images from a DOCX Word file online and download them in a ZIP. Processing stays private in your browser.",["extract images from docx","download word document images","docx image extractor"],".docx",".zip","Recover pictures stored inside a Word document without copying them one at a time.",["Choose a DOCX file.","Scan its internal media folder.","Download all discovered images as a ZIP."],["Original image files","ZIP download","No quality conversion"]),
make("markdown-to-docx","Convert Markdown to DOCX Online","Markdown to DOCX","Ⓜ️","Convert Markdown text or an MD file into an editable DOCX document online with headings, lists and private browser processing.",["markdown to docx","md to word","convert markdown to word"],".md or text",".docx","Turn Markdown notes, documentation or AI-generated drafts into a Word-compatible file.",["Paste Markdown or choose an MD file.","Review the source text.","Convert and download DOCX."],["Headings and lists","Editable Word output","Paste or upload"]),
make("markdown-to-pdf","Convert Markdown to PDF Online","Markdown to PDF","📕","Convert Markdown text or MD files to a clean PDF online with headings and lists, using private processing entirely in your browser.",["markdown to pdf","md to pdf online","convert markdown document"],".md or text",".pdf","Create a portable PDF from Markdown content for sharing, printing or archiving.",["Paste Markdown or choose an MD file.","Confirm the generated preview.","Convert and download PDF."],["Heading support","List formatting","Private conversion"]),
make("text-to-docx","Convert Text to DOCX Online","Text to DOCX","✍️","Convert plain text or TXT files into an editable DOCX Word document online. Free browser processing keeps your content private.",["text to docx","txt to word","convert text file to docx"],".txt or text",".docx","Package plain text into a standard Word document that can be edited in Word, LibreOffice or compatible apps.",["Paste text or choose a TXT file.","Add an optional document title.","Convert and download DOCX."],["Editable output","Paragraph preservation","Optional title"]),
make("text-to-pdf","Convert Text to PDF Online","Text to PDF","📃","Convert plain text or TXT files into a clean PDF online with an optional title. Free private processing runs in your browser.",["text to pdf","txt to pdf online","convert plain text to pdf"],".txt or text",".pdf","Create a simple, portable and printable document from notes, drafts or exported plain text.",["Paste text or choose a TXT file.","Add an optional title.","Convert and download PDF."],["Automatic page wrapping","Optional title","No server upload"]),
make("html-to-docx","Convert HTML to DOCX Online","HTML to DOCX","🌐","Convert pasted HTML or an HTML file to editable DOCX online. Headings, paragraphs and lists are processed privately in-browser.",["html to docx","html to word","convert webpage html to docx"],".html or code",".docx","Turn clean HTML content into a Word document for editing, review or offline use.",["Paste HTML or choose an HTML file.","Review the plain rendered content.","Convert and download DOCX."],["Common HTML elements","Editable output","Script removal"]),
make("html-to-pdf","Convert HTML to PDF Online","HTML to PDF","📰","Convert pasted HTML or an HTML file to a readable PDF online with private browser processing and no server-side file upload.",["html to pdf online","convert html file to pdf","html code to pdf"],".html or code",".pdf","Create a PDF from clean HTML content such as an article, report, email or documentation page.",["Paste HTML or choose an HTML file.","Review the sanitized content.","Convert and download PDF."],["Readable layout","Automatic page wrapping","Script removal"]),
make("csv-to-excel","Convert CSV to Excel Online","CSV to Excel","📊","Convert CSV data into an Excel XLSX workbook online with automatic column detection and private processing in your browser.",["csv to excel","csv to xlsx online","convert csv spreadsheet"],".csv",".xlsx","Turn comma-separated data into a workbook that is easier to filter, format and share.",["Choose a CSV file.","Confirm the detected rows and columns.","Convert and download XLSX."],["Header detection","Worksheet creation","UTF-8 data"]),
make("excel-to-csv","Convert Excel to CSV Online","Excel to CSV","📈","Convert the first worksheet of an Excel XLSX file into CSV online. Free private processing keeps spreadsheet data local.",["excel to csv","xlsx to csv online","convert spreadsheet to csv"],".xlsx or .xls",".csv","Export the first worksheet as portable comma-separated values for databases, tools and imports.",["Choose an Excel workbook.","Select a worksheet when available.","Convert and download CSV."],["Worksheet selection","Quoted CSV output","Local processing"]),
make("json-to-excel","Convert JSON to Excel Online","JSON to Excel","🧾","Convert JSON arrays or objects into an Excel XLSX workbook online with private browser processing and automatic columns.",["json to excel","json to xlsx online","convert json data spreadsheet"],".json",".xlsx","Flatten common JSON records into spreadsheet rows and columns for analysis, reporting or sharing.",["Paste JSON or choose a JSON file.","Validate and preview the detected records.","Convert and download XLSX."],["JSON validation","Automatic columns","Object and array support"])
];
export const getDocumentTool=(slug:string)=>documentTools.find(t=>t.slug===slug);
