export type GeneratorField={name:string;label:string;type?:"text"|"number"|"date"|"email"|"tel"|"textarea";placeholder?:string;required?:boolean};
export type GeneratorTool={slug:string;title:string;shortTitle:string;icon:string;category:"QR & Barcode"|"Business Documents";kind:"qr"|"scanner"|"barcode"|"document";description:string;keywords:string[];intro:string;howTo:string[];features:string[];fields:GeneratorField[];preset?:string;faqs:{question:string;answer:string}[]};

const common=(name:string,category:GeneratorTool["category"])=>[
 {question:"Is "+name+" free to use?",answer:"Yes. It is free, requires no account and creates the result directly in your browser."},
 {question:"Does SolvePilot store my information?",answer:"No. The information you enter is processed in the current browser session and is not submitted to SolvePilot servers."},
 {question:"Does it work on mobile phones?",answer:"Yes. The interface works in modern mobile browsers, although document editing is usually more comfortable on a larger screen."},
 {question:"Can I use the result commercially?",answer:category==="Business Documents"?"You can use the generated document for ordinary business purposes. Review names, figures, tax treatment and legal requirements before issuing it.":"You can use the generated code for personal or business purposes, but always test that it scans correctly before publishing or printing."},
 {question:"Should I check the downloaded result?",answer:"Yes. Test QR codes and barcodes with another device, and review business documents carefully before sharing, printing or relying on them."}
];
const f=(name:string,label:string,type:GeneratorField["type"]="text",placeholder="",required=true):GeneratorField=>({name,label,type,placeholder,required});
const make=(slug:string,title:string,shortTitle:string,icon:string,category:GeneratorTool["category"],kind:GeneratorTool["kind"],description:string,keywords:string[],intro:string,howTo:string[],features:string[],fields:GeneratorField[],preset?:string):GeneratorTool=>({slug,title,shortTitle,icon,category,kind,description,keywords,intro,howTo,features,fields,preset,faqs:common(shortTitle,category)});

const qrFields=[f("value","Content","textarea","Enter text, a link or other content")];
const docBase=[f("business","Business or organisation name","text","Your business name"),f("number","Document number","text","INV-001"),f("date","Issue date","date"),f("customer","Customer or recipient","text","Customer name"),f("details","Description or details","textarea","Item, service or purpose"),f("amount","Amount","number","0"),f("notes","Notes","textarea","Payment terms or additional information",false)];

export const generatorTools:GeneratorTool[]=[
 make("qr-code-generator","QR Code Generator Online Free","QR Code Generator","▦","QR & Barcode","qr","Create a downloadable QR code from text or a link online with private browser processing, adjustable size and no account required.",["qr code generator","create qr code online","free qr maker"],"Turn ordinary text or a web address into a scannable QR image for screens, documents, labels and printed material.",["Enter the text or URL you want to encode.","Choose a suitable image size.","Generate, test and download the PNG."],["PNG download","Adjustable size","Local generation"],qrFields,"text"),
 make("wifi-qr-code-generator","Wi-Fi QR Code Generator Online","Wi-Fi QR Generator","📶","QR & Barcode","qr","Create a Wi-Fi QR code for guests to join your network without typing the password. Generation stays private inside your browser.",["wifi qr code generator","wifi password qr","share wifi qr code"],"Create a convenient network card that compatible phones can scan to fill the Wi-Fi name, security type and password.",["Enter the exact Wi-Fi network name.","Choose the security type and enter its password.","Generate and test the QR code before sharing."],["WPA and open networks","Hidden-network option","Password stays local"],[f("ssid","Network name (SSID)"),f("password","Wi-Fi password","text","Leave blank for an open network",false),f("security","Security type","text","WPA"),f("hidden","Hidden network? Use true or false","text","false")],"wifi"),
 make("whatsapp-qr-code-generator","WhatsApp QR Code Generator","WhatsApp QR Generator","💬","QR & Barcode","qr","Generate a WhatsApp QR code that opens a chat with a phone number and optional message. Free private processing needs no signup.",["whatsapp qr code generator","whatsapp chat qr","wa me qr code"],"Give customers or contacts a scan-to-chat route without asking them to save a phone number first.",["Enter the full international phone number.","Add an optional pre-filled message.","Generate, scan-test and download the QR image."],["Direct chat link","Optional message","PNG download"],[f("phone","Phone number with country code","tel","923001234567"),f("message","Pre-filled message","textarea","Hello, I would like more information.",false)],"whatsapp"),
 make("vcard-qr-code-generator","vCard Contact QR Code Generator","Contact QR Generator","👤","QR & Barcode","qr","Create a vCard contact QR code containing a name, phone, email and organisation for quick saving on compatible phones.",["vcard qr code generator","contact qr code","business contact qr"],"Package common contact details into a standard vCard payload that many phone cameras and QR apps can recognise.",["Enter the contact information.","Generate the QR code locally.","Scan it on another phone and confirm every field."],["Contact-card format","Phone and email","Organisation field"],[f("name","Full name"),f("phone","Phone number","tel"),f("email","Email address","email"),f("business","Organisation","text","Optional",false)],"vcard"),
 make("url-qr-code-generator","URL QR Code Generator Online","URL QR Generator","🔗","QR & Barcode","qr","Convert a website URL into a downloadable QR code online with adjustable size, private browser generation and no registration.",["url qr code generator","website qr code","link to qr code"],"Create a scannable link for menus, posters, packaging, presentations or offline promotional material.",["Paste the complete HTTPS website address.","Generate the QR image.","Test the destination before downloading or printing."],["Website links","PNG output","No redirect service"],[f("url","Website URL","text","https://example.com")],"url"),
 make("email-qr-code-generator","Email QR Code Generator Online","Email QR Generator","✉️","QR & Barcode","qr","Create a QR code that starts an email with a recipient, subject and optional message using free browser-based generation.",["email qr code generator","mailto qr code","email contact qr"],"Let people scan a code to open their email application with useful fields already prepared.",["Enter the recipient email address.","Add a subject and optional message.","Generate and test the code on a phone."],["Recipient address","Subject and body","Local QR creation"],[f("email","Recipient email","email"),f("subject","Subject","text","Enquiry",false),f("message","Message","textarea","",false)],"email"),
 make("sms-qr-code-generator","SMS QR Code Generator Online","SMS QR Generator","💬","QR & Barcode","qr","Generate an SMS QR code with a phone number and optional message so compatible phones can prepare a text after scanning.",["sms qr code generator","text message qr code","sms link qr"],"Create a quick scan-to-text action for support, registrations, campaigns or customer responses.",["Enter a phone number with country code.","Write an optional message.","Generate and verify the action before publishing."],["Phone number encoding","Optional message","PNG download"],[f("phone","Phone number","tel","923001234567"),f("message","SMS message","textarea","",false)],"sms"),
 make("qr-code-scanner","QR Code Scanner Online","QR Code Scanner","▣","QR & Barcode","scanner","Scan a QR code from an uploaded image in supported browsers without sending the image to a server or creating an account.",["qr code scanner online","scan qr from image","qr reader online"],"Read a QR image selected from your device using the browser's supported barcode-detection capability.",["Choose a clear image containing a QR code.","Start the private browser scan.","Copy or open the decoded content only after checking it."],["Image-based scanning","Local image handling","Decoded-text preview"],[],"qr"),
 make("barcode-generator","Barcode Generator Online Free","Barcode Generator","▥","QR & Barcode","barcode","Generate a downloadable CODE128 barcode from letters and numbers online with private processing and no registration required.",["barcode generator online","code 128 barcode generator","create barcode free"],"Create a practical CODE128 barcode for internal references, inventory labels and documents.",["Enter the exact value to encode.","Generate the barcode in your browser.","Download and test it before printing labels."],["CODE128 format","SVG-quality rendering","PNG download"],[f("value","Barcode value","text","ITEM-1001")],"barcode"),
 make("barcode-scanner","Barcode Scanner Online from Image","Barcode Scanner","🔍","QR & Barcode","scanner","Scan common barcodes from an image online in supported browsers. The selected image remains on your device during processing.",["barcode scanner online","scan barcode image","barcode reader"],"Decode supported retail or inventory barcodes from a clear photograph or saved image without uploading it.",["Choose a sharp image of the barcode.","Run the browser-based scan.","Review and copy the detected format and value."],["Common barcode formats","Local image processing","Format identification"],[],"barcode"),
 make("invoice-generator","Free Invoice Generator Online","Invoice Generator","🧾","Business Documents","document","Create a professional invoice PDF online with business, customer, amount and payment details. Free browser generation requires no account.",["invoice generator free","create invoice online","invoice pdf maker"],"Prepare a straightforward invoice for products or services and download it as a PDF for review and delivery.",["Enter the business and customer details.","Add the invoice number, description and amount.","Generate the PDF and verify every figure."],["Numbered invoice","Customer details","PDF download"],docBase,"Invoice"),
 make("receipt-generator","Free Receipt Generator Online","Receipt Generator","🧾","Business Documents","document","Generate a simple payment receipt PDF with payer, amount, date and notes using private browser processing and no registration.",["receipt generator free","payment receipt maker","receipt pdf generator"],"Document an ordinary payment with a clean downloadable receipt that can be printed or shared.",["Enter the issuer and payer information.","Record the receipt number, date and amount.","Download and review the PDF."],["Payment acknowledgement","Receipt numbering","Printable PDF"],docBase,"Receipt"),
 make("quotation-generator","Free Quotation Generator Online","Quotation Generator","📋","Business Documents","document","Create a quotation PDF online with customer, service, price and validity notes. Your entered business information stays in the browser.",["quotation generator free","quote maker online","quotation pdf"],"Prepare a clear preliminary price quotation before work begins or an order is confirmed.",["Enter supplier and customer details.","Describe the proposed work and quoted amount.","Add validity or conditions and download the PDF."],["Quote reference","Service description","Terms and notes"],docBase,"Quotation"),
 make("purchase-order-generator","Purchase Order Generator Online","Purchase Order Generator","🛒","Business Documents","document","Create a purchase order PDF containing buyer, supplier, order reference, description and amount with no account or server storage.",["purchase order generator","po maker online","purchase order pdf"],"Create a basic written purchase instruction that records what is being ordered and the expected value.",["Enter buyer and supplier details.","Add the PO number, item description and amount.","Generate and confirm the PDF before sending."],["PO numbering","Supplier details","Downloadable PDF"],docBase,"Purchase Order"),
 make("delivery-challan-generator","Delivery Challan Generator Online","Delivery Challan Generator","🚚","Business Documents","document","Generate a delivery challan PDF with sender, recipient, delivery reference and item details using free private browser processing.",["delivery challan generator","delivery note maker","challan pdf generator"],"Record goods sent to a customer or location with a simple printable delivery document.",["Enter sender and recipient details.","Describe the delivered goods and reference number.","Download, print and obtain acknowledgement where required."],["Delivery reference","Goods description","Printable acknowledgement"],docBase,"Delivery Challan"),
 make("payslip-generator","Free Payslip Generator Online","Payslip Generator","💵","Business Documents","document","Create a basic payslip PDF with employer, employee, pay period, earnings and deduction notes directly inside your browser.",["payslip generator free","salary slip maker","pay slip pdf"],"Prepare a simple salary statement for an employee while keeping the entered payroll details on the current device.",["Enter employer and employee details.","Record the pay period, gross amount and deduction notes.","Generate and carefully review the payslip PDF."],["Employee details","Pay-period record","Private PDF generation"],[f("business","Employer name"),f("customer","Employee name"),f("number","Employee or payslip number"),f("date","Pay date","date"),f("details","Pay period and earnings details","textarea"),f("amount","Net pay","number"),f("notes","Deductions or notes","textarea","",false)],"Payslip"),
 make("timesheet-generator","Free Timesheet Generator Online","Timesheet Generator","⏱️","Business Documents","document","Generate a simple employee or freelancer timesheet PDF with period, work summary, hours and approval notes without creating an account.",["timesheet generator","employee timesheet maker","freelance timesheet pdf"],"Record working time for a defined period in a compact document suitable for review or attachment to an invoice.",["Enter the worker, client and reporting period.","Describe completed work and total hours.","Generate the PDF and confirm the time entries."],["Worker and client fields","Hours summary","Approval notes"],[f("business","Business or client"),f("customer","Employee or contractor"),f("number","Timesheet reference"),f("date","Period ending","date"),f("details","Work completed","textarea"),f("amount","Total hours","number"),f("notes","Approval notes","textarea","",false)],"Timesheet"),
 make("expense-report-generator","Expense Report Generator Online","Expense Report Generator","📊","Business Documents","document","Create an expense report PDF with claimant, reporting period, expense details and total using private browser-based generation.",["expense report generator","expense claim form maker","expense report pdf"],"Summarise ordinary reimbursable or business expenses in one downloadable document for checking and approval.",["Enter the claimant and organisation.","Describe expenses and enter the total.","Generate the report and attach supporting receipts separately."],["Claimant details","Expense summary","Total and notes"],docBase,"Expense Report"),
 make("business-card-maker","Business Card Maker Online Free","Business Card Maker","💳","Business Documents","document","Design and download a clean business card PDF with your name, role, company and contact information using private browser processing.",["business card maker free","create business card online","business card pdf"],"Create a simple contact card for printing or sharing without saving personal details to a SolvePilot account.",["Enter your name, role and organisation.","Add the contact details you want to publish.","Generate the PDF and check print size and spelling."],["Contact layout","Print-ready PDF","No saved profile"],[f("customer","Full name"),f("details","Role or profession"),f("business","Business name"),f("phone","Phone number","tel"),f("email","Email address","email"),f("notes","Website or address","textarea","",false)],"Business Card"),
 make("letterhead-maker","Letterhead Maker Online Free","Letterhead Maker","📄","Business Documents","document","Create a clean business letterhead PDF with organisation name, contact details and optional footer text directly in your browser.",["letterhead maker free","company letterhead generator","letterhead pdf"],"Generate a reusable-looking first page for simple letters, proposals or notices while keeping business details local.",["Enter the organisation and contact details.","Add an optional reference or footer line.","Generate the PDF and confirm margins before use."],["Header identity","Contact information","Printable A4 PDF"],[f("business","Organisation name"),f("details","Address","textarea"),f("phone","Phone number","tel"),f("email","Email address","email"),f("notes","Website, registration or footer text","textarea","",false)],"Letterhead")
];
export const getGeneratorTool=(slug:string)=>generatorTools.find(t=>t.slug===slug);
