import type { Tool } from "@/lib/tools";

type Seed=Pick<Tool,"slug"|"title"|"shortTitle"|"description"|"formula"|"example">&{focus:string;intent:string};

const seeds:Seed[]=[
 {slug:"debt-snowball-vs-avalanche-calculator",title:"Debt Snowball vs Avalanche Calculator",shortTitle:"Snowball vs Avalanche",description:"Compare debt snowball and debt avalanche payoff strategies using balances, rates and an extra monthly payment.",formula:"Each month interest is added to every open balance, minimum payments are applied, and the extra payment targets either the smallest balance or highest rate.",example:"Compare 8,000 of debt across several accounts with 350 in minimum payments and 200 extra each month to see which order saves more interest.",focus:"minimum-payment rules, changing rates, fees, payment timing and the accuracy of each entered balance",intent:"choose between two popular multi-debt repayment strategies"},
 {slug:"credit-card-minimum-payment-calculator",title:"Credit Card Minimum Payment Calculator",shortTitle:"Minimum Payment",description:"Estimate payoff time and interest when a credit-card balance is repaid using a percentage-based minimum payment.",formula:"Monthly minimum = greater of balance × minimum percentage or fixed floor, limited to the remaining balance plus interest.",example:"A 5,000 balance at 24% with a 3% minimum and a 25 floor can take years to clear because the payment falls as the balance declines.",focus:"issuer formulas, promotional rates, new purchases, late fees and compounding conventions",intent:"understand the long-term cost of paying only a card minimum"},
 {slug:"credit-card-payoff-calculator",title:"Credit Card Payoff Calculator",shortTitle:"Card Payoff",description:"Estimate the months and total interest required to clear a credit-card balance with a fixed monthly payment.",formula:"The balance receives monthly interest, then the entered fixed payment is deducted until the balance reaches zero.",example:"A 6,000 balance at 22% with a 250 monthly payment can be tested against 300 to quantify the time and interest saved.",focus:"rate changes, fees, additional spending, statement timing and payment allocation",intent:"find a practical fixed payment and payoff date for one card"},
 {slug:"credit-card-utilization-calculator",title:"Credit Card Utilization Calculator",shortTitle:"Card Utilization",description:"Calculate utilization for one credit card and across total revolving credit limits before a statement is reported.",formula:"Utilization = reported balance ÷ credit limit × 100. Overall utilization uses total balances divided by total limits.",example:"A reported balance of 900 on a 3,000 limit equals 30% utilization; an additional unused limit changes the overall ratio.",focus:"statement reporting dates, issuer reporting practices, closed accounts and scoring-model differences",intent:"measure reported revolving balance as a percentage of available limits"},
 {slug:"investment-fee-calculator",title:"Investment Fee Calculator",shortTitle:"Investment Fees",description:"Compare long-term investment growth before and after annual fund or adviser fees using regular contributions.",formula:"Each period applies gross return minus the selected annual fee before adding the next contribution; fee drag is the difference between scenarios.",example:"Investing 20,000 plus 500 monthly for 20 years can produce a materially different balance at 0.2% versus 1.2% annual fees.",focus:"market returns, contribution timing, layered fees, taxes and inflation",intent:"see how recurring investment fees compound over time"},
 {slug:"inflation-adjusted-return-calculator",title:"Inflation-Adjusted Return Calculator",shortTitle:"Real Return",description:"Convert a nominal investment return into a real return after inflation and optional annual fees.",formula:"Real return = ((1 + nominal return − fees) ÷ (1 + inflation)) − 1.",example:"A nominal 7% return with 2.5% inflation and 0.5% fees produces a real return below the simple 4% subtraction estimate.",focus:"variable inflation, taxes, fee definitions, sequence of returns and purchasing-power measurement",intent:"measure investment growth in purchasing-power terms"},
 {slug:"dollar-cost-averaging-calculator",title:"Dollar-Cost Averaging Calculator",shortTitle:"DCA Calculator",description:"Project the future value of equal recurring investments using a configurable return and contribution period.",formula:"The balance grows at the monthly equivalent of the entered annual return and receives a contribution at the end of each month.",example:"A 400 monthly contribution over 10 years can be compared at 4%, 6% and 8% assumed annual returns.",focus:"market volatility, contribution timing, fees, taxes and uncertain future returns",intent:"estimate growth from regular scheduled investing"},
 {slug:"lump-sum-vs-dca-calculator",title:"Lump Sum vs Dollar-Cost Averaging Calculator",shortTitle:"Lump Sum vs DCA",description:"Compare investing available cash immediately with investing the same amount gradually over a selected schedule.",formula:"The lump sum compounds for the full period; the DCA scenario holds uninvested cash separately and invests equal portions over time.",example:"Compare investing 24,000 today with investing 2,000 monthly for 12 months under the same assumed market return.",focus:"market timing, cash yield, volatility, contribution dates, fees and risk tolerance",intent:"compare immediate investing with staged market entry"},
 {slug:"coast-fire-calculator",title:"Coast FIRE Calculator",shortTitle:"Coast FIRE",description:"Estimate whether current investments could grow to a retirement target without additional contributions.",formula:"Retirement target = annual retirement spending ÷ withdrawal rate. Coast number = target ÷ (1 + real return)^years.",example:"A person with 25 years until retirement can compare current investments with the present amount required to reach a 750,000 target.",focus:"retirement spending, real returns, withdrawal rates, taxes, fees and pension income",intent:"estimate the investment balance required to coast toward retirement"},
 {slug:"fire-number-calculator",title:"FIRE Number Calculator",shortTitle:"FIRE Number",description:"Estimate a financial-independence portfolio target from annual spending and a chosen withdrawal rate.",formula:"FIRE number = annual retirement spending ÷ planned withdrawal rate.",example:"Annual spending of 40,000 with a 4% withdrawal assumption produces a starting target of 1,000,000 before taxes and buffers.",focus:"future spending, withdrawal sustainability, healthcare, taxes, longevity and other income",intent:"turn expected annual spending into a financial-independence target"},
 {slug:"savings-rate-calculator",title:"Savings Rate Calculator",shortTitle:"Savings Rate",description:"Calculate the percentage of take-home income saved or invested and project the annual amount.",formula:"Savings rate = monthly saving ÷ monthly take-home income × 100.",example:"Saving 1,200 from take-home income of 5,000 creates a 24% savings rate and 14,400 annual contribution pace.",focus:"pre-tax versus after-tax income, employer contributions, debt principal and irregular income",intent:"measure how much disposable income is retained each month"},
 {slug:"dividend-reinvestment-calculator",title:"Dividend Reinvestment Calculator",shortTitle:"Dividend Reinvestment",description:"Project portfolio value and dividend income when distributions are reinvested over time.",formula:"Each period applies price growth, calculates dividend yield on the balance and adds reinvested dividends plus contributions.",example:"A 25,000 portfolio with a 3% yield, 4% price growth and reinvestment can be projected for 15 years.",focus:"dividend changes, market prices, taxes, reinvestment dates, fees and company risk",intent:"estimate compounding when investment distributions buy more shares"},
 {slug:"portfolio-rebalancing-calculator",title:"Portfolio Rebalancing Calculator",shortTitle:"Portfolio Rebalancing",description:"Calculate trades required to restore two portfolio assets to selected target percentages.",formula:"Target value for each asset = total portfolio × target weight. Required trade = target value − current value.",example:"A 70,000 stock allocation and 30,000 bond allocation can be rebalanced toward a 60/40 target.",focus:"taxable gains, trading costs, account restrictions, target design and market movement",intent:"calculate buy and sell amounts for target asset weights"},
 {slug:"capital-gains-calculator-global",title:"Capital Gains Calculator",shortTitle:"Capital Gains",description:"Calculate gross capital gain, taxable gain and an estimated tax amount using user-entered adjustments and rate.",formula:"Adjusted gain = sale proceeds − selling costs − cost basis − eligible adjustments. Estimated tax = taxable gain × entered rate.",example:"Selling an asset for 30,000 with a 20,000 basis and 1,000 selling costs creates a 9,000 gain before exemptions or adjustments.",focus:"local tax law, holding periods, exemptions, loss offsets, currency and allowable costs",intent:"estimate a gain before applying jurisdiction-specific tax rules"},
 {slug:"tiered-commission-calculator",title:"Tiered Commission Calculator",shortTitle:"Tiered Commission",description:"Calculate sales commission across progressive tiers and show the blended commission rate.",formula:"Commission is calculated separately for sales falling inside each tier, then the tier amounts are added.",example:"Sales of 120,000 can pay 3% on the first 50,000 and 5% above that threshold instead of applying 5% to everything.",focus:"progressive versus retroactive tiers, returns, quota definitions, caps and payment timing",intent:"calculate progressive sales compensation accurately"},
 {slug:"prorated-salary-calculator",title:"Prorated Salary Calculator",shortTitle:"Prorated Salary",description:"Calculate partial-period salary using calendar days or working days and optional unpaid leave.",formula:"Prorated pay = full-period salary × payable days ÷ total eligible days.",example:"A monthly salary of 4,000 with 16 payable working days in a 22-day work month produces prorated gross pay of about 2,909.",focus:"payroll policy, calendar versus workdays, leave treatment, benefits, deductions and rounding",intent:"estimate salary for joining, leaving or unpaid leave during a pay period"},
 {slug:"pay-raise-percentage-calculator",title:"Pay Raise Percentage Calculator",shortTitle:"Pay Raise",description:"Calculate raise amount, new salary and percentage change between old and new pay.",formula:"Raise percentage = (new pay − old pay) ÷ old pay × 100.",example:"Moving from 50,000 to 54,000 annually is an 8% raise and increases gross monthly pay by about 333.",focus:"gross versus net pay, bonuses, benefits, inflation, work hours and tax",intent:"compare an offered salary with current compensation"},
 {slug:"overtime-pay-calculator-global",title:"Overtime Pay Calculator",shortTitle:"Overtime Pay",description:"Estimate regular pay, overtime pay and total gross earnings using an editable overtime multiplier.",formula:"Overtime pay = overtime hours × hourly rate × overtime multiplier.",example:"Ten overtime hours at 20 per hour with a 1.5 multiplier add 300 to regular gross pay.",focus:"local employment law, eligibility, blended rates, pay periods, breaks and deductions",intent:"estimate gross earnings from overtime hours"},
 {slug:"invoice-due-date-calculator",title:"Invoice Due Date Calculator",shortTitle:"Invoice Due Date",description:"Find an invoice payment deadline from an invoice date and user-entered payment term.",formula:"Due date = invoice date plus the selected number of calendar days.",example:"An invoice issued on the first day of a month with Net 30 terms is due 30 calendar days later unless the contract says otherwise.",focus:"calendar versus business days, weekends, holidays, receipt dates and contract wording",intent:"convert common invoice terms into a clear payment date"},
 {slug:"net-payment-terms-calculator",title:"Net 30, 60 and 90 Date Calculator",shortTitle:"Net Terms Date",description:"Compare Net 30, Net 60 and Net 90 deadlines from the same invoice or delivery date.",formula:"Each deadline equals the starting date plus 30, 60 or 90 calendar days.",example:"Use one starting date to display all three common payment deadlines and compare their effect on cash collection.",focus:"term start events, calendar rules, holidays, customer agreements and late-payment clauses",intent:"compare common business payment-term dates"},
 {slug:"invoice-discount-calculator",title:"Invoice Discount Calculator",shortTitle:"Invoice Discount",description:"Calculate an early-payment discount, customer payment and supplier cash received from invoice terms.",formula:"Discount = invoice value × discount rate. Discounted payment = invoice value − discount.",example:"A 10,000 invoice offering a 2% early-payment discount reduces payment by 200 when the customer qualifies.",focus:"eligibility dates, tax treatment, credit notes, partial payments and contract terms",intent:"quantify the cost of offering an invoice-payment discount"},
 {slug:"freelance-project-profit-calculator",title:"Freelance Project Profit Calculator",shortTitle:"Project Profit",description:"Calculate freelance project profit after labour value, platform fees and direct expenses.",formula:"Net profit = project revenue − platform fees − direct costs − hours × internal hourly cost.",example:"A 3,000 project with 10% platform fees, 200 expenses and 40 hours valued at 35 produces 1,100 economic profit.",focus:"scope changes, unpaid revisions, taxes, payment risk, non-billable time and overhead",intent:"check whether a freelance quote remains profitable"},
 {slug:"saas-pricing-calculator",title:"SaaS Pricing Calculator",shortTitle:"SaaS Pricing",description:"Estimate a subscription price from per-customer cost, target gross margin and fixed monthly costs.",formula:"Price before fixed-cost allocation = variable cost ÷ (1 − target margin). Break-even customers = fixed costs ÷ contribution per customer.",example:"A service costing 8 per active customer with an 80% target gross margin needs a 40 price before fixed-cost allocation.",focus:"support usage, churn, payment fees, taxes, annual discounts and customer acquisition cost",intent:"test subscription price, contribution and break-even customer count"},
 {slug:"debt-service-coverage-ratio-calculator",title:"Debt Service Coverage Ratio Calculator",shortTitle:"Debt Service Coverage",description:"Calculate debt service coverage ratio from operating income and required principal and interest payments.",formula:"DSCR = net operating income ÷ total debt service for the same period.",example:"Annual net operating income of 150,000 and annual debt service of 100,000 produces a debt service coverage ratio of 1.50.",focus:"income definitions, one-time items, lender adjustments, payment periods and changing debt obligations",intent:"measure how comfortably operating income covers scheduled debt payments"},
 {slug:"merchant-processing-fee-calculator",title:"Merchant Processing Fee Calculator",shortTitle:"Processing Fees",description:"Calculate percentage and fixed payment-processing fees, net proceeds and effective fee rate.",formula:"Processing fee = transaction amount × percentage rate + fixed fee. Net proceeds = amount − fee.",example:"A 100 payment charged at 2.9% plus 0.30 produces a 3.20 fee and 96.80 net proceeds.",focus:"cross-border charges, currency conversion, refunds, tax, chargebacks and fee tiers",intent:"estimate net revenue after card or platform transaction fees"},
];

const faqs=(t:Seed)=>[
 {question:`Is the ${t.shortTitle.toLowerCase()} tool free?`,answer:"Yes. It is free, requires no registration and performs the calculation in your browser."},
 {question:"Can I use any currency?",answer:"Yes. Enter every monetary value in the same currency; the calculator does not convert or assume a currency."},
 {question:"Does SolvePilot store my financial information?",answer:"No. Values entered into this calculator remain on your device and are not submitted to SolvePilot."},
 {question:"Is the result financial, tax or investment advice?",answer:"No. It is an educational estimate for comparison and planning, not a recommendation or official calculation."},
 {question:"Why can the real result differ?",answer:`Actual outcomes can differ because of ${t.focus}. Verify important decisions with current documents and an appropriate professional.`},
 {question:"How should I test the result?",answer:"Check the inputs against current records, change one uncertain assumption at a time and compare a cautious scenario with the baseline."},
];

export const globalFinanceExpansionTools:Tool[]=seeds.map(t=>({...t,icon:"💳",category:t.slug.includes("invoice")||t.slug.includes("commission")||t.slug.includes("freelance")||t.slug.includes("saas")||t.slug.includes("merchant")||t.slug.includes("debt-service")?"Business":"Money",accent:"green",updatedAt:"2026-09-25",keywords:[t.title.toLowerCase(),`free ${t.shortTitle.toLowerCase()} calculator`,`online ${t.shortTitle.toLowerCase()} tool`,t.intent],intro:`${t.description} This currency-neutral calculator is designed for people comparing ${t.intent}. It shows supporting figures alongside the main answer so the result can be checked instead of accepted as an unexplained number. No country, currency, provider rate or legal rule is selected automatically.`,howTo:["Enter current figures from statements, contracts, invoices or payroll records.","Keep currencies and monthly, annual or daily periods consistent across every input.","Calculate a baseline, then change one uncertain value to create a cautious comparison.","Save the assumptions with the result and confirm material decisions using authoritative documents."],considerations:[{title:"Definitions and timing",text:`Confirm how each provider defines balances, rates, periods and payment dates. The result is particularly sensitive to ${t.focus}.`},{title:"Comparable values",text:"Do not mix gross with net amounts, monthly with annual rates, or currencies without converting them first."},{title:"Scenario uncertainty",text:"Future rates, prices, income and investment results are not guaranteed. Use a range rather than one optimistic assumption."},{title:"External rules",text:"Contracts, tax rules, employment law and regulated financial-product disclosures vary by country and provider."}],limitations:`This ${t.shortTitle.toLowerCase()} calculator is an educational planning tool. It cannot validate source documents, identify the law or tax treatment in a visitor's country, predict investment performance, assess suitability, discover undisclosed charges or create a binding quotation. Review current contractual terms and obtain qualified financial, tax, accounting, investment or legal guidance when the result could affect a material decision.`,faqs:faqs(t)}));
