import type { Tool } from "@/lib/tools";

type FinanceSeed = Pick<Tool,"slug"|"title"|"shortTitle"|"description"|"formula"|"example"> & {
  focus:string;
  howTo:[string,string,string,string];
};

const seeds:FinanceSeed[]=[
  {slug:"personal-cash-runway-calculator",title:"Personal Cash Runway Calculator",shortTitle:"Personal Cash Runway",description:"Estimate how many months your available savings can cover an ongoing monthly cash shortfall.",formula:"Monthly shortfall = essential monthly spending − dependable monthly income. Cash runway = available savings ÷ monthly shortfall.",example:"Savings of 18,000 with monthly essentials of 3,000 and dependable income of 1,500 provides about 12 months of cash runway.",focus:"income reliability, essential spending, emergency costs and restricted savings",howTo:["Enter only savings that are available for living costs.","Add essential monthly spending on the same basis.","Enter dependable monthly income expected during the runway period.","Compare the baseline with a higher-expense or lower-income scenario."]},
  {slug:"business-cash-runway-calculator",title:"Business Cash Runway Calculator",shortTitle:"Business Cash Runway",description:"Estimate how long a business can operate from available cash at its current net monthly burn.",formula:"Usable cash = cash balance − protected reserve. Net burn = monthly expenses − monthly cash revenue. Runway = usable cash ÷ net burn.",example:"A business with 120,000 cash, a 20,000 reserve, 35,000 monthly revenue and 55,000 monthly expenses has about five months of runway.",focus:"cash collection timing, payroll, tax reserves, seasonal revenue and unexpected costs",howTo:["Use the current unrestricted business cash balance.","Enter average monthly cash collected, not merely invoiced revenue.","Enter complete recurring monthly cash expenses.","Protect tax or emergency reserves before interpreting the runway."]},
  {slug:"monthly-burn-rate-calculator",title:"Monthly Burn Rate Calculator",shortTitle:"Burn Rate",description:"Calculate gross burn, net burn and the percentage of opening cash consumed each month.",formula:"Gross monthly burn = monthly operating expenses. Net monthly burn = expenses − cash revenue. Burn percentage = net burn ÷ opening cash × 100.",example:"With 50,000 of expenses, 32,000 of cash revenue and 180,000 opening cash, net burn is 18,000 per month or 10% of opening cash.",focus:"cash versus accrual accounting, one-off costs, revenue collection and owner withdrawals",howTo:["Enter the opening cash available to the operation.","Use cash revenue actually collected in a typical month.","Include payroll, rent, software and other operating cash expenses.","Separate unusual one-time payments and test them as a second scenario."]},
  {slug:"emergency-fund-calculator",title:"Emergency Fund Calculator",shortTitle:"Emergency Fund",description:"Set a configurable emergency-fund target and measure current savings coverage in months.",formula:"Target fund = essential monthly expenses × selected coverage months. Funding gap = target − current emergency savings.",example:"Essential spending of 2,500 for six months creates a 15,000 target; 6,000 already saved covers 2.4 months and leaves a 9,000 gap.",focus:"job stability, insurance, dependants, essential expenses and access to funds",howTo:["Total only expenses that must continue during an emergency.","Choose a coverage period appropriate to your circumstances.","Enter savings reserved specifically for emergencies.","Review the target whenever income or essential commitments change."]},
  {slug:"sinking-fund-calculator",title:"Sinking Fund Calculator",shortTitle:"Sinking Fund",description:"Calculate the regular contribution needed for a known future expense, with optional interest.",formula:"With no return, contribution = remaining target ÷ months. With a monthly rate, payment = remaining target × rate ÷ ((1 + rate)^months − 1).",example:"A 12,000 target with 3,000 saved and 18 months remaining requires 500 per month before interest.",focus:"goal cost changes, contribution timing, fees, taxes and uncertain returns",howTo:["Set the complete expected future cost.","Subtract only money already assigned to this goal.","Enter the exact number of monthly contributions remaining.","Use zero or a conservative return unless interest is contractually known."]},
  {slug:"debt-to-income-ratio-calculator",title:"Debt-to-Income Ratio Calculator",shortTitle:"Debt-to-Income Ratio",description:"Compare required monthly debt payments with gross monthly income using front-end and total DTI views.",formula:"Total DTI = (housing payment + other required debt payments) ÷ gross monthly income × 100.",example:"Gross monthly income of 6,000, housing of 1,500 and other debt payments of 600 produces a total DTI of 35%.",focus:"gross versus net income, required payments, lender definitions and variable income",howTo:["Enter dependable gross monthly income before deductions.","Enter the required monthly housing payment.","Add minimum required payments for other debts.","Compare the result with the method used by the relevant lender."]},
  {slug:"loan-comparison-calculator",title:"Loan Comparison Calculator",shortTitle:"Loan Comparison",description:"Compare monthly payments and total interest for two fixed-rate loans over the same term.",formula:"Payment = principal × monthly rate × (1 + rate)^payments ÷ ((1 + rate)^payments − 1).",example:"On a 25,000 five-year loan, comparing 7% with 9% shows both the monthly-payment difference and additional lifetime interest.",focus:"origination fees, effective rates, variable terms, insurance and prepayment rules",howTo:["Enter the same amount and repayment term for a rate-only comparison.","Enter Loan A's annual reducing-balance rate.","Enter Loan B's comparable annual reducing-balance rate.","Add lender fees separately before choosing the lower total cost."]},
  {slug:"effective-interest-rate-calculator",title:"Effective Interest Rate Calculator",shortTitle:"Effective Interest Rate",description:"Convert a nominal annual rate and compounding frequency into an effective annual rate.",formula:"Effective annual rate = (1 + nominal rate ÷ compounding periods)^compounding periods − 1.",example:"A 12% nominal rate compounded monthly has an effective annual rate of about 12.68% before fees.",focus:"compounding conventions, fees, introductory periods and variable rates",howTo:["Enter the quoted nominal annual percentage rate.","Enter how many times interest compounds each year.","Use the result to compare quotations on the same annual basis.","Review fees separately because this calculation is not a complete APR disclosure."]},
  {slug:"loan-early-payment-calculator",title:"Loan Early Payment Calculator",shortTitle:"Loan Early Payment",description:"Estimate payoff time and interest savings from adding a fixed extra amount to each loan payment.",formula:"The balance is reduced month by month after interest; the extra payment is applied directly to principal in the estimate.",example:"A 100,000 balance at 7% with a 2,000 regular payment can be compared with a 300 monthly extra payment to estimate time and interest saved.",focus:"prepayment penalties, payment allocation, rate changes and lender rounding",howTo:["Enter the current principal balance rather than the original loan amount.","Use the current annual reducing-balance interest rate.","Enter the contractual monthly payment and proposed extra payment.","Confirm that the lender applies extra money to principal without penalty."]},
  {slug:"invoice-financing-cost-calculator",title:"Invoice Financing Cost Calculator",shortTitle:"Invoice Financing Cost",description:"Estimate the cash advanced, financing fee and implied annualized cost of financing an invoice.",formula:"Advance = invoice × advance rate. Fee = invoice × fee rate. Annualized simple cost = fee ÷ advance × 365 ÷ financed days.",example:"A 10,000 invoice with an 80% advance and 2% fee provides 8,000 now at a 200 fee; over 30 days the simple annualized cost is about 30.4%.",focus:"recourse, service charges, minimum fees, delayed payment and annualization",howTo:["Enter the invoice face value eligible for financing.","Enter the percentage advanced immediately.","Enter the complete fee charged on the invoice value.","Use the expected financed days and verify recourse and additional charges."]},
  {slug:"late-payment-interest-calculator",title:"Late Payment Interest Calculator",shortTitle:"Late Payment Interest",description:"Calculate simple late-payment interest and an optional fixed recovery charge from user-entered terms.",formula:"Interest = overdue amount × annual rate × overdue days ÷ 365. Total due = principal + interest + fixed charge.",example:"An overdue balance of 5,000 at 8% for 45 days creates about 49.32 interest before any valid fixed charge.",focus:"contract terms, statutory rules, day-count basis, compounding and partial payments",howTo:["Enter the unpaid principal after credits or partial payments.","Use only an annual rate permitted by the contract or applicable rules.","Count overdue days using the required day-count convention.","Add a fixed charge only where it is valid and documented."]},
  {slug:"subscription-cost-calculator",title:"Subscription Cost Calculator",shortTitle:"Subscription Cost",description:"Project the multi-year cost of recurring subscriptions with an optional annual price increase.",formula:"Yearly cost starts at monthly price × subscription count × 12 and increases annually by the entered percentage.",example:"Five subscriptions averaging 20 per month cost 1,200 in year one; a 5% annual increase raises the three-year total above 3,700.",focus:"annual plans, cancellation dates, taxes, price increases and unused services",howTo:["Use the average monthly price paid per subscription.","Enter the number of active recurring subscriptions.","Choose the number of years to project.","Test both zero increase and a cautious price-increase scenario."]},
  {slug:"salary-to-freelance-rate-calculator",title:"Salary to Freelance Rate Calculator",shortTitle:"Salary to Freelance Rate",description:"Translate an annual employee salary target into a sustainable freelance hourly rate.",formula:"Required hourly rate = (target salary + annual overhead) ÷ (billable hours per week × working weeks).",example:"Replacing a 60,000 salary with 12,000 annual overhead across 25 billable hours for 48 weeks requires at least 60 per billable hour before tax and profit margin.",focus:"unpaid administration, leave, taxes, benefits, overhead and billable utilization",howTo:["Enter the annual salary value you want freelance work to replace.","Add annual software, equipment, insurance and business overhead.","Use realistic billable—not total working—hours per week.","Reduce working weeks for holidays, illness and business development."]},
  {slug:"savings-withdrawal-runway-calculator",title:"Savings Withdrawal Runway Calculator",shortTitle:"Savings Withdrawal Runway",description:"Estimate how long savings may last under fixed monthly withdrawals and an assumed annual return.",formula:"The estimate applies monthly return, then subtracts the chosen withdrawal until the balance reaches zero or the simulation limit.",example:"Savings of 100,000 withdrawn at 2,000 monthly lasts about 50 months with no return, before inflation, tax or unexpected withdrawals.",focus:"sequence of returns, inflation, fees, taxes and changing withdrawals",howTo:["Enter the savings balance available for planned withdrawals.","Enter the intended monthly withdrawal in the same currency.","Use a conservative net annual return after fees.","Compare the result with zero return and a higher withdrawal."]},
  {slug:"recurring-expense-impact-calculator",title:"Recurring Expense Impact Calculator",shortTitle:"Recurring Expense Impact",description:"Project the long-term cash cost of a recurring monthly expense and optional annual price growth.",formula:"Each year's monthly expense is multiplied by 12 and increased by the entered annual growth rate; yearly totals are accumulated.",example:"A 75 monthly expense over 10 years costs 9,000 with no increase, or more than 10,700 if it rises 4% each year.",focus:"price escalation, cancellation, taxes, usage and opportunity cost assumptions",howTo:["Enter the complete recurring monthly charge.","Choose the period over which you expect to keep paying it.","Add a realistic annual price-change assumption.","Compare the projection with cancellation or a lower-cost alternative."]},
  {slug:"lifestyle-inflation-calculator",title:"Lifestyle Inflation Calculator",shortTitle:"Lifestyle Inflation",description:"Measure how much monthly spending increased after an income change and project its annual effect.",formula:"Lifestyle increase = current monthly spending − previous monthly spending. Share of income increase consumed = spending increase ÷ income increase × 100.",example:"If monthly income rises from 4,000 to 5,000 while spending rises from 2,800 to 3,500, lifestyle costs consume 70% of the income increase.",focus:"one-time purchases, inflation, household changes, debt payments and savings",howTo:["Enter monthly income before the change.","Enter current monthly income on the same basis.","Enter comparable monthly spending before and after the change.","Separate general price inflation from optional lifestyle upgrades where possible."]},
  {slug:"rent-affordability-calculator",title:"Rent Affordability Calculator",shortTitle:"Rent Affordability",description:"Estimate a cautious rent ceiling from monthly income, essential commitments and a chosen income percentage.",formula:"Guideline rent = income × selected percentage. Cash-flow ceiling = income − essential non-rent commitments. Suggested ceiling is the lower value.",example:"Income of 5,000, non-rent commitments of 2,500 and a 30% guideline produces a 1,500 planning ceiling before utilities and move-in costs.",focus:"net versus gross income, utilities, deposits, debt, income stability and local housing costs",howTo:["Use dependable monthly take-home income for cash-flow planning.","Enter essential commitments excluding rent.","Select a personal maximum rent percentage rather than treating 30% as a rule.","Reserve utilities, deposits, moving costs and emergency savings separately."]},
  {slug:"financial-goal-timeline-calculator",title:"Financial Goal Timeline Calculator",shortTitle:"Goal Timeline",description:"Estimate how many months regular contributions may take to reach a financial target.",formula:"The balance grows monthly by the assumed return and the regular contribution until it reaches the target.",example:"Starting with 2,000 and adding 300 monthly reaches a 10,000 goal in about 27 months with no return.",focus:"irregular contributions, changing target costs, fees, taxes and uncertain returns",howTo:["Enter the complete target value in one currency.","Enter money already reserved for that goal.","Use a contribution you can maintain each month.","Test zero return as well as a conservative net-return scenario."]},
  {slug:"budget-percentage-calculator",title:"Budget Percentage Calculator",shortTitle:"Budget Percentage",description:"Convert monthly spending and saving amounts into percentages of take-home income.",formula:"Category percentage = category amount ÷ monthly take-home income × 100. Unallocated amount = income − entered categories.",example:"On income of 5,000, essentials of 2,500, discretionary spending of 1,000 and savings of 750 use 50%, 20% and 15%, leaving 750 unallocated.",focus:"irregular expenses, annual bills, debt principal, transfers and double counting",howTo:["Use monthly take-home income after compulsory deductions.","Group essential spending consistently.","Separate optional spending from saving or debt reduction.","Investigate any negative or unusually large unallocated balance."]},
  {slug:"net-worth-change-calculator",title:"Net Worth Change Calculator",shortTitle:"Net Worth Change",description:"Compare assets and liabilities at two dates to measure the amount and percentage change in net worth.",formula:"Net worth = total assets − total liabilities. Change = current net worth − previous net worth.",example:"Assets rising from 120,000 to 135,000 while liabilities fall from 45,000 to 40,000 increases net worth from 75,000 to 95,000, a 26.7% gain.",focus:"asset valuation, currency conversion, pension treatment, taxes and omitted liabilities",howTo:["Choose two comparable measurement dates.","Value assets using the same reasonable method at both dates.","Include all outstanding liabilities on each date.","Explain large changes instead of treating percentage growth alone as performance."]},
];

const faqs=(tool:FinanceSeed)=>[
  {question:`Is the ${tool.shortTitle.toLowerCase()} calculator free?`,answer:"Yes. The calculator is free, requires no account and processes the values in your browser."},
  {question:"Can I use dollars, euros, pounds or another currency?",answer:"Yes. Monetary calculations are currency-neutral. Use one currency consistently for every amount in the same calculation."},
  {question:"Does SolvePilot store my financial information?",answer:"No. The entered values are calculated on your device and are not submitted to a SolvePilot server."},
  {question:"Is this financial advice?",answer:"No. The result is an educational planning estimate based only on the values and assumptions you provide."},
  {question:"Why might the real result be different?",answer:`Actual outcomes can differ because of ${tool.focus}. Confirm material decisions using current documents and a qualified professional where appropriate.`},
  {question:"How should I compare scenarios?",answer:"Change one assumption at a time, keep the time periods and currency consistent, and include a conservative case rather than relying only on the most favourable result."},
];

export const globalFinanceTools:Tool[]=seeds.map(tool=>({
  ...tool,icon:"💰",category:"Money",accent:"green",updatedAt:"2026-09-22",
  keywords:[tool.title.toLowerCase(),`free ${tool.shortTitle.toLowerCase()} calculator`,`online ${tool.shortTitle.toLowerCase()} tool`,`${tool.shortTitle.toLowerCase()} formula`],
  intro:`${tool.description} It uses currency-neutral inputs so the same calculation can be used globally. The result explains the arithmetic and supporting figures instead of presenting a single unexplained number. Use it to explore choices and prepare questions, not as an approval, quotation, forecast or personal financial recommendation.`,
  howTo:tool.howTo,
  considerations:[
    {title:"Use comparable inputs",text:"Keep currency, monthly or annual periods, and before-tax or after-tax amounts consistent throughout the calculation."},
    {title:"Stress-test uncertainty",text:`The answer is sensitive to ${tool.focus}. Test a less favourable scenario before relying on the estimate.`},
    {title:"Check product terms",text:"Provider fees, contractual definitions, payment timing, compounding and local regulation can change the real result."},
    {title:"Review over time",text:"Update the calculation when income, expenses, rates, balances or the planning date changes."},
  ],
  limitations:`This ${tool.shortTitle.toLowerCase()} calculation is an educational estimate, not financial, investment, credit, tax, accounting or legal advice. It cannot check whether an input is complete, determine local eligibility, predict returns, incorporate undisclosed fees or replace the terms supplied by a regulated provider. Verify important decisions using current statements, contractual documents and an appropriately qualified professional.`,
  faqs:faqs(tool),
}));
