export type ImageTool={slug:string;title:string;shortTitle:string;icon:string;description:string;keywords:string[];accept:string;intro:string;howTo:string[];features:string[];faqs:{question:string;answer:string}[]};
const common=(name:string)=>[
 {question:"Is "+name+" free?",answer:"Yes. It is free, requires no account and does not add a watermark unless you select the watermark tool."},
 {question:"Are my images uploaded?",answer:"No. Processing happens inside your browser and selected images are not sent to SolvePilot servers."},
 {question:"Does it work on phones?",answer:"Yes, in current mobile browsers. Very large photographs may work faster on a computer with more memory."},
 {question:"Will processing reduce image quality?",answer:"Lossless PNG keeps detail, while JPG and WebP quality depends on the chosen compression setting. Always review the result."},
 {question:"What image size is supported?",answer:"There is no upload limit, but images below 20 MB and 20 megapixels are recommended for reliable browser processing."}
];
const make=(slug:string,title:string,shortTitle:string,icon:string,description:string,keywords:string[],accept:string,intro:string,howTo:string[],features:string[],extra?:{question:string;answer:string}):ImageTool=>({slug,title,shortTitle,icon,description,keywords,accept,intro,howTo,features,faqs:[...(extra?[extra]:[]),...common(shortTitle)].slice(0,5)});
export const imageTools:ImageTool[]=[
make("jpg-to-png","Convert JPG to PNG Online","JPG to PNG","🟦","Convert JPG and JPEG images to PNG online with private browser processing, original dimensions and no account or server upload.",["jpg to png","jpeg to png online","convert jpg image"],"image/jpeg","Create a PNG copy of a JPG photograph or graphic while preserving its pixel dimensions.",["Choose a JPG or JPEG image.","Preview its dimensions and appearance.","Convert and download the PNG file."],["Original dimensions","Lossless PNG output","Local conversion"]),
make("png-to-jpg","Convert PNG to JPG Online","PNG to JPG","🟨","Convert PNG images to smaller JPG files online with adjustable quality, background color and private browser processing.",["png to jpg","png to jpeg online","convert transparent png"],"image/png","Create a widely compatible JPG and choose the solid background used behind transparent PNG areas.",["Choose a PNG image.","Select quality and background color.","Convert and download the JPG."],["Quality control","Transparency background","Smaller output"]),
make("image-to-webp","Convert Image to WebP Online","Image to WebP","🟩","Convert JPG or PNG images to modern WebP online with adjustable quality and private processing that keeps files on your device.",["image to webp","jpg to webp","png to webp online"],"image/jpeg,image/png","Produce efficient WebP images for websites, apps and sharing while controlling the quality level.",["Choose a JPG or PNG image.","Adjust WebP quality.","Convert and download the result."],["JPG and PNG input","Quality slider","Modern WebP output"]),
make("heic-to-jpg","Convert HEIC to JPG Online","HEIC to JPG","📱","Convert iPhone HEIC photos to compatible JPG images online. Private browser processing requires no account or server upload.",["heic to jpg","iphone photo converter","convert heic online"],".heic,.heif,image/heic,image/heif","Make iPhone and HEIF photographs easier to open, upload and share on services that expect JPG.",["Choose a HEIC or HEIF photo.","Wait for local decoding.","Download the converted JPG."],["HEIC and HEIF input","JPG compatibility","Local decoding"]),
make("compress-image","Compress Image Online","Image Compressor","🗜️","Compress JPG, PNG or WebP images online with quality and format controls. Files stay private through local browser processing.",["compress image online","reduce image file size","photo compressor"],"image/jpeg,image/png,image/webp","Reduce image file size for web pages, forms, email and messaging while previewing the output size.",["Choose an image.","Select output format and quality.","Compress and download the optimized file."],["Quality control","Format selection","Before and after sizes"]),
make("resize-image","Resize Image Online","Image Resizer","↔️","Resize JPG, PNG or WebP images online by exact width and height with aspect-ratio control and private browser processing.",["resize image online","change image dimensions","photo resizer"],"image/jpeg,image/png,image/webp","Create exact image dimensions for websites, profiles, applications, listings or social posts.",["Choose an image.","Enter the required width or height.","Resize and download the new image."],["Exact dimensions","Aspect-ratio lock","Multiple output formats"]),
make("crop-rotate-image","Crop and Rotate Image Online","Crop & Rotate","✂️","Crop and rotate JPG, PNG or WebP images online using exact coordinates, dimensions and angle with private processing.",["crop image online","rotate image online","crop photo exact size"],"image/jpeg,image/png,image/webp","Remove unwanted edges and correct orientation in one browser-based operation.",["Choose an image.","Enter crop coordinates and size, then choose rotation.","Process and download the edited image."],["Exact crop controls","90-degree rotation","Live source dimensions"]),
make("passport-photo-maker","Passport Photo Maker Online","Passport Photo Maker","🪪","Create a 35×45 mm-style passport photo from an uploaded portrait with centered cropping and private browser processing.",["passport photo maker","35x45 photo online","passport size image"],"image/jpeg,image/png,image/webp","Create a correctly proportioned 35:45 portrait image for preview or printing preparation.",["Choose a clear front-facing portrait.","Adjust zoom and background color.","Create and download the 413×531 pixel image."],["35:45 ratio","413×531 output","Background selection"],{question:"Is the result guaranteed for official documents?",answer:"No. Photo rules vary by country and authority. Check current official requirements before submitting it."}),
make("add-watermark-image","Add Watermark to Image Online","Image Watermark","💧","Add custom text watermarks to JPG, PNG or WebP images online with position, size and opacity controls in your browser.",["add watermark to image","photo watermark online","watermark picture"],"image/jpeg,image/png,image/webp","Protect previews, credit your work or label product images with configurable watermark text.",["Choose an image.","Enter text and select position, size and opacity.","Apply and download the watermarked image."],["Custom text","Opacity and size","Five positions"]),
make("remove-image-metadata","Remove EXIF Metadata from Image","Remove Image Metadata","🧹","Remove common EXIF and location metadata by creating a clean JPG, PNG or WebP copy privately inside your browser.",["remove exif data","remove image metadata","delete photo location"],"image/jpeg,image/png,image/webp","Create a freshly encoded image that excludes the source file's common camera, date and GPS metadata.",["Choose an image.","Select the desired clean output format.","Re-encode and download the metadata-free copy."],["EXIF removal","Location privacy","Fresh image encoding"],{question:"Does this remove every possible hidden field?",answer:"Re-encoding removes ordinary EXIF, GPS and application metadata, but specialist forensic guarantees are outside this tool's scope."}),
make("svg-to-png","Convert SVG to PNG Online","SVG to PNG","🔷","Convert SVG vector files or pasted SVG code to transparent PNG images online with custom dimensions and private processing.",["svg to png","convert vector to png","svg code to image"],".svg,image/svg+xml","Rasterize an SVG logo, icon, chart or illustration at the exact pixel dimensions you require.",["Choose an SVG file or paste SVG markup.","Enter output width and height.","Convert and download PNG."],["File or code input","Custom resolution","Transparent PNG"]),
make("image-to-base64","Convert Image to Base64 Online","Image to Base64","🔤","Convert an image into a Base64 data URL online for CSS, HTML or development work without uploading it to a server.",["image to base64","base64 image encoder","convert image data url"],"image/*","Encode an image as a copyable data URL for prototypes, small embedded assets and developer workflows.",["Choose an image.","Generate its Base64 data URL.","Copy or download the encoded text."],["Data URL output","Copy-ready text","No image upload"]),
make("base64-to-image","Convert Base64 to Image Online","Base64 to Image","🖼️","Decode a Base64 string or data URL into a downloadable image online with validation and private browser-side processing.",["base64 to image","decode base64 image","data url to image"],"text","Turn valid encoded image data back into a preview and downloadable JPG, PNG, WebP, GIF or SVG file.",["Paste a Base64 image string or data URL.","Validate and preview the decoded image.","Download the restored image."],["Data URL support","Automatic format detection","Instant preview"])
];
export const getImageTool=(slug:string)=>imageTools.find(t=>t.slug===slug);
