export type MediaTool={slug:string;title:string;shortTitle:string;icon:string;kind:"Video"|"Audio"|"Subtitles";description:string;keywords:string[];accept:string;intro:string;howTo:string[];features:string[];faqs:{question:string;answer:string}[]};
const common=(name:string)=>[
 {question:"Is "+name+" free?",answer:"Yes. It is free, requires no account and adds no watermark or spoken branding."},
 {question:"Are my media files uploaded?",answer:"No. Processing runs inside your browser and selected files are not sent to SolvePilot servers."},
 {question:"Does it work on phones?",answer:"Yes, but video encoding uses significant memory. Short files work best, and a desktop is more reliable for larger media."},
 {question:"Will conversion reduce quality?",answer:"Re-encoding can change quality. Use the available quality controls and review the downloaded result before publishing."},
 {question:"What file size is recommended?",answer:"Use files below 100 MB and short clips for reliable browser processing. Available device memory sets the practical limit."}
];
const make=(slug:string,title:string,shortTitle:string,icon:string,description:string,keywords:string[],accept:string,intro:string,howTo:string[],features:string[],extra?:{question:string;answer:string}):MediaTool=>{const kind:MediaTool["kind"]=slug.includes("video")||slug==="mp4-to-gif"?"Video":slug.includes("srt")||slug.includes("vtt")?"Subtitles":"Audio",seoDescription=description.length<110?description+" No account or server upload is required.":description;return{slug,title,shortTitle,icon,kind,description:seoDescription,keywords,accept,intro,howTo,features,faqs:[...(extra?[extra]:[]),...common(shortTitle)].slice(0,5)}};
export const mediaTools:MediaTool[]=[
make("video-to-mp3","Convert Video to MP3 Online","Video to MP3","🎵","Extract MP3 audio from MP4, WebM or MOV video online with selectable bitrate and private processing inside your browser.",["video to mp3","extract audio from video","mp4 to mp3 online"],"video/*","Save speech, music or other audio from a video as a widely compatible MP3 file.",["Choose a video file.","Select the required MP3 bitrate.","Convert and download the audio."],["MP3 extraction","Bitrate selection","Local processing"]),
make("mp4-to-gif","Convert MP4 to GIF Online","MP4 to GIF","🎞️","Convert a short MP4 video clip to an animated GIF online with width, frame-rate and time controls in your browser.",["mp4 to gif","video to animated gif","convert mp4 clip"],"video/mp4","Create a shareable animated GIF from a short portion of an MP4 video.",["Choose an MP4 video.","Set start time, duration, width and frame rate.","Convert and download the GIF."],["Clip selection","Width control","Frame-rate control"]),
make("compress-video","Compress Video Online","Video Compressor","🗜️","Compress MP4, WebM or MOV video online using resolution and quality controls with private browser-side processing.",["compress video online","reduce video size","mp4 compressor"],"video/*","Reduce a video's file size for messaging, websites or form uploads by lowering resolution or encoding quality.",["Choose a video.","Select output resolution and compression level.","Compress and download the MP4."],["Resolution presets","Quality control","MP4 output"]),
make("trim-video","Trim Video Online Free","Video Trimmer","✂️","Trim MP4, WebM or MOV videos online by exact start time and duration without uploading your private file to a server.",["trim video online","cut mp4 video","video clip cutter"],"video/*","Keep only the required section of a video by choosing when the new clip starts and how long it lasts.",["Choose a video.","Enter the start time and clip duration.","Trim and download the MP4 clip."],["Second-level timing","MP4 output","Audio preserved"]),
make("convert-video","Convert Video Format Online","Video Converter","🔁","Convert common MP4, WebM and MOV videos to MP4 or WebM online with resolution controls and private browser processing.",["video converter online","mp4 to webm","webm to mp4"],"video/*","Change a video's container and codec for improved compatibility with browsers, editors or sharing services.",["Choose a supported video.","Select MP4 or WebM and an output resolution.","Convert and download the new file."],["MP4 and WebM output","Resolution options","Audio included"]),
make("convert-audio","Convert Audio Format Online","Audio Converter","🎧","Convert MP3, WAV, M4A, AAC, OGG or FLAC audio to MP3, WAV or OGG privately online inside your browser.",["audio converter online","convert audio format","mp3 wav ogg converter"],"audio/*","Change common audio files into a format accepted by your player, editor, website or messaging app.",["Choose an audio file.","Select MP3, WAV or OGG output and quality.","Convert and download the audio."],["Three output formats","Bitrate control","Local conversion"]),
make("trim-audio","Trim Audio Online Free","Audio Trimmer","✂️","Trim MP3, WAV, M4A, AAC, OGG or FLAC audio online using exact start and duration controls without file uploads.",["trim audio online","cut mp3","audio clip maker"],"audio/*","Create a shorter audio clip from music, voice recordings, interviews or sound effects.",["Choose an audio file.","Enter the start time and duration.","Trim and download the MP3 clip."],["Exact timing","MP3 output","Quick clip creation"]),
make("merge-audio","Merge Audio Files Online","Audio Merger","🔗","Merge multiple MP3, WAV, M4A, AAC, OGG or FLAC files into one MP3 online with private browser processing.",["merge audio online","join mp3 files","combine audio"],"audio/*","Join voice notes, music sections, lessons or recordings in the same order as the selected files.",["Choose two or more audio files in order.","Select output bitrate.","Merge and download one MP3."],["Multiple file support","Sequential joining","MP3 output"]),
make("change-audio-volume","Change Audio Volume Online","Audio Volume Changer","🔊","Increase or decrease MP3, WAV, M4A, AAC, OGG or FLAC volume online with private processing in your browser.",["increase audio volume","audio volume changer","make mp3 louder"],"audio/*","Adjust an audio file's loudness with a clear decibel control while preserving its duration.",["Choose an audio file.","Select a positive or negative decibel adjustment.","Process and download the MP3."],["Decibel control","Boost or reduce","Duration preserved"]),
make("wav-to-mp3","Convert WAV to MP3 Online","WAV to MP3","🎼","Convert large WAV audio files to smaller MP3 files online with selectable bitrate and private processing in your browser.",["wav to mp3","convert wav audio","wav mp3 converter"],"audio/wav,.wav","Create a smaller, widely compatible MP3 copy of an uncompressed WAV recording.",["Choose a WAV file.","Select the desired MP3 bitrate.","Convert and download the MP3."],["Smaller output","Bitrate selection","Wide compatibility"]),
make("mp3-to-wav","Convert MP3 to WAV Online","MP3 to WAV","🌊","Convert MP3 audio to uncompressed WAV online for editing or compatibility using private browser-side processing.",["mp3 to wav","convert mp3 audio","mp3 wav converter"],"audio/mpeg,.mp3","Decode an MP3 into a PCM WAV file for software or devices that require uncompressed audio.",["Choose an MP3 file.","Start the local conversion.","Download the WAV result."],["PCM WAV output","Editing compatibility","No upload"]),
make("srt-to-vtt","Convert SRT to VTT Online","SRT to VTT","💬","Convert SRT subtitle files or pasted captions to WebVTT online with timestamp validation and private browser processing.",["srt to vtt","subtitle converter","convert srt webvtt"],".srt,text/plain","Create WebVTT captions for HTML5 video players and web publishing from standard SRT subtitles.",["Choose an SRT file or paste its contents.","Convert comma-based timestamps to WebVTT format.","Download the VTT file."],["WEBVTT header","Timestamp conversion","Paste or upload"]),
make("vtt-to-srt","Convert VTT to SRT Online","VTT to SRT","💭","Convert WebVTT captions or pasted subtitle text into an SRT file online with private processing inside your browser.",["vtt to srt","webvtt to srt","subtitle format converter"],".vtt,text/vtt,text/plain","Create a broadly supported SRT subtitle file from WebVTT captions.",["Choose a VTT file or paste caption text.","Remove WebVTT-only header data and convert timestamps.","Download the SRT file."],["SRT numbering","Timestamp conversion","Paste or upload"]),
make("subtitle-time-shifter","Shift Subtitle Timing Online","Subtitle Time Shifter","⏱️","Shift every SRT or VTT subtitle timestamp forward or backward online by milliseconds with preview and private browser processing.",["subtitle time shifter","sync subtitles online","delay srt timestamps"],".srt,.vtt,text/plain","Correct captions that consistently appear too early or too late without editing every cue by hand.",["Choose or paste an SRT or VTT subtitle file.","Enter a positive delay or negative advance in milliseconds.","Preview and download the retimed subtitle file."],["Positive or negative shift","Negative-time protection","SRT and VTT support"]),
make("merge-subtitle-files","Merge Subtitle Files Online","Merge Subtitle Files","🔗","Merge multiple SRT or VTT subtitle files online in selected order with optional sequential timing and private browser processing.",["merge subtitle files online","combine srt files","join subtitle files"],".srt,.vtt,text/plain","Combine caption segments or language-editing batches into one subtitle file while retaining readable cue order.",["Choose two or more subtitle files in the required order.","Select direct or sequential merging and review timing.","Download one merged subtitle file."],["Multiple files","Cue renumbering","Sequential timing option"]),
make("subtitle-encoding-fixer","Fix Subtitle Encoding Online","Subtitle Encoding Fixer","🔤","Fix common subtitle encoding problems online by decoding SRT or VTT bytes as UTF-8 or legacy text and downloading clean UTF-8.",["subtitle encoding fixer","fix srt characters","convert subtitles to utf-8"],".srt,.vtt,text/plain","Repair garbled accented letters and common legacy-text decoding issues by creating a normalized UTF-8 subtitle copy.",["Choose the affected subtitle file.","Select UTF-8, Windows-1252 or ISO-8859-1 source decoding.","Preview and download normalized UTF-8 text."],["UTF-8 output","Legacy decoding","Character preview"])
];
export const getMediaTool=(slug:string)=>mediaTools.find(t=>t.slug===slug);
