export type PdfTool={slug:string;title:string;shortTitle:string;icon:string;description:string;keywords:string[];intro:string;howTo:string[];features:string[];faqs:{question:string;answer:string}[]};
const faqs=(name:string)=>[
 {question:`Is \${name} free to use?`,answer:"Yes. It is free, needs no account and adds no watermark unless you choose the watermark tool."},
 {question:"Are my PDF files uploaded?",answer:"No. Processing happens in your browser and files are not sent to SolvePilot servers."},
 {question:"Does it work on phones?",answer:"Yes, on modern mobile browsers. Large documents may work better on a computer because browsers have limited memory."},
 {question:"What is the maximum file size?",answer:"There is no server upload limit, but we recommend files below 50 MB for reliable browser processing."},
 {question:"Will PDF quality change?",answer:"Existing PDF pages are copied without intentional recompression. Image output depends on its selected resolution."}
];
const make=(slug:string,title:string,shortTitle:string,icon:string,description:string,keywords:string[],intro:string,howTo:string[],features:string[],extra?:{question:string;answer:string}):PdfTool=>({slug,title,shortTitle,icon,description,keywords,intro,howTo,features,faqs:[...(extra?[extra]:[]),...faqs(shortTitle)].slice(0,5)});
export const pdfTools:PdfTool[]=[
make("merge-pdf","Merge PDF Online Free","Merge PDF","🧩","Merge multiple PDF files online in the order you choose. Free, private browser processing with no upload, signup or added watermark.",["merge pdf online","combine pdf files","join pdf free"],"Combine reports, scans, invoices or chapters into one downloadable PDF while keeping the order under your control.",["Select two or more PDF files in the required order.","Review the selected file names.","Choose Merge PDF and download the combined document."],["Multiple-file support","No server upload","Original pages preserved"]),
make("split-pdf","Split PDF Online Free","Split PDF","✂️","Split a PDF into separate pages or custom page ranges online. Files stay private in your browser with no signup or server upload.",["split pdf online","separate pdf pages","pdf splitter free"],"Create smaller PDFs from one document, either one file per page or a ZIP containing the ranges you specify.",["Choose the PDF to divide.","Leave ranges blank for every page, or enter groups such as 1-3; 4-7.","Run the tool and download the ZIP."],["Every-page splitting","Custom page ranges","ZIP download"]),
make("extract-pdf-pages","Extract Pages from PDF Online","Extract PDF Pages","📤","Extract selected pages from a PDF into a new file online. Free private processing in your browser with page-range control.",["extract pages from pdf","save pdf pages","pdf page extractor"],"Keep only the pages you need and create a clean new document without editing the original file.",["Select one PDF.","Enter page numbers or ranges such as 1,3,6-9.","Extract and download the new PDF."],["Flexible page ranges","Single clean output","Original remains unchanged"]),
make("reorder-pdf-pages","Reorder PDF Pages Online","Reorder PDF","🔀","Reorder PDF pages online by entering a new page sequence. Free, private and processed locally without uploading your document.",["reorder pdf pages","arrange pdf pages","change pdf page order"],"Fix pages in the wrong order by defining the exact sequence for the finished PDF.",["Select a PDF file.","Enter the full new order, for example 3,1,2,4-8.","Create and download the reordered PDF."],["Exact page sequence","Range support","Local processing"]),
make("rotate-pdf-pages","Rotate PDF Pages Online Free","Rotate PDF","🔄","Rotate all or selected PDF pages by 90, 180 or 270 degrees online. Your file stays private and is never uploaded.",["rotate pdf online","turn pdf pages","rotate selected pdf pages"],"Correct sideways or upside-down scanned pages while preserving the rest of the document.",["Choose a PDF.","Enter pages to rotate or leave blank for all pages.","Select an angle, process and download."],["Selected or all pages","Three rotation angles","No recompression"]),
make("delete-pdf-pages","Delete PDF Pages Online Free","Delete PDF Pages","🗑️","Remove unwanted pages from a PDF online and download the cleaned file. Free local processing keeps your document private.",["delete pages from pdf","remove pdf pages","pdf page remover"],"Remove blank, duplicate or confidential pages without changing the source file stored on your device.",["Select a PDF.","Enter the pages to remove.","Create and download the cleaned PDF."],["Multiple page ranges","Safety validation","Original stays intact"]),
make("images-to-pdf","Convert Images to PDF Online","Images to PDF","🖼️","Convert JPG and PNG images to one PDF online. Arrange images, fit pages automatically and process privately in your browser.",["images to pdf","jpg to pdf","png to pdf online"],"Turn photos, receipts, notes or scans into a portable multi-page PDF in the same order as selected.",["Select JPG or PNG images in the required order.","Review the selected file names.","Convert and download one PDF."],["JPG and PNG support","Automatic page sizing","Multi-image document"]),
make("pdf-to-images","Convert PDF to Images Online","PDF to Images","📸","Convert each PDF page to a high-quality PNG image online. Private browser processing provides a convenient ZIP download.",["pdf to images","pdf to png","convert pdf pages to image"],"Render PDF pages as PNG images for presentations, previews, design work or easy sharing.",["Choose a PDF file.","Select normal or high-resolution output.","Convert and download the images as a ZIP."],["PNG output","Resolution control","ZIP download"]),
make("add-pdf-watermark","Add Watermark to PDF Online","PDF Watermark","💧","Add a custom text watermark to every PDF page online. Control text and position with private browser processing.",["add watermark to pdf","pdf watermark online","stamp pdf text"],"Place a visible label such as Draft, Confidential or a business name across every page.",["Select a PDF.","Enter watermark text and choose its position.","Apply and download the marked PDF."],["Custom text","Readable transparency","Three positions"]),
make("add-page-numbers-pdf","Add Page Numbers to PDF Online","PDF Page Numbers","🔢","Add page numbers to a PDF online with custom starting number and position. Free private processing runs inside your browser.",["add page numbers to pdf","number pdf pages","pdf pagination"],"Number reports, submissions and handouts with a consistent footer or header position.",["Select a PDF.","Choose the starting number and page position.","Add numbers and download the PDF."],["Custom start number","Six positions","Consistent typography"]),
make("pdf-metadata-viewer","PDF Metadata Viewer Online","PDF Metadata Viewer","🔎","View PDF title, author, subject, keywords, dates and page count online without uploading the file or changing its contents.",["pdf metadata viewer","check pdf properties","view pdf author"],"Inspect document information stored inside a PDF before publishing, sharing or archiving it.",["Select a PDF file.","Wait while the browser reads its properties.","Review the metadata shown on screen."],["Read-only inspection","Page count included","No download required"]),
make("remove-pdf-metadata","Remove PDF Metadata Online","Remove PDF Metadata","🧹","Remove common PDF metadata such as title, author, subject and keywords online with private, browser-only processing.",["remove pdf metadata","clean pdf properties","delete pdf author"],"Create a cleaned copy before sharing a file when its embedded properties should not travel with it.",["Select a PDF.","Read the privacy note.","Remove metadata and download the cleaned copy."],["Clears common properties","Creates a separate copy","Local privacy"]),
make("protect-pdf-password","Password Protect PDF Online","Protect PDF","🔐","Password protect a PDF online with strong 256-bit encryption. Your document and password remain inside your browser.",["password protect pdf","encrypt pdf online","lock pdf with password"],"Encrypt a PDF so readers need the password you choose before opening the document.",["Select a PDF.","Enter a strong password.","Protect and download the encrypted copy."],["256-bit encryption","Password stays local","No account required"],{question:"Can a lost PDF password be recovered?",answer:"No. Store it safely; SolvePilot never receives it and cannot recover it."}),
make("unlock-pdf","Unlock PDF Online","Unlock PDF","🔓","Remove a known password from a PDF online and download an unlocked copy. Decryption happens privately inside your browser.",["unlock pdf","remove pdf password","decrypt pdf online"],"Create an unprotected copy when you know the password and have permission to remove the restriction.",["Select the protected PDF.","Enter its current password.","Unlock and download the new copy."],["Works with known passwords","Local decryption","Original remains protected"],{question:"Can this bypass an unknown password?",answer:"No. You must know the current password and have authorization to unlock the document."})
];
export const getPdfTool=(slug:string)=>pdfTools.find(t=>t.slug===slug);
