export type ProductivityMode="resume"|"ats"|"matcher"|"cover-letter"|"job-description"|"interview"|"salary"|"experience"|"certificate"|"id-card"|"attendance"|"timetable"|"graph-paper"|"flashcards"|"citation"|"gpa"|"reading-time"|"word-counter";
export type ProductivityTool={slug:string;title:string;shortTitle:string;icon:string;category:"Career Tools"|"Student & Office";mode:ProductivityMode;description:string;keywords:string[];intro:string;howTo:string[];features:string[];faqs:{question:string;answer:string}[]};
const common=(name:string)=>[
 {question:"Is "+name+" free to use?",answer:"Yes. It is free, requires no account and creates the result inside your browser."},
 {question:"Does SolvePilot save my information?",answer:"No. Text and personal details entered here are processed in the current browser session and are not submitted to SolvePilot servers."},
 {question:"Does this tool work on mobile?",answer:"Yes. It works in modern mobile browsers, although longer resumes, tables and printable documents are easier to review on a larger screen."},
 {question:"Can I edit the generated result?",answer:"Yes. Change the inputs and generate the result again. Text results can be copied, while supported document tools create a new downloadable PDF."},
 {question:"Should I review the result before using it?",answer:"Yes. Check names, dates, calculations, wording and formatting. Generated material is a practical draft and should be adapted to its real purpose."}
];
const make=(slug:string,title:string,shortTitle:string,icon:string,category:ProductivityTool["category"],mode:ProductivityMode,description:string,keywords:string[],intro:string,howTo:string[],features:string[]):ProductivityTool=>({slug,title,shortTitle,icon,category,mode,description,keywords,intro,howTo,features,faqs:common(shortTitle)});
export const productivityTools:ProductivityTool[]=[
 make("resume-builder","Free Resume and CV Builder Online","Resume/CV Builder","📄","Career Tools","resume","Build a clean resume or CV PDF online using your profile, skills and experience. Private browser generation requires no account or upload.",["resume builder free","cv maker online","resume pdf generator"],"Prepare a concise chronological resume for applications and download a clean PDF that you can review and improve.",["Enter your contact details and professional summary.","Add skills, experience and education using clear lines.","Generate the PDF and proofread it before applying."],["PDF resume","Structured sections","Local processing"]),
 make("ats-resume-checker","Free ATS Resume Checker Online","ATS Resume Checker","✅","Career Tools","ats","Check resume text for common ATS-readability signals, missing sections and formatting risks without uploading a private document to a server.",["ats resume checker free","resume ats score","check cv for ats"],"Run a practical checklist over pasted resume text to identify common parsing and completeness problems before submitting an application.",["Paste the resume text copied from your document.","Run the ATS-oriented checks.","Review each warning and improve the original resume."],["Section detection","Readability checks","Actionable warnings"]),
 make("resume-keyword-matcher","Resume Keyword Matcher for Job Descriptions","Resume Keyword Matcher","🎯","Career Tools","matcher","Compare resume text with a job description to find important missing terms and estimate keyword coverage privately in your browser.",["resume keyword matcher","job description resume match","cv keyword checker"],"Compare the language used in a vacancy with your resume so you can represent relevant, truthful experience more clearly.",["Paste your resume text.","Paste the target job description.","Review matched and missing terms, then edit truthfully."],["Keyword coverage","Missing-term list","Private comparison"]),
 make("cover-letter-generator","Free Cover Letter Generator Online","Cover Letter Generator","✉️","Career Tools","cover-letter","Generate a structured cover-letter draft from your experience, target role and company using private browser processing and no signup.",["cover letter generator free","job application letter maker","cover letter draft"],"Create a focused first draft that connects your relevant experience to a specific position and company.",["Enter the target role, company and your strongest relevant experience.","Generate the cover-letter draft.","Personalise claims, tone and examples before sending."],["Role-specific draft","Editable text","Copy-ready output"]),
 make("job-description-generator","Job Description Generator Online","Job Description Generator","💼","Career Tools","job-description","Create a clear job-description draft with responsibilities, requirements and working arrangement using a simple private browser form.",["job description generator","write job description","job posting template"],"Prepare a consistent vacancy draft that explains the role, expected outcomes and essential qualifications.",["Enter the job title, company, seniority and arrangement.","Describe the main responsibilities and requirements.","Generate and edit the posting before publication."],["Responsibilities section","Requirements section","Editable job post"]),
 make("interview-question-generator","Interview Question Generator by Role","Interview Question Generator","❓","Career Tools","interview","Generate practical interview questions for a selected role, seniority and skill focus without an account or external AI request.",["interview question generator","job interview questions by role","technical interview question maker"],"Create a balanced practice list covering experience, problem solving, technical depth and workplace situations.",["Enter the role, seniority and skills to assess.","Choose how many questions you need.","Generate the list and prepare evidence-based answers."],["Role-based questions","Technical and behavioural mix","No API calls"]),
 make("salary-to-hourly-converter","Salary to Hourly Rate Converter","Salary-to-Hourly Converter","💰","Career Tools","salary","Convert annual, monthly, weekly or daily salary into an estimated hourly rate using editable workdays and weekly hours.",["salary to hourly converter","monthly salary hourly rate","annual pay per hour"],"Compare compensation across different pay periods by converting income to a consistent approximate hourly value.",["Enter the salary amount and its pay period.","Confirm weekly hours and working days.","Calculate and compare the hourly, daily, weekly, monthly and annual values."],["Multiple pay periods","Editable working hours","Instant breakdown"]),
 make("work-experience-calculator","Work Experience Calculator","Experience Calculator","🗓️","Career Tools","experience","Calculate employment duration between two dates in years, months and days for a resume, application or service record.",["work experience calculator","calculate job duration","employment duration calculator"],"Measure one period of employment accurately without estimating from calendar years alone.",["Choose the employment start date.","Choose the end date or use today's date.","Calculate and verify the duration against employment records."],["Years and months","Total days","Present-date option"]),
 make("certificate-maker","Free Certificate Maker Online","Certificate Maker","🏆","Student & Office","certificate","Create and download a printable achievement, participation or completion certificate PDF with private browser-based generation.",["certificate maker free","certificate generator online","completion certificate pdf"],"Prepare a simple landscape certificate with recipient, achievement, issuer and date for ordinary school, training or event use.",["Enter the recipient and certificate title.","Add the issuer, achievement and date.","Generate the PDF and verify spelling before printing."],["Landscape PDF","Custom recipient","Issuer and date"]),
 make("id-card-maker","ID Card Maker Online Free","ID Card Maker","🪪","Student & Office","id-card","Create a simple printable student, employee or membership ID card PDF using private browser processing and no saved profile.",["id card maker online","student id card generator","employee id card pdf"],"Produce a compact identification-card layout with name, identifier, organisation, role and validity information.",["Enter the cardholder and organisation details.","Add the ID number, role and validity date.","Generate and review the PDF before printing."],["Compact card layout","Identity fields","Printable PDF"]),
 make("attendance-sheet-generator","Attendance Sheet Generator Online","Attendance Sheet Generator","📋","Student & Office","attendance","Generate a printable attendance sheet PDF online from a class, team or event name and a pasted list of participants.",["attendance sheet generator","class attendance sheet","employee attendance template"],"Turn a simple name list into a numbered attendance register with blank status and signature space.",["Enter the class, team or event name.","Paste one participant name per line.","Generate and print the attendance sheet PDF."],["Numbered rows","Status columns","Printable register"]),
 make("timetable-maker","Timetable Maker Online Free","Timetable Maker","🗓️","Student & Office","timetable","Create a weekly timetable PDF from pasted time-slot rows for school, study or work using private browser-based generation.",["timetable maker online","weekly schedule generator","class timetable pdf"],"Build a clean Monday-to-Friday table from rows written in a predictable time and activity format.",["Enter a timetable title.","Paste one row per time slot with weekday activities.","Generate the PDF and check every scheduled item."],["Weekly grid","Custom time slots","PDF download"]),
 make("graph-paper-generator","Printable Graph Paper Generator","Graph Paper Generator","▦","Student & Office","graph-paper","Generate printable A4 graph paper PDF with adjustable grid spacing and line colour directly inside your browser.",["graph paper generator","printable grid paper pdf","custom graph paper"],"Create a clean square grid for mathematics, diagrams, plotting, planning, crafts or handwriting practice.",["Choose the grid spacing in millimetres.","Select a practical line colour.","Generate and print the A4 PDF at actual size."],["Adjustable spacing","A4 PDF","Print-ready grid"]),
 make("flashcard-maker","Printable Flashcard Maker Online","Flashcard Maker","🗂️","Student & Office","flashcards","Create printable study flashcards from question-and-answer pairs using private browser processing and a downloadable PDF.",["flashcard maker online","printable flashcards generator","study card maker"],"Turn revision notes into clear prompt-and-answer cards for active recall and classroom practice.",["Enter one question and answer per line separated by a vertical bar.","Generate the flashcard pages.","Print, cut and review the cards."],["Question-answer pairs","Printable cards","Active-recall format"]),
 make("citation-generator","Citation Generator for APA, MLA and Harvard","Citation Generator","📚","Student & Office","citation","Generate a basic website or article citation in APA, MLA or Harvard style from author, title, year and URL fields.",["citation generator free","apa citation generator","mla harvard citation"],"Create a consistent reference draft for common online sources and then confirm it against your institution's required style.",["Choose the citation style.","Enter the available source details.","Generate, copy and verify the reference."],["APA-style draft","MLA-style draft","Harvard-style draft"]),
 make("gpa-cgpa-calculator","GPA and CGPA Calculator Online","GPA/CGPA Calculator","🎓","Student & Office","gpa","Calculate weighted GPA or CGPA from course credits and grade points with a transparent course-by-course breakdown.",["gpa calculator","cgpa calculator online","credit hour gpa"],"Combine course grade points using credit-hour weighting rather than treating every course as equally important.",["Enter one course per line with credit hours and grade points.","Choose the grading scale.","Calculate and verify the weighted GPA or CGPA."],["Credit weighting","Editable scale","Course breakdown"]),
 make("reading-time-calculator","Reading Time Calculator Online","Reading-Time Calculator","⏱️","Student & Office","reading-time","Estimate reading and speaking time from pasted text using adjustable words-per-minute speeds with instant word totals.",["reading time calculator","speech time calculator","words to minutes"],"Estimate how long an article, lesson, script or presentation may take at a chosen reading or speaking pace.",["Paste the complete text.","Choose an appropriate words-per-minute speed.","Calculate and round the estimate for practical planning."],["Word total","Reading estimate","Speaking estimate"]),
 make("word-character-counter","Word and Character Counter Online","Word & Character Counter","🔢","Student & Office","word-counter","Count words, characters, sentences, paragraphs and estimated reading time instantly from text pasted into your browser.",["word counter online","character counter","sentence paragraph counter"],"Measure text length for assignments, application fields, captions, articles and publishing requirements.",["Paste or type the text.","Review the live counts.","Edit the text until it meets the required limit."],["Word count","Characters with and without spaces","Sentence and paragraph totals"])
];
export const getProductivityTool=(slug:string)=>productivityTools.find(t=>t.slug===slug);

