import type {Tool} from './tools';
import {roadmap106Keywords} from './roadmap-106-125-keywords';
export function upgradeRoadmap106(tool:Tool):Tool {
 const terms=roadmap106Keywords.filter(k=>k.slug===tool.slug).map(k=>k.keyword);
 if(!terms.length)return tool;
 const upgraded={...tool,updatedAt:'2026-10-02',keywords:[...new Set([...tool.keywords,...terms])]};
 if(tool.slug==='interest-rate-calculator')return {...upgraded,title:'Interest Rate, CD and FD Calculator',shortTitle:'Interest Rate & Deposits',description:'Solve an implied interest rate or project CD and fixed-deposit maturity, interest earned and annual yield using your entered rate and compounding.',intro:'Use the solve mode for a rate implied by two balances, or choose cd, fd or apy mode for a fixed deposit. CD and FD share the same compound-growth calculation, so their matching keywords use one maintained calculator. For a six-month deposit enter 0.5 years. APY already includes compounding; nominal rates require a compounds-per-year input. The estimate excludes tax, fees, early-withdrawal penalties, additional deposits and live bank rates. A projected maturity value is not a quote or guaranteed return.',faqs:[...tool.faqs,{question:'How do I calculate CD interest or FD maturity?',answer:'Choose cd or fd mode, enter the deposit, nominal annual rate, years and compounding periods per year. Maturity is principal multiplied by (1 + rate/periods) raised to periods times years. Subtract principal for interest. Enter 0.5 years for six months.'},{question:'Should I enter APY as a nominal rate?',answer:'No. Choose apy mode when the quoted number is APY. That mode uses principal times (1 + APY) raised to years. Applying a compounding frequency to APY again would double-count compounding. Confirm the bank’s term, payout timing and actual disclosure.'}]};
 if(tool.slug==='pay-raise-percentage-calculator')return {...upgraded,title:'Pay Raise Calculator',shortTitle:'Pay Raise',description:'Compare old and new pay to calculate a salary raise amount, wage increase percentage and the change on a consistent pay-period basis.'};
 if(tool.slug==='stud-calculator')return {...upgraded,title:'Wall Stud Calculator',shortTitle:'Wall Studs'};
 if(tool.slug==='tile-quantity-calculator-pakistan')return {...upgraded,intro:tool.intro+' Tile sq ft calculator and tile estimator searches use this same area-to-tile calculation. Use floor or wall area in square feet and tile dimensions in inches. The waste allowance and box count are explicit inputs; layout, offcuts and package coverage must be checked with the supplier.'};
 return upgraded;
}
