import type {Tool} from './tools';
import {roadmap126Keywords} from './roadmap-126-145-keywords';
export function upgradeRoadmap126(tool:Tool):Tool {
 const terms=roadmap126Keywords.filter(k=>k.slug===tool.slug).map(k=>k.keyword);
 if(!terms.length)return tool;
 const updated={...tool,updatedAt:'2026-10-02',keywords:[...new Set([...tool.keywords,...terms])]};
 if(tool.slug==='running-pace-calculator')return {...updated,title:'Running Pace and Split Calculator',shortTitle:'Running Pace & Splits',formula:'Average pace = total minutes ÷ race distance. Cumulative checkpoint time = average pace × checkpoint distance. Distances use the selected kilometre or mile unit.',description:'Calculate running pace or generate cumulative even-pace race splits from distance, target time and a chosen kilometre or mile split interval.',intro:'Use average pace mode for a time-per-distance estimate, or choose even race splits to generate cumulative checkpoint times. Enter target time in minutes and keep the split interval in the same distance unit as the race. The last partial interval is included. Split results assume constant pace and do not model fatigue, stops, terrain or training readiness. Bill splitting is a different intent and uses the separate Split Bill Calculator.',faqs:[...tool.faqs,{question:'How does the split calculator work?',answer:'Average pace is total minutes divided by distance. Multiply that pace by each cumulative checkpoint distance to find elapsed minutes from the start. The finish row includes a partial last split if the race distance is not an exact multiple of your interval.'},{question:'Are these cumulative or individual split times?',answer:'The listed checkpoint times are cumulative from the race start. Subtract the previous checkpoint to find a segment time. This even-pace method does not predict a realistic race from a shorter effort or set a training prescription.'}]};
 if(tool.slug==='interest-rate-calculator')return {...updated,title:'Interest Calculator — Simple, Compound, CD and FD',shortTitle:'Interest',description:'Calculate interest earned and ending balances with simple or compound growth, CD or FD nominal rates, quoted APY, or an implied rate from two balances.',formula:tool.formula+' Simple mode uses interest = principal × annual rate × years and ending amount = principal + interest.',faqs:[...tool.faqs,{question:'How much interest will I earn with simple interest?',answer:'Choose simple mode, then enter principal, annual percentage rate and years. Interest is principal times the rate fraction times years. It is charged or earned on original principal only, so it differs from compounding. Fees, taxes and changing balances are excluded.'},{question:'Does bank interest always follow this estimate?',answer:'No. A bank can use day counts, transaction timing, tiered rates, payout rules and contractual rounding. These modes disclose an educational fixed-rate method. Confirm account disclosures and use quoted APY as APY rather than compounding it a second time.'}]};
 return updated;
}
