import type {Tool} from './tools';
import type {Audit} from './semrush-batch-one-audit';
import {next20Keywords} from './roadmap-next20-keywords';
const updates:Record<string,Partial<Tool>>={
 'asphalt-calculator':{title:'Asphalt and Pavement Calculator — Tonnage and Supplied Cost',description:'Estimate asphalt pavement volume, compacted mass, explicit material allowance and supplied material cost from area, thickness and supplier density.',formula:'Compacted ft³ = area ft² × depth in/12. US short tons = ft³ × density lb/ft³ /2,000. Planned tons = base tons ×(1+allowance/100). Material cost = planned tons × supplied price per US short ton.',example:'1,000 ft² at 3 in and 145 lb/ft³ gives 250 ft³ and 18.125 US short tons. A 5% supplied allowance gives 19.03125 tons; a supplied price of 100 models 1,903.125 currency units.',considerations:[{title:'Pavement calculator scope and compacted density',text:'This pavement calculator estimates the material for a uniform asphalt layer. It does not choose structural pavement thickness, soil preparation or a compaction procedure. Density must match the compacted-volume basis; loose truck volume is a different quantity. The allowance is explicit and editable, with five percent used only as an example rather than a universal recommendation. Cost is material-only on the supplied short-ton basis, so labor, transport, removal and taxes require separate treatment. Concrete pavement belongs on the concrete calculator rather than this density model.'}],faqs:[{question:'Does pavement mean concrete or asphalt here?',answer:'This canonical page covers asphalt pavement material quantities. Use the linked concrete volume model for concrete; neither page selects structural pavement thickness.'},{question:'Is the allowance always five percent?',answer:'No. You supply the allowance. The earlier five-percent example remains available by entering 5; no universal waste recommendation is made.'}]},
 'ap-biology-score-calculator':{formula:'Practice composite % = 0.5 ×(MC correct/MC total ×100) +0.5 ×FRQ percentage.',considerations:[{title:'AP Bio exam score calculator validation',text:'The AP Bio exam score calculator retains the 50/50 multiple-choice and free-response composite. The official AP Biology structure uses sixty MC questions and six FRQs; the FRQ section includes two nine-point long questions and four four-point short questions. For that rubric, sum earned FRQ points out of thirty-four and convert to a percentage before entry. A practice set can have a different MC total, but correct answers must remain a whole count no greater than that total. The computed percentage is not an official AP 1–5 score, a fixed annual cutoff or a prediction of the final exam outcome.'}],faqs:[{question:'How do I convert current AP Biology FRQ points?',answer:'For the structure cited here, two long questions at nine points and four short questions at four points total thirty-four. Divide earned rubric points by thirty-four and multiply by one hundred. Verify the applicable administration’s scoring materials.'}]},
 'womens-bmi-calculator':{title:'Adult BMI and Reverse BMI Calculator — Measured or Supplied Basis',description:'Calculate adult BMI from measured weight and height, or find the weight corresponding to a supplied BMI, with clear screening and target-weight limits.',formula:'BMI = weight kg/(height cm/100)². Reverse identity: weight kg = supplied BMI ×(height cm/100)².',example:'At 170 cm, a supplied BMI of 22 corresponds arithmetically to 63.58 kg. This is a supplied-value identity, not a recommended personal weight.',considerations:[{title:'Reverse BMI calculates an identity, not an ideal weight',text:'Reverse BMI rearranges the same adult BMI equation. Enter a supplied BMI and measured height to calculate the corresponding weight. The tool does not choose a target, prescribe weight change or determine whether that weight is appropriate. CDC adult categories apply regardless of sex; the legacy women’s URL is retained and improved instead of duplicating the page. This page does not assess children, pregnancy, body composition or individual medical circumstances. A BMI screening measure is not a diagnosis, and an algebraic reverse result is not a treatment plan.'}],faqs:[{question:'Does reverse BMI choose my ideal weight?',answer:'No. You supply the BMI. The calculator rearranges weight = BMI ×height² and does not recommend that value.'},{question:'Does adult BMI have a separate formula for women?',answer:'The adult weight/height² identity is the same. The legacy URL is retained, while this page labels the broader adult arithmetic and its limits.'}]}
};
export function upgradeNext20(t:Tool):Tool{
 const update=updates[t.slug];if(!update)return t;
 return{...t,...update,updatedAt:'2026-10-04',keywords:[...new Set([...t.keywords,...next20Keywords.filter(k=>k.slug===t.slug).map(k=>k.keyword)])],considerations:[...t.considerations,...(update.considerations||[])],faqs:[...t.faqs,...(update.faqs||[])]};
}
const inbound:Record<string,Array<{slug:string;title:string;path?:string}>>={
 'quarter-mile-calculator':[{slug:'horsepower-calculator',title:'Power from torque and rotational speed'}],
 'interest-rate-calculator':[{slug:'interest-rate-cap-payout-calculator',title:'Single-period cap payout from supplied contract inputs'}],
 'ratio-calculator':[{slug:'geographic-midpoint-calculator',title:'Spherical midpoint of two supplied locations'}],
 'business-break-even-calculator':[{slug:'cake-pricing-calculator',title:'Order pricing with labor and fees'},{slug:'cpm-calculator',title:'Advertising cost per thousand impressions'}],
 'goat-gestation-calculator':[{slug:'sheep-gestation-calculator',title:'Sheep mating-date calendar'}],
 'binary-calculator':[{slug:'boolean-algebra-calculator',title:'Boolean expression truth tables'}],
 'ohms-law-calculator':[{slug:'megawatt-calculator',title:'Convert power-unit prefixes'}],
 'matrix-inverse-calculator':[{slug:'substitution-calculator',title:'Two-variable linear-system checks'}],
 'arv-calculator':[{slug:'cap-rate-calculator',title:'Annual NOI to property-value ratio'}],
 'running-pace-calculator':[{slug:'swim-time-converter',title:'Swimming distance and supplied-factor time scenarios'}],
 'linear-feet-calculator':[{slug:'fence-cost-estimator',title:'Fence quotation worksheet with supplied rates'}],
 'volume-calculator':[{slug:'subwoofer-case-calculator',title:'Rectangular enclosure net air volume'}],
 'productivity-calculator':[{slug:'acres-per-hour-calculator',title:'Effective machine field capacity'}],
 'basic-calculator':[{slug:'torque-converter',title:'Newton-metre and pound-force-foot conversion'}],
 'dog-pregnancy-calculator':[{slug:'puppy-weight-estimator-guide',title:'Puppy growth records and adult-size uncertainty',path:'/guides/puppy-weight-estimator-guide/'}],
 'torque-converter':[{slug:'ski-din-calculator-guide',title:'Ski release-setting limits and qualified equipment checks',path:'/guides/ski-din-calculator-guide/'}]
};
export function enhanceNext20(t:Tool,audit:Audit|undefined):Audit|undefined{
 if(!audit)return audit;
 const terms=next20Keywords.filter(k=>k.slug===t.slug).map(k=>k.keyword);
 const links=[...(audit.relatedCalculators||[]),...(inbound[t.slug]||[])];
 let next:Audit={...audit,keywordThemes:[...new Set([...audit.keywordThemes,...terms])],relatedCalculators:links.filter((v,i)=>links.findIndex(x=>x.slug===v.slug)===i)};
 if(t.slug==='asphalt-calculator')next={...next,interpretation:'Uniform compacted asphalt geometry with explicit supplier density, allowance and material-only price. Planned mass uses US short tons; it is not a pavement design or site quotation.',scenarios:['1,000 ft² ×3 in ×145 lb/ft³ — base 18.125 US short tons.','5% allowance — planned mass 19.03125 US short tons.','100 per planned short ton — material scenario 1,903.125 currency units.'],verification:'Calculate compacted volume first, multiply by matching compacted density and divide pounds by two thousand. Apply the allowance once, then the supplied material price. Keep transport, labor and structural design outside this model.'};
 if(t.slug==='womens-bmi-calculator')next={...next,interpretation:'Adult BMI and its reverse algebraic identity. Reverse mode uses a BMI supplied by the user and does not recommend a personal target or determine health status.',scenarios:['60 kg at 165 cm — BMI approximately 22.038567.','BMI 22 at 170 cm — corresponding weight 63.58 kg.','The same height and BMI produce the same identity regardless of sex.'],verification:'Square height in metres, then divide measured kg by that square or multiply the supplied BMI by it. Check the direction of the selected mode. The reverse result is not a recommended weight.',sourceUrl:'https://www.cdc.gov/bmi/adult-calculator/bmi-categories.html',sourceNote:'CDC describes adult BMI as a screening measure and gives the same adult identity regardless of sex. Editorial review is not individual clinical assessment.'};
 if(t.slug==='ap-biology-score-calculator')next={...next,sourceUrl:'https://apcentral.collegeboard.org/courses/ap-biology/exam',sourceNote:'College Board supplies current section weights and rubric point structure. The output is a practice percentage, not an official 1–5 score conversion.'};
 return next;
}
