import type {Tool} from './tools';
import type {Audit} from './semrush-batch-one-audit';
import {roadmap206Keywords} from './roadmap-206-225-keywords';
const inbound:Record<string,{slug:string;title:string;path?:string}[]>={
 'percent-calculator':[{slug:'gc-content-calculator',title:'GC percentage and base counts'},{slug:'basic-calculator',title:'Basic arithmetic expressions'}],
 'ratio-calculator':[{slug:'charles-law-calculator',title:'Constant-pressure volume/temperature ratios'}],
 'profit-margin-calculator-global':[{slug:'llc-tax-calculator',title:'User-rate LLC cash reserve'},{slug:'crypto-conversion-calculator',title:'Manual quote and proportional-fee conversion'}],
 'linear-feet-calculator':[{slug:'wainscoting-calculator',title:'Equal wainscoting panel layout'}],
 'nether-portal-calculator':[{slug:'minecraft-sphere-generator',title:'Block sphere layers and coordinates'}],
 'paycheck-estimator-calculator':[{slug:'new-jersey-tax-calculator',title:'2025 New Jersey resident tax table'}],
 'payment-calculator':[{slug:'bank-calculators-guide',title:'Choose a bank calculation model',path:'/guides/bank-calculators-guide/'}],
 'interest-rate-calculator':[{slug:'bank-calculators-guide',title:'Bank interest conventions and simple accrual',path:'/guides/bank-calculators-guide/'}],
 'grade-curve-calculator':[{slug:'study-score-calculator-guide',title:'VCE study score and moderation limits',path:'/guides/study-score-calculator-guide/'}],
 'mean-standard-deviation-calculator':[{slug:'study-score-calculator-guide',title:'Assessment percentages and relative study scores',path:'/guides/study-score-calculator-guide/'}],
 'volume-calculator':[{slug:'breast-implant-size-calculator-guide',title:'Implant volume units and clinical selection limits',path:'/guides/breast-implant-size-calculator-guide/'}]
};
export function enhanceRoadmap206(tool:Tool,audit:Audit|undefined):Audit|undefined{
 if(!audit)return audit;
 const terms=roadmap206Keywords.filter(k=>k.slug===tool.slug).map(k=>k.keyword);
 const links=[...(audit.relatedCalculators||[]),...(inbound[tool.slug]||[])];
 let updated:Audit={...audit,keywordThemes:[...new Set([...audit.keywordThemes,...terms])],relatedCalculators:links.filter((v,i)=>links.findIndex(x=>x.slug===v.slug)===i)};
 if(tool.slug==='roof-area-calculator')updated={...updated,interpretation:'Uniform-pitch geometry, explicit waste, supplier package coverage and supplied-basis price arithmetic. Roof pitch mode separately solves measured rise/run. Unit price applies to planned roof area including waste; no market price or standard bundle coverage is assumed. The model does not resolve valleys, hips, dormers, access, structural suitability or an actual contractor quotation.',scenarios:['40×30 ft at 6/12: sloped area 1,341.640786 ft²; 10% waste gives 1,475.804865 ft².','Coverage of 33.3 ft²/package gives 45 whole packages for that planned area.','Rise 6 and horizontal run 12 in matching units: pitch 6/12 and angle 26.565051 degrees.'],mistakes:['Entering a sloped rafter length as a horizontal plan dimension overstates area.','Double-counting labor or fixed charges already included in an installed unit price inflates cost.','Assuming every shingle bundle has the same coverage hides the selected product basis.'],verification:'Check plan area, multiply by the slope factor and then add the stated waste. Divide planned area by the actual package coverage before rounding upward. Multiply that same planned area by the supplied unit rate and add separate charges exactly once. Complex roofs need a takeoff of their actual planes.',sourceNote:'Original geometric identities and user-supplied coverage/cost arithmetic. Product coverage and quotation basis must be verified with the chosen supplier or contractor.',relatedCalculators:[{slug:'linear-feet-calculator',title:'Area to uniform-width length'},{slug:'soffit-calculator',title:'Soffit panel planning'},{slug:'wainscoting-calculator',title:'Equal trim-panel layout'}]};
 if(tool.slug==='linear-feet-calculator')updated={...updated,interpretation:'Piece mode converts feet plus inches before multiplying by a positive whole quantity. Area mode divides square feet by actual uniform coverage width in feet. Neither mode assumes waste, overlap or nominal product width. Read the mode and unit labels before calculating; a square-foot amount alone cannot determine linear feet.',scenarios:['Eight pieces at two feet six inches each total 20 linear feet.','100 ft² at six-inch coverage width requires 200 linear feet before allowances.','Halving uniform coverage width doubles required length for a fixed area.'],mistakes:['Treating square feet as directly equivalent to linear feet omits width.','Using nominal board width where installed coverage is smaller understates required length.','A fractional number of physical pieces is not a whole-count piece-length input.'],verification:'For area mode, multiply the answer by coverage width in feet and recover the supplied area. For piece mode, multiply length per piece by the integer quantity. Preserve any separately chosen waste allowance rather than assuming it was already added.'};
 if(tool.slug==='calories-burned-calculator')updated={...updated,interpretation:audit.interpretation+' Rucking options use explicit Adult Compendium categories: backpacking 17010 (7.0 MET), level city daypack walking 17011 (3.5 MET), or organized daypack hiking 17012 (7.8 MET). Their duration is supplied minutes; no pack-weight, terrain or speed correction is extrapolated.',sourceUrl:'https://pacompendium.com/walking/',sourceNote:'2024 Adult Compendium of Physical Activities, walking categories 17010, 17011 and 17012. Fixed category MET estimates are not measured individual expenditure.'};
 return updated;
}
