export const roadmapDeferredKeywords = [
  {
    "rank": 245,
    "keyword": "five number summary calculator",
    "slug": "five-number-summary-calculator",
    "path": "/tools/five-number-summary-calculator/",
    "volume": 1600,
    "kd": 11,
    "cpc": 0,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2215.xlsx"
  },
  {
    "rank": 276,
    "keyword": "5 number summary calculator",
    "slug": "five-number-summary-calculator",
    "path": "/tools/five-number-summary-calculator/",
    "volume": 1600,
    "kd": 13,
    "cpc": 0,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2215.xlsx"
  },
  {
    "rank": 226,
    "keyword": "average time calculator",
    "slug": "average-time-calculator",
    "path": "/tools/average-time-calculator/",
    "volume": 2400,
    "kd": 21,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 292,
    "keyword": "rewrite using a single positive exponent calculator",
    "slug": "integer-exponent-calculator",
    "path": "/tools/integer-exponent-calculator/",
    "volume": 3600,
    "kd": 21,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 292,
    "keyword": "exponents calculator",
    "slug": "integer-exponent-calculator",
    "path": "/tools/integer-exponent-calculator/",
    "volume": 2400,
    "kd": 41,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 314,
    "keyword": "stem and leaf plot generator",
    "slug": "stem-and-leaf-plot-generator",
    "path": "/tools/stem-and-leaf-plot-generator/",
    "volume": 1000,
    "kd": 13,
    "cpc": 2.07,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2215.xlsx"
  },
  {
    "rank": 317,
    "keyword": "battery run time calculator",
    "slug": "battery-runtime-calculator",
    "path": "/tools/battery-runtime-calculator/",
    "volume": 1000,
    "kd": 13,
    "cpc": 1.93,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2215.xlsx"
  },
  {
    "rank": 348,
    "keyword": "dilution calculator",
    "slug": "dilution-ratio-calculator",
    "path": "/tools/dilution-ratio-calculator/",
    "volume": 12100,
    "kd": 35,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2604.xlsx"
  },
  {
    "rank": 431,
    "keyword": "bond calculator",
    "slug": "fixed-coupon-bond-calculator",
    "path": "/tools/fixed-coupon-bond-calculator/",
    "volume": 4400,
    "kd": 47,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 431,
    "keyword": "bond price calculator",
    "slug": "fixed-coupon-bond-calculator",
    "path": "/tools/fixed-coupon-bond-calculator/",
    "volume": 1600,
    "kd": 43,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 431,
    "keyword": "bond value calculator",
    "slug": "fixed-coupon-bond-calculator",
    "path": "/tools/fixed-coupon-bond-calculator/",
    "volume": 1600,
    "kd": 45,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 431,
    "keyword": "calculator bond",
    "slug": "fixed-coupon-bond-calculator",
    "path": "/tools/fixed-coupon-bond-calculator/",
    "volume": 1000,
    "kd": 43,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 431,
    "keyword": "bond valuation calculator",
    "slug": "fixed-coupon-bond-calculator",
    "path": "/tools/fixed-coupon-bond-calculator/",
    "volume": 1000,
    "kd": 47,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 477,
    "keyword": "distance formula calculator",
    "slug": "cartesian-distance-calculator",
    "path": "/tools/cartesian-distance-calculator/",
    "volume": 5400,
    "kd": 49,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2604.xlsx | semrush-export-4100.xlsx"
  },
  {
    "rank": 477,
    "keyword": "distance between two points calculator",
    "slug": "cartesian-distance-calculator",
    "path": "/tools/cartesian-distance-calculator/",
    "volume": 1300,
    "kd": 46,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 477,
    "keyword": "distance between two points solver",
    "slug": "cartesian-distance-calculator",
    "path": "/tools/cartesian-distance-calculator/",
    "volume": 1000,
    "kd": 47,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 480,
    "keyword": "bpm calculator",
    "slug": "bpm-calculator",
    "path": "/tools/bpm-calculator/",
    "volume": 5400,
    "kd": 45,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2604.xlsx"
  },
  {
    "rank": 461,
    "keyword": "protein calculator in food",
    "slug": "food-protein-calculator",
    "path": "/tools/food-protein-calculator/",
    "volume": 1000,
    "kd": 32,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 461,
    "keyword": "protein counter",
    "slug": "food-protein-calculator",
    "path": "/tools/food-protein-calculator/",
    "volume": 1300,
    "kd": 43,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 461,
    "keyword": "food protein calculator",
    "slug": "food-protein-calculator",
    "path": "/tools/food-protein-calculator/",
    "volume": 1300,
    "kd": 44,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 461,
    "keyword": "protein calculator online",
    "slug": "food-protein-calculator",
    "path": "/tools/food-protein-calculator/",
    "volume": 1000,
    "kd": 42,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 424,
    "keyword": "physics calculator",
    "slug": "force-mass-acceleration-calculator",
    "path": "/tools/force-mass-acceleration-calculator/",
    "volume": 1900,
    "kd": 31,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx"
  },
  {
    "rank": 449,
    "keyword": "mifflin st jeor calculator",
    "slug": "resting-energy-calculator",
    "path": "/tools/resting-energy-calculator/",
    "volume": 5400,
    "kd": 49,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-2604.xlsx | semrush-export-4100.xlsx"
  },
  {
    "rank": 443,
    "keyword": "estimate vo2 max calculator",
    "slug": "rockport-vo2-max-calculator",
    "path": "/tools/rockport-vo2-max-calculator/",
    "volume": 12100,
    "kd": 46,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2604.xlsx"
  },
  {
    "rank": 299,
    "keyword": "rmd calculator",
    "slug": "rmd-uniform-lifetime-calculator",
    "path": "/tools/rmd-uniform-lifetime-calculator/",
    "volume": 74000,
    "kd": 42,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx"
  }
] as const;
