export const roadmapGap20Keywords = [
  {
    "rank": 287,
    "keyword": "decathlon calculator",
    "slug": "decathlon-scoring-calculator",
    "path": "/tools/decathlon-scoring-calculator/",
    "volume": 1300,
    "kd": 11,
    "cpc": 0,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2215.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 305,
    "keyword": "basis calculator",
    "slug": "matrix-basis-calculator",
    "path": "/tools/matrix-basis-calculator/",
    "volume": 1300,
    "kd": 13,
    "cpc": 0.23,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2215.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 309,
    "keyword": "dotted calculator",
    "slug": "dotted-note-duration-calculator",
    "path": "/tools/dotted-note-duration-calculator/",
    "volume": 1000,
    "kd": 9,
    "cpc": 0,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2215.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 367,
    "keyword": "snow load calculator",
    "slug": "snow-weight-load-calculator",
    "path": "/tools/snow-weight-load-calculator/",
    "volume": 1000,
    "kd": 14,
    "cpc": 0,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2215.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 374,
    "keyword": "dog age calculator",
    "slug": "labrador-human-age-calculator",
    "path": "/tools/labrador-human-age-calculator/",
    "volume": 22200,
    "kd": 43,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2604.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 374,
    "keyword": "age calculator of dog",
    "slug": "labrador-human-age-calculator",
    "path": "/tools/labrador-human-age-calculator/",
    "volume": 18100,
    "kd": 42,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-2604.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 374,
    "keyword": "human years to dog years calculator",
    "slug": "labrador-human-age-calculator",
    "path": "/tools/labrador-human-age-calculator/",
    "volume": 6600,
    "kd": 43,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-2604.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 382,
    "keyword": "clothing size calculator",
    "slug": "clothing-size-chart-matcher",
    "path": "/tools/clothing-size-chart-matcher/",
    "volume": 1300,
    "kd": 38,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 402,
    "keyword": "golf handicap calculator",
    "slug": "golf-handicap-worksheet",
    "path": "/tools/golf-handicap-worksheet/",
    "volume": 9900,
    "kd": 40,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 402,
    "keyword": "handicap calculator",
    "slug": "golf-handicap-worksheet",
    "path": "/tools/golf-handicap-worksheet/",
    "volume": 4400,
    "kd": 35,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 402,
    "keyword": "handicap calculator golf",
    "slug": "golf-handicap-worksheet",
    "path": "/tools/golf-handicap-worksheet/",
    "volume": 1600,
    "kd": 46,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 402,
    "keyword": "calculate golf handicap",
    "slug": "golf-handicap-worksheet",
    "path": "/tools/golf-handicap-worksheet/",
    "volume": 1300,
    "kd": 45,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 414,
    "keyword": "anc calculator",
    "slug": "absolute-neutrophil-count-calculator",
    "path": "/tools/absolute-neutrophil-count-calculator/",
    "volume": 6600,
    "kd": 37,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2604.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 441,
    "keyword": "taxable income calculator",
    "slug": "taxable-income-worksheet",
    "path": "/tools/taxable-income-worksheet/",
    "volume": 6600,
    "kd": 41,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 447,
    "keyword": "nyc income tax calculator",
    "slug": "nyc-resident-income-tax-calculator",
    "path": "/tools/nyc-resident-income-tax-calculator/",
    "volume": 12100,
    "kd": 43,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-2604.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 449,
    "keyword": "harris benedict calculator",
    "slug": "harris-benedict-calculator",
    "path": "/tools/harris-benedict-calculator/",
    "volume": 1300,
    "kd": 32,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 449,
    "keyword": "harris benedict equation calculator",
    "slug": "harris-benedict-calculator",
    "path": "/tools/harris-benedict-calculator/",
    "volume": 1000,
    "kd": 33,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 454,
    "keyword": "women's to men's shoe size conversion calculator",
    "slug": "adult-shoe-size-converter",
    "path": "/tools/adult-shoe-size-converter/",
    "volume": 3600,
    "kd": 40,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 454,
    "keyword": "foot size calculator",
    "slug": "adult-shoe-size-converter",
    "path": "/tools/adult-shoe-size-converter/",
    "volume": 1300,
    "kd": 35,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 454,
    "keyword": "shoe size converter and calculator",
    "slug": "adult-shoe-size-converter",
    "path": "/tools/adult-shoe-size-converter/",
    "volume": 2400,
    "kd": 44,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 467,
    "keyword": "lbm calculator",
    "slug": "boer-lean-body-mass-calculator",
    "path": "/tools/boer-lean-body-mass-calculator/",
    "volume": 1600,
    "kd": 37,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 467,
    "keyword": "lean mass calculator",
    "slug": "boer-lean-body-mass-calculator",
    "path": "/tools/boer-lean-body-mass-calculator/",
    "volume": 2400,
    "kd": 43,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 467,
    "keyword": "lean mass weight calculator",
    "slug": "boer-lean-body-mass-calculator",
    "path": "/tools/boer-lean-body-mass-calculator/",
    "volume": 2900,
    "kd": 47,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 472,
    "keyword": "texas state tax calculator",
    "slug": "texas-sales-tax-calculator",
    "path": "/tools/texas-sales-tax-calculator/",
    "volume": 2400,
    "kd": 42,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 472,
    "keyword": "car sales tax calculator",
    "slug": "texas-sales-tax-calculator",
    "path": "/tools/texas-sales-tax-calculator/",
    "volume": 1900,
    "kd": 42,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 484,
    "keyword": "kcal calories converter",
    "slug": "food-energy-calculator",
    "path": "/tools/food-energy-calculator/",
    "volume": 1600,
    "kd": 43,
    "cpc": null,
    "role": "PRIMARY",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  },
  {
    "rank": 484,
    "keyword": "how to calculate calories in food",
    "slug": "food-energy-calculator",
    "path": "/tools/food-energy-calculator/",
    "volume": 2400,
    "kd": 47,
    "cpc": null,
    "role": "SECONDARY / MERGED",
    "sourceFiles": "semrush-export-4100.xlsx",
    "historicalWorkbookMetrics": true
  }
] as const;
