import type { Tool } from "./tools";
import { buildTool } from "./semrush-phase-one-b-tools";

const definitions: Array<[string,string,string,string,string,string,string[]]> = [
  ["money-counter-calculator","Money Counter Calculator","Money","Count bills and coins by entering matching denomination and quantity lists. Totals stay currency-neutral so you can use any currency.","Cash total = Σ(denomination × quantity).","Five 20-unit notes, three 5-unit notes and two 1-unit coins total 117.", ["money counter calculator","money counter","money calculator","cash counter","bill counter","coin counter","denomination calculator","count money calculator"]],
  ["soil-calculator","Soil Calculator","Home","Estimate topsoil volume for a rectangular garden bed, lawn or raised bed from its length, width and depth.","Soil volume = length × width × depth; convert cubic feet to cubic yards by dividing by 27.","A 12 ft × 8 ft bed with 4 in of topsoil needs about 1.19 cubic yards before settling or waste.",["soil calculator","topsoil calculator","top soil calculator","garden soil calculator","soil volume calculator","topsoil volume calculator"]],
  ["ffmi-calculator","FFMI Calculator","Everyday","Calculate fat-free mass index from body weight, height and entered body-fat percentage.","FFMI = fat-free mass in kg ÷ height in metres²; fat-free mass = weight × (1 − body-fat fraction).","At 80 kg, 20% body fat and 1.80 m tall, FFMI is about 19.8.",["ffmi calculator","fat free mass index calculator","fat-free mass index"]],
  ["hex-calculator","Hex Calculator","Education","Convert hexadecimal values to decimal and binary, or perform basic arithmetic with hexadecimal integers.","Hexadecimal uses base 16. Convert each digit with its positional power of 16; arithmetic is performed on integer values.","Hexadecimal 2F equals decimal 47 and binary 101111.",["hex calculator","hexadecimal calculator","hex to decimal calculator","calculate hexadecimal to decimal","hex and decimal converter","calculator for hexadecimal","decimal to hex calculator","decimal to hexadecimal calculator","dec hex calculator","hex converter"]],
  ["dunk-calculator","Dunk Calculator","Everyday","Compare standing reach plus vertical jump with a basketball rim to estimate the clearance available for a dunk.","Reach at jump = standing reach + vertical jump; clearance = reach at jump − rim height.","A 7 ft 8 in standing reach plus a 30 in jump reaches 10 ft 2 in, about 2 in above a 10 ft rim.",["dunk calculator","vertical jump dunk calculator","how high to dunk calculator","basketball dunk calculator"]],
  ["mare-gestation-calculator","Mare Gestation Calculator","Everyday","Estimate a mare's foaling date and a broad planning window from the breeding date.","Planning midpoint = breeding date + 340 days; a broad reference window is approximately 320–360 days.","A breeding date of January 1 gives a 340-day midpoint around December 7, with foaling possible earlier or later.",["mare gestation calculator","horse pregnancy calculator","mare pregnancy calculator","horse gestation calculator","foaling date calculator"]],
  ["linear-feet-calculator","Linear Feet Calculator","Home","Calculate total linear feet from repeated pieces measured in feet and inches.","Total linear feet = quantity × (feet per piece + inches per piece ÷ 12).","Eight 2 ft 6 in pieces total 20 linear feet.",["linear feet calculator","linear foot calculator","calculate linear feet","linear footage calculator"]],
  ["water-intake-calculator","Water Intake Calculator","Everyday","Compare an adult's entered daily water intake with National Academies reference adequate intakes for total water from food and beverages.","Reference intake is 3.7 L/day for adult men and 2.7 L/day for adult women; total water includes water in food and all drinks.","An adult woman comparing 2.0 L with the 2.7 L total-water reference is 0.7 L below that population reference.",["water intake calculator","water calculator","daily water intake calculator","how much water to drink a day calculator","calculator for water consumption","water consumption calculator"]],
  ["steps-to-miles-calculator","Steps to Miles Calculator","Everyday","Convert steps to miles or miles to steps using your own average step length.","Miles = steps × step length in inches ÷ 63,360; reverse the equation to estimate steps from miles.","2,000 steps at 28 inches per step are about 0.88 miles.",["steps to miles calculator","miles to steps calculator","steps in a mile calculator","walking distance calculator","convert steps to miles"]],
  ["minecraft-circle-generator","Minecraft Circle Generator","Everyday","Generate a pixel-style Minecraft circle or filled disk as a block grid for building plans.","A raster circle marks grid cells by their distance from the center; filled mode includes interior cells and outline mode keeps the perimeter.","A 9-block-wide outline produces a symmetrical grid that can be copied row by row into a Minecraft build.",["minecraft circle generator","circle generator minecraft","minecraft circle maker","pixel circle generator","minecraft circle chart"]],
  ["density-altitude-calculator","Density Altitude Calculator","Everyday","Estimate density altitude from pressure altitude and outside-air temperature using the common rule-of-thumb approximation.","ISA temperature °C ≈ 15 − 1.98 × (pressure altitude in 1,000 ft); density altitude ≈ pressure altitude + 120 × (OAT − ISA temperature) in feet.","At 5,000 ft pressure altitude and 25°C, the estimated density altitude is about 7,390 ft.",["density altitude calculator","density altitude calculator aviation","calculate density altitude","pressure altitude temperature calculator"]],
  ["height-calculator","Height Calculator","Everyday","Estimate an adult height target from biological parents' heights using the traditional mid-parental-height method.","Mid-parental estimate for boys = (father + mother + 5 in) ÷ 2; for girls = (father + mother − 5 in) ÷ 2. The result is a rough family-height estimate, not Khamis–Roche.","A 70 in father and 64 in mother give a rough 69.5 in boy estimate or 64.5 in girl estimate.",["height calculator","child height calculator","height calculator boys","height prediction calculator","height predictor calculator","height estimator","projected height calculator","adult height calculator"]],
  ["weighted-mean-calculator","Weighted Mean Calculator","Education","Calculate a weighted mean from paired values and weights, such as grades weighted by credits or measurements weighted by sample size.","Weighted mean = Σ(value × weight) ÷ Σ(weights), with non-negative weights and a positive total weight.","Scores 80 and 90 weighted 1 and 3 have a weighted mean of 87.5.",["weighted mean calculator","weighted average calculator","weighted average calculator with steps","calculate weighted mean"]],
  ["yardage-calculator","Yardage Calculator","Home","Estimate fabric yardage for repeated rectangular pieces across a usable fabric width, comparing both cutting orientations.","Rows = ceiling(quantity ÷ pieces per row); base yardage = rows × piece length ÷ 36. A waste allowance is added afterward.","Ten 12 in × 18 in pieces on 44 in usable fabric width need five rows; the best orientation determines the estimated yardage.",["yardage calculator","fabric yardage calculator","fabric calculator","calculate yards of fabric","sewing yardage calculator"]],
  ["mean-standard-deviation-calculator","Mean and Standard Deviation Calculator","Education","Calculate the mean and either population or sample standard deviation from a list of numbers.","Mean = Σx ÷ n. Population SD uses √(Σ(x−mean)²/n); sample SD uses √(Σ(x−mean)²/(n−1)).","For 2, 4 and 6, the mean is 4; population SD is about 1.63 and sample SD is 2.",["mean and standard deviation calculator","mean standard deviation calculator","standard deviation calculator","mean calculator","sample standard deviation calculator","population standard deviation calculator"]],
  ["visceral-fat-calculator","Visceral Fat Calculator","Everyday","Estimate visceral adipose tissue area from waist, proximal thigh, age, BMI and sex using a published anthropometric equation.","Samouda et al. equations estimate VAT area in cm² from sex-specific combinations of waist and proximal thigh circumference, age and, for women, BMI.","This estimate is based on tape measurements and a study-population model; imaging methods directly measure visceral adipose tissue.",["visceral fat calculator","visceral adipose tissue calculator","visceral fat estimate calculator","VAT calculator"]],
  ["body-fat-calculator","Body Fat Calculator — U.S. Navy Estimate","Everyday","Estimate body-fat percentage with the classic U.S. Navy circumference equations using height, waist or abdomen, neck and (for women) hip measurements.","The classic equations use logarithms of circumference combinations and height in inches; this is an estimate and is not an official service eligibility determination.","Enter measurements in inches at the method's specified sites; use the result only as a rough tape-based estimate.",["body fat calculator","body fat calculator u.s. navy","us navy body fat calculator","us naval body fat calculator","fat percentage calculator","bfp calculator","bodyfat calculator","how to find your body fat percentage","how to know fat percentage","how to figure out percentage of body fat","how to know your body fat percentage","how to calculate percentage fat","how to calculate the percentage of fat in your body"]],
];

export const semrushRoadmapTools: Tool[] = definitions.map(([slug,title,category,description,formula,example,keywords]) => buildTool({
  slug,title,shortTitle:title.replace(" Calculator","").replace(" Generator",""),description,icon:category==="Home"?"📐":category==="Education"?"🧮":"📊",category,accent:category==="Home"?"green":category==="Education"?"violet":"blue",keywords,formula,example,focus:"units, assumptions, rounding, source limits and checking entered values",
}));
