export type Tool = {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  icon: string;
  category: string;
  accent: "blue" | "green" | "amber" | "violet" | "rose";
  updatedAt: string;
  keywords: string[];
  intro: string;
  formula: string;
  example: string;
  howTo: string[];
  considerations: { title: string; text: string }[];
  limitations: string;
  faqs: { question: string; answer: string }[];
};

const commonFaq = (name: string) => [
  { question: `Is the ${name} free?`, answer: "Yes. SolvePilot tools are free, work in your browser, and require no account." },
  { question: "Does SolvePilot store my values?", answer: "No. Calculations run locally in your browser and the values you enter are not sent to a server." },
  { question: "Should I treat the result as an exact bill or quotation?", answer: "No. Results are informed estimates. Final charges can vary because of taxes, tariffs, lender terms, usage patterns, or provider rules." },
  { question: "How can I improve the accuracy?", answer: "Use recent values from your own bill, statement or institution, review every assumption, and confirm important results with the relevant official source." },
];

type BaseTool = Omit<Tool, "howTo" | "considerations" | "limitations">;

const baseTools: BaseTool[] = [
  {
    slug: "electricity-bill-calculator-pakistan",
    title: "Electricity Bill Calculator Pakistan",
    shortTitle: "Electricity Bill",
    description: "Estimate your Pakistan electricity bill from monthly units with a transparent slab-by-slab breakdown.",
    icon: "⚡", category: "Energy", accent: "amber", updatedAt: "2026-09-17",
    keywords: ["electricity bill calculator Pakistan", "unit bill calculator", "Pakistan electricity units"],
    intro: "Enter the electricity units consumed during the month to receive a transparent planning estimate. The result separates estimated energy charges from adjustable taxes and surcharges so you can understand the assumptions.",
    formula: "Estimated bill = slab-based energy charges + configurable taxes and surcharges. Actual DISCO bills may include FCA, QTR adjustments, TV fee and other provider charges.",
    example: "If a household uses 250 units, the calculator applies each configured slab to the relevant portion rather than multiplying all units by a single rate.",
    faqs: [...commonFaq("electricity bill calculator"), {question:"Why can the real bill differ?",answer:"FCA, quarterly adjustments, protected status, taxes and the billing period can change the final amount."}],
  },
  {
    slug: "solar-system-calculator-pakistan",
    title: "Solar System Calculator Pakistan",
    shortTitle: "Solar System",
    description: "Estimate solar system size, panel count, monthly generation, savings and payback period for Pakistan.",
    icon: "☀️", category: "Solar", accent: "green", updatedAt: "2026-09-17",
    keywords: ["solar calculator Pakistan", "solar system size calculator", "solar panels required Pakistan"],
    intro: "Plan a solar system from your average monthly electricity usage. The tool estimates system capacity, panel count, monthly production and a simple payback period using editable Pakistan-focused assumptions.",
    formula: "Daily units = monthly units ÷ 30. Required kW = daily units ÷ (peak-sun-hours × system efficiency).",
    example: "A home consuming 600 units monthly uses about 20 units daily. At 5.2 peak-sun-hours and 80% efficiency, it needs roughly a 4.8 kW array before practical rounding.",
    faqs: [...commonFaq("solar system calculator"), {question:"Does it include batteries?",answer:"The initial result sizes panels. Battery capacity depends on the backup load and required backup hours and should be calculated separately."}],
  },
  {
    slug: "salary-tax-calculator-pakistan",
    title: "Salary Tax Calculator Pakistan",
    shortTitle: "Salary Tax",
    description: "Estimate annual and monthly salary tax and take-home pay using configurable Pakistan tax slabs.",
    icon: "💼", category: "Money", accent: "blue", updatedAt: "2026-09-17",
    keywords: ["salary tax calculator Pakistan", "income tax calculator Pakistan", "take home salary Pakistan"],
    intro: "Estimate the income tax deducted from a salaried person and see monthly take-home pay. Rates are versioned by tax year so past calculations remain reproducible when the federal budget changes.",
    formula: "Annual tax is calculated progressively: each rate applies only to the income portion inside its corresponding slab.",
    example: "For a PKR 150,000 monthly salary, the annual salary is PKR 1.8 million. The calculator applies the selected year’s progressive slabs and divides annual tax into monthly withholding.",
    faqs: [...commonFaq("salary tax calculator"), {question:"Does it include every tax credit?",answer:"No. This estimator focuses on salary taxation and does not replace an individual return calculation with credits, exemptions or multiple income sources."}],
  },
  {
    slug: "pta-tax-calculator-pakistan",
    title: "PTA Mobile Tax Estimator Pakistan",
    shortTitle: "PTA Tax",
    description: "Estimate PTA registration duty for an imported phone by USD value and registration method.",
    icon: "📱", category: "Technology", accent: "violet", updatedAt: "2026-09-17",
    keywords: ["PTA tax calculator", "mobile registration tax Pakistan", "PTA duty estimator"],
    intro: "Use the declared mobile value to estimate registration duty for planning. Customs valuation and official DIRBS assessment remain authoritative, so the result is clearly presented as an estimate.",
    formula: "Estimated duty uses value bands and registration method. Passport and CNIC assessments can differ and official valuation may not equal purchase price.",
    example: "Select passport or CNIC registration, enter the phone value in USD and the exchange rate, then review the estimated PKR range.",
    faqs: [...commonFaq("PTA tax estimator"), {question:"Is this an official PTA result?",answer:"No. Only the official DIRBS/PSID assessment confirms the payable amount for a specific IMEI."}],
  },
  {
    slug: "ev-vs-petrol-calculator-pakistan",
    title: "EV vs Petrol Cost Calculator Pakistan",
    shortTitle: "EV vs Petrol",
    description: "Compare monthly petrol and electric vehicle running costs and estimate your payback period.",
    icon: "🚙", category: "Vehicles", accent: "green", updatedAt: "2026-09-17",
    keywords: ["EV vs petrol calculator Pakistan", "electric bike savings Pakistan", "petrol cost calculator"],
    intro: "Compare energy costs using your real daily distance, petrol price, vehicle mileage, EV efficiency and electricity rate. The calculator shows monthly savings and how long a higher purchase price may take to recover.",
    formula: "Petrol cost = distance ÷ mileage × petrol price. EV cost = distance × kWh/km × electricity rate.",
    example: "At 50 km daily, a 40 km/litre bike uses 37.5 litres monthly. Compare that with the electricity needed by the selected EV efficiency.",
    faqs: [...commonFaq("EV versus petrol calculator"), {question:"Does this include battery replacement?",answer:"The primary result compares energy expense. Purchase difference and optional maintenance allowance are included separately; long-term battery replacement should also be considered."}],
  },
  {
    slug: "daraz-profit-calculator-pakistan",
    title: "Daraz Profit Calculator Pakistan",
    shortTitle: "Daraz Profit",
    description: "Estimate Daraz product profit after commission, payment fees, shipping support, ads and product cost.",
    icon: "📦", category: "Business", accent: "rose", updatedAt: "2026-09-17",
    keywords: ["Daraz profit calculator", "Daraz seller fee calculator Pakistan", "ecommerce profit calculator"],
    intro: "Know the amount left from a sale after product cost and marketplace expenses. All fee fields are editable because commission and campaign charges vary by category and seller agreement.",
    formula: "Net profit = selling price − product cost − commission − payment fee − seller shipping cost − advertising cost − other costs.",
    example: "A product sold for PKR 3,000 with a PKR 1,500 product cost and 12% commission starts with PKR 1,140 before other costs.",
    faqs: [...commonFaq("Daraz profit calculator"), {question:"Why is commission editable?",answer:"Daraz commission varies by category and can change. Enter the rate shown in your current seller information for the best estimate."}],
  },
  {
    slug: "percentage-calculator",
    title: "Percentage Calculator",
    shortTitle: "Percentage",
    description: "Calculate a percentage of a number, percentage change, or what percentage one value is of another.",
    icon: "%", category: "Everyday", accent: "blue", updatedAt: "2026-09-17",
    keywords: ["percentage calculator", "percentage change calculator", "calculate percent"],
    intro: "Solve the three most common percentage questions with clear formulas and instant results. This lightweight tool runs entirely in your browser.",
    formula: "Percentage of value = value × percentage ÷ 100. Percentage change = (new − old) ÷ old × 100.",
    example: "Twenty percent of 5,000 is 1,000 because 5,000 × 20 ÷ 100 = 1,000.",
    faqs: commonFaq("percentage calculator"),
  },
  {
    slug: "cgpa-percentage-calculator-pakistan",
    title: "CGPA to Percentage Calculator Pakistan",
    shortTitle: "CGPA Converter",
    description: "Convert CGPA to an estimated percentage using common scales and a custom institution multiplier.",
    icon: "🎓", category: "Education", accent: "violet", updatedAt: "2026-09-17",
    keywords: ["CGPA to percentage Pakistan", "GPA percentage calculator", "CGPA converter"],
    intro: "Convert CGPA into an estimated percentage for planning and comparisons. Universities use different conversion rules, so this tool lets you select a common method or enter the formula supplied by your institution.",
    formula: "Estimated percentage = CGPA × institution multiplier. Always prefer the conversion formula printed by the relevant university or authority.",
    example: "On a 4.0 scale with a multiplier of 25, a CGPA of 3.2 corresponds to an estimated 80%.",
    faqs: [...commonFaq("CGPA converter"), {question:"Is one CGPA formula valid for every university?",answer:"No. Institutions may use different formulas. Use your university’s official conversion when available."}],
  },
  {
    slug: "loan-emi-calculator-pakistan",
    title: "Loan EMI Calculator Pakistan",
    shortTitle: "Loan EMI",
    description: "Estimate a loan's monthly instalment, total repayment and financing cost from the principal, rate and term.",
    icon: "🏦", category: "Money", accent: "blue", updatedAt: "2026-09-17",
    keywords: ["loan EMI calculator Pakistan", "monthly installment calculator", "loan markup calculator Pakistan"],
    intro: "Compare loan scenarios before speaking with a bank or financing company. Enter the amount you plan to borrow, the annual percentage rate and the repayment term to see the estimated fixed monthly instalment and the total financing cost over the full term.",
    formula: "For a reducing-balance loan, EMI = P × r × (1 + r)^n ÷ ((1 + r)^n − 1), where P is principal, r is the monthly rate and n is the number of monthly payments.",
    example: "A PKR 1,000,000 loan at 18% per year for five years is converted to a monthly rate and 60 payments. The result shows the instalment as well as how much of the complete repayment is financing cost.",
    faqs: [...commonFaq("loan EMI calculator"), {question:"Is bank markup always calculated this way?",answer:"No. Some products use flat rates, fees, takaful or changing benchmark rates. Check the bank's repayment schedule before signing."}],
  },
  {
    slug: "fuel-cost-calculator-pakistan",
    title: "Fuel Cost Calculator Pakistan",
    shortTitle: "Fuel Cost",
    description: "Plan petrol spending for a trip or month using distance, vehicle mileage and the fuel price you enter.",
    icon: "⛽", category: "Vehicles", accent: "amber", updatedAt: "2026-09-17",
    keywords: ["fuel cost calculator Pakistan", "petrol expense calculator", "trip fuel calculator Pakistan"],
    intro: "Turn a route distance into a realistic fuel budget using your own vehicle's average mileage and the price displayed at the pump. The breakdown includes litres required, cost per kilometre and total estimated spend.",
    formula: "Fuel required = distance ÷ average mileage. Estimated cost = fuel required × price per litre. Cost per kilometre = price per litre ÷ mileage.",
    example: "For a 450 km journey in a car averaging 13 km/l at PKR 265 per litre, the estimate uses about 34.6 litres and reports the corresponding trip cost.",
    faqs: [...commonFaq("fuel cost calculator"), {question:"Which mileage figure should I enter?",answer:"Use your recent tank-to-tank average. Manufacturer figures may be higher than real driving mileage."}],
  },
  {
    slug: "battery-backup-calculator-pakistan",
    title: "Battery Backup Time Calculator",
    shortTitle: "Battery Backup",
    description: "Estimate UPS or solar battery runtime from appliance load, battery capacity, voltage and practical losses.",
    icon: "🔋", category: "Energy", accent: "green", updatedAt: "2026-09-17",
    keywords: ["battery backup calculator Pakistan", "UPS runtime calculator", "solar battery backup time"],
    intro: "Estimate how long a battery bank can support a known load during an outage. The result applies a conservative usable-capacity and conversion-loss allowance so it is more useful than simply dividing watt-hours by watts.",
    formula: "Nominal energy = amp-hours × voltage. Estimated runtime = nominal energy × usable-capacity factor × inverter efficiency ÷ connected load.",
    example: "A 150 Ah, 12 V battery stores 1,800 nominal watt-hours. At 80% combined usable energy and conversion efficiency with a 300 W load, estimated runtime is about 4.8 hours.",
    faqs: [...commonFaq("battery backup calculator"), {question:"Why is actual backup sometimes shorter?",answer:"Battery age, temperature, discharge rate, wiring losses and inverter cut-off voltage can all reduce usable runtime."}],
  },
  {
    slug: "inverter-load-calculator-pakistan",
    title: "Inverter Load Calculator Pakistan",
    shortTitle: "Inverter Size",
    description: "Estimate a suitable inverter VA rating from appliance watts, safety headroom and power factor.",
    icon: "🔌", category: "Energy", accent: "violet", updatedAt: "2026-09-17",
    keywords: ["inverter load calculator Pakistan", "inverter size calculator", "UPS VA calculator"],
    intro: "Add the running wattage of the appliances you want to power and allow capacity for losses and short peaks. The result converts watts into an estimated VA requirement and suggests the next practical minimum size.",
    formula: "Required VA = connected watts × (1 + safety margin) ÷ power factor. Motors and compressors may also require separate surge capacity.",
    example: "A planned 800 W running load with 25% headroom and a 0.8 power factor produces a minimum estimate of 1,250 VA before checking startup surges.",
    faqs: [...commonFaq("inverter load calculator"), {question:"Do refrigerators need special allowance?",answer:"Yes. Compressors and pumps can draw several times their running power briefly, so verify the inverter's surge rating."}],
  },
  {
    slug: "profit-margin-calculator",
    title: "Profit Margin Calculator",
    shortTitle: "Profit Margin",
    description: "Calculate gross profit, margin percentage and markup from revenue and total cost.",
    icon: "📈", category: "Business", accent: "green", updatedAt: "2026-09-17",
    keywords: ["profit margin calculator", "gross margin calculator", "markup calculator Pakistan"],
    intro: "Understand whether a product or job is priced sustainably. Enter sales revenue and all direct costs to compare gross profit margin with markup—two related percentages that are often confused.",
    formula: "Profit = revenue − cost. Margin = profit ÷ revenue × 100. Markup = profit ÷ cost × 100.",
    example: "If an item sells for PKR 2,000 and costs PKR 1,400, gross profit is PKR 600, margin is 30%, and markup on cost is about 42.9%.",
    faqs: [...commonFaq("profit margin calculator"), {question:"Is margin the same as markup?",answer:"No. Margin divides profit by selling price, while markup divides profit by cost, so the percentages differ."}],
  },
  {
    slug: "discount-calculator-pakistan",
    title: "Discount Calculator Pakistan",
    shortTitle: "Discount",
    description: "Find the sale price, amount saved and optional tax-adjusted total after a percentage discount.",
    icon: "🏷️", category: "Everyday", accent: "rose", updatedAt: "2026-09-17",
    keywords: ["discount calculator Pakistan", "sale price calculator", "percentage discount calculator"],
    intro: "Check a sale offer without doing mental arithmetic. The calculator first removes the stated percentage from the original price, then optionally applies a tax or service rate to the discounted amount.",
    formula: "Discount = original price × discount rate ÷ 100. Sale price = original price − discount. Final total = sale price × (1 + additional rate ÷ 100).",
    example: "A PKR 8,000 item at 25% off saves PKR 2,000 and costs PKR 6,000 before any optional tax or service charge.",
    faqs: [...commonFaq("discount calculator"), {question:"Is an extra percentage applied before or after discount?",answer:"This tool applies the optional tax or service rate after the discount, which is the common retail sequence."}],
  },
  {
    slug: "attendance-percentage-calculator",
    title: "Attendance Percentage Calculator",
    shortTitle: "Attendance",
    description: "Calculate current attendance and the classes needed to reach a target percentage.",
    icon: "🗓️", category: "Education", accent: "blue", updatedAt: "2026-09-17",
    keywords: ["attendance percentage calculator", "classes needed for attendance", "student attendance calculator"],
    intro: "See your current attendance and plan how many consecutive classes you need to attend to reach a required target. The result also flags when the target has already been met.",
    formula: "Current attendance = attended ÷ held × 100. Classes needed x satisfies (attended + x) ÷ (held + x) ≥ target percentage.",
    example: "A student who attended 36 of 50 classes has 72% attendance. To reach 75%, both attended and held totals increase for every future class attended.",
    faqs: [...commonFaq("attendance percentage calculator"), {question:"Does an attended future class increase both totals?",answer:"Yes. Each new class increases total classes held, and attending it also increases your attended count."}],
  },
  {
    slug: "marks-percentage-calculator-pakistan",
    title: "Marks Percentage Calculator Pakistan",
    shortTitle: "Marks Percentage",
    description: "Convert obtained marks into a percentage and compare the result with a passing threshold.",
    icon: "📝", category: "Education", accent: "violet", updatedAt: "2026-09-17",
    keywords: ["marks percentage calculator Pakistan", "exam percentage calculator", "obtained marks calculator"],
    intro: "Convert a score from any total into a consistent percentage. Add the applicable passing percentage to see the minimum marks and how far the entered score sits above or below it.",
    formula: "Percentage = obtained marks ÷ total marks × 100. Minimum passing marks = total marks × passing percentage ÷ 100.",
    example: "Obtaining 735 out of 1,100 gives approximately 66.82%. With a 40% threshold, the minimum passing score is 440 marks.",
    faqs: [...commonFaq("marks percentage calculator"), {question:"Does this assign an official grade?",answer:"No. Boards and institutions use different grade boundaries, so the tool reports percentage and threshold only."}],
  },
  {
    slug: "freelance-hourly-rate-calculator-pakistan",
    title: "Freelance Hourly Rate Calculator Pakistan",
    shortTitle: "Freelance Rate",
    description: "Estimate a sustainable freelance hourly rate from income goal, billable time and monthly business costs.",
    icon: "💻", category: "Business", accent: "blue", updatedAt: "2026-09-17",
    keywords: ["freelance rate calculator Pakistan", "hourly rate calculator", "freelancer pricing Pakistan"],
    intro: "Set a rate from the income you need rather than copying a competitor. The calculation combines your monthly income target with operating costs and divides the total by realistic billable hours—not every hour you work.",
    formula: "Required hourly rate = (monthly income target + monthly business costs) ÷ monthly billable hours.",
    example: "A freelancer targeting PKR 200,000, carrying PKR 30,000 in monthly costs and billing 100 hours needs an average of PKR 2,300 per billable hour before taxes.",
    faqs: [...commonFaq("freelance hourly rate calculator"), {question:"Why use billable rather than total work hours?",answer:"Sales, administration, learning and revisions consume time but may not be directly billed to a client."}],
  },
  {
    slug: "paint-quantity-calculator-pakistan",
    title: "Paint Quantity Calculator Pakistan",
    shortTitle: "Paint Quantity",
    description: "Estimate paint litres and container count from wall area, coats and the product's stated coverage.",
    icon: "🪣", category: "Home", accent: "amber", updatedAt: "2026-09-17",
    keywords: ["paint calculator Pakistan", "paint quantity calculator", "wall paint litres calculator"],
    intro: "Estimate material before purchasing paint for a room or project. Use the paint manufacturer's coverage rate and the net wall area after subtracting large doors and windows for a more useful result.",
    formula: "Paint litres = wall area × number of coats ÷ coverage per litre. A practical purchase estimate then includes a small waste and touch-up allowance.",
    example: "For 1,000 square feet of net wall area, two coats and coverage of 120 square feet per litre, the base estimate is 16.7 litres before allowance.",
    faqs: [...commonFaq("paint quantity calculator"), {question:"Should primer be included as a paint coat?",answer:"Calculate primer separately because its coverage and number of coats can differ from the finish paint."}],
  },
  {
    slug: "appliance-electricity-cost-calculator-pakistan",
    title: "Appliance Electricity Cost Calculator Pakistan",
    shortTitle: "Appliance Cost",
    description: "Estimate the monthly electricity units and cost of running an appliance from watts, daily hours and your tariff.",
    icon: "🔌", category: "Energy", accent: "amber", updatedAt: "2026-09-17",
    keywords: ["appliance electricity cost calculator Pakistan", "watts to units calculator", "monthly appliance bill"],
    intro: "Estimate how much one appliance contributes to your monthly electricity consumption. Enter its rated power, average daily runtime and the effective price per unit to compare air conditioners, fans, computers and other equipment on the same basis.",
    formula: "Monthly units (kWh) = appliance watts ÷ 1,000 × hours per day × 30. Estimated monthly cost = monthly units × price per unit.",
    example: "A 1,200 W appliance used for six hours daily consumes about 216 units in a 30-day month. At PKR 55 per unit, its estimated energy cost is PKR 11,880.",
    faqs: [...commonFaq("appliance electricity cost calculator"), {question:"Is the wattage label always the actual consumption?",answer:"No. Many appliances cycle or change power by mode. A plug-in energy meter provides a better average."}],
  },
  {
    slug: "generator-fuel-cost-calculator-pakistan",
    title: "Generator Fuel Cost Calculator Pakistan",
    shortTitle: "Generator Cost",
    description: "Estimate generator fuel consumption and operating cost from hourly usage, burn rate and fuel price.",
    icon: "⚙️", category: "Energy", accent: "rose", updatedAt: "2026-09-17",
    keywords: ["generator fuel cost calculator Pakistan", "generator diesel consumption", "generator running cost"],
    intro: "Plan the direct fuel expense of generator backup using the operating hours and consumption rate for your machine at the expected load. The result shows daily litres, daily expense and a 30-day monthly projection.",
    formula: "Daily fuel = operating hours × litres consumed per hour. Daily cost = daily fuel × fuel price. Monthly cost = daily cost × 30.",
    example: "A generator running four hours daily at 1.5 litres per hour consumes six litres per day. At PKR 280 per litre, that is PKR 1,680 daily before maintenance.",
    faqs: [...commonFaq("generator fuel cost calculator"), {question:"Why does generator consumption change with load?",answer:"Engines burn more fuel as electrical load rises, and very light loading can also be inefficient."}],
  },
  {
    slug: "ac-tonnage-calculator-pakistan",
    title: "AC Tonnage Estimator Pakistan",
    shortTitle: "AC Tonnage",
    description: "Estimate a starting air-conditioner capacity from room area, ceiling height and climate allowance.",
    icon: "❄️", category: "Home", accent: "blue", updatedAt: "2026-09-17",
    keywords: ["AC tonnage calculator Pakistan", "room AC size calculator", "BTU calculator Pakistan"],
    intro: "Get a preliminary cooling-capacity estimate before comparing air conditioners. Room area is adjusted for ceiling height, then converted into approximate BTU per hour and common tonnage sizes using a configurable heat-load factor.",
    formula: "Estimated BTU/h = room area × ceiling-height adjustment × heat-load factor. One refrigeration ton is approximately 12,000 BTU/h.",
    example: "A 180 sq ft room with a 10 ft ceiling and a 65 BTU-per-square-foot planning factor needs roughly 13,000 BTU/h, suggesting the next practical size near 1.25 tons.",
    faqs: [...commonFaq("AC tonnage estimator"), {question:"Should a sunny top-floor room use more capacity?",answer:"Usually yes. Direct sun, roof heat, large windows, occupants and appliances increase the cooling load."}],
  },
  {
    slug: "water-tank-volume-calculator-pakistan",
    title: "Water Tank Volume Calculator Pakistan",
    shortTitle: "Tank Volume",
    description: "Calculate rectangular water-tank capacity in litres, cubic feet and US gallons from internal dimensions.",
    icon: "💧", category: "Home", accent: "blue", updatedAt: "2026-09-17",
    keywords: ["water tank calculator Pakistan", "tank capacity litres calculator", "water storage calculator"],
    intro: "Convert internal tank dimensions into litres without mixing imperial and metric units. This rectangular-tank mode also reports cubic feet and US gallons so capacity can be compared with common supplier specifications.",
    formula: "Volume in cubic feet = length × width × depth. Capacity in litres = cubic feet × 28.3168. Storage days = litres ÷ daily usage.",
    example: "A tank measuring 6 ft by 4 ft by 4 ft holds about 96 cubic feet, or approximately 2,718 litres before allowing for freeboard and unusable residue.",
    faqs: [...commonFaq("water tank volume calculator"), {question:"Should I use outside or inside dimensions?",answer:"Use internal dimensions because wall thickness does not hold water."}],
  },
  {
    slug: "tile-quantity-calculator-pakistan",
    title: "Tile Quantity Calculator Pakistan",
    shortTitle: "Tile Quantity",
    description: "Estimate tiles required from floor area and tile dimensions, including a practical cutting and breakage allowance.",
    icon: "◫", category: "Home", accent: "violet", updatedAt: "2026-09-17",
    keywords: ["tile calculator Pakistan", "floor tiles quantity calculator", "tiles boxes calculator"],
    intro: "Plan a tile order from the net surface area and the size of one tile. The calculator includes a configurable cutting and breakage allowance, then rounds the quantity up so partial tiles or boxes do not leave the project short.",
    formula: "Tiles required = floor area ÷ tile area × (1 + waste rate). Tile area must first be converted into the same unit as the floor area.",
    example: "A 200 sq ft floor covered with 24-by-24-inch tiles needs 50 tiles before waste. With a 10% allowance, the order estimate becomes 55 tiles.",
    faqs: [...commonFaq("tile quantity calculator"), {question:"How much waste should I allow?",answer:"Simple straight layouts often use 8–10%; diagonal patterns, complex rooms and fragile tiles may need more."}],
  },
  {
    slug: "concrete-volume-calculator-pakistan",
    title: "Concrete Volume Calculator Pakistan",
    shortTitle: "Concrete Volume",
    description: "Estimate wet concrete volume and cement bags for a rectangular slab using editable mix assumptions.",
    icon: "🏗️", category: "Home", accent: "amber", updatedAt: "2026-09-17",
    keywords: ["concrete calculator Pakistan", "slab concrete volume", "cement bags calculator"],
    intro: "Calculate the geometric volume of a simple rectangular slab and add a practical waste allowance. The result also provides a rough cement-bag guide using an editable bags-per-cubic-metre assumption for early budgeting.",
    formula: "Concrete volume = length × width × thickness, with all dimensions converted to metres. Purchase volume includes the selected waste allowance.",
    example: "A 5 m by 4 m slab that is 0.1 m thick has a geometric volume of 2 m³. A 7% allowance increases the planning quantity to about 2.14 m³.",
    faqs: [...commonFaq("concrete volume calculator"), {question:"Can this design the concrete mix?",answer:"No. Structural strength and mix design must be specified by a qualified engineer for the actual project."}],
  },
  {
    slug: "download-time-calculator",
    title: "Internet Download Time Calculator",
    shortTitle: "Download Time",
    description: "Estimate how long a file will take to download from its gigabyte size and connection speed in Mbps.",
    icon: "⬇️", category: "Technology", accent: "blue", updatedAt: "2026-09-17",
    keywords: ["download time calculator", "GB download time Mbps", "internet speed calculator"],
    intro: "Translate an advertised internet speed into an understandable download time. The calculator correctly distinguishes gigabytes from gigabits and applies an efficiency allowance for protocol overhead and normal network variation.",
    formula: "Seconds = file size in GB × 8,000 ÷ connection speed in Mbps ÷ efficiency. Eight bits equal one byte.",
    example: "A 20 GB game contains roughly 160,000 megabits. On a 50 Mbps connection at 90% practical efficiency, it takes about 59 minutes.",
    faqs: [...commonFaq("download time calculator"), {question:"Why is my download slower than the package speed?",answer:"Wi-Fi quality, server limits, network congestion, protocol overhead and other users can reduce throughput."}],
  },
  {
    slug: "mobile-data-usage-calculator-pakistan",
    title: "Mobile Data Usage Calculator Pakistan",
    shortTitle: "Data Usage",
    description: "Estimate monthly mobile data needs from daily streaming time, hourly consumption and browsing allowance.",
    icon: "📶", category: "Technology", accent: "green", updatedAt: "2026-09-17",
    keywords: ["mobile data calculator Pakistan", "monthly internet data usage", "GB package calculator"],
    intro: "Estimate the data package needed for a typical month instead of choosing only by price. Combine daily video or social-media hours with an estimated consumption rate and a separate allowance for browsing, messaging and updates.",
    formula: "Monthly streaming data = daily hours × data per hour × 30. Total monthly data adds the browsing and app allowance.",
    example: "Streaming one hour daily at 0.7 GB per hour uses about 21 GB monthly. Adding 8 GB for browsing and app use creates a 29 GB planning estimate.",
    faqs: [...commonFaq("mobile data usage calculator"), {question:"How much data does video quality use?",answer:"Higher resolution and frame rate use more data; check the app's own usage screen for a personal hourly average."}],
  },
  {
    slug: "compound-interest-calculator-pakistan",
    title: "Compound Interest Calculator Pakistan",
    shortTitle: "Compound Interest",
    description: "Project future value from an initial amount, annual return and investment period with monthly compounding.",
    icon: "🌱", category: "Money", accent: "green", updatedAt: "2026-09-17",
    keywords: ["compound interest calculator Pakistan", "investment return calculator", "future value calculator"],
    intro: "Explore how time and reinvested returns can change the future value of a lump sum. Enter a starting amount, an assumed annual return and the number of years to view growth under monthly compounding.",
    formula: "Future value = principal × (1 + annual rate ÷ 12)^(12 × years). Growth equals future value minus the original principal.",
    example: "PKR 500,000 growing at an assumed 10% annual rate compounded monthly for five years reaches approximately PKR 823,500 before tax, fees and inflation.",
    faqs: [...commonFaq("compound interest calculator"), {question:"Is the displayed return guaranteed?",answer:"No. It is a mathematical projection from the rate you enter, not a prediction or investment recommendation."}],
  },
  {
    slug: "savings-goal-calculator-pakistan",
    title: "Savings Goal Calculator Pakistan",
    shortTitle: "Savings Goal",
    description: "Calculate the monthly saving required to reach a target amount from current savings and available months.",
    icon: "🎯", category: "Money", accent: "rose", updatedAt: "2026-09-17",
    keywords: ["savings goal calculator Pakistan", "monthly saving calculator", "how much to save per month"],
    intro: "Turn a future purchase or emergency-fund target into a simple monthly action. Enter the goal, the amount already saved and the number of months available to see the remaining gap and required monthly contribution.",
    formula: "Remaining gap = target amount − current savings. Required monthly saving = remaining gap ÷ months available.",
    example: "To reach PKR 600,000 with PKR 120,000 already saved and 24 months remaining, the required contribution is PKR 20,000 per month before any investment return.",
    faqs: [...commonFaq("savings goal calculator"), {question:"Does this include profit or investment return?",answer:"No. It uses a straightforward contribution plan so the target does not depend on uncertain returns."}],
  },
  {
    slug: "monthly-investment-calculator-pakistan", title: "Monthly Investment Calculator Pakistan", shortTitle: "Monthly Investment",
    description: "Project the future value of regular monthly investments using an editable assumed annual return and investment period.",
    icon: "📊", category: "Money", accent: "green", updatedAt: "2026-09-17",
    keywords: ["monthly investment calculator Pakistan", "SIP calculator Pakistan", "monthly saving return calculator"],
    intro: "Explore how consistent monthly contributions may accumulate over time. The calculator separates the money contributed from hypothetical growth so you can see how much of the projected balance depends on the assumed return.",
    formula: "Future value of monthly contributions = payment × (((1 + monthly rate)^months − 1) ÷ monthly rate), assuming contributions are made at the end of each month.",
    example: "Investing PKR 20,000 at the end of every month for five years with a hypothetical 10% annual return produces 60 contributions plus compounded growth.",
    faqs: [...commonFaq("monthly investment calculator"), {question:"Does this guarantee an investment return?",answer:"No. It illustrates the mathematical result of the rate entered; real returns can be higher, lower or negative."}],
  },
  {
    slug: "loan-affordability-calculator-pakistan", title: "Loan Affordability Calculator Pakistan", shortTitle: "Loan Affordability",
    description: "Estimate the loan principal supported by a chosen monthly instalment, annual rate and repayment term.",
    icon: "🏠", category: "Money", accent: "blue", updatedAt: "2026-09-17",
    keywords: ["loan affordability calculator Pakistan", "how much loan can I afford", "installment loan amount calculator"],
    intro: "Work backwards from a monthly instalment that fits your budget. Instead of starting with the amount a lender advertises, this tool estimates the principal that the chosen payment could support under a fixed reducing-balance rate.",
    formula: "Affordable principal = monthly payment × ((1 + r)^n − 1) ÷ (r × (1 + r)^n), where r is the monthly rate and n is the number of payments.",
    example: "A PKR 50,000 monthly budget at an 18% annual rate over five years is converted into 60 payments to estimate the corresponding loan amount before fees.",
    faqs: [...commonFaq("loan affordability calculator"), {question:"Will a bank approve the displayed amount?",answer:"Not necessarily. Income verification, debt obligations, credit policy, down payment and fees affect approval."}],
  },
  {
    slug: "credit-card-payoff-calculator-pakistan", title: "Credit Card Payoff Calculator Pakistan", shortTitle: "Card Payoff",
    description: "Estimate credit-card repayment time and financing cost from balance, monthly payment and annual rate.",
    icon: "💳", category: "Money", accent: "rose", updatedAt: "2026-09-17",
    keywords: ["credit card payoff calculator Pakistan", "credit card repayment calculator", "card interest calculator"],
    intro: "See how a fixed monthly payment affects the time and cost of clearing a card balance. The calculator checks whether the payment exceeds the first month's estimated interest before calculating a payoff schedule.",
    formula: "Months to repay = −ln(1 − monthly rate × balance ÷ payment) ÷ ln(1 + monthly rate), assuming no new purchases and a fixed rate.",
    example: "A PKR 200,000 balance at 30% per year with a PKR 15,000 monthly payment can be compared with a higher payment to see the reduction in months and total interest.",
    faqs: [...commonFaq("credit card payoff calculator"), {question:"What if my payment is below the monthly interest?",answer:"The balance will not reduce under these assumptions; the calculator warns when the payment is insufficient."}],
  },
  {
    slug: "emergency-fund-calculator-pakistan", title: "Emergency Fund Calculator Pakistan", shortTitle: "Emergency Fund",
    description: "Set an emergency-fund target from essential monthly expenses, desired coverage months and existing reserves.",
    icon: "🛟", category: "Money", accent: "amber", updatedAt: "2026-09-17",
    keywords: ["emergency fund calculator Pakistan", "emergency savings target", "months of expenses calculator"],
    intro: "Build a target around essential expenses rather than total income. Enter the monthly amount required for housing, food, utilities, transport and minimum obligations, then choose how many months of coverage you want.",
    formula: "Emergency-fund target = essential monthly expenses × coverage months. Funding gap = target − emergency savings already reserved.",
    example: "Essential expenses of PKR 90,000 with six months of coverage create a PKR 540,000 target. PKR 150,000 already reserved leaves a PKR 390,000 gap.",
    faqs: [...commonFaq("emergency fund calculator"), {question:"How many months should I choose?",answer:"It depends on income stability, dependants, insurance and risk; the tool lets you model different coverage periods."}],
  },
  {
    slug: "salary-increment-calculator-pakistan", title: "Salary Increment Calculator Pakistan", shortTitle: "Salary Increment",
    description: "Calculate a revised monthly salary, annual increase and percentage change from current pay and increment rate.",
    icon: "📈", category: "Money", accent: "green", updatedAt: "2026-09-17",
    keywords: ["salary increment calculator Pakistan", "salary increase percentage calculator", "new salary calculator"],
    intro: "Convert an increment percentage into monthly and annual rupee amounts. A separate recurring allowance field makes it possible to distinguish an increase to base salary from additional fixed monthly compensation.",
    formula: "New monthly salary = current salary × (1 + increment rate ÷ 100) + new recurring allowance.",
    example: "A PKR 100,000 monthly salary with a 12% increment becomes PKR 112,000 before adding any new fixed allowance, an annual increase of PKR 144,000.",
    faqs: [...commonFaq("salary increment calculator"), {question:"Is this the same as take-home salary?",answer:"No. Tax, provident fund, benefits and deductions can change the amount received."}],
  },
  {
    slug: "business-break-even-calculator-pakistan", title: "Business Break-Even Calculator Pakistan", shortTitle: "Break-Even",
    description: "Calculate break-even sales units and revenue from fixed costs, selling price and variable cost per unit.",
    icon: "⚖️", category: "Business", accent: "violet", updatedAt: "2026-09-17",
    keywords: ["break even calculator Pakistan", "break even units calculator", "business break even revenue"],
    intro: "Estimate how many units must be sold before contribution covers fixed operating costs. The result also shows contribution per unit and break-even revenue, helping evaluate whether a price and cost structure is practical.",
    formula: "Contribution per unit = selling price − variable cost. Break-even units = fixed costs ÷ contribution per unit.",
    example: "With PKR 300,000 in fixed costs, a PKR 2,000 selling price and PKR 1,200 variable cost, each sale contributes PKR 800 and about 375 units cover fixed costs.",
    faqs: [...commonFaq("business break-even calculator"), {question:"Does breaking even mean the business has cash available?",answer:"Not always. Payment timing, inventory purchases, debt and taxes can create different cash-flow results."}],
  },
  {
    slug: "solar-battery-size-calculator-pakistan", title: "Solar Battery Size Calculator Pakistan", shortTitle: "Solar Battery Size",
    description: "Estimate battery-bank amp-hours and nominal energy for a backup load, duration and system voltage.",
    icon: "🔋", category: "Solar", accent: "green", updatedAt: "2026-09-17",
    keywords: ["solar battery size calculator Pakistan", "battery Ah calculator", "backup battery bank sizing"],
    intro: "Size a starting battery bank from the appliances that must remain on and the desired backup duration. The calculation includes a conservative usable-energy allowance before converting required watt-hours into amp-hours.",
    formula: "Required nominal watt-hours = load watts × backup hours ÷ usable-energy factor. Required amp-hours = nominal watt-hours ÷ system voltage.",
    example: "A 600 W essential load for four hours requires 2,400 usable Wh. At 80% usable energy on a 24 V bank, the estimate is about 125 Ah.",
    faqs: [...commonFaq("solar battery size calculator"), {question:"Can lead-acid and lithium use the same allowance?",answer:"No. Safe depth of discharge and efficiency differ, so confirm the factor with the battery manufacturer."}],
  },
  {
    slug: "solar-panel-output-calculator-pakistan", title: "Solar Panel Output Calculator Pakistan", shortTitle: "Solar Output",
    description: "Estimate daily and monthly solar generation from system capacity, peak-sun-hours and system efficiency.",
    icon: "🌤️", category: "Solar", accent: "amber", updatedAt: "2026-09-17",
    keywords: ["solar panel output calculator Pakistan", "solar units per day", "solar generation calculator"],
    intro: "Translate installed solar capacity into a planning estimate of energy production. Peak-sun-hours and whole-system efficiency are editable so the result can reflect location, season, temperature, dust and conversion losses.",
    formula: "Daily generation = system kW × peak-sun-hours × system efficiency. Monthly generation uses 30 days.",
    example: "A 5 kW system receiving 5.2 peak-sun-hours with 80% overall efficiency produces an estimated 20.8 units daily or 624 units in 30 days.",
    faqs: [...commonFaq("solar panel output calculator"), {question:"Why do actual daily units change?",answer:"Cloud, heat, shade, dust, inverter clipping, orientation and seasonal sunlight change production."}],
  },
  {
    slug: "solar-payback-calculator-pakistan", title: "Solar Payback Calculator Pakistan", shortTitle: "Solar Payback",
    description: "Estimate simple solar payback time from installed cost, monthly savings and annual maintenance allowance.",
    icon: "☀️", category: "Solar", accent: "green", updatedAt: "2026-09-17",
    keywords: ["solar payback calculator Pakistan", "solar ROI calculator", "solar recovery period Pakistan"],
    intro: "Estimate how long energy savings may take to recover the upfront system cost. This simple-payback view subtracts a yearly maintenance allowance from annual savings and clearly separates recovery time from investment return.",
    formula: "Net annual saving = monthly bill saving × 12 − annual maintenance. Simple payback years = installed cost ÷ net annual saving.",
    example: "A PKR 1,200,000 system saving PKR 30,000 monthly with PKR 20,000 yearly maintenance produces PKR 340,000 net annual saving and roughly 3.5-year simple payback.",
    faqs: [...commonFaq("solar payback calculator"), {question:"Does simple payback include financing or equipment replacement?",answer:"No. Financing, tariff changes, degradation, inverter or battery replacement and resale value require a fuller cash-flow model."}],
  },
  {
    slug: "ac-electricity-cost-calculator-pakistan", title: "AC Electricity Cost Calculator Pakistan", shortTitle: "AC Running Cost",
    description: "Estimate monthly AC units and expense using rated input power, daily runtime and effective electricity rate.",
    icon: "❄️", category: "Energy", accent: "blue", updatedAt: "2026-09-17",
    keywords: ["AC electricity cost calculator Pakistan", "AC units per month", "air conditioner bill calculator"],
    intro: "Estimate the electricity impact of air-conditioner use with a practical cycling allowance. The result reports monthly units and expense while explaining why inverter AC consumption varies with temperature and room conditions.",
    formula: "Monthly units = rated input kW × daily runtime × 30 × average-load factor. This estimate uses a 70% average-load factor.",
    example: "A 1,500 W AC used eight hours daily at a 70% average load consumes about 252 units monthly. At PKR 55 per unit, the energy portion is about PKR 13,860.",
    faqs: [...commonFaq("AC electricity cost calculator"), {question:"Why use a load factor?",answer:"An inverter AC normally reduces power after approaching the set temperature instead of drawing full rated power continuously."}],
  },
  {
    slug: "battery-charging-time-calculator-pakistan", title: "Battery Charging Time Calculator Pakistan", shortTitle: "Charging Time",
    description: "Estimate battery charging hours from amp-hour capacity, charger current and an adjustable loss allowance.",
    icon: "⚡", category: "Energy", accent: "amber", updatedAt: "2026-09-17",
    keywords: ["battery charging time calculator Pakistan", "battery charge hours calculator", "Ah charger time"],
    intro: "Estimate how long a substantially discharged battery may take to charge at a known current. The calculation adds an adjustable allowance for conversion losses and the slower finishing stage used by many chargers.",
    formula: "Estimated charging hours = battery amp-hours ÷ charger amps × (1 + loss allowance ÷ 100).",
    example: "A 150 Ah battery charged at 20 A has a base time of 7.5 hours. With a 20% allowance, the planning estimate becomes about nine hours.",
    faqs: [...commonFaq("battery charging time calculator"), {question:"Will the charger supply its rated current throughout?",answer:"Often not. Current can taper near full charge, and battery-management systems may limit charging."}],
  },
  {
    slug: "watts-amps-volts-calculator", title: "Watts, Amps and Volts Calculator", shortTitle: "Watts & Amps",
    description: "Calculate electrical current from watts and volts with an efficiency or power-factor allowance.",
    icon: "〽️", category: "Energy", accent: "violet", updatedAt: "2026-09-17",
    keywords: ["watts amps volts calculator", "watts to amps calculator Pakistan", "electrical current calculator"],
    intro: "Convert a known power load and voltage into estimated current for basic planning. An efficiency or power-factor field accounts for loads where apparent current is higher than a simple watts-divided-by-volts calculation.",
    formula: "Estimated current in amps = watts ÷ (volts × efficiency factor). For ideal DC loads, the factor is 1.0.",
    example: "A 1,000 W load at 230 V with a 0.9 factor draws an estimated 4.83 A, compared with 4.35 A under ideal unity conditions.",
    faqs: [...commonFaq("watts, amps and volts calculator"), {question:"Can this determine cable or breaker size?",answer:"No. Cable and protection design also requires installation method, temperature, distance, surge and applicable electrical standards."}],
  },
];

const editorial: Record<string, Pick<Tool, "howTo" | "considerations" | "limitations">> = {
  "electricity-bill-calculator-pakistan": {howTo:["Copy the units consumed from your meter or latest bill.","Enter an average energy rate and the additional-charge percentage shown on your bill.","Review energy charges separately from the estimated taxes and surcharges."],considerations:[{title:"Tariff category",text:"Residential, commercial and protected-consumer tariffs can be calculated differently."},{title:"Billing adjustments",text:"Fuel and quarterly adjustments may change from one billing period to another."},{title:"Meter period",text:"A longer or shorter meter-reading cycle changes total units even if daily use is stable."}],limitations:"This simplified planner does not reproduce every DISCO slab, protected-status rule, minimum charge or time-varying government adjustment."},
  "solar-system-calculator-pakistan": {howTo:["Use the average of several recent electricity bills instead of one unusual month.","Enter realistic peak-sun-hours for your location and the panel wattage you plan to buy.","Use the capacity and panel count as a starting point for a professional site survey."],considerations:[{title:"Shade and orientation",text:"Trees, buildings, roof direction and tilt directly affect daily production."},{title:"Seasonal demand",text:"Summer cooling loads may require a larger system than the annual average suggests."},{title:"System losses",text:"Temperature, dust, wiring and inverter losses reduce output from nameplate capacity."}],limitations:"The estimate does not model an hourly load profile, roof geometry, export limits, battery storage or site-specific solar irradiance."},
  "salary-tax-calculator-pakistan": {howTo:["Enter gross monthly salary and any regularly taxable allowances.","Add other monthly deductions only when you want them reflected in take-home pay.","Compare the estimate with the tax-year rules and payroll calculation used by your employer."],considerations:[{title:"Tax year",text:"Federal salary slabs can change with each Finance Act."},{title:"Other income",text:"Business, property or investment income may alter an individual's final liability."},{title:"Credits and exemptions",text:"Eligible credits, exemptions and special treatment are outside this quick estimate."}],limitations:"This is a salary-only planning estimate and not a tax return, legal interpretation or confirmation of current FBR withholding."},
  "pta-tax-calculator-pakistan": {howTo:["Find the device's declared or assessed USD value rather than guessing from a local resale listing.","Enter the exchange rate and an estimated duty rate for planning.","Use DIRBS to obtain the official PSID amount for the exact IMEI before paying."],considerations:[{title:"Customs valuation",text:"The assessed value may differ from the amount shown on a shop receipt."},{title:"Registration route",text:"Passport and CNIC treatment or eligibility can differ under official rules."},{title:"Device identity",text:"Model, storage variant and IMEI status influence the official assessment."}],limitations:"The calculator cannot query DIRBS, validate an IMEI or determine an official tax band; only the government assessment confirms payment."},
  "ev-vs-petrol-calculator-pakistan": {howTo:["Estimate your normal daily distance rather than using a single long trip.","Enter real-world petrol mileage and the fuel price you currently pay.","Compare monthly energy expense, then account separately for purchase price and battery replacement."],considerations:[{title:"Driving conditions",text:"Congestion, speed, load and terrain change petrol and electric efficiency."},{title:"Charging source",text:"Grid tariff, off-peak charging and solar power create different electricity costs."},{title:"Ownership costs",text:"Maintenance, financing, insurance and resale value may outweigh energy savings."}],limitations:"The quick comparison uses a fixed EV energy assumption and does not model a specific vehicle, charger losses, battery ageing or financing."},
  "daraz-profit-calculator-pakistan": {howTo:["Enter the actual selling price after seller-funded discounts.","Use landed product cost, including packaging or inbound freight when relevant.","Enter the category commission and subtract campaign, shipping and advertising charges before deciding margin."],considerations:[{title:"Category commission",text:"Marketplace commission depends on the product category and seller terms."},{title:"Returns and damage",text:"A return allowance can materially reduce profit on products with high return rates."},{title:"Advertising",text:"Campaign spend should be attributed per order instead of ignored as a general expense."}],limitations:"The result does not retrieve a seller account, live fee table, withholding tax record, return cost or settlement statement."},
  "percentage-calculator": {howTo:["Enter the percentage you want to apply.","Enter the base value that the percentage belongs to.","Read the calculated portion, decimal form and remaining value."],considerations:[{title:"Correct base",text:"A percentage is meaningful only when the base value is clearly identified."},{title:"Percentage points",text:"A change from 20% to 25% is five percentage points but a 25% relative increase."},{title:"Rounding",text:"Currency and measured quantities may need a defined rounding rule."}],limitations:"This mode calculates a percentage of a value; more complex compound changes should be handled one step at a time."},
  "cgpa-percentage-calculator-pakistan": {howTo:["Enter the CGPA printed on your transcript.","Find the official multiplier or conversion rule issued by the receiving institution.","Treat the result as an estimate unless the institution explicitly accepts that method."],considerations:[{title:"Scale",text:"A 4.0, 5.0 or 10.0 CGPA scale cannot be compared without the correct rule."},{title:"Institution policy",text:"Some universities use tables or offsets instead of a simple multiplier."},{title:"Application purpose",text:"Admissions bodies may request the original CGPA rather than a self-converted percentage."}],limitations:"A multiplier cannot represent every institutional formula, transcript policy, course weighting method or credential evaluation."},
  "loan-emi-calculator-pakistan": {howTo:["Enter the amount you will actually borrow after any down payment.","Use the annual reducing-balance rate and complete repayment term.","Compare the instalment and total financing cost with the lender's official schedule."],considerations:[{title:"Rate type",text:"A flat advertised rate is not equivalent to a reducing-balance annual rate."},{title:"Fees and insurance",text:"Processing charges, documentation, takaful and insurance can raise total cost."},{title:"Variable benchmark",text:"A floating rate can change future instalments or the repayment term."}],limitations:"The formula assumes equal monthly payments and a constant rate; it excludes fees, late charges, early settlement and lender-specific rounding."},
  "fuel-cost-calculator-pakistan": {howTo:["Enter the full driving distance, including the return journey where applicable.","Use your vehicle's recent real-world kilometres per litre.","Enter the current pump price and allow extra budget for congestion or detours."],considerations:[{title:"Traffic",text:"Idling and stop-start driving usually reduce fuel economy."},{title:"Vehicle condition",text:"Tyre pressure, servicing, load and air conditioning influence consumption."},{title:"Route profile",text:"Motorway, city and mountain routes can produce very different mileage."}],limitations:"The estimate assumes one average mileage and price; it cannot predict traffic, route changes, fuel-quality effects or refuelling-price changes."},
  "battery-backup-calculator-pakistan": {howTo:["Add the running watts of every appliance that will operate during backup.","Enter the battery bank's rated amp-hours and total voltage.","Use the estimated time conservatively and avoid discharging batteries beyond manufacturer guidance."],considerations:[{title:"Battery chemistry",text:"Lead-acid and lithium batteries have different safe depth-of-discharge limits."},{title:"Battery health",text:"Age, heat and repeated deep discharge reduce available capacity."},{title:"Conversion losses",text:"Inverters and wiring consume energy before it reaches appliances."}],limitations:"Runtime is an energy estimate, not a battery guarantee; it omits chemistry-specific discharge curves, surge loads and inverter cut-off behaviour."},
  "inverter-load-calculator-pakistan": {howTo:["Add the running watts from appliance labels or reliable measurements.","Choose safety headroom and use the inverter manufacturer's power-factor guidance.","Check that both continuous and surge ratings support the intended appliances."],considerations:[{title:"Startup surge",text:"Motors, pumps and compressors can briefly draw much more than running watts."},{title:"Power factor",text:"Some loads require more volt-amperes than their watt figure suggests."},{title:"Future expansion",text:"Planned appliances should be included before choosing the inverter size."}],limitations:"This sizing aid does not replace appliance-by-appliance surge measurement, cable sizing, protection design or an electrician's assessment."},
  "profit-margin-calculator": {howTo:["Enter net sales revenue after customer discounts and refunds.","Enter all direct costs attributable to those sales.","Compare margin with markup and add operating expenses before judging overall profitability."],considerations:[{title:"Direct costs",text:"Product, packaging, transaction and fulfilment costs may all belong in cost of sales."},{title:"Returns",text:"Refunds and damaged inventory reduce realised margin."},{title:"Overheads",text:"Gross margin does not include salaries, rent, software, tax or financing."}],limitations:"The result is a gross unit or period comparison and is not a complete profit-and-loss statement or tax calculation."},
  "discount-calculator-pakistan": {howTo:["Enter the original listed price before the promotion.","Enter the advertised discount percentage.","Add any tax or service percentage that is charged after the discount."],considerations:[{title:"Stacked offers",text:"Two sequential discounts do not equal their percentages simply added together."},{title:"Price basis",text:"Confirm whether the offer applies to the full item price or only selected components."},{title:"Extra charges",text:"Delivery, service fees and taxes can reduce the effective saving."}],limitations:"The calculator assumes one discount followed by one optional percentage charge and does not interpret store-specific offer conditions."},
  "attendance-percentage-calculator": {howTo:["Enter classes attended and the total classes held so far.","Set the attendance target required by your institution.","Use the required-classes result only if you plan to attend every upcoming class."],considerations:[{title:"Institution records",text:"The official portal may include corrections, excused absences or late updates."},{title:"Future absences",text:"Missing another class changes the number needed to reach the target."},{title:"Subject-level rules",text:"Attendance may be assessed separately for each course, lab or semester."}],limitations:"The projection assumes every future class is attended and does not account for cancelled classes, exemptions or institutional rounding policies."},
  "marks-percentage-calculator-pakistan": {howTo:["Enter the obtained score exactly as shown on the result.","Enter the maximum possible score for the same subjects or assessment.","Set the relevant passing threshold and compare it with the calculated percentage."],considerations:[{title:"Subject weighting",text:"Some final results weight subjects or components instead of simply adding marks."},{title:"Practical marks",text:"Labs, internal assessment and practical examinations may be counted separately."},{title:"Grade boundaries",text:"The same percentage can receive different grades across boards and institutions."}],limitations:"This tool performs a direct marks-to-percentage conversion and does not reproduce a board's grading, moderation or subject-weighting rules."},
  "freelance-hourly-rate-calculator-pakistan": {howTo:["Set a realistic monthly personal income target.","Add recurring business costs such as software, internet and equipment allowance.","Estimate hours you can actually invoice, then review the required rate before quoting."],considerations:[{title:"Non-billable work",text:"Proposals, administration and learning reduce the hours available for client billing."},{title:"Taxes and currency",text:"Tax, payment fees and exchange-rate movement can reduce take-home income."},{title:"Utilisation",text:"Quiet months require a buffer when setting a sustainable average rate."}],limitations:"The calculation does not set a market price or include taxes, platform commissions, unpaid revisions, bad debt or currency conversion."},
  "paint-quantity-calculator-pakistan": {howTo:["Measure net paintable wall or ceiling area in square feet.","Choose the required number of coats and use the coverage printed on the product tin.","Round up for the available container sizes and keep a small touch-up allowance."],considerations:[{title:"Surface condition",text:"Porous, rough or newly plastered surfaces can absorb more paint."},{title:"Colour change",text:"Covering a dark colour with a light one may require extra coats or primer."},{title:"Application method",text:"Spraying, rolling and brushing can have different waste rates."}],limitations:"The estimate cannot inspect surface porosity, application technique, paint thickness, openings or manufacturer-specific coverage conditions."},
  "appliance-electricity-cost-calculator-pakistan": {howTo:["Find the appliance's rated watts or measure average power with an energy meter.","Estimate typical operating hours per day, accounting for appliances that cycle on and off.","Enter your effective per-unit rate and compare the result with total bill usage."],considerations:[{title:"Duty cycle",text:"Refrigerators and inverter ACs do not draw rated power continuously."},{title:"Tariff structure",text:"The effective cost per unit can rise across slabs and additional charges."},{title:"Standby use",text:"Some electronics consume a smaller amount even when apparently switched off."}],limitations:"This estimate uses constant average watts and one effective unit rate; it does not reproduce slab billing, voltage variation or automatic cycling."},
  "generator-fuel-cost-calculator-pakistan": {howTo:["Use the fuel-consumption figure at the load you actually expect, not only the maximum rating.","Enter daily generator runtime and the current price for the correct fuel type.","Add maintenance, oil, filters and repairs separately when budgeting total ownership cost."],considerations:[{title:"Electrical load",text:"Fuel consumption changes significantly between light, normal and full load."},{title:"Engine condition",text:"Poor servicing, clogged filters and worn components can increase consumption."},{title:"Fuel price",text:"Petrol and diesel prices can change, so refresh the input before decisions."}],limitations:"The calculator assumes a constant hourly burn rate and excludes warm-up, variable loading, maintenance, depreciation and generator efficiency curves."},
  "ac-tonnage-calculator-pakistan": {howTo:["Measure the room's internal floor area and note the ceiling height.","Choose a heat-load factor suited to a warm climate and normal residential use.","Discuss sun exposure, windows, insulation and occupancy with a qualified installer before purchase."],considerations:[{title:"Solar heat",text:"West-facing windows and an exposed roof can add substantial afternoon heat."},{title:"People and equipment",text:"Occupants, computers, cooking and lighting add heat to the room."},{title:"Insulation and leakage",text:"Poor roof insulation and gaps around doors increase the required cooling capacity."}],limitations:"Area-based sizing is only a first estimate; it cannot replace a room-by-room heat-load calculation or confirm electrical and installation requirements."},
  "water-tank-volume-calculator-pakistan": {howTo:["Measure the internal length, width and usable water depth in feet.","Calculate capacity and allow space below the overflow instead of filling to the absolute top.","Compare usable litres with a realistic daily household consumption figure."],considerations:[{title:"Freeboard",text:"The water level normally remains below the tank's full internal height."},{title:"Tank shape",text:"This mode is for rectangular tanks; cylinders require a different volume formula."},{title:"Usable reserve",text:"Sediment, outlet height and pump protection can leave some water unusable."}],limitations:"The result assumes a perfect rectangular interior and does not assess structural strength, leakage, plumbing capacity or water-quality requirements."},
  "tile-quantity-calculator-pakistan": {howTo:["Measure the net floor or wall area and keep all dimensions in consistent units.","Enter the length and width of one tile, including the actual nominal size used for ordering.","Apply a waste allowance appropriate to the room shape and laying pattern, then round up to full boxes."],considerations:[{title:"Layout pattern",text:"Diagonal, herringbone and centred layouts usually create more offcuts."},{title:"Batch matching",text:"Buying all boxes together reduces the risk of later shade or calibre differences."},{title:"Breakage reserve",text:"Keeping a few matching tiles helps with future repairs."}],limitations:"The estimate does not create a cutting layout, subtract grout joints precisely or account for box quantities unless verified against the product packaging."},
  "concrete-volume-calculator-pakistan": {howTo:["Convert slab length, width and thickness to metres before calculating.","Add an allowance for uneven excavation, spillage and ordering tolerance.","Use the volume for budgeting only and obtain the structural mix specification from an engineer."],considerations:[{title:"Actual thickness",text:"Uneven ground or formwork can increase volume beyond the drawing dimensions."},{title:"Dry materials",text:"Wet concrete volume is not the same as simply adding dry ingredient volumes."},{title:"Structural design",text:"Cement content, aggregate grading and reinforcement depend on engineering requirements."}],limitations:"This is a geometric material estimator and cannot design structural concrete, verify strength, specify reinforcement or replace site measurement."},
  "download-time-calculator": {howTo:["Enter the file size shown by the store or download page in gigabytes.","Enter the connection speed in megabits per second, not megabytes per second.","Use the efficiency setting to allow for Wi-Fi, protocol and network overhead."],considerations:[{title:"Server speed",text:"The source server may send data more slowly than your internet package allows."},{title:"Shared connection",text:"Streaming and downloads on other devices divide the available bandwidth."},{title:"Wi-Fi signal",text:"Distance, interference and older routers can reduce real throughput."}],limitations:"The result assumes a steady average speed and cannot predict pauses, server throttling, mobile signal changes or installation time after download."},
  "mobile-data-usage-calculator-pakistan": {howTo:["Estimate daily hours spent on video, reels or other data-heavy activity.","Use the app or phone settings to find an approximate gigabytes-per-hour rate.","Add a separate monthly allowance for browsing, messaging, backups and software updates."],considerations:[{title:"Video quality",text:"Resolution, frame rate and compression strongly affect data used per hour."},{title:"Background activity",text:"Cloud backups, auto-updates and social apps may transfer data without active viewing."},{title:"Hotspot users",text:"Laptops and connected family devices can consume a package much faster."}],limitations:"The estimate uses average consumption and cannot measure a device, predict adaptive video quality or include unreported background transfers."},
  "compound-interest-calculator-pakistan": {howTo:["Enter only the amount invested at the beginning of the period.","Choose a hypothetical annual return and the number of complete years.","Compare nominal growth with inflation, fees and tax before judging purchasing-power improvement."],considerations:[{title:"Return variability",text:"Real investments rarely deliver the same return every month or year."},{title:"Inflation",text:"A larger future balance may buy less if prices rise over the same period."},{title:"Fees and tax",text:"Management fees, taxes and transaction costs reduce net compound growth."}],limitations:"The projection assumes a constant rate compounded monthly and excludes additional contributions, withdrawals, tax, fees, inflation and investment risk."},
  "savings-goal-calculator-pakistan": {howTo:["Define the target amount and deadline for the purchase or emergency fund.","Subtract only savings genuinely reserved for that goal.","Set an automatic monthly contribution and revisit the plan when income or costs change."],considerations:[{title:"Price changes",text:"The target may need to rise if the planned purchase becomes more expensive."},{title:"Unexpected withdrawals",text:"Using goal savings for another expense increases future monthly requirements."},{title:"Income timing",text:"Weekly or irregular earners may find smaller contribution intervals easier to maintain."}],limitations:"This simple plan assumes equal monthly saving, no withdrawals and no return, inflation, tax or account charges."},
  "monthly-investment-calculator-pakistan": {howTo:["Enter the contribution you can make consistently at the end of each month.","Use a cautious hypothetical annual return rather than a best historical year.","Compare total contributions with projected growth and test lower-return scenarios."],considerations:[{title:"Market variability",text:"Returns can change sharply and may be negative during parts of the investment period."},{title:"Contribution timing",text:"Beginning-of-month contributions produce a slightly different result."},{title:"Costs and inflation",text:"Fees, tax and rising prices reduce real purchasing-power growth."}],limitations:"The projection assumes a constant return, monthly compounding and uninterrupted end-of-month contributions; it is not an investment forecast."},
  "loan-affordability-calculator-pakistan": {howTo:["Choose a monthly payment that leaves room for essential expenses and emergencies.","Enter the lender's reducing-balance annual rate and complete term.","Treat the result as a ceiling for comparison, then review fees and eligibility with the lender."],considerations:[{title:"Existing debt",text:"Other instalments and card balances reduce practical affordability."},{title:"Rate changes",text:"A floating benchmark can increase future payments or extend the term."},{title:"Upfront costs",text:"Down payment, processing, insurance and registration are outside the principal estimate."}],limitations:"The result assumes a fixed rate and equal payments and cannot predict lender approval, fees, income tests or changing rates."},
  "credit-card-payoff-calculator-pakistan": {howTo:["Enter the statement balance and annual rate shown by the issuer.","Choose a fixed monthly payment above the estimated monthly interest.","Compare a larger payment to see how repayment time and total interest change."],considerations:[{title:"New purchases",text:"Continuing to use the card increases the balance and delays payoff."},{title:"Fees and taxes",text:"Late fees, annual charges, cash-advance fees and taxes add to the schedule."},{title:"Daily calculation",text:"Issuers may calculate finance charges daily rather than with this monthly model."}],limitations:"This is a fixed-rate, fixed-payment estimate with no new transactions, fees, missed payments or issuer-specific daily balance method."},
  "emergency-fund-calculator-pakistan": {howTo:["Total only expenses that must continue during an income interruption.","Select a coverage period suited to job stability and household responsibilities.","Subtract liquid savings reserved exclusively for emergencies."],considerations:[{title:"Income stability",text:"Irregular or single-income households may prefer a larger buffer."},{title:"Dependants",text:"Medical, school and family obligations can increase essential monthly costs."},{title:"Accessibility",text:"Emergency money should generally be accessible without large penalties or market risk."}],limitations:"The tool sets a simple expense-based target and does not assess insurance, job security, medical needs, inflation or personal risk tolerance."},
  "salary-increment-calculator-pakistan": {howTo:["Enter current gross monthly base salary.","Apply the confirmed increment percentage and any new recurring allowance separately.","Compare annual gross change, then request a payroll estimate for deductions and take-home pay."],considerations:[{title:"Tax withholding",text:"Higher taxable income may change monthly withholding and net benefit."},{title:"Base versus allowance",text:"Allowances may receive different treatment in benefits or future increments."},{title:"Inflation",text:"A nominal increase does not always improve real purchasing power."}],limitations:"The result shows gross arithmetic only and excludes tax slabs, deductions, bonuses, arrears, provident fund and employer benefit rules."},
  "business-break-even-calculator-pakistan": {howTo:["Separate costs that remain fixed from costs incurred for each unit sold.","Use the realised selling price after normal discounts.","Calculate the unit target and test how price or cost changes affect it."],considerations:[{title:"Mixed products",text:"Businesses with several products need a weighted average contribution margin."},{title:"Capacity",text:"A mathematical target may exceed production or market demand."},{title:"Cash timing",text:"Credit sales and inventory purchases can create cash pressure before accounting break-even."}],limitations:"The model assumes one product, constant price and variable cost, and fixed costs that do not change across the calculated volume."},
  "solar-battery-size-calculator-pakistan": {howTo:["Add the running watts of appliances that must operate together.","Choose realistic backup hours and the voltage of the planned battery bank.","Confirm usable depth of discharge, current limits and compatible capacity with the manufacturer or installer."],considerations:[{title:"Battery chemistry",text:"Lithium and lead-acid systems allow different usable proportions and charge cycles."},{title:"Surge demand",text:"Motors and compressors may require inverter power beyond the running load."},{title:"Age and temperature",text:"Available capacity can fall with battery age, heat and repeated deep discharge."}],limitations:"This energy estimate uses a fixed 80% usable allowance and does not design battery strings, protection, cables, charging or inverter surge capacity."},
  "solar-panel-output-calculator-pakistan": {howTo:["Enter the array's total rated DC capacity in kilowatts.","Use representative peak-sun-hours for the location and season.","Set a whole-system efficiency that includes temperature, dust, wiring and inverter losses."],considerations:[{title:"Orientation and shade",text:"Roof direction, tilt and partial shade change production throughout the day."},{title:"Weather and season",text:"Cloud cover and winter sun reduce output relative to clear summer periods."},{title:"Equipment limits",text:"Inverter clipping and grid interruptions can prevent available solar energy from being used."}],limitations:"This daily-average model does not use hourly irradiance, roof geometry, shade mapping, panel degradation, clipping or grid-export restrictions."},
  "solar-payback-calculator-pakistan": {howTo:["Enter the complete installed cost after any included equipment and labour.","Estimate monthly savings from actual consumption and a conservative production scenario.","Add recurring maintenance and compare several tariff and degradation assumptions."],considerations:[{title:"Tariff changes",text:"Future electricity pricing can shorten or extend recovery time."},{title:"Equipment replacement",text:"Inverter or battery replacement can materially increase lifecycle cost."},{title:"Self-consumption",text:"Export compensation and the portion used on-site affect realised savings."}],limitations:"Simple payback ignores financing, inflation, discounted cash flow, tariff changes, degradation, taxes and major component replacement."},
  "ac-electricity-cost-calculator-pakistan": {howTo:["Use rated electrical input watts rather than cooling capacity in BTU or tons.","Estimate daily runtime during a representative month.","Enter an effective unit rate and compare with measured AC consumption when available."],considerations:[{title:"Temperature setting",text:"Lower set points and extreme outdoor heat increase compressor workload."},{title:"Room heat gain",text:"Sun, roof exposure, windows, occupants and poor insulation increase consumption."},{title:"Maintenance",text:"Dirty filters, low refrigerant and restricted airflow reduce efficiency."}],limitations:"The estimate applies a fixed 70% average-load factor and cannot model a specific inverter control, climate, room or electricity slab bill."},
  "battery-charging-time-calculator-pakistan": {howTo:["Enter the battery's rated amp-hour capacity and charger's effective current.","Set a loss and finishing-stage allowance appropriate to the battery and charger.","Confirm maximum safe charging current and charging profile in the manufacturer documentation."],considerations:[{title:"State of charge",text:"A partially discharged battery needs less energy than an empty-capacity assumption."},{title:"Current taper",text:"Many chargers reduce current near full charge, extending the final stage."},{title:"Temperature control",text:"Battery management may reduce current when cells are hot or cold."}],limitations:"The calculator assumes a substantially discharged battery and average charger current; it cannot model charge curves, cell balancing or safety limits."},
  "watts-amps-volts-calculator": {howTo:["Enter the real power in watts and operating voltage.","Use 1.0 for an ideal resistive or DC calculation, or the verified factor for the equipment.","Use the estimated current only for early planning and obtain proper electrical design for wiring."],considerations:[{title:"AC power factor",text:"Motors and electronic supplies may draw more current than real watts alone suggest."},{title:"Startup current",text:"Compressors and motors can briefly draw several times normal current."},{title:"Voltage variation",text:"Actual supply voltage affects current and equipment behaviour."}],limitations:"This simplified single-phase calculation cannot size cables or breakers and does not cover three-phase systems, harmonics, surges or code requirements."},
};

export const tools: Tool[] = baseTools.map((tool) => ({ ...tool, ...editorial[tool.slug] }));

export const categories = [...new Set(tools.map((tool) => tool.category))];
export const getTool = (slug: string) => tools.find((tool) => tool.slug === slug);
