import type { Guide, GuideSource } from "@/lib/guides";

const publishedAt = "2026-09-18";
const reviewedAt = "2026-09-18";
const editorial: GuideSource = { name:"SolvePilot editorial and calculation policy", url:"/editorial-policy/", note:"How we select sources, test calculations, disclose limitations and correct errors." };
const nepra: GuideSource = { name:"National Electric Power Regulatory Authority", url:"https://www.nepra.org.pk/", note:"Official tariff determinations, notifications, regulations and consumer material." };
const fbr: GuideSource = { name:"Federal Board of Revenue", url:"https://www.fbr.gov.pk/", note:"Official tax laws, rate cards, ATL information, Iris access and public guidance." };
const pta: GuideSource = { name:"Pakistan Telecommunication Authority", url:"https://www.pta.gov.pk/", note:"Official telecom consumer information and device-compliance notices." };

export const trafficGuides: Guide[] = [
  {
    slug:"lesco-kelectric-fesco-iesco-bill-slabs-compared",
    title:"LESCO, K-Electric, FESCO and IESCO Bill Slabs Compared",
    description:"Compare what is common—and what must be checked separately—when reading residential electricity tariffs across major Pakistan providers.",
    category:"Electricity",icon:"⚡",publishedAt,reviewedAt,readingMinutes:12,
    quickAnswer:"Residential bills from LESCO, FESCO and IESCO generally follow federally notified tariff structures for distribution companies, while K-Electric has its own determinations and schedules. The provider name alone does not identify your rate: sanctioned load, protected status, consumption history, time-of-use metering, billing month and later adjustments all matter.",
    takeaways:["Compare the same consumer category and billing month—not just the provider logo.","Separate base energy charges from taxes, fuel adjustments, quarterly adjustments and arrears.","Use the official tariff schedule and your actual bill as the final reference."],
    sections:[
      {heading:"Begin with the connection, not the company",paragraphs:["A useful comparison starts with the consumer category printed on the bill. Two homes served by the same company can face different treatment because one has protected status, a different sanctioned load, a time-of-use meter or a billing history that places it in another group. Comparing the final rupees per unit without matching these details produces a misleading result.","LESCO, FESCO and IESCO are distribution companies operating in different service territories. K-Electric is an integrated utility serving Karachi and nearby areas. Their bills look broadly familiar because each must communicate units, tariff components and government charges, but the applicable notifications and adjustment periods may not be identical."]},
      {heading:"What is normally comparable",paragraphs:["The core measurement is kilowatt-hours consumed during the billing period. A bill then applies the relevant residential tariff treatment and adds other items. This common structure lets you compare energy use, but it does not mean every displayed charge will be the same in Lahore, Faisalabad, Islamabad and Karachi during the same calendar month.","For a fair comparison, record units, billing days, meter type, sanctioned load, category code, protected or non-protected status, previous balance and every adjustment line. If any of those fields differ, explain the difference before attributing the result to the provider."],bullets:["Units and meter readings","Billing period and days","Category and load","Protected status or time-of-use status","Taxes, adjustments, arrears and credits"]},
      {heading:"Why the effective rate changes",paragraphs:["Effective rate means the total payable amount divided by units. It rises when fixed charges or one-off adjustments are spread over low consumption, and it can jump when usage or history changes the tariff treatment. It is therefore a description of one bill, not a reusable tariff.","Fuel-cost and quarterly adjustments can refer to earlier periods even though they appear on the current invoice. Taxes can depend on government rules and consumer details. Arrears, late-payment surcharge, instalments or a credit from a corrected reading belong to the account history rather than the current month's electricity consumption."]},
      {heading:"How to read each provider's bill",paragraphs:["Find the category, current and previous readings, units, billing month and due date first. Then copy the energy charge and each additional line into separate rows. Do not combine an adjustment with the base tariff merely because both are calculated per unit.","Use the provider's own bill portal or helpline to verify a duplicate bill or correction. For tariff research, use NEPRA determinations and notifications. A social-media image of a slab table may be outdated, may omit a category, or may describe the calculation incorrectly." ]},
      {heading:"A sensible household comparison",paragraphs:["If you are comparing a move between cities, start with the same monthly usage profile rather than last month's payable totals. Model summer and winter separately, include the likely meter category and keep non-energy charges editable. This produces a planning range rather than a false promise.","If you are investigating an unexpectedly high bill, reproduce the account's own bill before comparing providers. Check reading type, billing days, accumulated units, previous balance and status. A meter-reading or history issue cannot be diagnosed from a national slab chart alone."]},
      {heading:"When to ask for correction",paragraphs:["Contact the relevant provider when the meter reading, category, load, account history or payment record appears wrong. Keep photographs of the meter, paid receipts and copies of bills. Use the provider's complaint process and retain the complaint number.","A calculator can reveal that a bill is unusual, but it cannot determine whether the meter or official assessment is wrong. Escalation should be based on documented account facts and the current regulatory complaint process, not only on an online estimate."]}
    ],
    tables:[{caption:"Provider comparison checklist",headers:["Item","LESCO / FESCO / IESCO","K-Electric","Why it matters"],rows:[["Base tariff","Check the applicable notified DISCO schedule","Check K-Electric's applicable schedule","Schedules and effective dates may differ"],["Consumer status","Match category, load and protected status","Match category, load and protected status","Provider name is not enough"],["Adjustments","Check month and notification","Check month and notification","An adjustment may relate to an earlier period"],["Final verification","Provider bill plus NEPRA material","K-Electric bill plus NEPRA material","The actual account controls the comparison"]],note:"This table compares the checking process; it deliberately does not publish a permanent rupees-per-unit figure because notified rates and adjustments change."}],
    example:{heading:"Worked example: compare two 350-unit bills",paragraphs:["Suppose two relatives each used 350 units, one in Lahore and one in Karachi. Their payable totals still cannot be compared fairly until the account category, protected history, billing days, load, taxes and adjustments are aligned."],steps:["Write the base energy charge from each bill.","Place fixed charges, taxes and every adjustment in separate rows.","Remove arrears, late fees and account-specific credits from the consumption comparison.","Divide the comparable subtotal by units and document remaining differences rather than assuming an error."]},
    faqs:[{question:"Does every DISCO use exactly the same residential slab calculation?",answer:"Do not assume that from a generic table. Match the official schedule, category, status and effective date for the bill being checked."},{question:"Why is my effective per-unit rate higher than the advertised slab?",answer:"The payable total can include fixed charges, taxes, fuel or quarterly adjustments, arrears and other items beyond the base energy charge."},{question:"Is K-Electric always more expensive than LESCO?",answer:"That claim cannot be made from one bill. Usage, consumer status, month and account-specific items must be normalised first."},{question:"Can I compare bills using only units?",answer:"Units are essential, but billing days, category, status, load, taxes and adjustments are also needed."},{question:"Which amount should a calculator reproduce first?",answer:"Start with the base energy charge, then add each visible bill component separately so any difference remains explainable."}],
    relatedTools:["electricity-bill-calculator-pakistan","electricity-slab-rate-calculator-pakistan","electricity-bill-comparison-calculator-pakistan","appliance-electricity-cost-calculator-pakistan"],
    relatedGuides:["how-electricity-bills-are-calculated-in-pakistan","protected-vs-unprotected-electricity-consumers-pakistan","electricity-bill-taxes-and-charges-pakistan"],sources:[nepra,{name:"Power Information Technology Company",url:"https://www.pitc.com.pk/",note:"Official service links and information for participating power distribution companies."},editorial],
    limitation:"This is a reading and comparison framework, not a tariff notification or bill adjudication. Provider schedules, adjustments and government charges may change after the review date."
  },
  {
    slug:"withholding-tax-rates-explained-pakistan",
    title:"Pakistan Withholding Tax Rates Explained",
    description:"Learn how withholding works across common payments, why filer status can change collection and why one rate cannot represent every transaction.",
    category:"Tax",icon:"✂️",publishedAt,reviewedAt,readingMinutes:14,
    quickAnswer:"Withholding tax is collected or deducted when a specified payment or transaction occurs. The applicable section, payment type, recipient status, tax year and sometimes transaction details determine the rate and whether the amount is adjustable, minimum or final. A universal filer and non-filer percentage does not exist.",
    takeaways:["Identify the legal section and payment category before entering a rate.","Treat cash received after withholding separately from final taxable income.","Keep certificates and reconcile deductions in the return where applicable."],
    sections:[
      {heading:"Withholding is a collection mechanism",paragraphs:["Pakistan uses withholding at many points: salary payroll, bank profit, contracts, goods and services, property and vehicle transactions, dividends and other payments. The payer or collecting agent applies the relevant rule and reports or deposits the amount according to law.","Because collection happens at transaction time, it may not equal the recipient's final annual tax. Whether it can be adjusted or represents minimum or final treatment depends on the applicable provision and current law. The certificate and legal section are therefore as important as the percentage."]},
      {heading:"Why rates cannot be memorised as one list",paragraphs:["A service payment and sale of goods can fall under different provisions even when both appear on the same invoice. Company, individual, association and other recipient categories may receive different treatment. ATL status can also change the collection rate for specified transactions.","Rates can be amended through a Finance Act or other legal change. An old rate card may remain high in search results after it is obsolete. Always record tax year, section, nature of payment, recipient type and status beside the rate used."]},
      {heading:"Gross amount, tax withheld and net receipt",paragraphs:["For a simple percentage deduction, withholding equals the eligible gross payment multiplied by the rate. Net cash equals gross payment minus withholding. But the eligible base may exclude or include components according to the contract and law; a calculator cannot decide that classification.","A gross-up works backwards when parties agree that the recipient must receive a fixed net amount. Gross-up changes the invoice required; it does not change who is legally responsible for the tax or whether the commercial agreement is valid."]},
      {heading:"Filer and non-filer comparisons",paragraphs:["ATL status can produce different collection rates for certain transactions, but the difference should be checked for the exact section. Do not market a calculator as the total cost of being a non-filer. It only compares the selected transaction and assumptions.","Verify status through an official FBR route close to the transaction date. A saved screenshot or an old return acknowledgement may not prove current ATL treatment. Keep the verification and transaction certificate with the record."]},
      {heading:"Certificates and reconciliation",paragraphs:["Ask the withholding agent for the required certificate or evidence showing payer, recipient, amount, date, section and tax deposited. Compare it with FBR records and the commercial payment. Missing or mismatched identity details can make reconciliation difficult.","During return preparation, classify each deduction correctly and determine its allowed treatment. Do not claim an amount merely because cash received was lower than the invoice; bank fees, platform commission and withholding are different deductions."]},
      {heading:"Use a calculator responsibly",paragraphs:["Make the rate an editable, dated input. Show gross payment, withheld amount, net receipt and gross-up separately. Add a field or note for section and status so the result remains auditable.","For property, cross-border, large contracts or uncertain classification, obtain professional advice before signing. A small misunderstanding in the base or section can outweigh any precision in the multiplication.","When comparing commercial offers, calculate both invoice value and cash received, then keep tax recoverability separate. This prevents a lower net payment from being mistaken for a lower project price and makes negotiations clearer."]}
    ],
    tables:[{caption:"Withholding calculation record",headers:["Field","Question to answer","Evidence"],rows:[["Payment type","Salary, goods, services, profit, property or other?","Contract, invoice or transaction document"],["Legal provision","Which current section applies?","FBR rate card and law"],["Recipient","Individual, company or another category?","Registration details"],["Status","What is the verified ATL treatment?","Official verification"],["Tax character","Adjustable, minimum, final or other?","Current law/professional review"]],note:"The table intentionally avoids publishing one permanent rate. Use FBR's current tax-year withholding material."}],
    example:{heading:"Worked example: an invoice with an editable rate",paragraphs:["A freelancer issues a PKR 100,000 invoice. The client identifies a current applicable rate of 5% after checking the payment classification and recipient details. This percentage is illustrative, not a published rate recommendation."],steps:["Eligible gross payment: PKR 100,000.","Illustrative withholding: 100,000 × 5% = PKR 5,000.","Net cash: PKR 95,000 before any bank or platform fee.","Keep the certificate and determine return treatment separately."]},
    faqs:[{question:"Is withholding tax an extra fee charged by the client?",answer:"It is a tax collection under the applicable law, not a substitute label for platform or bank fees."},{question:"Does a filer always pay exactly half the non-filer rate?",answer:"No. The relationship varies by provision and tax year; check the exact current rate."},{question:"Can withholding be refunded or adjusted?",answer:"That depends on its legal character and the taxpayer's final position. Verify the applicable section."},{question:"Should sales tax be included in the withholding base?",answer:"The base depends on current law and invoice facts. Do not assume without checking."},{question:"What proof should the recipient keep?",answer:"Keep the invoice, payment evidence and a certificate identifying the withholding agent, recipient, amount, date and provision."}],
    relatedTools:["withholding-tax-calculator-pakistan","filer-vs-non-filer-calculator-pakistan","freelance-project-quote-calculator-pakistan","invoice-tax-calculator-pakistan"],relatedGuides:["filer-vs-non-filer-pakistan","how-to-become-filer-active-taxpayer-pakistan","pakistan-income-tax-guide-salaried-employees"],sources:[{name:"FBR Withholding Taxes",url:"https://www.fbr.gov.pk/withholding-taxes/51147/101152",note:"Official withholding-tax information and current rate resources."},fbr,editorial],
    limitation:"The example rate is purely illustrative. Applicable rates and tax character depend on current law and transaction facts; verify before payment or filing."
  },
  {
    slug:"pta-tax-passport-vs-cnic-registration-pakistan",
    title:"PTA Mobile Tax: Passport vs CNIC Registration in Pakistan",
    description:"Understand how the registration route, travel eligibility, IMEI identity and official PSID affect an imported phone's payable assessment.",
    category:"Mobiles",icon:"🛂",publishedAt,reviewedAt,readingMinutes:13,
    quickAnswer:"Passport and CNIC are registration routes within the official device-registration process; they are not discount codes that an online calculator can guarantee. Eligibility, recent travel requirements, device identity, customs valuation and current duties affect the official assessment. Only the authorised system-generated PSID confirms the payable amount.",
    takeaways:["Check every IMEI before paying a seller or intermediary.","Use the passport route only when the official eligibility conditions are genuinely met.","Treat all web estimates as planning figures until the official assessment is generated."],
    sections:[
      {heading:"What DIRBS is checking",paragraphs:["DIRBS identifies devices operating on Pakistani mobile networks and manages compliance status. A dual-SIM or eSIM-capable phone can have more than one IMEI, and every relevant identifier should be checked. Registration of one IMEI does not prove that all device identities are compliant.","Match the IMEI in device settings, on the box where available, and in the official status result. A mismatch can indicate the wrong box, altered identity or a misunderstanding about the variant. Stop the purchase until it is explained."]},
      {heading:"CNIC and passport are not interchangeable shortcuts",paragraphs:["The CNIC route identifies a resident applicant through the national identity process. A passport route can be connected to traveller eligibility and official entry records under the rules then in force. Possessing any passport does not automatically make every device eligible for preferred treatment.","Do not pay someone to use an unrelated passport or identity. Besides fraud and privacy risk, the device may remain non-compliant or create problems for the identity holder. Follow the official portal's current requirements."]},
      {heading:"Why unofficial tax tables differ",paragraphs:["Websites often map a phone model or USD price into a simplified duty band. The official system may use a customs valuation, exchange rate, storage variant and duty schedule that differ from the buyer's receipt. Used or discounted purchase price does not necessarily control valuation.","Model naming creates further errors. Regional variants can share a marketing name while differing in storage, radio configuration or IMEI record. Only the official assessment for the exact identity should be treated as payable."]},
      {heading:"Safe registration process",paragraphs:["Use PTA's and FBR's authorised information and portal links. Enter personal information only on verified domains. Generate the official payment identifier through the approved process, confirm its details and pay through an authorised channel.","Save the application, PSID, receipt and final status. Recheck device compliance after processing. If payment is not reflected, use the official complaint route with the transaction evidence instead of paying a second intermediary."]},
      {heading:"Buying a phone advertised as PTA approved",paragraphs:["Verify status independently before handing over money. Check all physical and electronic IMEIs, SIM operation, model and storage. Ask for proof of ownership and registration payment, but do not rely on a screenshot alone.","Patched, paired, cloned or altered-IMEI claims carry serious risk. A temporarily working SIM does not establish lawful permanent compliance. Prefer transparent devices with verifiable identity and seller evidence."]},
      {heading:"Compare total ownership cost",paragraphs:["Add purchase price, official registration assessment, accessories, warranty, repair availability and resale risk. A cheap non-compliant device can cost more than a locally approved unit once official registration is included.","If the official assessment makes the device uneconomic, do not attempt a bypass. Choose another model or a verified approved unit. SolvePilot's estimator exists to screen scenarios, not to issue a tax amount or alter status."]}
    ],
    tables:[{caption:"Passport and CNIC route comparison",headers:["Check","Passport route","CNIC route"],rows:[["Identity","Valid passport and current official eligibility","Valid CNIC and current official requirements"],["Travel condition","Verify entry/travel linkage in the authorised system","Not presented as traveller relief"],["Device identity","Every IMEI and exact variant","Every IMEI and exact variant"],["Amount","Official PSID controls","Official PSID controls"],["Safe evidence","Application, PSID, receipt and status","Application, PSID, receipt and status"]],note:"This describes the verification process, not a guaranteed rate difference. Rules and eligibility can change."}],
    example:{heading:"Worked example: dual-SIM imported phone",paragraphs:["A traveller brings a dual-SIM phone with two IMEIs. A shop quotes an estimated passport amount based only on the marketing model."],steps:["Confirm the traveller meets the current passport-route requirements.","Check both IMEIs and the exact device variant.","Use the authorised process to generate the official assessment.","Compare the PSID amount with total ownership cost.","Pay through an authorised channel and retain proof."]},
    faqs:[{question:"Is passport registration always cheaper than CNIC?",answer:"Do not assume so. Eligibility and official assessment control; online tables can be outdated or incomplete."},{question:"Can I use a relative's passport?",answer:"Only follow the identity and traveller rules stated by the official system. Do not use another person's documents as a workaround."},{question:"Does one PSID cover both IMEIs?",answer:"Follow the official application for the exact device and verify every IMEI afterward rather than assuming."},{question:"Can SolvePilot check whether my phone is approved?",answer:"No. Use the official PTA/DIRBS status service."},{question:"Why is the PSID higher than the shop estimate?",answer:"The shop may have used the wrong valuation, variant, exchange rate, route or an outdated duty table. The official assessment controls."}],
    relatedTools:["pta-tax-calculator-pakistan","phone-value-score-calculator-pakistan","used-phone-condition-score-pakistan","phone-finder-pakistan"],relatedGuides:["how-pta-mobile-tax-works","used-mobile-buying-checklist-pakistan","gaming-phones-under-40000-60000-100000-pakistan"],sources:[{name:"PTA DIRBS",url:"https://dirbs.pta.gov.pk/",note:"Official device-registration and compliance-status service."},pta,fbr,editorial],
    limitation:"SolvePilot cannot verify travel eligibility, IMEIs, customs valuation or payable duty. Only the authorised official assessment and status are controlling."
  },
  {
    slug:"used-mobile-buying-checklist-pakistan",
    title:"Used Mobile Buying Checklist for Pakistan",
    description:"Inspect identity, PTA status, ownership, display, battery, cameras, connectivity and repairs before paying for a second-hand phone.",
    category:"Mobiles",icon:"🔎",publishedAt,reviewedAt,readingMinutes:14,
    quickAnswer:"A safe used-phone purchase requires three separate checks: identity and ownership, network/PTA compliance, and physical/functional condition. A clean body or high battery-health number cannot compensate for an account lock, altered IMEI, unpaid device issue, replaced display or unstable board.",
    takeaways:["Match every IMEI before negotiating price.","Test the phone with your own SIM, charger and accounts where safe.","Keep seller identity, written terms and payment evidence."],
    sections:[
      {heading:"Verify identity before condition",paragraphs:["Open device settings and display every IMEI, serial and exact model. Compare them with the box, receipt and official status result where available. Dual-SIM and eSIM phones can have multiple identifiers, so checking one number is incomplete.","Watch for inconsistent fonts, labels, storage or colour. A replacement box is not automatically suspicious, but the seller should explain it. Do not continue when the identity changes during the meeting or the seller refuses an official status check."]},
      {heading:"Confirm ownership and remove locks",paragraphs:["The seller should sign out of Apple, Google, Samsung, Xiaomi or other manufacturer accounts and disable activation protection before payment. Resetting from recovery mode does not necessarily remove an ownership lock.","Check device-management profiles, work supervision and financed-device restrictions where relevant. Obtain seller name, contact information, CNIC evidence appropriate to a lawful transaction, a description of the device and payment proof. Meet in a safe public place or reputable shop."]},
      {heading:"Inspect body, screen and repair signs",paragraphs:["Use bright light to inspect frame gaps, dents near corners, camera rings, screws, SIM tray and signs of moisture. Uneven frame separation can indicate swelling or a poor repair. Do not press a swollen battery or continue charging it.","Display a white, black, red, green and blue screen. Check dead pixels, burn-in, tint, touch across the edges, brightness, refresh behaviour and proximity sensing. A replaced display may work but can alter colour, brightness, fingerprint function, sealing and resale value."]},
      {heading:"Test cameras, audio and connectivity",paragraphs:["Record video using every camera, switch focus between near and far subjects and test stabilisation, flash and microphones. Make a call, use speakerphone, record voice, connect headphones where supported and test vibration.","Insert your SIM and test mobile data, calls and SMS. Check Wi-Fi, Bluetooth, GPS, hotspot, NFC if important, USB data and charging. Intermittent board faults may appear only when the phone warms up, so a five-minute glance is insufficient."]},
      {heading:"Battery and performance checks",paragraphs:["Battery-health software is evidence, not proof. Compare charge percentage over a sustained task, temperature, shutdown behaviour and charging speed with a compatible charger. Look for warnings about unknown parts or service history.","Run a game, camera recording or benchmark long enough to reveal severe heat, throttling, ghost touch or restart. Do not expect a used phone to match a new battery, but reject instability or unexplained rapid drain unless repair cost is explicitly priced."]},
      {heading:"Price the risk, not just the scratches",paragraphs:["Start from a verified current price for the exact approved variant, then subtract for age, battery condition, repair history, missing warranty and cosmetic damage. Add any official registration cost if the device is not compliant. Do not let a seller compare an unapproved import with an approved local unit without adjusting total cost.","A condition score helps maintain consistency but cannot authenticate ownership or hidden repairs. When the price is unusually low and the explanation is weak, walking away is often the cheapest decision."]}
    ],
    tables:[{caption:"15-minute used-phone inspection",headers:["Minutes","Check","Stop-buy warning"],rows:[["0–3","IMEIs, serial, model, ownership evidence","Mismatch or refused official check"],["3–6","Accounts, reset status, display and touch","Activation lock, frame separation or ghost touch"],["6–10","Cameras, microphones, speakers and biometrics","Focus failure, missing audio or disabled security"],["10–13","SIM, data, Wi-Fi, Bluetooth, GPS and charging","Network block, unstable radios or port damage"],["13–15","Heat, battery drain, restart and agreement","Unexpected shutdown, swelling or seller pressure"]]}],
    example:{heading:"Worked example: cheap phone with replaced display",paragraphs:["A phone is 20% below comparable approved units. The display has been replaced, fingerprint works inconsistently and the seller has no repair invoice."],steps:["Verify IMEIs and ownership before discussing discount.","Price a quality display and biometric repair from a trusted technician.","Reduce resale expectations and any water-resistance assumption.","Reject the purchase if account, network or board checks fail.","Document the disclosed repair if proceeding."]},
    faqs:[{question:"Is 100% battery health proof of an original battery?",answer:"No. Health can be reset, estimated or reported differently. Test behaviour and look for parts/service evidence."},{question:"Can a factory reset remove an iCloud or Google lock?",answer:"Not necessarily. The owner should properly remove the device from the account and activation service."},{question:"How do I know a phone is PTA approved?",answer:"Check every IMEI through the official PTA/DIRBS route close to purchase time."},{question:"Is a replaced display always bad?",answer:"No, but part quality, installation, biometric function, sealing and resale value must be considered."},{question:"Should I pay a deposit before inspection?",answer:"Avoid irreversible payment before identity, status, ownership and condition checks are complete."}],
    relatedTools:["used-phone-condition-score-pakistan","phone-value-score-calculator-pakistan","phone-comparison-score-calculator","phone-storage-requirement-calculator","pta-tax-calculator-pakistan"],relatedGuides:["mobile-buying-guide-pakistan","pta-tax-passport-vs-cnic-registration-pakistan","gaming-phones-under-40000-60000-100000-pakistan"],sources:[{name:"PTA Device Compliance Information",url:"https://www.pta.gov.pk/",note:"Use official PTA/DIRBS services for device status and current consumer guidance."},{name:"Google Android Help — device protection",url:"https://support.google.com/android/",note:"Official Android account, reset and device-protection guidance."},{name:"Apple Support — Activation Lock",url:"https://support.apple.com/en-us/108794",note:"Official explanation of Activation Lock and ownership removal."},editorial],
    limitation:"A checklist cannot detect every hidden repair, ownership dispute or intermittent fault. Use official status checks and a trusted technician for higher-risk purchases."
  },
  {
    slug:"gaming-phones-under-40000-60000-100000-pakistan",
    title:"Best Gaming Phones Under PKR 40k, 60k and 100k: A Pakistan Buying Guide",
    description:"Build an evidence-based gaming-phone shortlist by sustained performance, display, cooling, battery, PTA status and verified local price.",
    category:"Mobiles",icon:"🎮",publishedAt,reviewedAt,readingMinutes:15,
    quickAnswer:"The best gaming phone is the model that sustains your target game and frame rate inside the total approved budget. A chipset benchmark is only the first filter: cooling, game support, touch response, display brightness, battery bypass features, software stability, storage and warranty decide whether performance remains good after twenty minutes.",
    takeaways:["Verify today's approved price before placing a phone in a budget tier.","Prefer sustained game tests at the same graphics settings over peak benchmark scores.","Reserve part of the budget for storage, warranty and a safe charger rather than spending every rupee on chipset marketing."],
    sections:[
      {heading:"Why this guide uses criteria instead of permanent winners",paragraphs:["Pakistan phone prices and stock can move quickly with exchange rates, promotions, official warranty and PTA status. A model under PKR 60,000 today may leave that tier tomorrow. Publishing an undated winner with an invented price would be less useful than teaching a shortlist that can be rechecked.","For every candidate, record seller, exact RAM and storage, PTA status, warranty and checked date. A grey-market import and an officially warranted unit are not the same offer even when their model names match."]},
      {heading:"Under PKR 40,000: prioritise stability",paragraphs:["In this tier, target a balanced recent chipset, adequate RAM, at least practical modern storage and a display that can hold useful brightness. Expect compromises: very high graphics in demanding games, premium cameras and long update support may not coexist.","Avoid paying extra for a 120Hz label when the chipset cannot produce stable high frame rates in your game. A steady lower setting with controlled heat provides a better match experience than a short burst followed by throttling."]},
      {heading:"Under PKR 60,000: look for sustained value",paragraphs:["The middle tier can offer stronger processors, faster storage, AMOLED displays or better cooling, but not every model combines them. Compare a twenty- to thirty-minute gaming test, one-percent-low frame behaviour, battery drain and surface temperature.","Check whether the game's high-frame-rate option is actually enabled for that model. Hardware may support a refresh rate while the game developer or manufacturer limits available modes. Never convert a chipset capability into a guaranteed PUBG, Free Fire or Call of Duty setting."]},
      {heading:"Under PKR 100,000: demand fewer compromises",paragraphs:["At this budget, buyers should expect stronger sustained performance, capable storage and a good display, yet camera, software support and after-sales quality still vary. A previous-generation performance phone can beat a newer lifestyle model in games but may receive fewer remaining updates.","Compare official warranty and repair support with imported alternatives. Add PTA registration before calling an import a bargain. If the phone is primarily for competitive play, test touch sampling, gyro behaviour, network stability, speaker placement and charging while gaming."]},
      {heading:"Create a repeatable score",paragraphs:["Score sustained gaming performance, thermal control, display, battery/charging, software and ownership value separately. Weight performance and thermals heavily, but set a minimum for each remaining category so one benchmark cannot hide a poor screen or unreliable battery.","Use at least two independent long-form reviews and look for matching results. Different room temperature, firmware and game version can explain disagreement. Prefer measurements over words such as flagship killer or ultra gaming."]},
      {heading:"Buy safely and keep performance",paragraphs:["Verify the exact approved device, inspect warranty terms and update firmware cautiously after reading game-specific reports. Use a quality charger and cable, avoid blocking ventilation, and do not game in direct sun or under bedding.","Leave storage free for updates and shader caches. High temperature and charging at the same time can increase battery stress; use a supported bypass or charge-separation mode only according to manufacturer instructions. A cooler environment often improves sustained performance more than a cosmetic gaming accessory."]}
    ],
    tables:[{caption:"Gaming-phone targets by budget",headers:["Budget tier","Prioritise","Acceptable compromise","Verify before buying"],rows:[["Under PKR 40k","Stable performance, 8GB-class memory where available, practical storage","Camera extras and maximum graphics","Approved price, game settings, heat"],["Under PKR 60k","Stronger chipset, faster storage, display and cooling balance","Premium build or flagship camera","Long-session FPS, warranty, battery drain"],["Under PKR 100k","High sustained FPS, good thermals, fast storage, strong display","Choose between gaming focus and camera/support","PTA total cost, updates, service and exact variant"]],note:"These are selection targets, not claims that every model in a tier provides the listed features. Prices must be checked on the publication date."}],
    example:{heading:"Worked example: choose between two PKR 60k candidates",paragraphs:["Phone A has a higher peak benchmark but loses 30% performance after twenty minutes. Phone B starts lower but remains stable, has faster storage and an official warranty."],steps:["Confirm both prices, variants and PTA status on the same date.","Compare the same game, map, graphics, frame cap and room conditions.","Give sustained FPS and one-percent-low behaviour more weight than peak score.","Compare battery drain, temperature, display and network stability.","Choose Phone B if consistent competitive play matters more than benchmark screenshots."]},
    faqs:[{question:"Which chipset is best under PKR 60,000?",answer:"There is no permanent answer because phone prices and models move. Compare current candidates by sustained game tests, not chipset name alone."},{question:"Does a 120Hz display guarantee 120 FPS?",answer:"No. The chipset, game support, manufacturer profile, graphics settings and thermal conditions all affect the available frame rate."},{question:"How much RAM is enough for gaming?",answer:"Game requirements and software differ. Adequate real RAM and fast storage matter more than heavily marketed virtual-RAM numbers."},{question:"Should I buy a non-PTA gaming phone?",answer:"Include official registration and network-use restrictions in total cost. A low purchase price alone is not a fair comparison."},{question:"Are gaming coolers safe?",answer:"Use reputable accessories carefully, avoid condensation and follow device guidance. A cooler cannot fix unsafe charging or internal damage."}],
    relatedTools:["mobile-gaming-fps-estimator","phone-comparison-score-calculator","phone-value-score-calculator-pakistan","phone-storage-requirement-calculator","phone-finder-pakistan"],relatedGuides:["mobile-buying-guide-pakistan","used-mobile-buying-checklist-pakistan","pta-tax-passport-vs-cnic-registration-pakistan"],sources:[{name:"Google Play Help",url:"https://support.google.com/googleplay/",note:"Official Android app compatibility and account guidance; individual game publishers control supported settings."},{name:"PTA",url:"https://www.pta.gov.pk/",note:"Official device-compliance and consumer guidance."},editorial],
    limitation:"This guide does not declare permanent model winners or quote unverified prices. Stock, firmware, game support, PTA status and local prices change; verify every shortlist item on the purchase date."
  },
  {
    slug:"five-kw-vs-ten-kw-solar-system-pakistan",
    title:"5kW vs 10kW Solar System in Pakistan: Size, Output and Cost Planning",
    description:"Compare 5kW and 10kW solar systems using energy demand, roof space, inverter limits, export assumptions and itemised quotations.",
    category:"Solar",icon:"☀️",publishedAt,reviewedAt,readingMinutes:13,
    quickAnswer:"A 10kW array has roughly twice the nameplate capacity of a 5kW array, but it is not automatically twice as valuable. Choose between them using annual and daytime consumption, approved connection capacity, usable roof, seasonal production, equipment design and an itemised installed quotation—not house size or one summer bill.",
    takeaways:["Calculate required energy before choosing the familiar 5kW or 10kW label.","Compare installed scope and warranties, not only a headline package price.","Model self-consumption and export separately under current rules."],
    sections:[
      {heading:"The kW label describes peak DC capacity",paragraphs:["Five or ten kilowatts usually describes the combined rated power of the solar modules under standard test conditions. It does not promise that the system will produce that output at every hour. Heat, irradiance, dust, angle, shade, wiring, mismatch and inverter conversion all affect real power.","Inverter AC rating may differ from panel DC capacity. A carefully selected DC-to-AC ratio can be reasonable, but the inverter's MPPT voltage, input current and total power limits must support the final string design. A package title is not an electrical design."]},
      {heading:"Start with twelve months of consumption",paragraphs:["Collect a full year of billed units when possible. Summer air-conditioning can make one month unusually high, while winter may understate future needs. Calculate annual units, daily average and the share used during solar hours.","Decide whether the objective is bill reduction, daytime load support, backup, future electrification or a combination. Batteries, electric vehicles, additional air-conditioners and business equipment can change the plan, but speculative future load should not justify unverified oversizing."]},
      {heading:"Estimate generation as a range",paragraphs:["A planning estimate multiplies array kW by site-specific peak-sun-hours and system efficiency. Use monthly or seasonal conditions rather than one annual average when cash flow matters. Production per installed kW is site dependent, so this guide does not publish one guaranteed national figure.","For an illustrative day at five equivalent sun hours and 80% overall efficiency, 5kW produces about 20kWh and 10kW about 40kWh. That is arithmetic for understanding scale, not a forecast or warranty. A credible installer should provide a location-specific simulation and disclose losses."]},
      {heading:"Roof and electrical constraints",paragraphs:["Usable roof is smaller than measured roof. Water tanks, access routes, parapets, shade, structural capacity, row spacing and setbacks reduce the installable area. Module dimensions and orientation determine actual count.","The connection, sanctioned load, distribution equipment, earthing and protection must suit the project. Large arrays can require changes that are absent from a cheap quotation. Ask who is responsible for design approval, meter work and any service upgrade."]},
      {heading:"Compare cost without inventing a market price",paragraphs:["Prices change with exchange rates, module grade, inverter model, mounting material, cable, protection, warranty, labour, application scope and taxes. A current 5kW quote and 10kW quote are only comparable after normalising those items.","Calculate total installed cost per usable projected annual kWh, not only cost per nameplate watt. Include financing, expected maintenance and replacements. Keep batteries separate because chemistry, usable capacity and cycle life can dominate the package price."]},
      {heading:"Choose the smaller system when it fits better",paragraphs:["A well-matched 5kW system may outperform a poorly placed 10kW system financially if the home has moderate daytime demand, limited roof or uncertain export value. Expansion-ready design can preserve options without paying for unused capacity today.","Choose 10kW only when the load, approval, roof and budget support it. The decision should survive a conservative scenario with lower production, no optimistic export income and reasonable equipment ageing."]}
    ],
    tables:[{caption:"5kW and 10kW planning comparison",headers:["Question","5kW array","10kW array"],rows:[["Nameplate size","5,000W DC","10,000W DC"],["Illustrative daily energy at 5 sun-hours, 80% efficiency","About 20kWh","About 40kWh"],["Approximate panel count","Array watts ÷ selected module watts","Array watts ÷ selected module watts"],["Best fit","Moderate energy demand or constrained roof","Higher verified demand and sufficient roof/approval"],["Main risk","Under-sizing future load","Over-sizing relative to use or export value"]],note:"The energy row is a worked assumption, not a Pakistan-wide production guarantee. Replace it with a site-specific estimate."}],
    example:{heading:"Worked example: 900 monthly units",paragraphs:["A household uses 900 units in a 30-day month, or 30kWh daily. If about 60% occurs during solar hours, the immediate daytime opportunity is roughly 18kWh before considering load shifting or export."],steps:["Model a 5kW array with local monthly sun-hours and losses.","Model a 10kW array using the same assumptions.","Split each result into self-consumed and exported energy.","Apply current billing treatment and add fixed charges.","Compare conservative payback and roof layout before choosing."]},
    faqs:[{question:"How many panels make 5kW?",answer:"Divide 5,000W by the selected module wattage and round to a practical string design. The final count must also satisfy inverter voltage and current limits."},{question:"Can a 5kW inverter take more than 5kW of panels?",answer:"Some models permit a defined DC oversizing ratio, but only the manufacturer's datasheet and professional design should decide it."},{question:"Is 10kW enough for two air-conditioners?",answer:"Air-conditioner input, simultaneous loads, usage hours, starting behaviour and night operation matter. Capacity alone cannot answer that."},{question:"Should batteries be included in the comparison?",answer:"Compare them separately using essential load, backup hours, usable depth of discharge, efficiency and cycle life."},{question:"Why are two quotations for the same kW so different?",answer:"Module and inverter models, structure, protection, cabling, warranty, application work and after-sales service can differ substantially."}],
    relatedTools:["solar-system-calculator-pakistan","solar-panel-count-calculator-pakistan","solar-panel-output-calculator-pakistan","solar-roof-area-calculator-pakistan","solar-payback-calculator-pakistan"],relatedGuides:["how-to-size-a-solar-system-in-pakistan","net-metering-solar-buyback-guide-pakistan","lithium-vs-lead-acid-battery-pakistan"],sources:[nepra,{name:"National Renewable Energy Laboratory PVWatts",url:"https://pvwatts.nrel.gov/",note:"Independent production-modelling resource; enter location and system assumptions rather than treating results as a guarantee."},editorial],
    limitation:"The production example is illustrative. Final output, approval, cost and safety depend on the site, current rules, equipment and installation quality."
  },
  {
    slug:"lithium-vs-lead-acid-battery-pakistan",
    title:"Lithium vs Lead-Acid Batteries for UPS and Solar in Pakistan",
    description:"Compare usable energy, cycle life, heat, charging, safety, maintenance and lifetime value before choosing a backup battery.",
    category:"Energy",icon:"🔋",publishedAt,reviewedAt,readingMinutes:13,
    quickAnswer:"Lithium batteries often provide more usable energy, higher efficiency and longer cycle life for the same nominal capacity, while lead-acid batteries can have a lower initial price and broad local familiarity. The correct choice depends on compatible charging, required backup, temperature, cycle frequency, warranty and verifiable lifetime cost.",
    takeaways:["Compare usable kWh and warranted cycles—not amp-hours alone.","Confirm inverter and charger compatibility before purchase.","Treat ventilation, protection, installation and warranty evidence as part of the battery cost."],
    sections:[
      {heading:"Nominal capacity is not usable capacity",paragraphs:["A 12V 200Ah battery has 2.4kWh of nominal energy, but the safe usable portion depends on chemistry, discharge rate, age, temperature and the manufacturer's permitted depth of discharge. Two products with the same amp-hour label can therefore deliver very different practical backup.","Lithium packs are often specified with an internal battery-management system and a larger usable percentage. Lead-acid life is sensitive to deep discharge and remaining partially charged. Use the exact datasheet rather than applying one universal depth-of-discharge number."]},
      {heading:"Cycle life needs context",paragraphs:["A cycle-life claim is meaningful only with the stated depth of discharge, temperature, end-of-life capacity and test method. Five thousand shallow laboratory cycles are not the same as five thousand hot, deep household outages.","Estimate expected cycles per year. A home cycling twice daily uses battery life differently from a backup bank discharged a few times each month. Calendar ageing can also matter, so extremely high cycle claims do not guarantee decades of useful service."]},
      {heading:"Charging and inverter compatibility",paragraphs:["Lead-acid charging commonly uses bulk, absorption and float stages appropriate to the battery type. Lithium packs require the manufacturer's voltage and current limits and may communicate with compatible inverters. An incorrect profile can reduce life or create a safety risk.","Check system voltage, maximum charge and discharge current, low-voltage cut-off, communication protocol, parallel-unit rules and generator or solar-charger behaviour. A connector that physically fits does not prove electrical or software compatibility."]},
      {heading:"Heat, ventilation and safety",paragraphs:["Karachi and many other Pakistani cities experience high ambient temperatures. Heat accelerates ageing and can reduce available power or trigger protection. Install equipment within the specified temperature range, away from direct sun and water, with required clearance.","Lead-acid batteries may release gas during charging and need appropriate ventilation; flooded batteries require maintenance and spill precautions. Lithium systems need a credible BMS, correct fusing, secure mounting and a product designed for stationary storage. Never place either chemistry where occupants cannot escape a fault safely."]},
      {heading:"Calculate lifetime value",paragraphs:["Compare purchase and installation cost with usable kWh, expected warranted energy throughput, efficiency, maintenance and likely replacement. A cheaper battery replaced several times can cost more than a higher-priced pack, but only if the premium product and warranty are genuine.","Include downtime and service access. Verify seller identity, serial number, manufacturing date, warranty process and local support. A long warranty has little value if exclusions are unclear or the supplier cannot test and replace the pack."]},
      {heading:"Choose for the actual duty",paragraphs:["For occasional short outages and a tight upfront budget, a properly sized lead-acid system may remain practical. For frequent cycling, limited space or higher efficiency needs, compatible lithium can be attractive. Neither chemistry fixes an undersized inverter or unsafe wiring.","Begin with essential watts and backup hours, add conversion losses and an ageing margin, then choose capacity. Reduce nonessential loads before buying extra storage; an old refrigerator or electric heater can dominate the bank.","Write the final assumptions on the quotation: continuous load, surge, expected hours, usable energy, charging source and ambient temperature. This gives the installer and buyer the same target and makes later troubleshooting more objective."]}
    ],
    tables:[{caption:"Battery decision matrix",headers:["Factor","Lead-acid","Lithium"],rows:[["Upfront cost","Often lower","Often higher"],["Usable share","Usually more conservative; follow datasheet","Often higher; follow BMS and datasheet"],["Cycle behaviour","Deep discharge can shorten life sharply","Often suited to frequent cycling when correctly managed"],["Maintenance","Flooded types may need checks; sealed types differ","Typically low routine maintenance"],["Compatibility","Common charger profiles, but type still matters","Voltage, current and communication must match"],["Safety focus","Ventilation, acid, terminals and fusing","BMS quality, fusing, thermal and installation controls"]],note:"These are tendencies, not product guarantees. Compare the exact models and warranty conditions."}],
    example:{heading:"Worked example: a 600W essential load for four hours",paragraphs:["The appliances require 2.4kWh of delivered AC energy. The battery must supply more because the inverter and wiring are not perfectly efficient."],steps:["Divide 2.4kWh by the assumed inverter efficiency.","Divide again by the permitted usable fraction for the exact battery.","Check discharge current and inverter surge requirements.","Add a justified ageing margin.","Compare compliant battery options by installed lifetime cost."]},
    faqs:[{question:"Is lithium always better for solar?",answer:"No. It may suit frequent cycling, but product quality, compatibility, temperature, warranty and budget decide the outcome."},{question:"Can I replace lead-acid with lithium on the same UPS?",answer:"Only if voltage, charging profile, current limits and protection are compatible and approved by the manufacturers."},{question:"Why did my lead-acid battery fail early?",answer:"Common contributors include heat, repeated deep discharge, undercharging, overcharging, imbalance, poor terminals and low product quality."},{question:"Can different battery ages or capacities be mixed?",answer:"Mixing can create imbalance and unreliable operation. Follow manufacturer rules and professional design."},{question:"What matters more than amp-hours?",answer:"Usable energy, discharge power, permitted depth of discharge, efficiency, cycle conditions, temperature and warranty evidence."}],
    relatedTools:["ups-battery-backup-calculator-pakistan","battery-capacity-calculator-pakistan","battery-runtime-calculator-pakistan","ups-charging-cost-calculator-pakistan","solar-battery-size-calculator-pakistan"],relatedGuides:["ups-and-battery-sizing-guide","five-kw-vs-ten-kw-solar-system-pakistan","how-to-size-a-solar-system-in-pakistan"],sources:[{name:"U.S. Department of Energy — Energy Storage",url:"https://www.energy.gov/oe/energy-storage",note:"Independent background on storage technologies and safe, reliable system planning."},{name:"International Electrotechnical Commission",url:"https://www.iec.ch/",note:"International standards context; use the applicable product and installation standards for the project."},editorial],
    limitation:"Battery performance and safety are model- and installation-specific. Use manufacturer documentation and a qualified installer; this guide does not certify a product or system."
  },
  {
    slug:"pakistan-income-tax-guide-salaried-employees",
    title:"Pakistan Income Tax Guide for Salaried Employees",
    description:"Understand annual taxable salary, progressive slabs, payroll withholding, bonuses, certificates, returns and common reconciliation problems.",
    category:"Tax",icon:"💼",publishedAt,reviewedAt,readingMinutes:14,
    quickAnswer:"Salaried income tax is normally estimated on annual taxable salary for the relevant tax year, using progressive slabs and the current legal treatment of allowances and benefits. Employers withhold during payroll, but the employee should still reconcile salary certificates, deductions and any other income when filing.",
    takeaways:["Use the correct tax year and annual taxable amount.","Separate cash received from amounts legally treated as taxable salary.","Reconcile employer withholding with certificates and the return rather than assuming the monthly deduction is final."],
    sections:[
      {heading:"Tax year and annualisation",paragraphs:["Pakistan's income-tax year and Finance Act changes make the effective period essential. A slab table without a tax-year label is unsafe. Monthly payroll systems project expected annual salary, then spread or adjust withholding across remaining pay periods.","Joining midyear, changing jobs, receiving an increment or taking unpaid leave can alter the projection. Keep both employers' certificates if you move jobs. Each payroll may know only the salary it paid, while the return must reflect the employee's complete position."]},
      {heading:"Gross pay is not automatically taxable salary",paragraphs:["Base salary, cash allowances, bonuses, benefits and reimbursements can receive different treatment under current law and documentation. A payslip label does not by itself determine taxability. The employer's annual statement should identify taxable components and tax deducted.","Keep employment contracts, payslips, reimbursement evidence, benefit details and the salary certificate. If an item is material or unusual, verify it using current FBR law or professional advice before excluding it from an estimate."]},
      {heading:"How progressive slabs work",paragraphs:["Progressive slabs apply a fixed amount for completed bands and a marginal percentage to the excess within the current band, as specified by the law for that year. Multiplying the entire annual salary by the highest percentage usually overstates tax.","Calculate with full annual figures and round at the end. When comparing job offers, show gross annual salary, estimated annual tax, monthly average tax and take-home pay. Benefits and one-time bonuses should remain visible rather than hidden inside a single monthly number."]},
      {heading:"Payroll withholding and true-up",paragraphs:["Employers can revise withholding when the annual estimate changes. A bonus late in the year may produce a larger deduction because fewer salary months remain to collect the projected annual tax. A correction can also reduce later deductions.","Compare year-to-date taxable salary and tax deducted after every major change. If two payslips appear inconsistent, ask payroll for the annual projection and calculation instead of comparing only the latest month."]},
      {heading:"Return filing and other income",paragraphs:["Salary withholding does not remove the need to consider bank profit, property, freelance or business income, capital gains and other reportable items. The final return can differ from the salary-only estimate, and wealth-statement reconciliation may also be relevant.","Use official Iris access, keep tax-payment and withholding evidence, and protect login credentials. Avoid giving an unverified intermediary unrestricted account access. Review the submitted return and acknowledgements for your own records."]},
      {heading:"A practical annual checklist",paragraphs:["At year-end, obtain the salary certificate, compare it with payslips and verify tax deducted. Reconcile CNIC and employer information, then gather certificates for other deductions or income. Use current FBR forms and guidance.","If the difference is large, the facts are complex or a notice is received, consult a qualified tax professional. A calculator is valuable for arithmetic and scenario planning, but it cannot interpret every exemption, credit or legal classification."]}
    ],
    tables:[{caption:"Salary-tax working paper",headers:["Step","Evidence","Output"],rows:[["1. Select year","Finance Act and FBR material","Applicable slab schedule"],["2. Build salary","Contract, payslips and certificate","Annual taxable salary estimate"],["3. Calculate slabs","Current thresholds and rates","Estimated annual salary tax"],["4. Reconcile payroll","Year-to-date payslips","Tax already withheld"],["5. Complete return","Other income and certificates","Final filing position"]],note:"The table explains the process and intentionally omits volatile slab figures; use the current official tax-year schedule."}],
    example:{heading:"Worked example: salary increase during the year",paragraphs:["An employee receives one monthly salary for six months and a higher amount for the next six. Multiplying the final monthly salary by twelve would overstate actual annual salary."],steps:["Add taxable salary actually paid for the first six months.","Add projected taxable salary for the remaining six months.","Include any taxable bonus or benefit.","Apply the correct annual slabs.","Subtract tax already withheld and spread the remaining estimate across future payrolls."]},
    faqs:[{question:"Is monthly salary tax calculated from a monthly slab?",answer:"Payroll normally annualises expected taxable salary and applies the annual rules, then allocates withholding."},{question:"Why did tax increase in my bonus month?",answer:"The bonus can raise annual taxable salary and may leave fewer payroll periods for the employer to collect the revised estimate."},{question:"Does filer status remove salary tax?",answer:"No. ATL status and salary-tax liability are different concepts."},{question:"Can allowances be excluded automatically?",answer:"No. Treatment depends on current law, the nature of the payment and documentation."},{question:"What if I worked for two employers?",answer:"Keep both salary certificates and calculate the combined annual position for the relevant return."}],
    relatedTools:["salary-tax-calculator-pakistan","annual-to-monthly-salary-calculator-pakistan","bonus-tax-estimator-pakistan","salary-allowance-calculator-pakistan","salary-to-hourly-rate-calculator-pakistan"],relatedGuides:["pakistan-salary-tax-slabs-explained","how-to-become-filer-active-taxpayer-pakistan","withholding-tax-rates-explained-pakistan"],sources:[{name:"FBR Income Tax",url:"https://www.fbr.gov.pk/income-tax/142261/131271",note:"Official income-tax information, legislation and taxpayer resources."},{name:"FBR Budget and Finance Act material",url:"https://www.fbr.gov.pk/",note:"Use the documents for the relevant tax year before applying slabs."},editorial],
    limitation:"This guide cannot determine an individual's taxable benefits, exemptions, credits, other income or final liability. Use current FBR law and professional advice where needed."
  },
  {
    slug:"how-to-become-filer-active-taxpayer-pakistan",
    title:"How to Become a Filer and Active Taxpayer in Pakistan",
    description:"A practical path from registration and records to return filing, wealth reconciliation and checking the Active Taxpayers List.",
    category:"Tax",icon:"✅",publishedAt,reviewedAt,readingMinutes:14,
    quickAnswer:"Becoming a filer generally involves obtaining or confirming tax registration, accessing FBR's Iris system, preparing the correct income-tax return and required wealth information, submitting accurately, and then checking Active Taxpayers List status under the rules and timing currently in force. Filing and appearing on the ATL are connected but not always instantaneous.",
    takeaways:["Gather records before opening the return form.","Do not invent figures merely to make the wealth statement balance.","Verify ATL status through an official FBR channel after filing."],
    sections:[
      {heading:"Understand registration, filing and ATL",paragraphs:["Registration identifies the taxpayer in FBR systems. Filing means submitting the required return and related statements for a tax year. ATL status means the taxpayer appears on the current Active Taxpayers List under applicable rules. These are related steps, not interchangeable labels.","A person can have an NTN or Iris account without having completed the current filing obligation. A late filer may need to follow additional requirements before appearing on the ATL. Always check current FBR guidance rather than relying on an agent's permanent rule of thumb."]},
      {heading:"Prepare evidence before filing",paragraphs:["Collect CNIC and contact details, salary certificates, bank and withholding certificates, business records where relevant, property and vehicle information, investments, liabilities, household and personal expense information, and evidence of taxes paid or collected.","The exact documents depend on the taxpayer. Organising them first reduces guesswork and makes it easier to explain changes. Keep source files and calculation notes with the submitted return instead of saving only a final acknowledgement.","Name each record with its tax year and source, and preserve original statements rather than screenshots alone. A short index showing where every income, tax and closing-balance figure came from can save hours when reviewing the return or answering a later question."]},
      {heading:"Access Iris securely",paragraphs:["Use the official FBR website and verify the domain before entering credentials. Register or recover access through the official process. Use an email and mobile number you control, choose a strong password and do not share one-time codes casually.","If a representative assists, understand what will be submitted and retain copies. Taxpayer credentials provide access to sensitive identity and financial information; convenience is not a reason to hand permanent control to an unknown person."]},
      {heading:"Complete income and tax information",paragraphs:["Report income under the correct heads and reconcile tax deducted or paid using certificates and system records. Do not treat every withholding amount as proof of final tax. Classification affects how the return calculates liability.","Review employer, bank and transaction information for omissions or duplicates. Where system data and personal records differ, investigate rather than forcing the return to match one side blindly."]},
      {heading:"Reconcile the wealth statement",paragraphs:["The wealth statement connects opening wealth, income, expenses, gifts, loans, asset purchases and closing wealth. If it does not reconcile, an amount is missing or classified incorrectly. Adding an invented gift or loan merely to make the form balance creates a new problem.","Use bank trails and ownership evidence. Separate personal and business funds where possible. Significant unexplained changes, overseas assets or complex family transfers deserve professional review."]},
      {heading:"Submit, verify and maintain status",paragraphs:["Review the completed forms, submit through Iris and save acknowledgements and working papers. Then check ATL status using an official FBR verification method at the appropriate time. If late-filing rules or a surcharge apply, follow current official instructions.","Filer status requires ongoing compliance. Maintain records during the year, collect withholding certificates and note major transactions when they occur. Filing becomes easier when it is an annual process rather than an emergency before a vehicle or property transaction.","Set a quarterly routine: download statements, file certificates and update a private asset-and-liability note. It does not replace the return, but it reduces missing records and makes year-end reconciliation much more defensible."]}
    ],
    tables:[{caption:"Filer preparation checklist",headers:["Area","Examples of records","Purpose"],rows:[["Income","Salary, business, bank profit, rent","Report complete income"],["Tax paid","Payroll and withholding certificates, challans","Claim verifiable deductions or payments"],["Assets","Bank balances, property, vehicles, investments","Prepare closing wealth"],["Liabilities","Documented loans and payables","Explain financed assets"],["Expenses/transfers","Household spending, gifts, remittances","Reconcile movement in wealth"]]}],
    example:{heading:"Worked example: a salaried first-time filer",paragraphs:["A salaried employee has payroll withholding, one bank account, a motorcycle and family-supported living expenses. The return should be based on actual certificates and ownership records, not estimates copied from another filer."],steps:["Confirm Iris registration and tax year.","Enter salary from the employer certificate.","Reconcile tax withheld with available records.","List closing bank balance and owned assets.","Record genuine expenses and documented family support so wealth movement reconciles.","Review, submit and save the acknowledgement."]},
    faqs:[{question:"Is an NTN enough to call myself a filer?",answer:"Not by itself. Current return compliance and ATL rules determine active status."},{question:"How quickly does ATL status update?",answer:"Timing and late-filing treatment can change. Check current FBR guidance and verify through the official service."},{question:"Should I enter zero expenses to increase savings?",answer:"No. The wealth statement should reflect genuine personal and household outflows."},{question:"Can someone else file for me?",answer:"A qualified representative can assist, but you should understand the figures, protect credentials and keep the submitted records."},{question:"Do I need to file every year?",answer:"Ongoing obligations depend on current law and circumstances, but active status generally requires continued timely compliance rather than a one-time filing."}],
    relatedTools:["filer-vs-non-filer-calculator-pakistan","salary-tax-calculator-pakistan","withholding-tax-calculator-pakistan","wealth-statement-reconciliation-calculator-pakistan"],relatedGuides:["filer-vs-non-filer-pakistan","pakistan-income-tax-guide-salaried-employees","withholding-tax-rates-explained-pakistan"],sources:[{name:"FBR Active Taxpayer List",url:"https://www.fbr.gov.pk/active-taxpayer-list-income-tax/51147/30859",note:"Official ATL explanation and verification routes."},{name:"FBR Iris",url:"https://iris.fbr.gov.pk/",note:"Official online tax-return and registration system. Verify the domain before entering credentials."},editorial],
    limitation:"Tax filing obligations and ATL rules depend on current law and individual facts. This guide is not a substitute for FBR instructions or professional advice."
  },
  {
    slug:"protected-vs-unprotected-electricity-consumers-pakistan",
    title:"Protected vs Unprotected Electricity Consumers in Pakistan",
    description:"Understand how domestic protected status is determined, why recent consumption history matters and how to check the status shown on a bill.",
    category:"Electricity",icon:"🛡️",publishedAt,reviewedAt,readingMinutes:12,
    quickAnswer:"Protected status is not simply a button selected for a low-usage month. It is tied to the eligibility rules in the applicable residential tariff and typically considers recent consumption history and connection conditions. A single month below a threshold does not automatically prove that the account should be treated as protected.",
    takeaways:["Read the status and category printed on the current bill.","Review the required consumption-history window instead of one month.","Use conservative planning near any threshold because billing days and seasonal use vary."],
    sections:[
      {heading:"What protected status is designed to do",paragraphs:["Protected treatment is intended to provide targeted electricity relief to qualifying low-consumption residential users under the applicable tariff policy. It is an account classification for billing; it is not a declaration that every low-income household automatically qualifies or that every small bill is protected.","The precise wording and conditions should be taken from the tariff schedule in force for the connection. Consumer category, sanctioned load, meter type and consumption history can matter. A commercial connection or a time-of-use connection should not be evaluated with a simplified domestic protected-consumer explanation."]},
      {heading:"Why recent history matters",paragraphs:["Electricity demand changes with weather. If status depended on only the current month, a high-usage household could appear protected during a mild month and leave the group during summer. A rolling history requirement is intended to identify sustained low consumption rather than a temporary dip.","When checking eligibility, collect the required number of previous bills and write down billed units for each period. Mark estimated or corrected readings. If a provider later distributes accumulated units across periods, the status question may require official account review rather than a simple average."]},
      {heading:"Protected does not mean every charge disappears",paragraphs:["The energy tariff is only part of the invoice. Even where protected rates apply, the bill may include taxes, duties, fees, arrears or notified adjustments according to current rules. A very low energy charge therefore does not guarantee a near-zero payable amount.","Likewise, the difference between protected and non-protected totals cannot be estimated by changing one rate while leaving the calculation method untouched. The relevant slabs, fixed charges and additional items must all be checked for the same billing month."]},
      {heading:"How households accidentally cross a threshold",paragraphs:["Air-conditioners, electric water heating, old refrigerators, water pumps and long backup-battery charging can add more units than expected. A longer billing period can also raise billed units. Near a threshold, estimate the daily budget and track the meter weekly rather than waiting for the invoice.","Do not switch off essential cooling, medical equipment or safe water access merely to protect a tariff status. Efficiency should reduce waste, not create health or safety risk. Service appliances, improve insulation where practical and focus on the largest controllable loads."]},
      {heading:"How to check a disputed status",paragraphs:["Start with the printed category and status, then review the relevant history and meter readings. Compare this evidence with the official tariff definition effective for that billing period. If the account appears inconsistent, contact the provider with copies of the bills and readings.","Ask for a written explanation or complaint reference. An online calculator cannot change account status and should not be presented as proof that the provider is legally wrong. It can organise the facts and estimate the possible difference while the official review is pending."]},
      {heading:"Plan usage without false precision",paragraphs:["Create three scenarios: normal use, hot-weather use and an efficiency case. Keep a safety margin below any eligibility boundary instead of targeting the exact final unit. Meter timing, billing days and appliance behaviour make an exact prediction unrealistic.","Review the classification whenever the tariff is revised. Advice copied from an older bill or video may no longer reflect the definition, rates or extra charges in force. Record the source date beside every planning assumption."]}
    ],
    tables:[{caption:"Protected-status evidence checklist",headers:["Evidence","What to record","Common mistake"],rows:[["Current bill","Category, status, units, billing days","Looking only at payable total"],["Consumption history","Units for every required prior period","Using one low month"],["Meter evidence","Dated reading or photograph","Ignoring estimated readings"],["Tariff source","Notification and effective date","Using an undated social post"],["Complaint record","Reference number and documents","Relying on a calculator screenshot"]]}],
    example:{heading:"Worked example: one low month after a hot summer",paragraphs:["A household uses 170 units in September after several summer months above the relevant protected-consumer limit. The low September figure alone is not enough to declare the account protected."],steps:["Collect every bill required by the current history rule.","Check for estimated or corrected readings.","Match the connection category and load with the official definition.","Ask the provider to explain the printed status if the evidence still appears inconsistent."]},
    faqs:[{question:"Will using fewer units this month immediately make me protected?",answer:"Not necessarily. The applicable rule may consider a defined recent history and other connection conditions."},{question:"Can a protected consumer receive taxes or adjustments?",answer:"Yes. Protected treatment does not automatically remove every non-energy line on a bill."},{question:"Does a longer billing month affect the unit total?",answer:"It can. Always check billing days and meter readings when usage is close to a threshold."},{question:"Can SolvePilot confirm my legal status?",answer:"No. It can organise usage and estimate scenarios; the official account and applicable tariff control the status."},{question:"What should I do if the status appears wrong?",answer:"Keep bills and meter evidence, compare the current definition, then file a provider complaint and retain the reference number."}],
    relatedTools:["electricity-bill-calculator-pakistan","electricity-slab-rate-calculator-pakistan","monthly-units-target-calculator-pakistan","appliance-electricity-cost-calculator-pakistan"],relatedGuides:["how-electricity-bills-are-calculated-in-pakistan","lesco-kelectric-fesco-iesco-bill-slabs-compared","electricity-bill-taxes-and-charges-pakistan"],sources:[nepra,editorial],
    limitation:"Eligibility definitions and billing treatments can be amended. This guide does not classify an account or replace a provider decision, tariff document or regulatory complaint process."
  },
  {
    slug:"electricity-bill-taxes-and-charges-pakistan",
    title:"Pakistan Electricity Bill Taxes and Charges Explained",
    description:"Decode energy charges, fixed charges, GST, duties, fuel adjustments, quarterly adjustments, arrears and credits without mixing them together.",
    category:"Electricity",icon:"🧾",publishedAt,reviewedAt,readingMinutes:13,
    quickAnswer:"The amount due on an electricity bill is usually the result of several layers: energy and fixed charges, government taxes or duties, notified fuel and quarterly adjustments, account fees, and any arrears or credits. Not every line is calculated from current-month units, so each item should be checked separately.",
    takeaways:["Reconcile the base energy calculation before investigating adjustments.","Match every percentage or per-unit amount with its stated base and period.","Separate current consumption from account history such as arrears and late fees."],
    sections:[
      {heading:"Energy charges are the starting point",paragraphs:["Energy charges reflect billed kilowatt-hours under the applicable tariff method. Depending on category and status, units may be treated in slabs, at time-of-use rates or through another notified structure. The average rupees per unit shown by dividing the total bill by units is not the tariff rate.","Fixed or load-related charges may apply even when consumption is low. Because these amounts are spread over fewer units, they can make the effective rate look unusually high in a quiet month. Record them separately rather than forcing them into a slab calculation."]},
      {heading:"Taxes and duties need their own base",paragraphs:["A percentage printed beside a tax does not always apply to the final payable total. It may apply to a defined subtotal or be subject to consumer-specific rules. Recalculating it requires both the current rate and the legal base used on that bill.","Income-tax-related collection, sales tax, electricity duty and other government items can vary by category, status or jurisdiction. Their treatment may change through law or notification. For a material dispute, use the current official text and account details rather than a generic online percentage."]},
      {heading:"Fuel-cost adjustments",paragraphs:["A fuel-cost adjustment generally reflects the difference between a reference fuel cost and actual generation-related cost for a specified period. It may appear later than the electricity month to which the underlying cost relates. A positive amount increases the bill; a negative adjustment may create relief or credit where applicable.","Do not assume the adjustment is an error because it was absent last month. Match its label, units, rate and reference period with the relevant notification. Consumer categories or consumption groups may receive different treatment under a specific decision."]},
      {heading:"Quarterly and other tariff adjustments",paragraphs:["Quarterly adjustments recover or return specified power-sector costs under the regulatory framework. They can be shown as a per-unit amount or another bill component for an effective period. Like fuel adjustments, they should not be silently built into a permanent base tariff.","Financing, debt-related or other surcharges may also appear according to current policy. Names can look similar across bills while their legal bases differ. Preserve the exact label when researching an item; shortening everything to tax makes verification harder."]},
      {heading:"Arrears, late fees, instalments and credits",paragraphs:["Arrears are unpaid or carried amounts from the account, not electricity newly consumed. A late-payment surcharge arises from payment timing. Instalments may move a prior balance into the current due amount. Credits can result from overpayment, correction or a negative adjustment.","Reconcile these items against earlier bills and receipts. If a paid amount reappears as arrears, contact the provider with the payment evidence. A consumption calculator cannot resolve a ledger problem, but a month-by-month table can show where the balance entered the account."]},
      {heading:"A reliable bill-audit order",paragraphs:["First verify meter readings, units, category and base energy charges. Second, list fixed charges and account fees. Third, recalculate taxes only after identifying their base. Fourth, match adjustments to notifications. Finally, reconcile previous balance, payments, arrears and credits.","This sequence prevents one unexplained line from contaminating the whole calculation. It also produces a clearer complaint: instead of saying the bill is too high, you can identify the exact item, amount, period and evidence that needs review."]}
    ],
    tables:[{caption:"Common bill lines and how to verify them",headers:["Bill line","Usually relates to","Best check"],rows:[["Energy charge","Current billed units and tariff","Readings, category and official schedule"],["Fixed/load charge","Connection or sanctioned load","Category and tariff conditions"],["Tax or duty","A legally defined billing base","Current law, rate and consumer details"],["Fuel adjustment","A notified reference period","NEPRA decision and displayed units"],["Quarterly adjustment","A notified effective period","NEPRA notification"],["Arrears/credit","Account payment history","Earlier bills and receipts"]],note:"Labels differ by provider and period. Copy the wording from the actual bill before researching it."}],
    example:{heading:"Worked example: why 300 units are not simply multiplied once",paragraphs:["A household's bill shows an energy subtotal, a fixed charge, two notified adjustments, tax and a previous credit. Calculating 300 × one advertised rate cannot reproduce that invoice."],steps:["Recreate the 300-unit energy subtotal using the correct category.","Add the fixed charge as its own line.","Apply each adjustment only to the units or base shown.","Calculate taxes from their correct base.","Subtract the previous credit and compare with the payable amount."]},
    faqs:[{question:"Is GST included in the advertised unit rate?",answer:"Do not assume so. Check the tariff description and the separate lines on the bill."},{question:"Why did an adjustment appear months later?",answer:"Fuel and quarterly adjustments can be notified and billed after the period that created the underlying cost."},{question:"Can an adjustment be negative?",answer:"Some decisions may produce relief or credit. Confirm the applicable notification and consumer treatment."},{question:"Are arrears part of this month's electricity cost?",answer:"No. They belong to the account balance, although they increase the current amount due."},{question:"Why does my calculator differ from the bill?",answer:"The most common reasons are wrong category or status, omitted fixed charges, outdated rates, adjustments, taxes, arrears or an estimated reading."}],
    relatedTools:["electricity-bill-calculator-pakistan","electricity-tax-calculator-pakistan","fuel-price-adjustment-calculator-pakistan","electricity-bill-comparison-calculator-pakistan"],relatedGuides:["how-electricity-bills-are-calculated-in-pakistan","lesco-kelectric-fesco-iesco-bill-slabs-compared","protected-vs-unprotected-electricity-consumers-pakistan"],sources:[nepra,fbr,editorial],
    limitation:"Bill labels, rates, bases and exemptions change. This guide is educational and cannot determine the legal treatment of a specific account or replace the provider's detailed ledger."
  },
  {
    slug:"net-metering-solar-buyback-guide-pakistan",
    title:"Net Metering and Solar Buyback Guide for Pakistan",
    description:"Understand import, export, billing, application checks and payback assumptions without relying on an outdated buyback-rate claim.",
    category:"Solar",icon:"🔁",publishedAt,reviewedAt,readingMinutes:14,
    quickAnswer:"A grid-connected solar consumer can import electricity when demand exceeds generation and export eligible surplus under the arrangement approved for that connection. The financial result depends on current regulations, the applicable purchase and sale treatment, billing periods, daytime self-consumption, approved capacity and provider implementation—not panel size alone.",
    takeaways:["Confirm the currently available arrangement before buying equipment.","Value self-consumed solar separately from exported energy.","Model payback with a dated export assumption and a conservative generation estimate."],
    sections:[
      {heading:"Import, export and self-consumption",paragraphs:["Solar generation first serves loads operating behind the meter. When generation is lower than demand, the premises imports the difference. When eligible generation exceeds demand, the bidirectional meter records export. These three flows have different financial value and should not be merged into one monthly units figure.","Daytime self-consumption often offsets electricity that would otherwise be purchased under the consumer's tariff. Export is valued according to the approved regulatory and contractual treatment. If those values differ, moving flexible loads into solar hours can improve economics without increasing array size."]},
      {heading:"Net metering is not the same as backup",paragraphs:["A standard grid-tied inverter normally shuts down during an outage for anti-islanding safety, even under bright sun. Continued operation requires equipment designed and approved for backup, with appropriate isolation, batteries where needed and professional protection design.","Buyers sometimes pay for a large array expecting both low bills and whole-home backup. Those are separate design problems: energy offset concerns monthly kilowatt-hours, while backup concerns simultaneous watts, surge, duration and battery capacity."]},
      {heading:"Application and technical checks",paragraphs:["The applicant should confirm eligibility, sanctioned load, proposed generator capacity, inverter certification, protection, drawings, inspection steps, metering and the documents required by the relevant distribution company. Requirements and processing can change, so an installer's old checklist is not sufficient evidence.","Use qualified professionals for earthing, breakers, isolation, surge protection, cable sizing and structural work. Ask who owns the application process, what is included in the quotation and what happens if the requested capacity is not approved."]},
      {heading:"How billing should be modelled",paragraphs:["Build the model from hourly or at least daytime and night-time use. Monthly netting alone can hide whether production is actually consumed on site. Separate imported units, self-consumed solar and exported units, then apply the current treatment to each flow.","Check how credits, settlement periods, taxes and fixed charges are handled. A zero net-energy balance does not automatically mean a zero payable bill. Preserve non-energy charges and any rules that limit credit use or settlement."]},
      {heading:"Avoid fragile payback claims",paragraphs:["A responsible payback estimate uses conservative generation, realistic degradation and maintenance, the installed cost, financing cost if any, and dated tariff assumptions. It should show a range if export treatment is uncertain or under review.","Do not accept a proposal that values every generated unit at the highest retail rate. Some energy will be self-consumed, some exported and some lost. Shade, dust, temperature, clipping, downtime and seasonal weather reduce nameplate output."]},
      {heading:"Questions to ask an installer",paragraphs:["Request an itemised bill of materials, panel and inverter datasheets, warranties, expected monthly generation, loss assumptions, protection design, roof layout, application scope and after-sales responsibilities. Confirm serial numbers and warranty registration at handover.","Ask for separate scenarios with and without export income. A system that only looks attractive under one optimistic buyback rate is financially fragile. The homeowner should still understand the bill if regulations or tariffs change.","After commissioning, keep photographs of labels, settings, protection and meter readings with the single-line diagram. Compare actual monthly generation with the proposal, allowing for weather and outages, so underperformance is identified from evidence rather than memory."]}
    ],
    tables:[{caption:"Three solar-energy flows",headers:["Flow","What happens","Planning value"],rows:[["Self-consumed","Solar serves an appliance at the premises","Avoided eligible import cost"],["Exported","Surplus passes through the approved bidirectional meter","Current approved export treatment"],["Imported","Grid supplies the remaining load","Applicable retail tariff and charges"],["Battery charged","Energy is stored and later returned with losses","Avoided cost minus storage losses and ageing"]],note:"Never use a permanent rupees-per-unit value without recording the source and effective date."}],
    example:{heading:"Worked example: a 600-unit home",paragraphs:["A home uses 600 units in a month. Its system generates 500 units: 300 are consumed immediately and 200 are exported, while the home still imports 300 units at other times."],steps:["Value 300 self-consumed units using the eligible avoided import cost.","Value 200 exported units using the current approved treatment.","Price 300 imported units using the applicable retail calculation.","Add fixed charges, taxes and adjustments before estimating savings.","Repeat for summer and winter instead of multiplying one month by twelve."]},
    faqs:[{question:"Will solar keep my house running during load shedding?",answer:"Not automatically. Standard grid-tied systems usually disconnect during an outage; backup needs compatible equipment and safe isolation."},{question:"Is every exported unit worth the same as an imported unit?",answer:"Do not assume that. Confirm the current approved billing and settlement treatment for the connection."},{question:"Can I install any inverter and apply later?",answer:"Equipment and protection may need to meet current technical and certification requirements. Check before purchasing."},{question:"Does a larger system always pay back faster?",answer:"No. Roof, approval, self-consumption, export treatment, clipping and financing can make an oversized system less attractive."},{question:"What source should I trust for the buyback arrangement?",answer:"Use current NEPRA regulations and decisions plus the relevant distribution company's written process, not an undated sales claim."}],
    relatedTools:["solar-net-metering-savings-calculator-pakistan","solar-payback-calculator-pakistan","solar-system-calculator-pakistan","solar-panel-output-calculator-pakistan","solar-self-consumption-calculator-pakistan"],relatedGuides:["how-to-size-a-solar-system-in-pakistan","five-kw-vs-ten-kw-solar-system-pakistan","electricity-bill-taxes-and-charges-pakistan"],sources:[nepra,{name:"Alternative Energy Development Board",url:"https://www.aedb.org/",note:"Official renewable-energy information and applicable certification resources."},editorial],
    limitation:"Distributed-generation rules, eligibility, export treatment and provider processes can change. Obtain current written confirmation and a qualified technical design before purchase."
  },
];
