import type { Metadata } from "next";
import Link from "next/link";
import { CategoryBrowser } from "@/components/CategoryBrowser";
import { globalTools } from "@/lib/global-tools";

export const metadata:Metadata={title:"Free Online Calculators and Global Tools",description:"Use free global calculators for money, business, everyday decisions, technology, fitness and vehicles. Private calculations with explained formulas.",alternates:{canonical:"/tools/"}};

const copy:Record<string,string>={Money:"Plan savings, investment growth and borrowing with currency-neutral inputs and transparent assumptions.",Business:"Check pricing, tax, margins, break-even points and working time before making a commercial decision.",Everyday:"Solve shopping, dining, fitness and shared-expense calculations quickly without creating an account.",Technology:"Estimate downloads and resize digital media with clearly labelled technical units.",Vehicles:"Convert fuel-economy measurements correctly across regions and test standards."};

export default function GlobalToolsPage(){const categories=[...new Set(globalTools.map(tool=>tool.category))];return <div className="shell listing-page"><span className="eyebrow">Global SolvePilot collection</span><h1>Free online calculators for everyday decisions</h1><p>Choose a universal tool that works with your own currency and measurements. Calculations run privately in your browser, and every page explains its formula, assumptions and limits.</p><CategoryBrowser tools={globalTools} hrefPrefix="/tools"/><section className="category-explainers"><span className="eyebrow">Browse by purpose</span><h2>Global calculator collections</h2><div className="category-explainer-grid">{categories.map(category=><article key={category}><h3>{category} calculators</h3><p>{copy[category]}</p><div>{globalTools.filter(tool=>tool.category===category).slice(0,4).map(tool=><Link key={tool.slug} href={`/tools/${tool.slug}/`}>{tool.shortTitle} →</Link>)}</div></article>)}</div></section><section className="accuracy-note"><b>Looking for local calculations?</b> Pakistan tax, electricity, solar, property and marketplace tools remain in the <Link href="/pk/tools/">Pakistan tools directory</Link>.</section></div>}
