import {numberValue as n} from "./helpers";
import type {CalculatorResolver} from "./types";
const pct=(v:number)=>`${v.toFixed(2)}%`,multiple=(v:number)=>`${v.toFixed(2)}×`;
export const resolveEcommerce:CalculatorResolver=({slug,a,b,c,d,cash})=>{
 if(slug==="roas-calculator"){const roas=n(b)/(n(a)||1),needed=n(a)*n(c);return{labels:["Advertising spend","Attributed revenue","Target ROAS","Unused"],suffix:["currency","currency","×",""],calculate:()=>[{label:"Return on ad spend",value:multiple(roas),note:`${pct(roas*100)} revenue relative to ad spend`},{label:"Revenue needed at target",value:cash(needed)},{label:"Revenue gap to target",value:cash(needed-n(b))}]}}
 if(slug==="break-even-roas-calculator"){const net=n(a)*(1-n(d)/100),contribution=net-n(b)-n(c),roas=contribution>0?net/contribution:0;return{labels:["Average order value","Product cost","Shipping and payment fees","Expected return rate"],suffix:["currency","currency","currency","%"],calculate:()=>[{label:"Break-even ROAS",value:contribution>0?multiple(roas):"No positive contribution",note:"Advertising floor before overhead and profit"},{label:"Contribution before advertising",value:cash(contribution)},{label:"Contribution margin",value:pct(net?contribution/net*100:0)}]}}
 if(slug==="cost-per-acquisition-calculator"){const cpa=n(a)/(n(b)||1),allowed=n(b)*n(c);return{labels:["Advertising spend","Acquisitions","Target CPA","Unused"],suffix:["currency","customers","currency",""],calculate:()=>[{label:"Cost per acquisition",value:cash(cpa),note:"Media cost per entered conversion"},{label:"Allowed spend at target",value:cash(allowed)},{label:"Spend above or below target",value:cash(n(a)-allowed)}]}}
 if(slug==="customer-acquisition-cost-calculator"){const total=n(a)+n(b)+n(c),cac=total/(n(d)||1);return{labels:["Advertising cost","Sales and marketing payroll","Agencies, tools and incentives","New customers acquired"],suffix:["currency","currency","currency","customers"],calculate:()=>[{label:"Blended customer acquisition cost",value:cash(cac),note:"Based on the entered fully loaded cost scope"},{label:"Total acquisition cost",value:cash(total)},{label:"Cost per 100 new customers",value:cash(cac*100)}]}}
 if(slug==="customer-lifetime-value-calculator"){const revenue=n(a)*n(b)*n(c),gross=revenue*n(d)/100;return{labels:["Average order value","Purchases per customer per year","Customer lifespan","Gross margin"],suffix:["currency","purchases","years","%"],calculate:()=>[{label:"Gross-profit customer lifetime value",value:cash(gross),note:"Before acquisition cost, overhead and discounting"},{label:"Revenue lifetime value",value:cash(revenue)},{label:"Gross profit per customer-year",value:cash(n(a)*n(b)*n(d)/100)}]}}
 if(slug==="average-order-value-calculator"){const aov=n(a)/(n(b)||1),project=n(b)*n(c);return{labels:["Order revenue","Completed orders","Target AOV","Unused"],suffix:["currency","orders","currency",""],calculate:()=>[{label:"Average order value",value:cash(aov),note:"Use a consistent net or gross revenue definition"},{label:"Revenue at target AOV",value:cash(project)},{label:"Projected revenue change",value:cash(project-n(a))}]}}
 if(slug==="ecommerce-profit-per-order-calculator"){const profit=n(a)-n(b)-n(c)-n(d);return{labels:["Net selling revenue","Product cost","Shipping and payment fees","Advertising cost per order"],suffix:["currency","currency","currency","currency"],calculate:()=>[{label:"Contribution profit per order",value:cash(profit),note:"Before fixed overhead and tax"},{label:"Contribution margin",value:pct(n(a)?profit/n(a)*100:0)},{label:"Total variable cost",value:cash(n(b)+n(c)+n(d))}]}}
 if(slug==="discount-profit-impact-calculator"){const oldProfit=n(a)-n(b),newProfit=n(a)*(1-n(c)/100)-n(b),oldTotal=oldProfit*n(d),units=newProfit>0?oldTotal/newProfit:Infinity;return{labels:["Regular selling price","Direct unit cost","Proposed discount","Normal units sold"],suffix:["currency","currency","%","units"],calculate:()=>[{label:"Discounted unit profit",value:cash(newProfit),note:newProfit>0?"Before acquisition and overhead":"The discount removes unit contribution"},{label:"Units needed to preserve profit",value:Number.isFinite(units)?Math.ceil(units).toLocaleString():"Not achievable"},{label:"Additional units required",value:Number.isFinite(units)?Math.max(0,Math.ceil(units-n(d))).toLocaleString():"—"}]}}
 if(slug==="return-refund-impact-calculator"){const returned=n(a)*n(c)/100,refund=returned*n(b),impact=refund+returned*n(d);return{labels:["Completed orders","Average order value","Return or refund rate","Unrecoverable cost per return"],suffix:["orders","currency","%","currency"],calculate:()=>[{label:"Estimated total return impact",value:cash(impact),note:"Refunded revenue plus entered unrecoverable cost"},{label:"Estimated returned orders",value:returned.toFixed(1)},{label:"Refunded revenue",value:cash(refund)}]}}
 if(slug==="inventory-reorder-point-calculator"){const lead=n(a)*n(b),point=lead+n(c);return{labels:["Average daily demand","Lead time","Safety stock","Current inventory position"],suffix:["units/day","days","units","units"],calculate:()=>[{label:"Inventory reorder point",value:`${Math.ceil(point).toLocaleString()} units`,note:n(d)<=point?"Current position is at or below the trigger":"Current position remains above the trigger"},{label:"Expected lead-time demand",value:`${Math.ceil(lead).toLocaleString()} units`},{label:"Units above or below trigger",value:`${Math.round(n(d)-point).toLocaleString()} units`}]}}
 if(slug==="dimensional-weight-calculator"){const volume=n(a)*n(b)*n(c),dim=volume/(n(d)||1);return{labels:["Package length","Package width","Package height","Carrier dimensional divisor"],suffix:["cm","cm","cm","cm³/kg"],calculate:()=>[{label:"Dimensional weight",value:`${dim.toFixed(2)} kg`,note:"Compare with actual weight and apply carrier rounding"},{label:"Package volume",value:`${volume.toLocaleString()} cm³`},{label:"Volume in cubic metres",value:(volume/1e6).toFixed(4)}]}}
 if(slug==="ad-budget-sales-target-calculator"){const orders=n(a)/(n(b)||1),visits=orders/(n(c)/100||1),budget=orders*n(d);return{labels:["Net sales target","Average order value","Website conversion rate","Target cost per acquisition"],suffix:["currency","currency","%","currency"],calculate:()=>[{label:"Estimated advertising budget",value:cash(budget),note:"Scenario assumes stable CPA and conversion"},{label:"Orders required",value:Math.ceil(orders).toLocaleString()},{label:"Website visits required",value:Math.ceil(visits).toLocaleString()}]}}
 return null;
};
