import { formatPkr as money, numberValue as n } from "./helpers";
import type { CalculatorResolver } from "./types";

export const resolveEducationEveryday: CalculatorResolver = ({ slug, a, b, c, d, cash }) => {
  if(slug==="mdcat-aggregate-calculator-pakistan")return{labels:["Matric percentage","Intermediate percentage","MDCAT percentage"],suffix:["%","%","%"],calculate:()=>{const aggregate=n(a)*.10+n(b)*.40+n(c)*.50;return[{label:"Estimated MDCAT aggregate",value:`${aggregate.toFixed(2)}%`,note:"Uses editable-score inputs with planning weights of 10%, 40% and 50%"},{label:"Academic contribution",value:`${(n(a)*.10+n(b)*.40).toFixed(2)} points`},{label:"MDCAT contribution",value:`${(n(c)*.50).toFixed(2)} points`}]}};
  if(slug==="ecat-aggregate-calculator-pakistan")return{labels:["Matric percentage","Intermediate percentage","Entry-test percentage"],suffix:["%","%","%"],calculate:()=>{const aggregate=n(a)*.10+n(b)*.40+n(c)*.50;return[{label:"Estimated ECAT aggregate",value:`${aggregate.toFixed(2)}%`,note:"Confirm current weights with the target university"},{label:"Academic contribution",value:`${(n(a)*.10+n(b)*.40).toFixed(2)} points`},{label:"Test contribution",value:`${(n(c)*.50).toFixed(2)} points`}]}};
  if(slug==="university-merit-calculator-pakistan")return{labels:["Combined academic percentage","Admission-test percentage","Test weight"],suffix:["%","%","%"],calculate:()=>{const weight=Math.min(100,n(c)),merit=n(a)*(100-weight)/100+n(b)*weight/100;return[{label:"Estimated university merit",value:`${merit.toFixed(2)}%`,note:"Use the institution's official academic grouping and test weight"},{label:"Academic contribution",value:`${(n(a)*(100-weight)/100).toFixed(2)} points`},{label:"Test contribution",value:`${(n(b)*weight/100).toFixed(2)} points`}]}};
  if(slug==="semester-gpa-calculator")return{labels:["Total semester quality points","Attempted credit hours","Maximum GPA scale"],suffix:["points","credits","GPA"],calculate:()=>{const raw=n(a)/(n(b)||1),gpa=Math.min(n(c)||4,raw);return[{label:"Calculated semester GPA",value:gpa.toFixed(2),note:"Quality points must use the institution's grade-point scale"},{label:"Average quality points",value:raw.toFixed(3)},{label:"Credit hours entered",value:n(b).toFixed(1)}]}};
  if(slug==="required-final-exam-marks-calculator")return{labels:["Weighted points already earned","Target overall grade","Final-exam weight"],suffix:["points","%","%"],calculate:()=>{const required=(n(b)-n(a))/(n(c)/100||1),possible=required<=100;return[{label:"Required final-exam score",value:required<=0?"Target already secured":`${Math.max(0,required).toFixed(2)}%`,note:possible?"Assumes entered points exclude the final exam":"Target is not reachable with the entered final weight"},{label:"Maximum possible overall",value:`${Math.min(100,n(a)+n(c)).toFixed(2)}%`},{label:"Final weight",value:`${n(c)}%`}]}};
  if(slug==="study-time-planner")return{labels:["Total chapters or units","Already completed","Days available","Study hours per day"],suffix:["chapters","chapters","days","hours"],calculate:()=>{const remaining=Math.max(0,n(a)-n(b)),daily=remaining/(n(c)||1),minutes=n(d)*60/(daily||1);return[{label:"Daily chapter target",value:`${daily.toFixed(2)} chapters`,note:"Round up selectively and reserve review days"},{label:"Chapters remaining",value:Math.ceil(remaining).toLocaleString("en-PK")},{label:"Minutes available per chapter",value:`${minutes.toFixed(0)} minutes`}]}};
  if(slug==="age-calculator")return{labels:["Birth year","Birth month","Birth day"],suffix:["YYYY","MM","DD"],calculate:()=>{const today=new Date(),birth=new Date(Math.floor(n(a)),Math.max(0,Math.floor(n(b))-1),Math.max(1,Math.floor(n(c)))),valid=birth.getFullYear()===Math.floor(n(a))&&birth.getMonth()===Math.floor(n(b))-1&&birth.getDate()===Math.floor(n(c));let years=today.getFullYear()-birth.getFullYear();if(today.getMonth()<birth.getMonth()||(today.getMonth()===birth.getMonth()&&today.getDate()<birth.getDate()))years--;const days=valid?Math.max(0,Math.floor((today.getTime()-birth.getTime())/86400000)):0;return[{label:"Current age",value:valid&&years>=0?`${years} years`:"Check the birth date",note:"Calculated against today's device date"},{label:"Approximate age in days",value:days.toLocaleString("en-PK")},{label:"Birth date",value:valid?birth.toLocaleDateString("en-PK"):"Invalid date"}]}};
  if(slug==="date-duration-calculator")return{labels:["Start date","End date","Unused"],suffix:["YYYYMMDD","YYYYMMDD",""],calculate:()=>{const parse=(v:number)=>{const s=String(Math.floor(v)).padStart(8,"0"),y=Number(s.slice(0,4)),m=Number(s.slice(4,6)),day=Number(s.slice(6,8)),date=new Date(Date.UTC(y,m-1,day));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===day?date:null},start=parse(n(a)),end=parse(n(b)),days=start&&end?Math.round((end.getTime()-start.getTime())/86400000):0,abs=Math.abs(days);return[{label:"Elapsed calendar duration",value:start&&end?`${abs.toLocaleString("en-PK")} days`:"Check both dates",note:days<0?"End date is earlier than start date":"Dates are interpreted as YYYYMMDD"},{label:"Approximate weeks",value:(abs/7).toFixed(2)},{label:"Approximate months",value:(abs/30.4375).toFixed(2)}]}};
  if(slug==="bmi-calculator")return{labels:["Body weight","Height","Unused"],suffix:["kg","cm",""],calculate:()=>{const metres=n(b)/100,bmi=n(a)/(metres*metres||1),range=bmi<18.5?"Below standard adult range":bmi<25?"Within standard adult range":bmi<30?"Above standard adult range":"Well above standard adult range";return[{label:"Calculated BMI",value:bmi.toFixed(1),note:`${range}; BMI is only a screening measure`},{label:"Standard-range lower weight",value:`${(18.5*metres*metres).toFixed(1)} kg`},{label:"Standard-range upper weight",value:`${(24.9*metres*metres).toFixed(1)} kg`}]}};
  if(slug==="daily-calorie-requirement-estimator")return{labels:["Body weight","Height","Age","Activity factor"],suffix:["kg","cm","years","×"],calculate:()=>{const bmr=10*n(a)+6.25*n(b)-5*n(c)+5,maintenance=bmr*n(d);return[{label:"Estimated maintenance calories",value:`${Math.round(maintenance).toLocaleString("en-PK")} kcal/day`,note:"Uses the male Mifflin–St Jeor planning equation"},{label:"Estimated basal metabolism",value:`${Math.round(bmr).toLocaleString("en-PK")} kcal/day`},{label:"Weekly maintenance",value:`${Math.round(maintenance*7).toLocaleString("en-PK")} kcal`}]}};
  if(slug==="daily-water-intake-estimator")return{labels:["Body weight","Daily exercise duration","Hot-weather allowance"],suffix:["kg","minutes","ml/day"],calculate:()=>{const base=n(a)*35,exercise=n(b)/30*350,total=base+exercise+n(c);return[{label:"Estimated daily water target",value:`${(total/1000).toFixed(2)} litres`,note:"Food, medical conditions and clinician advice can change needs"},{label:"Weight-based starting amount",value:`${Math.round(base).toLocaleString("en-PK")} ml`},{label:"Exercise allowance",value:`${Math.round(exercise).toLocaleString("en-PK")} ml`}]}};
  if(slug==="internet-package-comparison-calculator-pakistan")return{labels:["Package A monthly price","Package A data","Package B monthly price","Package B data"],suffix:["PKR","GB","PKR","GB"],calculate:()=>{const first=n(a)/(n(b)||1),second=n(c)/(n(d)||1);return[{label:"Lower effective cost per GB",value:money(Math.min(first,second)),note:first===second?"Both packages have equal entered data value":first<second?"Package A costs less per GB":"Package B costs less per GB"},{label:"Package A cost per GB",value:money(first)},{label:"Package B cost per GB",value:money(second)}]}};
  if(slug==="internet-speed-requirement-calculator")return{labels:["Simultaneous 4K streams","Simultaneous HD streams","Gaming devices","Other active users"],suffix:["streams","streams","devices","users"],calculate:()=>{const raw=n(a)*25+n(b)*8+n(c)*5+n(d)*3,recommended=Math.ceil(raw*1.2/5)*5;return[{label:"Recommended internet speed",value:`${recommended} Mbps`,note:"Includes 20% planning headroom"},{label:"Calculated active demand",value:`${raw} Mbps`},{label:"Headroom",value:`${recommended-raw} Mbps`}]}};
  if(slug==="data-package-cost-per-gb-calculator-pakistan")return{labels:["Package price","Included usable data","Comparison cost per GB"],suffix:["PKR","GB","PKR/GB"],calculate:()=>{const rate=n(a)/(n(b)||1),difference=rate-n(c);return[{label:"Effective package cost",value:`${money(rate)} per GB`,note:"Exclude data that expires or cannot be used for your intended apps"},{label:"Difference from comparison",value:money(difference)},{label:"Total included data",value:`${n(b).toFixed(1)} GB`}]}};
  if(slug==="whatsapp-data-usage-calculator")return{labels:["Daily messages and media data","Daily voice-call time","Daily video-call time","Days of use"],suffix:["MB/day","minutes","minutes","days"],calculate:()=>{const daily=n(a)+n(b)*.5+n(c)*5,total=daily*n(d);return[{label:"Estimated WhatsApp data use",value:`${(total/1024).toFixed(2)} GB`,note:"Call codecs, media downloads and backups can change usage"},{label:"Estimated daily use",value:`${daily.toFixed(1)} MB`},{label:"Voice and video portion",value:`${((n(b)*.5+n(c)*5)*n(d)/1024).toFixed(2)} GB`}]}};
  if(slug==="youtube-data-usage-calculator")return{labels:["Watch time per day","Average video bitrate","Days watched"],suffix:["hours","Mbps","days"],calculate:()=>{const gb=n(a)*3600*n(b)*n(c)/8000;return[{label:"Estimated YouTube data use",value:`${gb.toFixed(1)} GB`,note:"Actual adaptive bitrate changes with quality, content and network"},{label:"Estimated daily use",value:`${(gb/(n(c)||1)).toFixed(2)} GB`},{label:"Estimated hourly use",value:`${(n(b)*3600/8000).toFixed(2)} GB`}]}};
  return null;
};
