import {numberValue as n} from "./helpers";
import type {CalculatorResolver} from "./types";

const monthsToText=(months:number)=>months>=1200?"More than 100 years":`${Math.floor(months/12)} years ${months%12} months`;
const simulateDebt=(balances:number[],rates:number[],minimums:number[],extra:number,mode:"snowball"|"avalanche")=>{let months=0,interest=0;const b=[...balances];while(b.some(x=>x>.01)&&months<1200){for(let i=0;i<b.length;i++){if(b[i]<=0)continue;const charge=b[i]*rates[i]/1200;b[i]+=charge;interest+=charge;const paid=Math.min(b[i],minimums[i]);b[i]-=paid}let available=extra;while(available>.01&&b.some(x=>x>.01)){const open=b.map((x,i)=>({x,i})).filter(v=>v.x>.01).sort((x,y)=>mode==="snowball"?x.x-y.x:rates[y.i]-rates[x.i]);const i=open[0].i,pay=Math.min(b[i],available);b[i]-=pay;available-=pay}months++}return{months,interest};};

export const resolveFinanceExpansion:CalculatorResolver=({slug,a,b,c,d,e,cash})=>{
 if(slug==="debt-snowball-vs-avalanche-calculator"){const balances=[n(a),n(c)],rates=[n(b),n(d)],minimums=balances.map(x=>Math.max(25,x*.025)),extra=n(e),s=simulateDebt(balances,rates,minimums,extra,"snowball"),v=simulateDebt(balances,rates,minimums,extra,"avalanche");return{labels:["Debt 1 balance","Debt 1 annual rate","Debt 2 balance","Debt 2 annual rate","Extra monthly payment"],suffix:["currency","%","currency","%","currency"],calculate:()=>[{label:s.interest<=v.interest?"Snowball estimated interest":"Avalanche estimated interest",value:cash(Math.min(s.interest,v.interest)),note:"Uses the entered extra monthly payment"},{label:"Snowball payoff",value:monthsToText(s.months)},{label:"Avalanche payoff",value:`${monthsToText(v.months)} · ${cash(v.interest)} interest`}]}}
 if(slug==="credit-card-minimum-payment-calculator"){let balance=n(a),months=0,interest=0;const r=n(b)/1200;while(balance>.01&&months<1200){const charge=balance*r;interest+=charge;balance+=charge;const pay=Math.min(balance,Math.max(balance*n(c)/100,n(d)));if(pay<=charge+.01){months=1200;break}balance-=pay;months++}return{labels:["Current card balance","Annual interest rate","Minimum payment percentage","Minimum payment floor"],suffix:["currency","%","%","currency"],calculate:()=>[{label:"Estimated payoff time",value:monthsToText(months),note:"Assumes no new purchases or fees"},{label:"Estimated interest",value:cash(interest)},{label:"First minimum payment",value:cash(Math.max(n(a)*n(c)/100,n(d)))}]}}
 if(slug==="credit-card-payoff-calculator"){let balance=n(a),months=0,interest=0;const r=n(b)/1200;while(balance>.01&&months<1200){const charge=balance*r;if(n(c)<=charge){months=1200;break}interest+=charge;balance=Math.max(0,balance+charge-n(c));months++}return{labels:["Card balance","Annual interest rate","Fixed monthly payment","Unused"],suffix:["currency","%","currency",""],calculate:()=>[{label:"Estimated payoff time",value:monthsToText(months),note:"Fixed rate and no new transactions"},{label:"Total interest",value:cash(interest)},{label:"Total paid",value:cash(n(a)+interest)}]}}
 if(slug==="credit-card-utilization-calculator"){const one=n(b)?n(a)/n(b)*100:0,all=n(d)?(n(a)+n(c))/n(d)*100:0;return{labels:["Selected card balance","Selected card limit","Total card balances","Total credit limits"],suffix:["currency","currency","currency","currency"],calculate:()=>[{label:"Selected-card utilization",value:`${one.toFixed(1)}%`,note:"Based on the balance and limit entered"},{label:"Overall utilization",value:`${all.toFixed(1)}%`},{label:"Available revolving credit",value:cash(Math.max(0,n(d)-n(c)))}]}}
 if(slug==="investment-fee-calculator"){const project=(fee:number)=>{let x=n(a);for(let i=0;i<Math.round(n(e)*12);i++)x=x*(1+(n(c)-fee)/1200)+n(b);return x},free=project(0),net=project(n(d));return{labels:["Starting investment","Monthly contribution","Gross annual return","Annual fee","Years"],suffix:["currency","currency","%","%","years"],calculate:()=>[{label:"Projected balance after fees",value:cash(net),note:"Constant return and fee assumptions"},{label:"Balance before fee drag",value:cash(free)},{label:"Estimated fee drag",value:cash(free-net)}]}}
 if(slug==="inflation-adjusted-return-calculator"){const nominal=n(a)/100,fees=n(c)/100,inflation=n(b)/100,real=((1+nominal-fees)/(1+inflation)-1)*100;return{labels:["Nominal annual return","Annual inflation","Annual fees","Unused"],suffix:["%","%","%",""],calculate:()=>[{label:"Inflation-adjusted real return",value:`${real.toFixed(2)}%`,note:"Uses the exact geometric relationship"},{label:"Return after fees",value:`${((nominal-fees)*100).toFixed(2)}%`},{label:"Purchasing-power growth on 10,000",value:cash(10000*real/100)}]}}
 if(slug==="dollar-cost-averaging-calculator"){let balance=n(a);const months=Math.max(1,Math.round(n(d)*12)),r=n(c)/1200;for(let i=0;i<months;i++)balance=balance*(1+r)+n(b);const contributions=n(a)+n(b)*months;return{labels:["Starting amount","Monthly investment","Assumed annual return","Years"],suffix:["currency","currency","%","years"],calculate:()=>[{label:"Projected portfolio value",value:cash(balance),note:"Constant illustrative return; not a forecast"},{label:"Total contributed",value:cash(contributions)},{label:"Projected growth",value:cash(balance-contributions)}]}}
 if(slug==="lump-sum-vs-dca-calculator"){const months=Math.max(1,Math.round(n(c))),r=n(b)/1200,totalMonths=Math.max(months,Math.round(n(d)*12)),lump=n(a)*Math.pow(1+r,totalMonths);let staged=0;for(let i=0;i<totalMonths;i++){staged*=1+r;if(i<months)staged+=n(a)/months}return{labels:["Available amount","Assumed annual return","DCA schedule","Total comparison period"],suffix:["currency","%","months","years"],calculate:()=>[{label:lump>=staged?"Lump-sum projected value":"DCA projected value",value:cash(Math.max(lump,staged)),note:"Assumes uninvested DCA cash earns zero"},{label:"Lump-sum value",value:cash(lump)},{label:"DCA value",value:cash(staged)}]}}
 if(slug==="coast-fire-calculator"){const years=Math.max(0,n(b)-n(a)),target=n(c)/(n(d)/100||.04),real=n(e)/100,coast=target/Math.pow(1+real,years);return{labels:["Current age","Target retirement age","Annual retirement spending","Withdrawal rate","Expected real return"],suffix:["years","years","currency","%","%"],calculate:()=>[{label:"Estimated Coast FIRE number today",value:cash(coast),note:"Uses the entered inflation-adjusted return"},{label:"Full retirement target",value:cash(target)},{label:"Years available to compound",value:`${years} years`}]}}
 if(slug==="fire-number-calculator"){const target=n(a)/(n(b)/100||.04),gap=Math.max(0,target-n(c));return{labels:["Expected annual spending","Withdrawal rate","Current invested assets","Unused"],suffix:["currency/year","%","currency",""],calculate:()=>[{label:"Estimated FIRE number",value:cash(target),note:"A planning target, not a safe-withdrawal guarantee"},{label:"Current funding gap",value:cash(gap)},{label:"Current target coverage",value:`${(target?n(c)/target*100:0).toFixed(1)}%`}]}}
 if(slug==="savings-rate-calculator"){const rate=n(a)?n(b)/n(a)*100:0;return{labels:["Monthly take-home income","Monthly amount saved","Employer contribution","Unused"],suffix:["currency","currency","currency",""],calculate:()=>[{label:"Personal savings rate",value:`${rate.toFixed(1)}%`,note:"Based on take-home income and personal saving"},{label:"Annual personal saving",value:cash(n(b)*12)},{label:"Annual saving including employer",value:cash((n(b)+n(c))*12)}]}}
 if(slug==="dividend-reinvestment-calculator"){let balance=n(a),dividends=0;for(let i=0;i<Math.round(n(d));i++){const div=balance*n(b)/100;dividends+=div;balance=balance*(1+n(c)/100)+div}return{labels:["Starting portfolio","Annual dividend yield","Annual price growth","Years"],suffix:["currency","%","%","years"],calculate:()=>[{label:"Projected value with reinvestment",value:cash(balance),note:"Constant yield and growth are illustrative"},{label:"Cumulative dividends reinvested",value:cash(dividends)},{label:"Initial capital",value:cash(n(a))}]}}
 if(slug==="portfolio-rebalancing-calculator"){const total=n(a)+n(b),target=Math.min(100,Math.max(0,n(c))),assetATarget=total*target/100,trade=assetATarget-n(a);return{labels:["Current Asset A value","Current Asset B value","Target Asset A weight","Unused"],suffix:["currency","currency","%",""],calculate:()=>[{label:trade>=0?"Buy Asset A":"Sell Asset A",value:cash(Math.abs(trade)),note:"Assumes only two assets and no new cash"},{label:"Target Asset A value",value:cash(assetATarget)},{label:"Target Asset B value",value:cash(total-assetATarget)}]}}
 if(slug==="capital-gains-calculator-global"){const gain=n(a)-n(b)-n(c),tax=Math.max(0,gain)*n(d)/100;return{labels:["Sale proceeds","Cost basis","Selling costs and adjustments","Entered tax rate"],suffix:["currency","currency","currency","%"],calculate:()=>[{label:"Estimated capital gain",value:cash(gain),note:"Before jurisdiction-specific exemptions and loss offsets"},{label:"Estimated tax at entered rate",value:cash(tax)},{label:"Proceeds after basis, costs and tax",value:cash(n(a)-n(c)-tax)}]}}
 if(slug==="tiered-commission-calculator"){const first=Math.min(n(a),n(b))*n(c)/100,second=Math.max(0,n(a)-n(b))*n(d)/100,total=first+second;return{labels:["Total eligible sales","Tier threshold","Rate below threshold","Rate above threshold"],suffix:["currency","currency","%","%"],calculate:()=>[{label:"Total progressive commission",value:cash(total),note:"Higher rate applies only above the threshold"},{label:"Blended commission rate",value:`${(n(a)?total/n(a)*100:0).toFixed(2)}%`},{label:"Sales above threshold",value:cash(Math.max(0,n(a)-n(b)))}]}}
 if(slug==="prorated-salary-calculator"){const payable=Math.max(0,n(b)-n(d)),pay=n(a)*payable/(n(c)||1);return{labels:["Full-period salary","Eligible days worked","Total eligible days","Unpaid leave days"],suffix:["currency","days","days","days"],calculate:()=>[{label:"Estimated prorated gross salary",value:cash(pay),note:"Before tax, benefits and payroll deductions"},{label:"Payable days",value:`${payable} days`},{label:"Daily proration rate",value:cash(n(a)/(n(c)||1))}]}}
 if(slug==="pay-raise-percentage-calculator"){const raise=n(b)-n(a),pct=n(a)?raise/n(a)*100:0;return{labels:["Current annual pay","New annual pay","Unused"],suffix:["currency","currency",""],calculate:()=>[{label:"Pay change",value:`${pct.toFixed(2)}%`,note:raise>=0?"Gross increase before deductions":"Gross decrease before deductions"},{label:"Annual amount change",value:cash(raise)},{label:"Monthly amount change",value:cash(raise/12)}]}}
 if(slug==="overtime-pay-calculator-global"){const regular=n(a)*n(b),ot=n(c)*n(a)*n(d);return{labels:["Base hourly rate","Regular hours","Overtime hours","Overtime multiplier"],suffix:["currency/hour","hours","hours","×"],calculate:()=>[{label:"Estimated gross pay",value:cash(regular+ot),note:"Before deductions and local payroll rules"},{label:"Regular pay",value:cash(regular)},{label:"Overtime pay",value:cash(ot)}]}}
 if(slug==="invoice-due-date-calculator"||slug==="net-payment-terms-calculator"){const start=new Date(`${a}T00:00:00Z`),add=(days:number)=>{const x=new Date(start);x.setUTCDate(x.getUTCDate()+days);return Number.isNaN(x.getTime())?"Enter a valid date":x.toLocaleDateString("en-GB",{timeZone:"UTC",day:"2-digit",month:"short",year:"numeric"})};if(slug==="invoice-due-date-calculator")return{labels:["Invoice date","Payment term in days","Unused"],suffix:["date","days",""],calculate:()=>[{label:"Calculated invoice due date",value:add(n(b)),note:"Uses calendar days"},{label:"Payment term",value:`Net ${Math.round(n(b))}`},{label:"Starting date",value:add(0)}]};return{labels:["Invoice or delivery date","Unused"],suffix:["date",""],calculate:()=>[{label:"Net 30 deadline",value:add(30),note:"Calendar-day comparison"},{label:"Net 60 deadline",value:add(60)},{label:"Net 90 deadline",value:add(90)}]}}
 if(slug==="invoice-discount-calculator"){const discount=n(a)*n(b)/100;return{labels:["Invoice amount","Early-payment discount","Days paid early","Unused"],suffix:["currency","%","days",""],calculate:()=>[{label:"Discounted customer payment",value:cash(n(a)-discount),note:"Eligibility must be confirmed separately"},{label:"Discount amount",value:cash(discount)},{label:"Simple annualized discount cost",value:`${(n(a)&&n(c)?discount/(n(a)-discount)*365/n(c)*100:0).toFixed(1)}%`}]}}
 if(slug==="freelance-project-profit-calculator"){const fee=n(a)*n(b)/100,labour=n(c)*n(d),profit=n(a)-fee-labour-n(e);return{labels:["Project revenue","Platform and payment fees","Project hours","Internal hourly cost","Direct project expenses"],suffix:["currency","%","hours","currency/hour","currency"],calculate:()=>[{label:"Estimated economic profit",value:cash(profit),note:"Before tax and general business overhead"},{label:"Fees and direct expenses",value:cash(fee+n(e))},{label:"Labour value",value:cash(labour)}]}}
 if(slug==="saas-pricing-calculator"){const price=n(a)/(1-n(b)/100||.01),contribution=price-n(a),customers=n(c)/(contribution||1);return{labels:["Variable cost per customer","Target gross margin","Monthly fixed costs","Unused"],suffix:["currency","%","currency",""],calculate:()=>[{label:"Price before fixed-cost allocation",value:cash(price),note:"Excludes tax and acquisition cost"},{label:"Contribution per customer",value:cash(contribution)},{label:"Customers to cover fixed costs",value:Math.ceil(customers).toLocaleString()}]}}
 if(slug==="debt-service-coverage-ratio-calculator"){const service=n(b)+n(c),ratio=service?n(a)/service:0;return{labels:["Net operating income","Principal payments","Interest payments","Unused"],suffix:["currency/period","currency/period","currency/period",""],calculate:()=>[{label:"Debt service coverage ratio",value:`${ratio.toFixed(2)}×`,note:"Use income and debt service from the same period"},{label:"Total debt service",value:cash(service)},{label:"Income after debt service",value:cash(n(a)-service)}]}}
 if(slug==="merchant-processing-fee-calculator"){const fee=n(a)*n(b)/100+n(c),effective=n(a)?fee/n(a)*100:0;return{labels:["Transaction amount","Percentage fee","Fixed fee","Unused"],suffix:["currency","%","currency",""],calculate:()=>[{label:"Net payment proceeds",value:cash(n(a)-fee),note:"Before refunds, tax and cross-border charges"},{label:"Processing fee",value:cash(fee)},{label:"Effective fee rate",value:`${effective.toFixed(2)}%`}]}}
 return null;
};
