import { formatPkr as money, numberValue as n } from "./helpers";
import type { CalculatorResolver } from "./types";

export const resolveGlobal: CalculatorResolver = ({ slug, a, b, c, d, cash }) => {
  if(slug==="compound-interest-calculator")return{labels:["Starting amount","Annual return","Investment period"],suffix:["currency","%","years"],calculate:()=>{const months=Math.round(n(c)*12),future=n(a)*Math.pow(1+n(b)/1200,months);return[{label:"Projected future value",value:cash(future),note:"Monthly compounding before tax, fees and inflation"},{label:"Projected growth",value:cash(future-n(a))},{label:"Total return",value:`${n(a)?((future/n(a)-1)*100).toFixed(1):0}%`} ]}};
  if(slug==="savings-goal-calculator")return{labels:["Savings target","Already saved","Months remaining"],suffix:["currency","currency","months"],calculate:()=>{const gap=Math.max(0,n(a)-n(b));return[{label:"Required monthly saving",value:cash(gap/(n(c)||1)),note:"Equal monthly contributions before interest"},{label:"Remaining gap",value:cash(gap)},{label:"Progress",value:`${n(a)?Math.min(100,n(b)/n(a)*100).toFixed(1):0}%`} ]}};
  if(slug==="mortgage-payment-calculator")return{labels:["Mortgage principal","Annual interest rate","Loan term"],suffix:["currency","%","years"],calculate:()=>{const months=Math.max(1,Math.round(n(c)*12)),r=n(b)/1200,p=r?n(a)*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1):n(a)/months,total=p*months;return[{label:"Monthly principal and interest",value:cash(p),note:"Excludes taxes, insurance and fees"},{label:"Total scheduled repayment",value:cash(total)},{label:"Total interest",value:cash(total-n(a))}]}};
  if(slug==="discount-calculator")return{labels:["Original price","Discount rate","Tax or service rate"],suffix:["currency","%","%"],calculate:()=>{const saving=n(a)*n(b)/100,sale=n(a)-saving,final=sale*(1+n(c)/100);return[{label:"Final price",value:cash(final),note:"After discount and entered additional rate"},{label:"Amount saved",value:cash(saving)},{label:"Sale price before extras",value:cash(sale)}]}};
  if(slug==="sales-tax-vat-calculator")return{labels:["Net or gross amount","Tax or VAT rate","Mode (0 add, 1 remove)"],suffix:["currency","%","0 / 1"],calculate:()=>{const remove=n(c)>=1,net=remove?n(a)/(1+n(b)/100):n(a),tax=remove?n(a)-net:n(a)*n(b)/100,gross=net+tax;return[{label:remove?"Net amount":"Gross amount",value:cash(remove?net:gross),note:remove?"Tax removed from entered gross amount":"Tax added to entered net amount"},{label:"Tax amount",value:cash(tax)},{label:remove?"Gross entered":"Net entered",value:cash(remove?n(a):net)}]}};
  if(slug==="profit-margin-calculator-global")return{labels:["Sales revenue","Direct cost","Unused"],suffix:["currency","currency",""],calculate:()=>{const profit=n(a)-n(b),margin=n(a)?profit/n(a)*100:0,markup=n(b)?profit/n(b)*100:0;return[{label:"Gross profit",value:cash(profit),note:`${margin.toFixed(1)}% gross margin`},{label:"Profit margin",value:`${margin.toFixed(1)}%`},{label:"Markup on cost",value:`${markup.toFixed(1)}%`}]}};
  if(slug==="business-break-even-calculator")return{labels:["Fixed costs","Selling price per unit","Variable cost per unit"],suffix:["currency","currency","currency"],calculate:()=>{const contribution=n(b)-n(c),units=contribution>0?Math.ceil(n(a)/contribution):0;return[{label:contribution>0?"Break-even sales volume":"No break-even point",value:contribution>0?`${units.toLocaleString()} units`:"Price must exceed variable cost",note:"Based on one product and constant costs"},{label:"Break-even revenue",value:cash(units*n(b))},{label:"Contribution per unit",value:cash(contribution)}]}};
  if(slug==="tip-calculator")return{labels:["Bill amount","Tip percentage","Number of people"],suffix:["currency","%","people"],calculate:()=>{const tip=n(a)*n(b)/100,total=n(a)+tip;return[{label:"Total with tip",value:cash(total),note:`Split between ${Math.max(1,n(c))} people`},{label:"Tip amount",value:cash(tip)},{label:"Per person",value:cash(total/(n(c)||1))}]}};
  if(slug==="split-bill-calculator")return{labels:["Bill amount","Tip or service rate","Number of people","Shared extras"],suffix:["currency","%","people","currency"],calculate:()=>{const total=n(a)*(1+n(b)/100)+n(d);return[{label:"Amount per person",value:cash(total/(n(c)||1)),note:"Equal split"},{label:"Combined total",value:cash(total)},{label:"Added tip/service",value:cash(n(a)*n(b)/100)}]}};
  if(slug==="unit-price-comparison-calculator")return{labels:["Pack A price","Pack A quantity","Pack B price","Pack B quantity"],suffix:["currency","units","currency","units"],calculate:()=>{const ua=n(a)/(n(b)||1),ub=n(c)/(n(d)||1),winner=ua<=ub?"Pack A":"Pack B";return[{label:"Lower unit price",value:winner,note:`${cash(Math.min(ua,ub))} per unit`},{label:"Pack A per unit",value:cash(ua)},{label:"Pack B per unit",value:cash(ub)}]}};
  if(slug==="work-hours-calculator")return{labels:["Start time (24-hour decimal)","End time (24-hour decimal)","Unpaid break","Hourly rate"],suffix:["hour","hour","hours","currency"],calculate:()=>{const elapsed=(n(b)>=n(a)?n(b)-n(a):24-n(a)+n(b)),paid=Math.max(0,elapsed-n(c));return[{label:"Paid work time",value:`${paid.toFixed(2)} hours`,note:"Supports an overnight end time"},{label:"Estimated gross pay",value:cash(paid*n(d))},{label:"Elapsed shift",value:`${elapsed.toFixed(2)} hours`}]}};
  if(slug==="running-pace-calculator")return{labels:["Distance","Elapsed time","Unit (0 km, 1 mile)"],suffix:["km or mi","minutes","0 / 1"],calculate:()=>{const pace=n(b)/(n(a)||1),minutes=Math.floor(pace),seconds=Math.round((pace-minutes)*60),speed=n(a)/(n(b)/60||1);return[{label:"Average pace",value:`${minutes}:${String(seconds).padStart(2,"0")} per ${n(c)>=1?"mile":"km"}`,note:"Even-pace average"},{label:"Average speed",value:`${speed.toFixed(2)} ${n(c)>=1?"mph":"km/h"}`},{label:"5-unit projection",value:`${(pace*5).toFixed(1)} minutes`}]}};
  if(slug==="aspect-ratio-calculator")return{labels:["Original width","Original height","New width"],suffix:["px","px","px"],calculate:()=>{const height=n(c)*n(b)/(n(a)||1),gcd=(x:number,y:number):number=>y?gcd(y,x%y):x,div=gcd(Math.round(n(a)),Math.round(n(b)))||1;return[{label:"Proportional new height",value:`${Math.round(height)} px`,note:"No cropping"},{label:"Aspect ratio",value:`${Math.round(n(a))/div}:${Math.round(n(b))/div}`},{label:"Scale",value:`${n(a)?(n(c)/n(a)*100).toFixed(1):0}%`}]}};
  if(slug==="fuel-economy-converter")return{labels:["Fuel consumption","Unused","Unused"],suffix:["L/100 km","",""],calculate:()=>{const litres=n(a),kpl=100/(litres||1),mpg=235.215/(litres||1);return[{label:"Kilometres per litre",value:`${kpl.toFixed(2)} km/L`,note:"Lower L/100 km indicates better economy"},{label:"US miles per gallon",value:`${mpg.toFixed(2)} mpg`},{label:"Imperial miles per gallon",value:`${(282.481/(litres||1)).toFixed(2)} mpg`}]}};
  return null;
};
