import { numberValue as n } from "./helpers";
import type { CalculatorResolver } from "./types";

export const resolveGlobalFinance:CalculatorResolver=({slug,a,b,c,d,cash})=>{
 if(slug==="personal-cash-runway-calculator"){const short=Math.max(0,n(b)-n(c));return{labels:["Available savings","Essential monthly spending","Dependable monthly income"],suffix:["currency","currency/month","currency/month"],calculate:()=>[{label:short?"Estimated cash runway":"No monthly cash shortfall",value:short?`${(n(a)/short).toFixed(1)} months`:"Savings are not being consumed",note:"Before emergencies, inflation and income changes"},{label:"Monthly shortfall",value:cash(short)},{label:"One-year reserve needed",value:cash(short*12)}]}}
 if(slug==="business-cash-runway-calculator"){const usable=Math.max(0,n(a)-n(d)),burn=Math.max(0,n(c)-n(b));return{labels:["Current cash balance","Monthly cash revenue","Monthly cash expenses","Protected cash reserve"],suffix:["currency","currency/month","currency/month","currency"],calculate:()=>[{label:burn?"Estimated business runway":"Business is not currently burning cash",value:burn?`${(usable/burn).toFixed(1)} months`:"No finite runway",note:"Uses collected revenue and unrestricted cash"},{label:"Net monthly burn",value:cash(burn)},{label:"Usable operating cash",value:cash(usable)}]}}
 if(slug==="monthly-burn-rate-calculator"){const net=n(c)-n(b),rate=n(a)?net/n(a)*100:0;return{labels:["Opening cash","Monthly cash revenue","Monthly operating expenses"],suffix:["currency","currency/month","currency/month"],calculate:()=>[{label:net>=0?"Net monthly burn":"Monthly cash surplus",value:cash(Math.abs(net)),note:net>=0?"Expenses exceed collected revenue":"Collected revenue exceeds expenses"},{label:"Gross burn",value:cash(n(c))},{label:"Opening cash consumed",value:`${rate.toFixed(1)}% per month`}]}}
 if(slug==="emergency-fund-calculator"){const target=n(a)*n(b),gap=Math.max(0,target-n(c));return{labels:["Essential monthly expenses","Coverage target","Already saved"],suffix:["currency/month","months","currency"],calculate:()=>[{label:"Emergency-fund target",value:cash(target),note:`Based on ${n(b)} months of entered essentials`},{label:"Remaining funding gap",value:cash(gap)},{label:"Current expense coverage",value:`${(n(c)/(n(a)||1)).toFixed(1)} months`}]}}
 if(slug==="sinking-fund-calculator"){const gap=Math.max(0,n(a)-n(b)),months=Math.max(1,Math.round(n(c))),r=n(d)/1200,p=r?gap*r/(Math.pow(1+r,months)-1):gap/months;return{labels:["Target amount","Already saved","Months remaining","Assumed annual return"],suffix:["currency","currency","months","%"],calculate:()=>[{label:"Required monthly contribution",value:cash(p),note:"Assumes end-of-month contributions"},{label:"Remaining target gap",value:cash(gap)},{label:"Total planned contributions",value:cash(p*months)}]}}
 if(slug==="debt-to-income-ratio-calculator"){const front=n(a)?n(b)/n(a)*100:0,total=n(a)?(n(b)+n(c))/n(a)*100:0;return{labels:["Gross monthly income","Monthly housing payment","Other monthly debt payments"],suffix:["currency","currency","currency"],calculate:()=>[{label:"Total debt-to-income ratio",value:`${total.toFixed(1)}%`,note:"Lenders define qualifying income and debt differently"},{label:"Housing ratio",value:`${front.toFixed(1)}%`},{label:"Total monthly debt payments",value:cash(n(b)+n(c))}]}}
 if(slug==="loan-comparison-calculator"){const months=Math.max(1,Math.round(n(d)*12)),pay=(x:number)=>{const r=x/1200;return r?n(a)*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1):n(a)/months},pa=pay(n(b)),pb=pay(n(c)),ta=pa*months,tb=pb*months;return{labels:["Loan principal","Loan A annual rate","Loan B annual rate","Repayment term"],suffix:["currency","%","%","years"],calculate:()=>[{label:ta<=tb?"Loan A has lower scheduled cost":"Loan B has lower scheduled cost",value:cash(Math.abs(ta-tb)),note:"Difference before lender fees and insurance"},{label:`Loan A: ${cash(pa)}/month`,value:`Interest ${cash(ta-n(a))}`},{label:`Loan B: ${cash(pb)}/month`,value:`Interest ${cash(tb-n(a))}`}]}}
 if(slug==="effective-interest-rate-calculator"){const periods=Math.max(1,Math.round(n(b))),effective=(Math.pow(1+n(a)/100/periods,periods)-1)*100;return{labels:["Nominal annual rate","Compounding periods per year","Unused"],suffix:["%","periods",""],calculate:()=>[{label:"Effective annual rate",value:`${effective.toFixed(3)}%`,note:"Excludes fees and changing rates"},{label:"Nominal annual rate",value:`${n(a).toFixed(3)}%`},{label:"Compounding effect",value:`${(effective-n(a)).toFixed(3)} percentage points`}]}}
 if(slug==="loan-early-payment-calculator"){const sim=(payment:number)=>{let balance=n(a),interest=0,months=0,r=n(b)/1200;while(balance>.005&&months<1200){const charge=balance*r;if(payment<=charge)return{months:1200,interest:Infinity};interest+=charge;balance=Math.max(0,balance+charge-payment);months++}return{months,interest}},base=sim(n(c)),extra=sim(n(c)+n(d)),valid=Number.isFinite(base.interest)&&Number.isFinite(extra.interest);return{labels:["Current loan balance","Annual interest rate","Regular monthly payment","Extra monthly payment"],suffix:["currency","%","currency","currency"],calculate:()=>[{label:valid?"Estimated time saved":"Payment does not cover interest",value:valid?`${Math.max(0,base.months-extra.months)} months`:"Increase the regular payment",note:"Assumes a fixed rate and monthly allocation"},{label:"Interest saved",value:valid?cash(Math.max(0,base.interest-extra.interest)):"—"},{label:"New payoff time",value:valid?`${extra.months} months`:"—"}]}}
 if(slug==="invoice-financing-cost-calculator"){const advance=n(a)*n(b)/100,fee=n(a)*n(c)/100,annual=advance&&n(d)?fee/advance*365/n(d)*100:0;return{labels:["Invoice face value","Advance rate","Financing fee","Financed period"],suffix:["currency","%","% of invoice","days"],calculate:()=>[{label:"Cash advanced",value:cash(advance),note:"Before additional service or collection charges"},{label:"Financing fee",value:cash(fee)},{label:"Simple annualized cost",value:`${annual.toFixed(1)}%`}]}}
 if(slug==="late-payment-interest-calculator"){const interest=n(a)*n(b)/100*n(c)/365;return{labels:["Overdue principal","Annual interest rate","Days overdue","Valid fixed charge"],suffix:["currency","%","days","currency"],calculate:()=>[{label:"Estimated total due",value:cash(n(a)+interest+n(d)),note:"Simple interest; confirm contractual and local rules"},{label:"Late-payment interest",value:cash(interest)},{label:"Interest plus fixed charge",value:cash(interest+n(d))}]}}
 if(slug==="subscription-cost-calculator"){let total=0,annual=n(a)*n(b)*12;for(let y=0;y<Math.round(n(c));y++){total+=annual;annual*=1+n(d)/100}return{labels:["Average monthly subscription","Number of subscriptions","Projection period","Annual price increase"],suffix:["currency","subscriptions","years","%"],calculate:()=>[{label:"Projected subscription cost",value:cash(total),note:"Assumes all subscriptions stay active"},{label:"Current annual cost",value:cash(n(a)*n(b)*12)},{label:"Final-year annual cost",value:cash(n(c)?annual/(1+n(d)/100||1):0)}]}}
 if(slug==="salary-to-freelance-rate-calculator"){const hours=n(c)*n(d),rate=(n(a)+n(b))/(hours||1);return{labels:["Target annual salary","Annual business overhead","Billable hours per week","Working weeks per year"],suffix:["currency","currency","hours","weeks"],calculate:()=>[{label:"Minimum freelance hourly rate",value:cash(rate),note:"Before personal tax and desired profit margin"},{label:"Annual billable hours",value:`${hours.toLocaleString()} hours`},{label:"Required monthly revenue",value:cash((n(a)+n(b))/12)}]}}
 if(slug==="savings-withdrawal-runway-calculator"){let balance=n(a),months=0,total=0;const r=n(c)/1200;while(balance>.005&&months<1200&&n(b)>0){balance*=1+r;const draw=Math.min(balance,n(b));balance-=draw;total+=draw;months++}return{labels:["Starting savings","Monthly withdrawal","Assumed annual return","Unused"],suffix:["currency","currency/month","%",""],calculate:()=>[{label:n(b)>0&&months<1200?"Estimated savings runway":"Runway exceeds simulation",value:n(b)>0&&months<1200?`${months} months`:"100+ years",note:"Constant return and withdrawal; excludes inflation and tax"},{label:"Total withdrawn",value:cash(total)},{label:"Ending balance",value:cash(balance)}]}}
 if(slug==="recurring-expense-impact-calculator"){let annual=n(a)*12,total=0;for(let y=0;y<Math.round(n(b));y++){total+=annual;annual*=1+n(c)/100}return{labels:["Current monthly expense","Projection period","Annual price increase","Unused"],suffix:["currency","years","%",""],calculate:()=>[{label:"Projected recurring cost",value:cash(total),note:"Assumes continuous use and yearly price adjustment"},{label:"Current annual cost",value:cash(n(a)*12)},{label:"Final-year annual cost",value:cash(n(b)?annual/(1+n(c)/100||1):0)}]}}
 if(slug==="lifestyle-inflation-calculator"){const income=n(b)-n(a),spend=n(d)-n(c),share=income?spend/income*100:0;return{labels:["Previous monthly income","Current monthly income","Previous monthly spending","Current monthly spending"],suffix:["currency","currency","currency","currency"],calculate:()=>[{label:"Monthly lifestyle-cost increase",value:cash(spend),note:income>0?`${share.toFixed(1)}% of the income increase is consumed`:"Income did not increase"},{label:"Annual spending increase",value:cash(spend*12)},{label:"Change in monthly surplus",value:cash(income-spend)}]}}
 if(slug==="rent-affordability-calculator"){const guide=n(a)*n(c)/100,flow=Math.max(0,n(a)-n(b)-n(d));return{labels:["Monthly take-home income","Essential non-rent commitments","Maximum rent share","Monthly utilities estimate"],suffix:["currency","currency","%","currency"],calculate:()=>[{label:"Planning rent ceiling",value:cash(Math.min(guide,flow)),note:"Lower of income-share and cash-flow limits"},{label:"Income-share ceiling",value:cash(guide)},{label:"Cash-flow ceiling after utilities",value:cash(flow)}]}}
 if(slug==="financial-goal-timeline-calculator"){let balance=n(b),months=0;const r=n(d)/1200;while(balance<n(a)&&months<1200&&(n(c)>0||r>0)){balance=balance*(1+r)+n(c);months++}const reached=balance>=n(a);return{labels:["Financial goal","Already saved","Monthly contribution","Assumed annual return"],suffix:["currency","currency","currency","%"],calculate:()=>[{label:reached?"Estimated time to goal":"Goal not reached in simulation",value:reached?`${months} months`:"Adjust contribution or assumptions",note:"End-of-month contributions and constant return"},{label:"Projected balance",value:cash(balance)},{label:"Amount contributed",value:cash(n(b)+n(c)*months)}]}}
 if(slug==="budget-percentage-calculator"){const total=n(b)+n(c)+n(d),pct=(x:number)=>`${(n(a)?x/n(a)*100:0).toFixed(1)}%`;return{labels:["Monthly take-home income","Essential spending","Optional spending","Saving and debt reduction"],suffix:["currency","currency","currency","currency"],calculate:()=>[{label:"Unallocated monthly income",value:cash(n(a)-total),note:`${pct(total)} of income has been assigned`},{label:"Essentials / Optional",value:`${pct(n(b))} / ${pct(n(c))}`},{label:"Saving and debt reduction",value:pct(n(d))}]}}
 if(slug==="net-worth-change-calculator"){const previous=n(a)-n(b),current=n(c)-n(d),change=current-previous,pct=previous?change/Math.abs(previous)*100:0;return{labels:["Previous total assets","Previous total liabilities","Current total assets","Current total liabilities"],suffix:["currency","currency","currency","currency"],calculate:()=>[{label:"Change in net worth",value:cash(change),note:previous?`${pct.toFixed(1)}% change from the previous date`:"Percentage unavailable from zero previous net worth"},{label:"Previous net worth",value:cash(previous)},{label:"Current net worth",value:cash(current)}]}}
 return null;
};
