import { formatPkr as money, numberValue as n } from "./helpers";
import type { CalculatorResolver } from "./types";

export const resolveHomeProperty: CalculatorResolver = ({ slug, a, b, c, d, cash }) => {
  if(slug==="brick-quantity-calculator-pakistan")return{labels:["Wall length","Wall height","Wall thickness","Wastage allowance"],suffix:["ft","ft","inches","%"],calculate:()=>{const volume=n(a)*n(b)*n(c)/12,base=volume*13.5,total=Math.ceil(base*(1+n(d)/100));return[{label:"Estimated bricks required",value:total.toLocaleString("en-PK"),note:"Before deducting openings; nominal 13.5 bricks per cubic foot"},{label:"Wall volume",value:`${volume.toFixed(1)} cu ft`},{label:"Wastage bricks",value:Math.max(0,total-Math.ceil(base)).toLocaleString("en-PK")}]}};
  if(slug==="cement-sand-calculator-pakistan")return{labels:["Wet mortar or screed volume","Cement ratio","Sand ratio","Dry-volume factor"],suffix:["cu ft","parts","parts","×"],calculate:()=>{const dry=n(a)*n(d),parts=n(b)+n(c)||1,cement=dry*n(b)/parts,sand=dry*n(c)/parts,bags=cement/1.25;return[{label:"Estimated cement requirement",value:`${Math.ceil(bags)} bags`,note:"Uses approximately 1.25 cubic feet per cement bag"},{label:"Sand requirement",value:`${sand.toFixed(1)} cu ft`},{label:"Calculated dry volume",value:`${dry.toFixed(1)} cu ft`}]}};
  if(slug==="plaster-material-calculator-pakistan")return{labels:["Plaster surface area","Plaster thickness","Sand parts in 1:N mix","Wastage"],suffix:["sq ft","inches","parts","%"],calculate:()=>{const wet=n(a)*n(b)/12,dry=wet*1.33*(1+n(d)/100),cement=dry/(1+n(c)),sand=dry-cement;return[{label:"Estimated cement requirement",value:`${Math.ceil(cement/1.25)} bags`,note:"Uses a 1:N cement-to-sand mix"},{label:"Estimated sand",value:`${sand.toFixed(1)} cu ft`},{label:"Dry material volume",value:`${dry.toFixed(1)} cu ft`}]}};
  if(slug==="flooring-cost-calculator-pakistan")return{labels:["Net floor area","Material wastage","Material rate","Labour rate"],suffix:["sq ft","%","PKR/sq ft","PKR/sq ft"],calculate:()=>{const purchase=n(a)*(1+n(b)/100),material=purchase*n(c),labour=n(a)*n(d);return[{label:"Estimated installed flooring cost",value:money(material+labour),note:"Subfloor repair and skirting are not included"},{label:"Material purchase area",value:`${Math.ceil(purchase).toLocaleString("en-PK")} sq ft`},{label:"Labour estimate",value:money(labour)}]}};
  if(slug==="false-ceiling-cost-calculator-pakistan")return{labels:["Room length","Room width","Ceiling installed rate","Perimeter finishing rate"],suffix:["ft","ft","PKR/sq ft","PKR/ft"],calculate:()=>{const area=n(a)*n(b),perimeter=2*(n(a)+n(b)),base=area*n(c),finish=perimeter*n(d);return[{label:"Estimated false-ceiling cost",value:money(base+finish),note:"Complex drops, lighting and demolition require separate pricing"},{label:"Ceiling area",value:`${area.toFixed(0)} sq ft`},{label:"Perimeter finishing",value:money(finish)}]}};
  if(slug==="steel-weight-calculator-pakistan")return{labels:["Bar diameter","Length of each bar","Number of bars"],suffix:["mm","metres","bars"],calculate:()=>{const unit=n(a)*n(a)/162,total=unit*n(b)*n(c);return[{label:"Estimated total steel weight",value:`${total.toFixed(1)} kg`,note:"Nominal round-bar formula; verify mill tolerances"},{label:"Weight per metre",value:`${unit.toFixed(3)} kg/m`},{label:"Total bar length",value:`${(n(b)*n(c)).toFixed(1)} m`}]}};
  if(slug==="rebar-quantity-calculator-pakistan")return{labels:["Width across bar spacing","Bar spacing","Length of each bar","Lap and wastage"],suffix:["metres","mm","metres","%"],calculate:()=>{const count=Math.floor(n(a)*1000/(n(b)||1))+1,total=count*n(c)*(1+n(d)/100);return[{label:"Estimated total rebar length",value:`${total.toFixed(1)} m`,note:"One-direction planning estimate; structural detailing controls"},{label:"Parallel bar count",value:count.toLocaleString("en-PK")},{label:"Length before allowance",value:`${(count*n(c)).toFixed(1)} m`}]}};
  if(slug==="boundary-wall-cost-calculator-pakistan")return{labels:["Total boundary perimeter","Wall height","Masonry rate","Foundation and gate allowance"],suffix:["ft","ft","PKR/sq ft","PKR/ft"],calculate:()=>{const area=n(a)*n(b),masonry=area*n(c),base=n(a)*n(d);return[{label:"Estimated boundary-wall cost",value:money(masonry+base),note:"Gate itself, columns and special finishes may require separate quotes"},{label:"One-face wall area",value:`${area.toLocaleString("en-PK")} sq ft`},{label:"Foundation allowance",value:money(base)}]}};
  if(slug==="house-construction-cost-calculator-pakistan")return{labels:["Total covered area","Grey-structure rate","Finishing rate","Contingency"],suffix:["sq ft","PKR/sq ft","PKR/sq ft","%"],calculate:()=>{const grey=n(a)*n(b),finish=n(a)*n(c),subtotal=grey+finish,total=subtotal*(1+n(d)/100);return[{label:"Estimated construction budget",value:money(total),note:"Land, design, approvals and finance costs are separate"},{label:"Grey-structure estimate",value:money(grey)},{label:"Finishing estimate",value:money(finish)}]}};
  if(slug==="room-renovation-budget-calculator-pakistan")return{labels:["Finishes and paint","Electrical and plumbing","Fixtures and furniture","Contingency"],suffix:["PKR","PKR","PKR","%"],calculate:()=>{const subtotal=n(a)+n(b)+n(c),total=subtotal*(1+n(d)/100);return[{label:"Suggested renovation budget",value:money(total),note:"Includes the entered contingency reserve"},{label:"Planned work subtotal",value:money(subtotal)},{label:"Contingency reserve",value:money(total-subtotal)}]}};
  if(slug==="property-rental-yield-calculator-pakistan")return{labels:["Current property value","Gross monthly rent","Expected vacancy","Annual operating expenses"],suffix:["PKR","PKR","%","PKR/year"],calculate:()=>{const gross=n(b)*12,received=gross*(1-n(c)/100),net=received-n(d),grossYield=gross/(n(a)||1)*100,netYield=net/(n(a)||1)*100;return[{label:"Estimated net rental yield",value:`${netYield.toFixed(2)}%`,note:"Before financing, tax and capital appreciation"},{label:"Gross rental yield",value:`${grossYield.toFixed(2)}%`},{label:"Net annual rental income",value:money(net)}]}};
  if(slug==="property-price-per-square-foot-calculator-pakistan")return{labels:["Total property price","Property area","Local comparison rate"],suffix:["PKR","sq ft","PKR/sq ft"],calculate:()=>{const rate=n(a)/(n(b)||1),difference=rate-n(c);return[{label:"Calculated price per square foot",value:money(rate),note:"Confirm whether listings use plot, covered, saleable or net area"},{label:"Difference from comparison",value:money(difference)},{label:"Area entered",value:`${n(b).toLocaleString("en-PK")} sq ft`}]}};
  if(slug==="marla-kanal-square-feet-converter-pakistan")return{labels:["Area in square feet","Square feet per marla","Unused"],suffix:["sq ft","sq ft/marla",""],calculate:()=>{const marla=n(a)/(n(b)||1),kanal=marla/20;return[{label:"Area in marla",value:`${marla.toFixed(3)} marla`,note:"The marla standard varies; keep the local standard selected"},{label:"Area in kanal",value:`${kanal.toFixed(3)} kanal`},{label:"Square feet",value:n(a).toLocaleString("en-PK")}]}};
  if(slug==="property-transfer-cost-estimator-pakistan")return{labels:["Declared or assessable value","Combined percentage charges","Fixed legal and processing fees"],suffix:["PKR","%","PKR"],calculate:()=>{const variable=n(a)*n(b)/100,total=variable+n(c);return[{label:"Estimated property transfer cost",value:money(total),note:"Verify current valuation, filer status, province and transaction rules"},{label:"Percentage-based charges",value:money(variable)},{label:"Total cost as value percentage",value:`${n(a)?(total/n(a)*100).toFixed(2):0}%`}]}};
  if(slug==="home-loan-vs-rent-calculator-pakistan")return{labels:["Home financing amount","Annual financing rate","Financing term","Comparable monthly rent"],suffix:["PKR","%","years","PKR/month"],calculate:()=>{const months=Math.max(1,Math.round(n(c)*12)),r=n(b)/1200,payment=r?n(a)*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1):n(a)/months,diff=payment-n(d);return[{label:diff>0?"Financing payment above rent":"Financing payment below rent",value:money(Math.abs(diff)),note:"Payment-only comparison; ownership costs and equity require separate review"},{label:"Estimated monthly payment",value:money(payment)},{label:"Comparable monthly rent",value:money(n(d))}]}};
  return null;
};
