import type {CalculatorResolver, CalculatorResult} from './types';
const row=(label:string,value:string,note?:string):CalculatorResult=>({label,value,note});
const fail=(message:string)=>[row('Check inputs',message)];
const valid=(s:string,min=-1e12,max=1e12)=>s.trim()!==''&&Number.isFinite(Number(s))&&Number(s)>=min&&Number(s)<=max;
const f=(n:number,p=6)=>n.toLocaleString('en-US',{maximumFractionDigits:p});
export function roundDecimal(input:string,precision:number,mode:string,tie:string):string{
 if(input.length>500||!/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(input.trim()))throw Error('Enter a plain decimal, without commas or scientific notation.');
 const raw=input.trim(),negative=raw.startsWith('-'),[whole,frac='']=raw.replace(/^[-+]/,'').split('.');
 if(whole.length>200||frac.length>200)throw Error('Limit integer and fractional parts to 200 digits each.');
 if(!['places','significant'].includes(mode)||!['away','even'].includes(tie)||!Number.isInteger(precision)||precision<(mode==='places'?-12:1)||precision>(mode==='places'?18:15))throw Error('Use decimal places −12 to 18, or 1–15 significant figures, and a supported tie rule.');
 const n=BigInt((whole||'0')+frac),scale=frac.length;
 let places=mode==='places'?precision:n===BigInt(0)?precision-1:precision-1-(n.toString().length-1-scale);
 const power=scale-places;let q=n;
 if(power>0){const div=BigInt(10)**BigInt(power),rem=n%div;q=n/div;if(rem*BigInt(2)>div||(rem*BigInt(2)===div&&(tie==='away'||q%BigInt(2)===BigInt(1))))q+=BigInt(1);}
 else q*=BigInt(10)**BigInt(-power);
 if(mode==='significant'&&n!==BigInt(0)&&q.toString().length>precision){q/=BigInt(10);places--;}
 let text=q.toString();if(places>0){text=text.padStart(places+1,'0');text=text.slice(0,-places)+'.'+text.slice(-places);}else if(places<0)text+='0'.repeat(-places);
 return(negative&&q!==BigInt(0)?'-':'')+text;
}
const date=(s:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return null;const dt=new Date(s+'T12:00:00Z');return Number.isFinite(+dt)&&dt.toISOString().slice(0,10)===s&&dt.getUTCFullYear()>=1900&&dt.getUTCFullYear()<=2200?dt:null;};
const iso=(d:Date)=>d.toISOString().slice(0,10);
const duration=(s:string)=>{const m=/^(\d{1,6}):(\d{2})(?::(\d{2}))?$/.exec(s.trim());return m&&+m[1]<=100000&&+m[2]<60&&+(m[3]||0)<60?+m[1]*3600+ +m[2]*60+ +(m[3]||0):NaN;};
export const resolveRoadmap186:CalculatorResolver=({slug,a,b,c,d,e,cash})=>{
 const A=Number(a),B=Number(b),C=Number(c),D=Number(d),E=Number(e);
 if(slug==='percent-calculator'){
 const labels:Record<string,string[]>={of:['Percentage','Whole number'],part:['Part','Whole'],reverse:['Known part','Percentage of whole'],change:['Original value','New value'],difference:['First value','Second value'],decimal:['Decimal fraction','Unused'],nested:['First percentage','Second percentage'],increase:['Original amount','Increase percentage'],reduce:['Original amount','Reduction percentage'],time:['Elapsed duration HH:MM[:SS]','Total duration HH:MM[:SS]']};
 return{labels:[...(labels[c]||labels.of),'Calculation mode'],suffix:[c==='time'?'text':c==='of'?'%':'number',c==='decimal'?'':c==='reverse'||c==='increase'||c==='reduce'||c==='nested'?'%':c==='time'?'text':'number','select:of=Percentage of number|part=Part as percentage|reverse=Find whole from percentage|change=Percentage change|difference=Relative percentage difference (RPD)|decimal=Decimal to percent|nested=Percentage of percentage|increase=Increase by percentage|reduce=Reduce by percentage|time=Time percentage'],calculate:()=>{
 if(!labels[c])return fail('Choose a supported calculation mode.');
 if(c==='time'){const part=duration(a),whole=duration(b);if(!Number.isFinite(part)||!Number.isFinite(whole)||whole<=0)return fail('Use HH:MM or HH:MM:SS durations, with minute/second components below 60 and a positive total.');return[row('Time percentage',f(part/whole*100)+' %'),row('Elapsed duration',f(part)+' seconds'),row('Total duration',f(whole)+' seconds')];}
 if(!valid(a)||(c!=='decimal'&&!valid(b)))return fail('Supply finite numbers within ±10¹²; the second field is unused in decimal mode.');
 if(c==='of')return[row('Percentage of number',f(A*B/100)),row('Decimal multiplier',f(A/100))];
 if(c==='part'){if(B===0)return fail('Whole cannot be zero.');return[row('Part as percentage',f(A/B*100)+' %', 'Part and whole must use the same units. Values above 100% are allowed.')];}
 if(c==='reverse'){if(B===0)return fail('A zero percentage cannot determine the whole.');return[row('Calculated whole',f(A*100/B)),row('Check: whole × percentage',f(A))];}
 if(c==='decimal')return[row('Converted percentage',f(A*100)+' %')];
 if(c==='nested')return[row('Percentage of percentage',f(A*B/100)+' %'),row('Fraction of original whole',f(A*B/10000))];
 if(c==='change'){if(A<=0||B<0)return fail('Percentage change here requires a positive original value and non-negative new value.');return[row('Percentage change',f((B-A)/A*100)+' %'),row('Signed numerical change',f(B-A))];}
 if(c==='difference'){if(A<0||B<0||A+B===0)return fail('Mean-based RPD requires non-negative values with a positive average. Two zeros have an undefined relative difference.');return[row('Relative percentage difference',f(Math.abs(A-B)/((A+B)/2)*100)+' %','Uses the average of the two non-negative values as denominator, rather than an original-value baseline.'),row('Absolute numerical difference',f(Math.abs(A-B))),row('Average denominator',f((A+B)/2))];}
 if(A<0||B<0||c==='reduce'&&B>100)return fail('Use a non-negative amount and percentage; reduction is limited to 0–100%.');const result=A*(1+(c==='reduce'?-1:1)*B/100);return[row('Adjusted amount',f(result)),row('Percentage amount',f(A*B/100))];
 }};}
 if(slug==='mulch-calculator')return{labels:['Bed length','Bed width','Finished mulch depth','Explicit volume allowance','Bag volume (0 to omit bags)'],suffix:['ft','ft','in','%','ft³'],calculate:()=>{
 if(!valid(a,1e-9,1e5)||!valid(b,1e-9,1e5)||!valid(c,1e-9,1000)||!valid(d,0,100)||!valid(e,0,1000))return fail('Enter positive dimensions, 0–100% allowance and a non-negative bag volume.');const geo=A*B*C/12,planned=geo*(1+D/100);return[row('Planned mulch volume',f(planned/27)+' yd³'),row('Planned cubic feet',f(planned)+' ft³'),row('Geometric volume before allowance',f(geo)+' ft³'),row('Whole bags',E===0?'Bag volume not supplied':f(Math.ceil(planned/E),0)+' bags','Volume estimate only; no assumed weight, price or planting-depth recommendation.')];
 }};
 if(slug==='concrete-block-calculator')return{labels:['Wall length','Wall height','Total opening area','Nominal modular face (inches): length; height','Explicit block allowance'],suffix:['ft','ft','ft²','text','%'],calculate:()=>{
 const face=d.split(';').map(s=>s.trim());if(!valid(a,1e-9,1e5)||!valid(b,1e-9,1e5)||!valid(c,0,1e10)||C>A*B||face.length!==2||face.some(s=>!valid(s,1,100))||!valid(e,0,100))return fail('Use positive wall dimensions, openings no larger than wall area, two modular face dimensions in inches separated by a semicolon, and 0–100% allowance.');const net=A*B-C,coverage=Number(face[0])*Number(face[1])/144,count=net/coverage;return[row('Whole blocks including allowance',f(Math.ceil(count*(1+E/100)),0)+' blocks','Area takeoff only. Nominal modular dimensions include the joint module; no engineering or cut-layout design.'),row('Whole blocks before allowance',f(Math.ceil(count),0)),row('Net wall area',f(net)+' ft²'),row('Modular coverage per block',f(coverage)+' ft²')];
 }};
 if(slug==='basis-points-calculator')return{labels:[c==='amount'?'Principal amount':c==='rate-change'||c==='apply'?'Starting rate in percent':'Input value',c==='rate-change'?'New rate in percent':c==='apply'||c==='amount'?'Basis-point change':'Unused','Calculation mode'],suffix:[c==='amount'?'currency':'number',c==='rate-change'?'%':c==='apply'||c==='amount'?'bps':'','select:bps=Basis points to percent|percent=Percent to basis points|decimal=Decimal fraction to basis points|rate-change=Rate change in basis points|apply=Apply basis-point change|amount=Simple amount impact'],calculate:()=>{
 if(!['bps','percent','decimal','rate-change','apply','amount'].includes(c)||!valid(a)||['rate-change','apply','amount'].includes(c)&&!valid(b))return fail('Choose a mode and enter finite values within ±10¹².');if(c==='bps')return[row('Percentage points',f(A/100)+' percentage points'),row('Decimal fraction',f(A/10000))];if(c==='percent')return[row('Basis points',f(A*100)+' bps')];if(c==='decimal')return[row('Basis points',f(A*10000)+' bps')];if(c==='rate-change')return[row('Rate difference',f((B-A)*100)+' bps'),row('Percentage-point difference',f(B-A)+' points')];if(c==='apply')return[row('Adjusted rate',f(A+B/100)+' %')];if(A<0)return fail('Principal must be non-negative.');return[row('Simple amount impact',cash(A*B/10000),'One supplied rate difference applied once; no duration, compounding, fees or tax is inferred.')];
 }};
 if(slug==='rounding-calculator')return{labels:['Exact decimal number','Precision','Halfway tie rule','Precision mode'],suffix:['text','integer','select:away=Half away from zero|even=Half to even','select:places=Decimal places (negative for tens/hundreds)|significant=Significant figures'],calculate:()=>{try{if(!valid(b,-12,18))throw Error('Supply a precision integer.');return[row('Rounded decimal',roundDecimal(a,B,d,c),'Exact base-ten integer arithmetic. Significant-figure mode reports the chosen precision separately; trailing integer zeros alone do not encode significant figures.'),row('Precision',b+(d==='places'?' decimal places':' significant figures')),row('Halfway rule',c==='even'?'Half to even':'Half away from zero')];}catch(error){return fail(error instanceof Error?error.message:'Invalid decimal.');}}};
 if(slug==='tire-size-calculator')return{labels:['Original metric tire size','Comparison metric tire size','Indicated speed','Speed unit'],suffix:['text','text','number','select:mph=mph|kmh=km/h'],calculate:()=>{
 const parse=(s:string)=>{const m=/^(?:P|LT)?(\d{2,3})\/(\d{2,3})R(\d{1,2}(?:\.\d)?)$/i.exec(s.trim());if(!m||!valid(m[1],50,500)||!valid(m[2],10,100)||!valid(m[3],5,40))return null;const width=+m[1],side=width*+m[2]/100,diam=+m[3]*25.4+2*side;return{width,side,diam};};const old=parse(a),next=parse(b);if(!old||!next||!valid(c,0,500)||!['mph','kmh'].includes(d))return fail('Use supported metric radial sizes such as 265/70R16, a speed of 0–500, and mph or km/h. Load/speed suffixes and flotation notation are not accepted.');const ratio=next.diam/old.diam,unit=d==='mph'?'mph':'km/h';return[row('Diameter difference',f((ratio-1)*100)+' %','Nominal geometry only, not Tacoma or other vehicle fitment approval.'),row('Original overall diameter',f(old.diam)+' mm / '+f(old.diam/25.4)+' in'),row('Comparison overall diameter',f(next.diam)+' mm / '+f(next.diam/25.4)+' in'),row('Comparison sidewall height',f(next.side)+' mm / '+f(next.side/25.4)+' in'),row('Comparison circumference',f(Math.PI*next.diam)+' mm'),row('Ideal speed at indicated reading',f(C*ratio)+' '+unit,'Assumes the gauge is calibrated to the original nominal diameter; real rolling radius and calibration differ.'),row('Nominal radius difference',f((next.diam-old.diam)/2)+' mm')];
 }};
 if(slug==='anniversary-calculator')return{labels:['Original event date','Reference date','February 29 in a non-leap year'],suffix:['date','date','select:feb28=Observe February 28|mar1=Observe March 1'],calculate:()=>{
 const start=date(a),ref=date(b);if(!start||!ref||+ref<+start||!['feb28','mar1'].includes(c))return fail('Use valid Gregorian dates from 1900–2200, a reference on or after the event, and a leap-day observation policy.');const occurrence=(year:number)=>{const leap=year%4===0&&(year%100!==0||year%400===0);return new Date(Date.UTC(year,start.getUTCMonth()===1&&start.getUTCDate()===29&&!leap&&c==='mar1'?2:start.getUTCMonth(),start.getUTCMonth()===1&&start.getUTCDate()===29&&!leap?(c==='feb28'?28:1):start.getUTCDate(),12));};const current=occurrence(ref.getUTCFullYear()),today=+current===+ref,complete=ref.getUTCFullYear()-start.getUTCFullYear()-(+ref<+current?1:0),next=+current>+ref?current:occurrence(ref.getUTCFullYear()+1);return[row('Completed annual anniversaries',String(Math.max(0,complete))),row('Next anniversary after reference date',iso(next)),row('Days until next anniversary',String(Math.round((+next-+ref)/86400000))),row('Calendar days since event',String(Math.round((+ref-+start)/86400000))),row('Anniversary on reference date',today?'Yes':'No','Annual Gregorian recurrence with your selected February 29 convention; not a legal deadline rule.')];
 }};
 if(slug==='compound-interest-calculator')return{labels:['Starting principal','Assumed annual return','Duration','End-of-month contribution','Annual rate basis'],suffix:['currency','%','years','currency/month','select:effective=Effective annual return|nominal=Nominal annual rate compounded monthly'],calculate:()=>{
 const months=Math.round(C*12);if(!valid(a,0)||!valid(b,-99,100)||!valid(c,0,100)||Math.abs(C*12-months)>1e-7||!valid(d,0)||!['effective','nominal'].includes(e))return fail('Use non-negative principal/contributions, −99% to 100% assumed annual return, a duration in whole months up to 100 years and an explicit annual-rate basis.');const rate=e==='effective'?Math.expm1(Math.log1p(B/100)/12):B/1200,growth=Math.expm1(months*Math.log1p(rate)),future=A*(growth+1)+D*(rate===0?months:growth/rate),paid=A+D*months;if(!Number.isFinite(future))return fail('Projection exceeds supported numeric range.');return[row('Illustrative future value',cash(future),'User-supplied constant return with end-of-month contributions. A VOO scenario is not a forecast or live quote; no fees, taxes or distributions are silently added.'),row('Total contributed',cash(paid)),row('Modeled growth',cash(future-paid)),row('Equivalent monthly rate',f(rate*100)+' %')];
 }};
 if(slug==='grade-curve-calculator')return{labels:['Class scores, comma separated','Curve method','Target mean or added points','Maximum score','Target population standard deviation'],suffix:['text','select:add=Add points|highest=Shift highest to maximum|mean=Shift to target mean|zscore=Linear z-score rescaling','points','points',b==='zscore'?'points':''],calculate:()=>{
 const tokens=a.trim().split(/[,;\s]+/).filter(Boolean);if(!tokens.length||tokens.length>10000||!valid(d,1,10000)||tokens.some(s=>!valid(s,0,D))||!['add','highest','mean','zscore'].includes(b)||b!=='highest'&&!valid(c,0,10000))return fail('Supply 1–10,000 scores within the positive maximum and valid method parameters.');const scores=tokens.map(Number),mean=scores.reduce((s,x)=>s+x,0)/scores.length,max=Math.max(...scores),sd=Math.sqrt(scores.reduce((s,x)=>s+(x-mean)**2,0)/scores.length);if(b==='zscore'&&(scores.length<2||sd===0||!valid(e,1e-9,10000)||C<0||C>D))return fail('Z-score mode needs varying scores, at least two observations, a target mean within the maximum and positive target SD.');const mapped=scores.map(x=>Math.max(0,Math.min(D,b==='add'?x+C:b==='highest'?x+D-max:b==='mean'?x+C-mean:C+(x-mean)/sd*E)));return[row('Curved scores',mapped.map(x=>f(x,3)).join(', '),'Scores are clipped to 0 and the maximum. Linear rescaling preserves distribution shape before clipping; it does not create a bell curve or assign letter grades.'),row('Original class mean',f(mean)),row('Original population SD',f(sd)),row('Curved mean after clipping',f(mapped.reduce((s,x)=>s+x,0)/mapped.length))];
 }};
 if(slug==='military-chart-points-total')return{labels:['Official component points, comma separated','Matching component maxima, comma separated','Unused'],suffix:['text','text',''],calculate:()=>{
 const points=a.split(',').map(s=>s.trim()),maxima=b.split(',').map(s=>s.trim());if(!points.length||points.length>10||points.length!==maxima.length||maxima.some(s=>!valid(s,1,10000))||points.some((s,i)=>!valid(s,0,Number(maxima[i]))))return fail('Supply 1–10 matched official point/max pairs, with positive maxima and each point value between zero and its maximum.');const total=points.reduce((s,x)=>s+Number(x),0),maximum=maxima.reduce((s,x)=>s+Number(x),0);return[row('Supplied official point total',f(total)+' / '+f(maximum),'Adds points already obtained from the applicable official charts; it does not convert raw performances or determine passing status.'),row('Arithmetic share of supplied maximum',f(total/maximum*100)+' %')];
 }};
 return null;
};
