import type {CalculatorResolver,CalculatorResult} from './types';
const row=(label:string,value:string,note?:string):CalculatorResult=>({label,value,note});
const bad=(s:string)=>[row('Check inputs',s)];
const ok=(s:string,min=0,max=1e12)=>s.trim()!==''&&Number.isFinite(Number(s))&&Number(s)>=min&&Number(s)<=max;
const fmt=(n:number)=>n.toLocaleString('en-US',{maximumFractionDigits:8});
export function booleanTable(source:string){
 const text=source.toUpperCase().replace(/\s/g,'');
 if(!text||text.length>200||!/^[A-D01!&|^()]+$/.test(text))throw Error('Use A–D, 0, 1, ! (NOT), & (AND), ^ (XOR), | (OR) and parentheses; maximum 200 characters.');
 const vars=[...new Set(text.match(/[A-D]/g)||[])].sort();
 const evaluate=(values:Record<string,boolean>)=>{let i=0,depth=0;const atom=():boolean=>{if(++depth>32)throw Error('Limit nesting to 32 levels.');let v:boolean;const t=text[i++];if(t==='!')v=!atom();else if(t==='('){v=or();if(text[i++]!==')')throw Error('Close parentheses.');}else if(t==='0'||t==='1')v=t==='1';else if(t&&vars.includes(t))v=values[t];else throw Error('Expected a variable, constant or parenthesized expression.');depth--;return v;};const and=()=>{let v=atom();while(text[i]==='&'){i++;const rhs=atom();v=v&&rhs;}return v;};const xor=()=>{let v=and();while(text[i]==='^'){i++;v=v!==and();}return v;};const or=()=>{let v=xor();while(text[i]==='|'){i++;const rhs=xor();v=v||rhs;}return v;};const v=or();if(i!==text.length)throw Error('Use explicit operators between values.');return v;};
 const rows:Array<{inputs:string;output:number}>=[];for(let mask=0;mask<2**vars.length;mask++){const values:Record<string,boolean>={};vars.forEach((v,i)=>values[v]=Boolean(mask&(1<<(vars.length-1-i))));rows.push({inputs:vars.map(v=>Number(values[v])).join(' '),output:Number(evaluate(values))});}return{vars,rows};
}
export function geographicMidpoint(lat1:number,lon1:number,lat2:number,lon2:number){
 const rad=Math.PI/180,point=(lat:number,lon:number)=>[Math.cos(lat*rad)*Math.cos(lon*rad),Math.cos(lat*rad)*Math.sin(lon*rad),Math.sin(lat*rad)];const p=point(lat1,lon1),q=point(lat2,lon2),s=p.map((v,i)=>v+q[i]),norm=Math.hypot(...s);if(norm<1e-10)throw Error('Antipodal points have no unique shortest-arc midpoint.');const lat=Math.atan2(s[2],Math.hypot(s[0],s[1]))/rad,lon=Math.atan2(s[1],s[0])/rad;return{lat,lon};
}
const duration=(s:string)=>{if(/^\d+(?:\.\d+)?$/.test(s.trim()))return Number(s);const m=s.trim().match(/^(\d+):(\d{1,2}(?:\.\d+)?)$/);if(!m||Number(m[2])>=60)return NaN;return Number(m[1])*60+Number(m[2]);};
const clock=(s:number)=>{const total=Math.round(s*100),minutes=Math.floor(total/6000),seconds=(total%6000)/100;return minutes+':'+seconds.toFixed(2).padStart(5,'0');};
export const resolveNext20:CalculatorResolver=({slug,a,b,c,d,e,f='0',g='0',h='0',cash})=>{
 const A=Number(a),B=Number(b),C=Number(c),D=Number(d),E=Number(e),F=Number(f),G=Number(g);
 if(slug==='horsepower-calculator')return{labels:['Torque at measured operating point','Rotational speed at same point','Unused'],suffix:['N·m','rpm',''],calculate:()=>{
 if(!ok(a)||!ok(b,0,1e7))return bad('Supply non-negative torque in N·m and matching rpm.');const watts=A*B*2*Math.PI/60;return[row('Mechanical horsepower',fmt(watts/745.6998715822702)+' hp','Shaft power at the supplied torque/rpm point; no peak power, vehicle ET or drivetrain-loss model.'),row('Shaft power',fmt(watts/1000)+' kW'),row('Metric horsepower',fmt(watts/735.49875)+' PS')];}};
 if(slug==='interest-rate-cap-payout-calculator')return{labels:['Covered notional','Observed index rate','Contract strike rate','Accrual days','Day-count denominator'],suffix:['currency','% annual','% annual','whole days','select:360=360|365=365|366=366'],calculate:()=>{
 if(!ok(a)||!ok(b,-100,100)||!ok(c,-100,100)||!ok(d,0,366)||!Number.isInteger(D)||!['360','365','366'].includes(e))return bad('Supply non-negative notional, rates −100 to 100%, 0–366 whole days and explicit denominator.');return[row('Illustrative cap-period payout',cash(A*Math.max(0,B-C)/100*D/E),'Single-period arithmetic only; no Chatham quote, market premium, curve, volatility, discounting, compounded SOFR observation or contract valuation.'),row('Positive rate excess',fmt(Math.max(0,B-C))+' percentage points'),row('Supplied accrual fraction',fmt(D/E))];}};
 if(slug==='geographic-midpoint-calculator')return{labels:['First latitude','First longitude','Second latitude','Second longitude'],suffix:['degrees −90 to 90','degrees −180 to 180','degrees −90 to 90','degrees −180 to 180'],calculate:()=>{
 if(!ok(a,-90,90)||!ok(c,-90,90)||!ok(b,-180,180)||!ok(d,-180,180))return bad('Enter two valid signed latitude/longitude pairs.');try{const p=geographicMidpoint(A,B,C,D);return[row('Shortest-arc geographic midpoint',fmt(p.lat)+', '+fmt(p.lon),'Spherical coordinate midpoint, not road distance, equal driving time, a named city or an accessible meeting location.'),row('Latitude',fmt(p.lat)+'°'),row('Longitude',fmt(p.lon)+'°')];}catch(err){return bad((err as Error).message);}}};
 if(slug==='cake-pricing-calculator')return{labels:['Ingredients and decoration cost','Packaging and allocated overhead','Labor hours','Your labor rate','Target profit margin','Percentage selling fee','Fixed transaction fee'],suffix:['currency','currency','hours','currency/hour','% of selling price','% of selling price','currency'],calculate:()=>{
 if([a,b,c,d,g].some(s=>!ok(s))||!ok(e,0,99.999)||!ok(f,0,99.999)||E+F>=100)return bad('Supply non-negative costs/hours/rate and margin plus percentage fee below 100%.');const cost=A+B+C*D+G,price=cost/(1-(E+F)/100);return[row('Scenario cake selling price',cash(price),'Target margin is a share of final price. Tax, delivery and market demand are not inferred; labor is cost before profit.'),row('Total cost including fixed fee',cash(cost)),row('Percentage selling fee',cash(price*F/100)),row('Target operating profit',cash(price*E/100))];}};
 if(slug==='sheep-gestation-calculator')return{labels:['Known mating date','Unused','Unused'],suffix:['date','',''],calculate:()=>{
 if(!/^\d{4}-\d{2}-\d{2}$/.test(a)||a<'1900-01-01'||a>'2100-12-31')return bad('Use a valid mating date from 1900 through 2100.');const date=new Date(a+'T12:00:00Z');if(!Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==a)return bad('Use a real Gregorian date.');const add=(n:number)=>new Date(date.getTime()+n*86400000).toISOString().slice(0,10);return[row('147-day lambing planning date',add(147),'Mating-date calendar estimate only, not confirmation of conception, pregnancy, fetal number or a veterinary intervention schedule.'),row('144–150-day reference window',add(144)+' to '+add(150))];}};
 if(slug==='asphalt-calculator')return{labels:['Paved surface area','Compacted layer depth','Supplier compacted density','Explicit material allowance','Supplied price per US short ton'],suffix:['ft²','in','lb/ft³','%','currency/US short ton (0 to omit cost)'],calculate:()=>{
 if(!ok(a,1e-9)||!ok(b,1e-9,120)||!ok(c,1e-9,1000)||!ok(d,0,100)||!ok(e))return bad('Use positive area/depth/density and non-negative allowance/price.');const volume=A*B/12,tons=volume*C/2000,planned=tons*(1+D/100);return[row('Planned asphalt mass',fmt(planned)+' US short tons','Rectangular uniform compacted layer with user-supplied density and allowance; no pavement design or structural thickness selection.'),row('Base asphalt mass',fmt(tons)+' US short tons'),row('Compacted volume',fmt(volume/27)+' yd³'),row('Supplied material-cost scenario',E?cash(planned*E):'No price supplied')];}};
 if(slug==='boolean-algebra-calculator')return{labels:['Boolean expression using A–D','Unused','Unused'],suffix:['text','',''],calculate:()=>{try{const t=booleanTable(a),trueRows=t.rows.filter(r=>r.output),names=t.vars.join(' ')||'constant';return[row('Truth table: '+names+' → output',t.rows.map(r=>r.inputs+' → '+r.output).join('; '),'Operator precedence: NOT, AND, XOR, OR. Up to four variables; no minimum-gate, HDL, symbolic simplification or general CAS claim.'),row('Classification',trueRows.length===t.rows.length?'Tautology':trueRows.length===0?'Contradiction':'Contingent'),row('True rows / total',trueRows.length+' / '+t.rows.length)];}catch(err){return bad((err as Error).message);}}};
 if(slug==='megawatt-calculator')return{labels:['Power value','Input unit','Unused'],suffix:['power','select:W=Watts|kW=Kilowatts|MW=Megawatts|GW=Gigawatts',''],calculate:()=>{const scale:Record<string,number>={W:1,kW:1e3,MW:1e6,GW:1e9};if(!ok(a)||!Object.hasOwn(scale,b))return bad('Supply non-negative power and a supported input unit.');const w=A*scale[b];return[row('Megawatts',fmt(w/1e6)+' MW','Power-unit conversion only; energy requires a duration and is measured in Wh or related units.'),row('Kilowatts',fmt(w/1e3)+' kW'),row('Watts',fmt(w)+' W'),row('Gigawatts',fmt(w/1e9)+' GW')];}};
 if(slug==='substitution-calculator')return{labels:['Equation 1: x coefficient','Equation 1: y coefficient','Equation 1: right side','Equation 2: x coefficient','Equation 2: y coefficient','Equation 2: right side'],suffix:['a₁','b₁','c₁','a₂','b₂','c₂'],calculate:()=>{
 if([a,b,c,d,e,f].some(s=>!ok(s,-1e6,1e6)))return bad('Supply six finite coefficients from −1,000,000 to 1,000,000 for a₁x+b₁y=c₁ and a₂x+b₂y=c₂.');const det=A*E-D*B,scale=Math.max(1,Math.abs(A*E),Math.abs(D*B));if(Math.abs(det)<=1e-12*scale)return bad('No numerically stable unique solution: the equations are dependent, inconsistent or nearly singular.');const x=(C*E-F*B)/det,y=(A*F-D*C)/det;return[row('Unique linear-system solution','x = '+fmt(x)+'; y = '+fmt(y),'Two real linear equations only. Solves equivalent substitution/elimination arithmetic; not arbitrary expression replacement or nonlinear solving.'),row('Equation 1 residual',fmt(A*x+B*y-C)),row('Equation 2 residual',fmt(D*x+E*y-F)),row('Coefficient determinant',fmt(det))];}};
 if(slug==='ap-biology-score-calculator')return{labels:['Multiple-choice correct','Multiple-choice total','Free-response percentage'],suffix:['whole questions','whole questions','%'],calculate:()=>{
 if(!ok(a,0,1000)||!ok(b,1,1000)||!Number.isInteger(A)||!Number.isInteger(B)||A>B||!ok(c,0,100))return bad('Use whole MC counts with correct ≤ total and FRQ percentage from 0–100.');return[row('Practice composite percentage',fmt(50*A/B+.5*C)+' %','50% multiple choice and 50% free response; not an official AP 1–5 score or fixed cutoff prediction.'),row('Multiple-choice percentage',fmt(100*A/B)+' %'),row('Free-response percentage',fmt(C)+' %')];}};
 if(slug==='womens-bmi-calculator'){const reverse=d==='reverse';return{labels:[reverse?'Supplied BMI value':'Measured body weight','Measured height','Unused','Mode'],suffix:[reverse?'kg/m²':'kg','cm','','select:bmi=BMI from measured weight|reverse=Weight from supplied BMI'],calculate:()=>{
 if(!['bmi','reverse'].includes(d)||!ok(a,1e-9,reverse?200:1000)||!ok(b,50,300))return bad('Use positive weight/BMI, measured height 50–300 cm and a supported mode.');const height=B/100,weight=reverse?A*height*height:A,bmi=reverse?A:A/(height*height);return[row(reverse?'Weight corresponding to supplied BMI':'Adult BMI',fmt(reverse?weight:bmi)+(reverse?' kg':' kg/m²'),'BMI identity only for adults; supplied BMI is not a recommended target, diagnosis, pregnancy model or child growth assessment.'),row('BMI on supplied basis',fmt(bmi)+' kg/m²'),row('Weight on supplied basis',fmt(weight)+' kg')];}};}
 if(slug==='cap-rate-calculator')return{labels:['Annual gross operating income','Annual operating expenses','Property value on chosen basis'],suffix:['currency/year','currency/year','currency'],calculate:()=>{
 if(!ok(a)||!ok(b)||!ok(c,1e-9))return bad('Supply non-negative annual income/expenses and positive property value in one currency.');const noi=A-B;return[row('Direct capitalization rate',fmt(100*noi/C)+' %','Annual NOI/property value. Debt service, income tax and depreciation must not be mixed into the supplied operating-expense basis; no valuation or investment recommendation.'),row('Annual net operating income',cash(noi)),row('NOI per month (annual average)',cash(noi/12))];}};
 if(slug==='swim-time-converter')return{labels:['Recorded time: seconds or m:ss.xx','Source swim distance','Target swim distance','Distance units','Explicit course conversion factor'],suffix:['text','distance','distance','select:m-m=Metres to metres|yd-yd=Yards to yards|yd-m=Yards to metres|m-yd=Metres to yards','factor (1 = distance-only)'],calculate:()=>{
 const time=duration(a),units=d.split('-');if(!Number.isFinite(time)||time<=0||time>86400||!ok(b,1e-9,1e6)||!ok(c,1e-9,1e6)||!['m-m','yd-yd','yd-m','m-yd'].includes(d)||!ok(e,.1,10))return bad('Supply positive time (seconds or m:ss.xx), positive distances, matching unit mode and explicit factor 0.1–10.');const source=B*(units[0]==='yd'?.9144:1),target=C*(units[1]==='yd'?.9144:1),result=time*target/source*E;return[row('Illustrative converted swim time',clock(result),'Distance-proportional arithmetic × your factor. Factor 1 does not adjust turns, stroke, fatigue or SCY/SCM/LCM race performance; not a meet-entry standard.'),row('Converted seconds',fmt(result)+' s'),row('Measured source pace per 100 m',clock(time/source*100)),row('Applied course factor',fmt(E))];}};
 if(slug==='cpm-calculator')return{labels:['Campaign spend','Impressions or supplied CPM (see mode)','Unused','Solve for'],suffix:['currency','number','','select:cpm=CPM from spend and impressions|impressions=Impressions from spend and CPM'],calculate:()=>{
 if(!ok(a)||!ok(b,1e-9)||!['cpm','impressions'].includes(d))return bad('Supply non-negative spend, positive impressions/CPM and a supported mode.');if(d==='cpm'&&!Number.isInteger(B))return bad('Observed impressions must be a positive whole count.');return d==='cpm'?[row('Cost per thousand impressions',cash(1000*A/B),'Use matching campaign, date range, spend and impression definitions; no ad revenue, unique-reach or conversion forecast.'),row('Impression count',fmt(B))]:[row('Impressions at supplied constant CPM',fmt(1000*A/B),'Arithmetic scenario only. Fractional expected impressions are not a delivered count or guarantee.'),row('Supplied CPM',cash(B))];}};
 if(slug==='fence-cost-estimator')return{labels:['Fence run length (exclude gate openings)','Supplier material rate','Contractor labor rate','Separate gate cost','Other separate project charges','Explicit material allowance'],suffix:['length units','currency/length unit','currency/length unit','currency','currency','% of material only'],calculate:()=>{
 if(!ok(a)||!ok(b)||!ok(c)||!ok(d)||!ok(e)||!ok(f,0,100))return bad('Supply non-negative quantities/prices and 0–100% material allowance.');const material=A*B*(1+F/100),labor=A*C;return[row('Supplied-basis fence cost',cash(material+labor+D+E),'Quotation worksheet only; no local rates, property boundary, permit, post-depth or structural design inferred.'),row('Material with explicit allowance',cash(material)),row('Labor without material allowance',cash(labor)),row('Separate gates and charges',cash(D+E))];}};
 if(slug==='subwoofer-case-calculator')return{labels:['External rectangular width','External rectangular height','External rectangular depth','Uniform panel thickness','Total internal displacement'],suffix:['in','in','in','in','ft³: drivers + braces + ports'],calculate:()=>{
 if(!ok(a,1e-9,1000)||!ok(b,1e-9,1000)||!ok(c,1e-9,1000)||!ok(d,1e-9,20)||!ok(e,0,1e6)||Math.min(A,B,C)<=2*D)return bad('Use positive external dimensions/thickness and non-negative displacement; every dimension must exceed twice thickness.');const dims=[A-2*D,B-2*D,C-2*D],gross=dims.reduce((p,x)=>p*x,1)/1728;if(E>=gross)return bad('Displacement must be smaller than gross internal volume.');return[row('Net enclosure air volume',fmt(gross-E)+' ft³','Rectangular six-panel geometry only; no driver selection, tuning frequency, port length, response or manufacturer target inferred.'),row('Net volume in litres',fmt((gross-E)*28.316846592)+' L'),row('Gross internal volume',fmt(gross)+' ft³'),row('Internal W × H × D',dims.map(fmt).join(' × ')+' in')];}};
 if(slug==='acres-per-hour-calculator')return{labels:['Effective implement working width','Average ground speed','Field efficiency','Field area to complete'],suffix:['ft','mph','%','acres'],calculate:()=>{
 if(!ok(a,1e-9,1000)||!ok(b,1e-9,100)||!ok(c,1e-9,100)||!ok(d))return bad('Supply positive width/speed/efficiency up to 100%, and non-negative field acres.');const theoretical=A*B/8.25,actual=theoretical*C/100;return[row('Effective field capacity',fmt(actual)+' acres/hour','Supplied width, speed and efficiency model; no prescribed safe travel speed or measured operating guarantee.'),row('Theoretical capacity at 100%',fmt(theoretical)+' acres/hour'),row('Estimated operating hours',fmt(D/actual)+' h'),row('Effective hectares per hour',fmt(actual*.40468564224)+' ha/hour')];}};
 if(slug==='torque-converter')return{labels:['Torque value','Conversion direction','Unused'],suffix:['torque','select:nm=N·m to lbf·ft|lbft=lbf·ft to N·m',''],calculate:()=>{
 if(!ok(a,-1e12,1e12)||!['nm','lbft'].includes(b))return bad('Supply finite signed torque and a supported direction.');const factor=1.3558179483314004;return[row('Converted torque',fmt(b==='nm'?A/factor:A*factor)+(b==='nm'?' lbf·ft':' N·m'),'Torque-unit conversion only. No fastener specification, tightening recommendation or energy conversion is inferred.'),row('Unit relationship','1 lbf·ft = 1.3558179483314004 N·m')];}};
 return null;
};
