import type {CalculatorConfig,CalculatorResolver,CalculatorResult} from './types';
import {nyc2025TaxTable,nikeAdultChart} from '../../lib/gap20-reference-data';

const num=(s:string)=>s.trim()?Number(s):NaN;
const valid=(x:number,min=-1e9,max=1e9)=>{if(!Number.isFinite(x)||x<min||x>max)throw Error(`Enter a finite number from ${min} to ${max}.`);return x};
const pos=(x:number)=>valid(x,Number.MIN_VALUE);
const whole=(x:number,min:number,max:number)=>{valid(x,min,max);if(!Number.isInteger(x))throw Error('A whole number is required.');return x};
const select=(s:string,options:string[])=>{if(!options.includes(s))throw Error('Choose a displayed option.');return s};
const fmt=(x:number)=>{if(!Number.isFinite(x))throw Error('Result exceeds numeric precision.');return x.toLocaleString('en-US',{maximumFractionDigits:8})};
const row=(label:string,value:string,note?:string):CalculatorResult=>({label,value,note});
const cfg=(labels:string[],suffix:string[],run:()=>CalculatorResult[]):CalculatorConfig=>({labels:[...labels,...Array(Math.max(0,3-labels.length)).fill('Unused')],suffix,calculate:()=>{try{return run()}catch(e){return[row('Unable to calculate','Review your inputs',e instanceof Error?e.message:'Invalid input.')]}}});
const lines=(text:string,min=1,max=100)=>{const ls=text.trim().split(/\n|;/);if(!text.trim()||ls.length<min||ls.length>max)throw Error(`Enter ${min}–${max} nonempty rows.`);return ls};
const values=(text:string,n:number)=>{const v=text.trim().split(/[\s,]+/).map(x=>valid(num(x)));if(v.length!==n)throw Error(`Each row requires ${n} numbers.`);return v};
const vector=(v:number[])=>v.map(fmt).join(', ');

export const decathlonEvents=[
 ['100 m',25.4347,18,1.81,'s','track'],['Long jump',.14354,220,1.4,'m','jump'],['Shot put',51.39,1.5,1.05,'m','field'],['High jump',.8465,75,1.42,'m','jump'],['400 m',1.53775,82,1.81,'s','track'],['110 m hurdles',5.74352,28.5,1.92,'s','track'],['Discus',12.91,4,1.1,'m','field'],['Pole vault',.2797,100,1.35,'m','jump'],['Javelin',10.14,7,1.08,'m','field'],['1500 m',.03768,480,1.85,'s','track'],
] as const;
export const decathlonPoints=(performances:number[])=>{if(performances.length!==10)throw Error('Supply ten event performances in the displayed order.');return decathlonEvents.map((event,i)=>{const p=pos(performances[i]),scaled=event[5]==='jump'?p*100:p,difference=event[5]==='track'?event[2]-scaled:scaled-event[2];return Math.floor(event[1]*Math.max(0,difference)**event[3])})};
export const matrixSpaces=(text:string)=>{
 const original=lines(text,1,8).map(l=>l.trim().split(/[\s,]+/).map(x=>valid(num(x),-1e6,1e6))),cols=original[0].length;
 if(cols<1||cols>8||original.some(r=>r.length!==cols))throw Error('Use a rectangular real matrix of at most 8 by 8.');
 const m=original.map(r=>[...r]),scale=Math.max(...m.flat().map(Math.abs)),epsilon=scale*1e-10;const pivots:number[]=[];let r=0;
 for(let c=0;c<cols&&r<m.length;c++){let best=r;for(let i=r+1;i<m.length;i++)if(Math.abs(m[i][c])>Math.abs(m[best][c]))best=i;if(Math.abs(m[best][c])<=epsilon)continue;[m[r],m[best]]=[m[best],m[r]];const divisor=m[r][c];m[r]=m[r].map(x=>x/divisor);for(let i=0;i<m.length;i++)if(i!==r){const factor=m[i][c];m[i]=m[i].map((x,j)=>x-factor*m[r][j])}pivots.push(c);r++}
 // Rank decisions use original-scale tolerance; the normalized display uses dimensionless tolerance.
 const clean=(x:number)=>Math.abs(x)<1e-10?0:x;m.forEach((row,i)=>row.forEach((x,j)=>row[j]=i>=pivots.length?0:clean(x)));
 const free=Array.from({length:cols},(_,i)=>i).filter(i=>!pivots.includes(i));
 const nullBasis=free.map(c=>{const v=Array(cols).fill(0);v[c]=1;pivots.forEach((p,i)=>v[p]=clean(-m[i][c]));return v});
 return{original,rref:m,pivots,free,nullBasis,columnBasis:pivots.map(c=>original.map(r=>r[c])),rowBasis:m.slice(0,pivots.length)};
};
export const nycTax2025=(income:number,status:string)=>{whole(income,0,1e9);select(status,['single','joint','head']);const col=status==='single'?2:status==='joint'?3:4;if(income<65000){const r=nyc2025TaxTable.find(r=>income>=r[0]&&income<r[1]);if(!r)throw Error('Tax table interval unavailable.');return{tax:r[col],method:`2025 city table: ${r[0]} ≤ income < ${r[1]}`}}const thresholds=status==='single'?[12000,25000,50000]:status==='joint'?[21600,45000,90000]:[14400,30000,60000],bases=status==='single'?[369,858,1813]:status==='joint'?[665,1545,3264]:[443,1030,2176];let tax=income*.03078;for(let i=0;i<3;i++)if(income>thresholds[i])tax=bases[i]+(income-thresholds[i])*[.03762,.03819,.03876][i];return{tax:Math.round(tax),method:'2025 official city rate schedule; whole-dollar rounding'}};
const roundTenth=(x:number)=>Math.sign(x)*Math.round((Math.abs(x)+Number.EPSILON)*10)/10;
export const golfRawIndex=(text:string)=>{const x=lines(text,3,20).flatMap(l=>l.trim().split(/[\s,]+/).map(t=>valid(num(t),-30,100)));if(x.length<3||x.length>20)throw Error('Enter 3–20 already rounded score differentials, one per line.');if(x.some(v=>Math.abs(v*10-Math.round(v*10))>1e-8))throw Error('Use recorded differentials rounded to one decimal.');const n=x.length,k=n<=5?1:n<=8?2:n<=11?3:n<=14?4:n<=16?5:n<=18?6:n===19?7:8,adjust=n===3?-2:n===4||n===6?-1:0,used=[...x].sort((a,b)=>a-b).slice(0,k);return{value:roundTenth(used.reduce((s,v)=>s+v,0)/k+adjust),used,adjust,n}};

export const resolveGap20:CalculatorResolver=({slug,a,b,c,d,e,f='',g='',h=''})=>{
 const A=num(a),B=num(b),C=num(c),D=num(d),E=num(e),F=num(f),G=num(g),H=num(h);
 if(slug==='decathlon-scoring-calculator')return cfg(['Ten performances in official event order: seconds or metres'],['textarea'],()=>{const p=a.trim().split(/[\s,;]+/).map(num),points=decathlonPoints(p);return[row('Men’s decathlon points',fmt(points.reduce((s,x)=>s+x,0))),...points.map((v,i)=>row(decathlonEvents[i][0],String(v)+' points',`${fmt(p[i])} ${decathlonEvents[i][4]}`)),row('Timing convention','Fully automatic sprint times; supplied seconds for 1500 m')]});
 if(slug==='dotted-note-duration-calculator')return cfg(['Quarter-note tempo','Base note denominator','Augmentation dots'],['BPM','select:1=Whole|2=Half|4=Quarter|8=Eighth|16=Sixteenth|32=Thirty-second|64=Sixty-fourth|128=One-hundred-twenty-eighth',''],()=>{valid(A,1,1000);select(b,['1','2','4','8','16','32','64','128']);whole(C,0,8);const factor=2-2**(-C),beats=4/B*factor;return[row('Note duration',fmt(60/A*beats*1000)+' ms'),row('Quarter-note beats',fmt(beats)),row('Fraction of a whole note',fmt(factor/B)),row('Dot multiplier',fmt(factor)),row('Seconds',fmt(60/A*beats))]});
 if(slug==='matrix-basis-calculator')return cfg(['Real matrix: one row per line'],['textarea'],()=>{const m=matrixSpaces(a);return[row('Rank and nullity',`${m.pivots.length} and ${m.original[0].length-m.pivots.length}`),row('Reduced row echelon form',m.rref.map(vector).join('\n')),row('Pivot columns: original matrix',m.pivots.map(i=>String(i+1)).join(', ')||'None'),row('Column-space basis',m.columnBasis.map(vector).join('\n')||'Empty basis: zero space'),row('Row-space basis',m.rowBasis.map(vector).join('\n')||'Empty basis: zero space'),row('Null-space basis',m.nullBasis.map(vector).join('\n')||'Empty basis: zero null space'),row('Tolerance','Relative pivot threshold 1e−10 of original maximum entry; numerical approximation')]});
 if(slug==='complex-number-calculator')return cfg(['First real part','First imaginary part','Second real part','Second imaginary part','Operation'],['','','','','select:add=Add|subtract=Subtract|multiply=Multiply|divide=Divide'],()=>{[A,B,C,D].forEach(x=>valid(x));select(e,['add','subtract','multiply','divide']);let re:number,im:number;if(e==='add'){re=A+C;im=B+D}else if(e==='subtract'){re=A-C;im=B-D}else if(e==='multiply'){re=A*C-B*D;im=A*D+B*C}else{const den=C*C+D*D;pos(den);re=(A*C+B*D)/den;im=(B*C-A*D)/den}const magnitude=Math.hypot(re,im);return[row('Complex result',`${fmt(re)} ${im<0?'−':'+'} ${fmt(Math.abs(im))}i`),row('Real part',fmt(re)),row('Imaginary coefficient',fmt(im)),row('Modulus',fmt(magnitude)),row('Principal argument',magnitude===0?'Undefined for zero':fmt(Math.atan2(im,re)*180/Math.PI)+' degrees')]});
 if(slug==='snow-weight-load-calculator')return cfg(['Measurement mode','Measured snow depth or water equivalent','Measured bulk snow density: depth mode only','Uniformly represented area'],['select:depth=Snow depth and density|swe=Snow water equivalent','m depth or mm SWE','kg/m³','m²'],()=>{select(a,['depth','swe']);valid(B,0,1000);pos(D);const massArea=a==='depth'?B*valid(C,Number.MIN_VALUE,1000):B;return[row('Measured snow mass per area',fmt(massArea)+' kg/m²'),row('Weight pressure at standard gravity',fmt(massArea*9.80665/1000)+' kPa'),row('Total represented snow mass',fmt(massArea*D)+' kg'),row('Total represented weight',fmt(massArea*D*9.80665/1000)+' kN'),row('Scope','Uniform measured mass model; no roof capacity or code design load')]});
 if(slug==='labrador-human-age-calculator')return cfg(['Age: dog years or human comparison years','Study population confirmed','Mapping direction'],['years','select:no=Other or unknown breed: unsupported|yes=Labrador: use study comparison','select:forward=Dog years to human comparison|reverse=Human comparison years to dog years'],()=>{if(b!=='yes')throw Error('The published mapping is scoped to Labradors, not all dog breeds.');select(c,['forward','reverse']);let dog:number,human:number;if(c==='forward'){dog=valid(A,1,16);human=16*Math.log(dog)+31}else{human=valid(A,31,16*Math.log(16)+31);dog=Math.exp((human-31)/16)}return[row(c==='forward'?'Published human-age comparison':'Inverted Labrador chronological age',fmt(c==='forward'?human:dog)+' years'),row('Dog age used or inferred',fmt(dog)+' years'),row('Human comparison age',fmt(human)+' years'),row('Model','16 × natural logarithm of dog age + 31; inverse exp((human − 31)/16)'),row('Interpretation','Population comparison or mathematical inverse; not a diagnosis or lifespan prediction')]});
 if(slug==='golf-handicap-worksheet')return cfg(['Worksheet mode','18-hole adjusted gross score','Matching course rating','Matching slope rating','Official PCC for that round','Most recent recorded differentials: one per line'],['select:differential=One 18-hole score differential|index=Raw index arithmetic from 3–20 differentials','strokes','','','select:-1=−1|0=0|1=+1|2=+2|3=+3','textarea'],()=>{select(a,['differential','index']);if(a==='differential'){whole(B,18,300);valid(C,30,90);whole(D,55,155);whole(E,-1,3);const diff=roundTenth(113/D*(B-C-E));return[row('18-hole score differential',fmt(diff)),row('Unrounded differential',fmt(113/D*(B-C-E))),row('PCC used',fmt(E)),row('Scope','Adjusted score must already include applicable hole-score limits')]}const x=golfRawIndex(f);return[row('Raw index arithmetic',x.value<0?'+'+fmt(-x.value):fmt(x.value),'Not an official Handicap Index; caps and exceptional-score adjustments are excluded.'),row('Signed raw value',fmt(x.value)),row('Lowest differentials used',vector(x.used)),row('Fewer-score adjustment',fmt(x.adjust)),row('Recorded scores supplied',String(x.n))]});
 if(slug==='absolute-neutrophil-count-calculator')return cfg(['Reported white blood cell count','WBC reporting unit','Mature neutrophils or combined neutrophils','Separately reported bands','Differential convention'],['','select:cells=Cells/µL|si=10⁹/L or 10³/µL','%','%','select:separate=Separate mature and band percentages|combined=Combined neutrophils: bands must be zero'],()=>{valid(A,0,1000000);select(b,['cells','si']);valid(C,0,100);valid(D,0,100);select(e,['separate','combined']);if(e==='combined'&&D!==0)throw Error('Set bands to zero when the neutrophil percentage already includes bands.');if(C+D>100)throw Error('Combined percentages cannot exceed 100.');const wbc=b==='si'?A*1000:A,anc=wbc*(C+D)/100;return[row('Calculated absolute neutrophil count',fmt(anc)+' cells/µL'),row('ANC in SI units',fmt(anc/1000)+' ×10⁹/L'),row('Neutrophil fraction used',fmt(C+D)+'%'),row('WBC converted to cells/µL',fmt(wbc)),row('Scope','Laboratory arithmetic only; compare with the original report and clinician interpretation')]});
 if(slug==='harris-benedict-calculator')return cfg(['Adult body mass','Height','Adult age','Published sex coefficient'],['kg','cm','years','select:male=Male coefficient|female=Female coefficient'],()=>{valid(A,30,250);valid(B,120,230);valid(C,18,65);select(d,['male','female']);const v=d==='male'?88.362+13.397*A+4.799*B-5.677*C:447.593+9.247*A+3.098*B-4.330*C;pos(v);return[row('1984 revised Harris–Benedict estimate',fmt(v)+' kcal/day'),row('Energy equivalent',fmt(v*4.184)+' kJ/day'),row('Model version','Roza and Shizgal revision, 1984'),row('Scope','Resting equation estimate; no activity multiplier or dietary prescription')]});
 if(slug==='adult-shoe-size-converter')return cfg(['Nike adult chart input scale','Published size or measured foot length','Chart scope confirmed'],['select:men=US men|women=US women|uk=UK|eu=EU|jp=CM / JP box label|cm=Measured foot length cm|inch=Measured foot length inches','','select:no=Not confirmed: do not convert|yes=Use Nike adult chart, checked 6 Oct 2026'],()=>{select(a,['men','women','uk','eu','jp','cm','inch']);pos(B);if(c!=='yes')throw Error('Confirm the brand-specific adult chart before converting.');const col=['men','women','uk','eu','jp','inch','cm'].indexOf(a);let matches=nikeAdultChart.filter(r=>Math.abs(r[col]-B)<1e-7);if(a==='cm'||a==='inch'){if(B<nikeAdultChart[0][col]||B>nikeAdultChart.at(-1)![col])throw Error('Foot length is outside the chart range.');if(!matches.length)matches=nikeAdultChart.filter(r=>r[col]>=B).slice(0,1)}if(!matches.length)throw Error('Size is not present in this adult chart.');return[row('Nike adult chart match',matches.map(r=>`US men ${r[0]} / US women ${r[1]}`).join('; ')),...matches.map((r,i)=>row(`Chart row ${i+1}`,`UK ${r[2]}; EU ${r[3]}; CM/JP ${r[4]}; foot ${fmt(r[5])} in (${fmt(r[6])} cm)`)),row('Scope','Brand chart comparison; duplicate labels show every match and do not guarantee fit')]});
 if(slug==='food-energy-calculator')return cfg(['Mode','Energy amount: conversion mode','Energy unit: conversion mode','Nutrient rows: name, grams on one common basis','Basis food mass: composition mode','Consumed portion: composition mode'],['select:convert=Energy unit conversion|composition=EU Annex XIV nutrient energy','','select:kcal=Kilocalories kcal|cal=Small thermochemical calories|kj=Kilojoules kJ','textarea','g','g'],()=>{select(a,['convert','composition']);if(a==='convert'){valid(B,0);select(c,['kcal','cal','kj']);const kcal=c==='kcal'?B:c==='cal'?B/1000:B/4.184;return[row('Kilocalories',fmt(kcal)+' kcal'),row('Small thermochemical calories',fmt(kcal*1000)+' cal'),row('Kilojoules',fmt(kcal*4.184)+' kJ')]}pos(E);valid(F,0);const factors:Record<string,number[]>={carbs:[4,17],protein:[4,17],fat:[9,37],polyols:[2.4,10],fibre:[2,8],alcohol:[7,29],acids:[3,13],salatrims:[6,25],erythritol:[0,0]};const used=new Set<string>();let kcal=0,kj=0,mass=0;for(const l of lines(d,1,9)){const p=l.trim().split(/[\s,]+/);if(p.length!==2||!factors[p[0].toLowerCase()])throw Error('Use rows: carbs, protein, fat, polyols, fibre, alcohol, acids, salatrims or erythritol, followed by grams.');const name=p[0].toLowerCase(),grams=valid(num(p[1]),0);if(used.has(name))throw Error('Combine repeated nutrient categories into one row.');used.add(name);mass+=grams;kcal+=grams*factors[name][0];kj+=grams*factors[name][1]}if(mass>E+1e-8)throw Error('Disjoint nutrient mass exceeds food basis; check double counting.');return[row('Portion energy from EU factors',fmt(kcal*F/E)+' kcal'),row('Portion kilojoules from EU factors',fmt(kj*F/E)+' kJ'),row('Basis energy',fmt(kcal)+' kcal / '+fmt(kj)+' kJ'),row('Portion multiplier',fmt(F/E)),row('Scope','Supplied composition only; regulatory kcal and kJ factors are independently specified')]});
 if(slug==='taxable-income-worksheet')return cfg(['Already assessed includible income amounts','Already assessed income adjustments','Allowed deductions on the same tax basis'],['textarea','textarea','textarea'],()=>{const sum=(s:string)=>lines(s).flatMap(l=>l.trim().split(/[\s,]+/).map(t=>valid(num(t),0))).reduce((s,x)=>s+x,0);const income=sum(a),adjust=sum(b),deduct=sum(c);if(adjust>income)throw Error('Adjustments exceed supplied includible income; verify this simplified worksheet applies.');return[row('Supplied taxable-income arithmetic',fmt(Math.max(0,income-adjust-deduct))+' currency'),row('Includible income total',fmt(income)),row('Adjusted subtotal',fmt(income-adjust)),row('Supplied deductions total',fmt(deduct)),row('Scope','No jurisdiction, eligibility, tax rates or filing liability inferred')]});
 if(slug==='texas-sales-tax-calculator')return cfg(['Texas transaction scope','Supplied taxable sale price','Taxable additional charges','Eligible dealer trade-in: vehicle mode only','Verified local rate: retail mode only'],['select:retail=General taxable retail|vehicle=Dealer motor vehicle purchase','USD','USD','USD','%'],()=>{select(a,['retail','vehicle']);valid(B,0);valid(C,0);let base=B+C,rate=.0625;if(a==='retail'){valid(E,0,2);rate+=E/100}else{valid(D,0,B);base-=D}return[row('Texas sales tax arithmetic',fmt(Math.round(base*rate*100)/100)+' USD'),row('Supplied taxable base',fmt(base)+' USD'),row('Applied combined rate',fmt(rate*100)+'%'),row('Taxable base plus calculated tax',fmt(base+Math.round(base*rate*100)/100)+' USD'),row('Scope',a==='retail'?'Local rate must be verified for sourcing location':'Dealer purchase only; private-party SPV and special exemptions excluded')]});
 if(slug==='nyc-resident-income-tax-calculator')return cfg(['2025 NYC taxable income: IT-201 line 47','2025 filing status','Full-year NYC resident scope confirmed'],['USD: whole dollars','select:single=Single or married filing separately|joint=Married jointly or qualifying surviving spouse|head=Head of household','select:no=Not confirmed: do not calculate|yes=Full-year NYC resident scope confirmed'],()=>{if(c!=='yes')throw Error('Confirm full-year NYC residency, applicable filing status and tax year 2025. Mixed-residency joint returns are excluded.');const t=nycTax2025(A,b);return[row('2025 NYC resident tax before credits',fmt(t.tax)+' USD'),row('Method',t.method),row('Taxable income used',fmt(A)+' USD'),row('Scope','City resident tax only; state, federal, credits and part-year calculations excluded')]});
 if(slug==='clothing-size-chart-matcher')return cfg(['Measured bust or chest','Measured waist','Measured hip','Own brand chart: label,bust min,max,waist min,max,hip min,max'],['same unit','same unit','same unit','textarea'],()=>{[A,B,C].forEach(pos);const chart=lines(d,1,50).map(l=>{const p=l.split(',').map(x=>x.trim());if(p.length!==7||!p[0])throw Error('Each row needs a label and six numeric range endpoints.');const v=p.slice(1).map(t=>valid(num(t),0));for(let i=0;i<6;i+=2)if(v[i]>v[i+1])throw Error('Range minimum must not exceed maximum.');return{label:p[0],v}});const matches=chart.filter(({v})=>A>=v[0]&&A<=v[1]&&B>=v[2]&&B<=v[3]&&C>=v[4]&&C<=v[5]);return[row('Matching supplied chart rows',matches.map(x=>x.label).join(', ')||'No row contains all three measurements'),...chart.map(({label,v})=>row(label,[A,B,C].map((x,i)=>x<v[i*2]?'below':x>v[i*2+1]?'above':'within').join(' / ')+' (bust, waist, hip)')),row('Scope','Inclusive supplied ranges; no body-shape label or fit guarantee')]});
 if(slug==='boer-lean-body-mass-calculator')return cfg(['Adult body mass','Height','Published sex coefficient','Adult age: scope check'],['kg','cm','select:male=Male coefficient|female=Female coefficient','years'],()=>{valid(A,30,200);valid(B,140,210);select(c,['male','female']);valid(D,18,65);const lean=c==='male'?.407*A+.267*B-19.2:.252*A+.473*B-48.3;if(lean<=0||lean>=A)throw Error('Equation output is outside plausible mass bounds; do not extrapolate this model.');return[row('Boer estimated lean body mass',fmt(lean)+' kg'),row('Estimated lean share',fmt(lean/A*100)+'%'),row('Model','Boer, 1984'),row('Scope','Equation estimate, not measured skeletal muscle or a medication dose')]});
 if(slug==='point-mass-center-of-mass-calculator')return cfg(['Point rows: positive mass, x, y, z'],['textarea'],()=>{const points=lines(a).map(l=>values(l,4));points.forEach(p=>pos(p[0]));const mass=points.reduce((s,p)=>s+p[0],0),center=[1,2,3].map(i=>points.reduce((s,p)=>s+(p[0]/mass)*p[i],0));return[row('Center of mass: x, y, z',vector(center)+' coordinate units'),row('Total supplied mass',fmt(mass)+' mass units'),row('First moments: x, y, z',vector([1,2,3].map(i=>points.reduce((s,p)=>s+p[0]*p[i],0)))+' mass × coordinate units'),row('Point count',String(points.length))]});
 if(slug==='construction-crew-size-calculator')return cfg(['Required productive labour hours','Available workdays','Paid hours per worker per day','Productive share of paid hours','Supplied cost per paid worker-hour'],['worker-hours','days','hours/day','%','currency/hour'],()=>{valid(A,0);whole(B,1,3650);valid(C,Number.MIN_VALUE,24);valid(D,Number.MIN_VALUE,100);valid(E,0);const perWorker=B*C*D/100,crew=Math.ceil(A/perWorker);return[row('Whole workers required in this model',String(crew)),row('Productive capacity with rounded crew',fmt(crew*perWorker)+' worker-hours'),row('Excess productive capacity',fmt(crew*perWorker-A)+' worker-hours'),row('Planned paid worker-hours',fmt(crew*B*C)),row('Supplied labour cost scenario',fmt(crew*B*C*E)+' currency')]});
 if(slug==='excavation-haul-calculator')return cfg(['Bank excavation length','Bank excavation width','Bank excavation depth','Supplied swell percentage','Bank bulk density','Truck loose-volume capacity','Truck payload capacity','Supplied cost per complete trip'],['m','m','m','%','kg/m³','m³','kg','currency'],()=>{[A,B,C,E,F,G].forEach(pos);valid(D,0,300);valid(H,0);const bank=A*B*C,loose=bank*(1+D/100),mass=bank*E,byVolume=Math.ceil(loose/F),byMass=Math.ceil(mass/G),trips=Math.max(byVolume,byMass);return[row('Required complete haul trips',fmt(trips)),row('Bank and loose volume',fmt(bank)+' / '+fmt(loose)+' m³'),row('Conserved material mass',fmt(mass)+' kg'),row('Loose bulk density',fmt(E/(1+D/100))+' kg/m³'),row('Volume / payload trip bounds',fmt(byVolume)+' / '+fmt(byMass)),row('Supplied haul cost',fmt(trips*H)+' currency'),row('Scope','Uniform material; legal payload and usable volume must be independently verified')]});
 if(slug==='vector-dot-cross-calculator')return cfg(['Vector A x','Vector A y','Vector A z','Vector B x','Vector B y','Vector B z'],['','','','','',''],()=>{const u=[A,B,C],v=[D,E,F];[...u,...v].forEach(x=>valid(x));const dot=A*D+B*E+C*F,cross=[B*F-C*E,C*D-A*F,A*E-B*D],mu=Math.hypot(...u),mv=Math.hypot(...v);return[row('Dot product',fmt(dot)),row('Cross product: A × B',vector(cross)),row('Vector magnitudes: A, B',vector([mu,mv])),row('Angle between nonzero vectors',mu===0||mv===0?'Undefined for a zero vector':fmt(Math.acos(Math.min(1,Math.max(-1,dot/(mu*mv))))*180/Math.PI)+' degrees'),row('Vector projection of A onto B',mv===0?'Undefined for zero B':vector(v.map(x=>x*dot/(mv*mv))))]});
 return null;
};
