import {whoWeightLms} from "../../lib/who-weight-for-age";
import type {CalculatorResolver,CalculatorResult} from './types';
const f=(v:number,d=2)=>v.toLocaleString('en-US',{maximumFractionDigits:d});
const out=(label:string,value:string,note?:string):CalculatorResult=>({label,value,note});
const error=(note:string)=>[out('Check your inputs','Unable to calculate',note)];
const nums=(...s:string[])=>s.every(x=>x.trim()!==''&&Number.isFinite(Number(x))&&Number(x)>=0);
export const resolveRoadmap106:CalculatorResolver=({slug,a,b,c,d,e,cash})=>{
 const A=Number(a),B=Number(b),C=Number(c),D=Number(d),E=Number(e);
 if(slug==='tile-quantity-calculator-pakistan')return{labels:['Net floor or wall area','Tile length','Tile width','Waste allowance','Tiles per box'],suffix:['ft²','in','in','%','tiles'],calculate:()=>{
 if(!nums(a,b,c,d,e)||A<=0||B<=0||C<=0||E<=0||!Number.isInteger(E))return error('Use positive area and tile dimensions, non-negative waste and a whole-number tiles-per-box count.');
 const base=A/(B*C/144),tiles=Math.ceil(base*(100+D)/100);
 return[out('Tiles including waste',f(tiles,0),'Estimate assumes area coverage; layout cuts and grout joints require a supplier takeoff.'),out('Tiles before waste',f(Math.ceil(base),0)),out('Whole boxes to order',f(Math.ceil(tiles/E),0)),out('One tile coverage',f(B*C/144,4)+' ft²')];}};
 if(slug==='sourdough-calculator')return{labels:['Final dough weight','Total hydration','Prefermented flour','Salt as total flour','Starter hydration'],suffix:['g','%','% of total flour','%','%'],calculate:()=>{
 if(!nums(a,b,c,d,e)||A<=0||C>100)return error('Use a positive dough weight and 0–100% prefermented flour.');
 const flour=A/(1+B/100+D/100),sf=flour*C/100,sw=sf*E/100,w=flour*B/100-sw;
 if(w<0)return error('Starter contributes more water than the requested final hydration permits.');
 return[out('Flour to add',f(flour-sf)+' g','Starter flour and water are included in total hydration.'),out('Water to add',f(w)+' g'),out('Ripe starter',f(sf+sw)+' g'),out('Salt',f(flour*D/100)+' g'),out('Total flour',f(flour)+' g')];}};
 if(slug==='audiobook-speed-calculator')return{labels:['Total audiobook hours','Additional minutes','Playback speed','Already listened at normal speed'],suffix:['hours','minutes','×','minutes'],calculate:()=>{
 if(!nums(a,b,c,d)||C<=0||B>=60||D>A*60+B)return error('Enter minutes below 60, positive speed, and elapsed content no longer than the book.');
 const total=A*60+B,remaining=total-D,t=remaining/C,display=(m:number)=>(()=>{const sec=Math.round(m*60);return `${Math.floor(sec/3600)} h ${Math.floor(sec/60)%60} min ${sec%60} sec`})();
 return[out('Remaining listening time',display(t),'Time saved compares the remaining content with 1× playback.'),out('Time saved',display(Math.max(0,remaining-t))),out('Full book at this speed',display(total/C)),out('Remaining content',f(remaining)+' min')];}};
 if(slug==='surface-area-calculator'){
 const mode=a,flat=['rectangle','square','circle','ellipse','triangle','trapezoid','parallelogram'].includes(mode);
 const labels=mode==='cube'?['Edge','Unused','Unused']:mode==='sphere'?['Radius','Unused','Unused']:mode==='cylinder'||mode==='cone'?['Radius','Height','Unused']:mode==='circle'?['Radius','Unused','Unused']:mode==='square'?['Side','Unused','Unused']:mode==='ellipse'?['Semi-major axis','Semi-minor axis','Unused']:mode==='triangle'||mode==='parallelogram'?['Base','Perpendicular height','Unused']:mode==='trapezoid'?['Parallel side 1','Parallel side 2','Perpendicular height']:['Length','Width',mode==='box'?'Height':'Unused'];
 return{labels:['Shape',...labels],suffix:['select:rectangle=Rectangle area|square=Square area|circle=Circle area|ellipse=Ellipse area|triangle=Triangle area|trapezoid=Trapezoid area|parallelogram=Parallelogram area|cube=Cube total surface|box=Box total surface|sphere=Sphere surface|cylinder=Closed cylinder surface|cone=Closed cone surface','units','units','units'],calculate:()=>{
 if(!nums(b,...(labels[1]!=='Unused'?[c]:[]),...(labels[2]!=='Unused'?[d]:[]))||B<=0||(labels[1]!=='Unused'&&C<=0)||(labels[2]!=='Unused'&&D<=0))return error('Enter positive dimensions in the same length unit.');
 const v:Record<string,number>={rectangle:B*C,square:B*B,circle:Math.PI*B*B,ellipse:Math.PI*B*C,triangle:B*C/2,trapezoid:(B+C)*D/2,parallelogram:B*C,cube:6*B*B,box:2*(B*C+B*D+C*D),sphere:4*Math.PI*B*B,cylinder:2*Math.PI*B*(B+C),cone:Math.PI*B*(B+Math.hypot(B,C))};
 return[out(flat?'Plane area':'Total surface area',f(v[mode])+' square units','Square units follow the entered length unit. Cylinder and cone include their bases.'),out('Selected shape',mode),out('Dimension type',flat?'Two-dimensional area':'Three-dimensional surface')];}};
 }
 if(slug==='body-surface-area-calculator')return{labels:['Height','Weight','Unused'],suffix:['cm','kg',''],calculate:()=>!nums(a,b)||A<=0||B<=0?error('Height and weight must be positive, in cm and kg.'): [out('Mosteller body surface area',f(Math.sqrt(A*B/3600),3)+' m²','A mathematical estimate, not a medication dose.'),out('Height in metres',f(A/100)+' m'),out('Weight',f(B)+' kg')]};
 if(slug==='roof-area-calculator')return{labels:['Horizontal plan length incl. overhang','Horizontal plan width incl. overhang','Pitch rise per 12 horizontal units','Material waste allowance'],suffix:['ft','ft','rise / 12','%'],calculate:()=>!nums(a,b,c,d)||A<=0||B<=0?error('Use positive plan dimensions and a non-negative pitch.'): [out('Sloped roof area',f(A*B*Math.hypot(1,C/12))+' ft²','Assumes a roof with a uniform pitch. Not a structural or access-safety assessment.'),out('Coverage with waste',f(A*B*Math.hypot(1,C/12)*(1+D/100))+' ft²'),out('Roofing squares before waste',f(A*B*Math.hypot(1,C/12)/100)),out('Slope multiplier',f(Math.hypot(1,C/12),4))]};
 if(slug==='corrected-calcium-calculator')return{labels:['Measured total calcium','Albumin','Units'],suffix:[c==='si'?'mmol/L':'mg/dL',c==='si'?'g/L':'g/dL','select:us=mg/dL and g/dL|si=mmol/L and g/L'],calculate:()=>!nums(a,b)||A<=0||B<=0?error('Enter positive calcium and albumin measurements from the same sample.'): [out('Legacy albumin-adjusted calcium',f(A+(c==='si'?.02*(40-B):.8*(4-B)),3)+(c==='si'?' mmol/L':' mg/dL'),'This legacy estimate can misclassify calcium status. It is not measured ionized calcium or a diagnosis.'),out('Unadjusted total calcium',f(A)+(c==='si'?' mmol/L':' mg/dL')),out('Albumin adjustment',f(c==='si'?.02*(40-B):.8*(4-B),3))]};
 if(slug==='grade-curve-calculator')return{labels:['Scores separated by commas','Curve method','Added points or target class mean','Maximum score'],suffix:['text','select:add=Add points|highest=Highest score to maximum|mean=Shift mean to target','points','points'],calculate:()=>{
 const scores=a.split(/[,;\s]+/).filter(Boolean).map(Number);if(!scores.length||scores.some(x=>!Number.isFinite(x)||x<0||x>D)||!nums(c,d)||D<=0)return error('Use scores between zero and the maximum and a non-negative curve parameter.');
 const mean=scores.reduce((t,x)=>t+x,0)/scores.length,shift=b==='highest'?D-Math.max(...scores):b==='mean'?C-mean:C,curved=scores.map(x=>Math.min(D,Math.max(0,x+shift)));
 return[out('Curved scores',curved.map(x=>f(x)).join(', '),'Scores are capped between zero and the maximum. This does not define your school’s grading policy.'),out('Original class mean',f(mean)),out('Curved class mean',f(curved.reduce((t,x)=>t+x,0)/scores.length)),out('Applied shift',f(shift)+' points')];}};
 if(slug==='pt-141-dosage-calculator')return{labels:['Hours since last prescribed Vyleesi dose','Doses already used this month','Unused'],suffix:['hours','doses',''],calculate:()=>{
 if(!nums(a,b)||!Number.isInteger(B))return error('Enter non-negative elapsed hours and a whole-number monthly dose count.');
 return[out('Label limit check',A<24||B>=8?'A label limit is reached':'Entered counts are below label limits','This does not establish that a dose is appropriate or safe. Follow your prescription; ask your prescriber about contraindications.'),out('Time short of 24-hour interval',f(Math.max(0,24-A))+' hours'),out('Monthly count before next dose',`${B} / 8`),out('Approved single-use presentation','1.75 mg / 0.3 mL')];}};
 if(slug==='btu-calculator')return{labels:['Floor area','Regular occupants','Sun exposure','Room type','Heating load if using heating mode'],suffix:['ft²','people','select:normal=Normal|sun=Very sunny|shade=Heavily shaded','select:room=Room cooling|kitchen=Kitchen cooling|heating=User-specified heating load','BTU/h per ft²'],calculate:()=>{
 if(!nums(a,b,e)||A<=0||!Number.isInteger(B))return error('Enter positive area, whole-number occupants, and non-negative heating load.');
 if(d==='heating'){if(E<=0)return error('Heating mode requires your own design load in BTU/h per ft².');return[out('Entered-load heating estimate',f(A*E)+' BTU/h','No automatic furnace sizing. Use a professionally calculated building heat loss.'),out('Heating load entered',f(E)+' BTU/h per ft²'),out('Floor area',f(A)+' ft²')];}
 if(A<100||A>=2500)return error('The room-cooling reference table covers 100 to under 2,500 ft². Ask a professional outside this range.');
 const table=[[150,5000],[250,6000],[300,7000],[350,8000],[400,9000],[450,10000],[550,12000],[700,14000],[1000,18000],[1200,21000],[1400,23000],[1500,24000],[2000,30000],[2500,34000]],base=table.find(([upper])=>A<upper)![1],v=base*(c==='sun'?1.1:c==='shade'?.9:1)+Math.max(0,B-2)*600+(d==='kitchen'?4000:0);
 return[out('Estimated room cooling capacity',f(v)+' BTU/h','ENERGY STAR area table for an 8-ft ceiling, with sun, occupant and kitchen adjustments. Not whole-house HVAC design.'),out('Cooling tons equivalent',f(v/12000,3)+' tons'),out('Unadjusted table capacity',f(base)+' BTU/h')];}};
 if(slug==='arrow-speed-calculator')return{labels:['Measured flight distance','Measured flight time','Arrow mass'],suffix:['ft','seconds','grains'],calculate:()=>!nums(a,b,c)||A<=0||B<=0||C<=0?error('Enter positive measured distance, elapsed seconds and arrow mass.'): [out('Average measured arrow speed',f(A/B)+' ft/s','Measured distance/time method. This is average flight speed, not an IBO bow-rating prediction or launch speed.'),out('Metric speed',f(A/B*.3048)+' m/s'),out('Kinetic energy at average speed',f(.5*C*.00006479891*(A/B*.3048)**2)+' J'),out('Arrow mass',f(C)+' grains')]};
 if(slug==='volume-calculator'){
 const mode=a,cylinder=['cylinder','pond-round','sphere','cone','tube'].includes(mode),labels=mode==='cube'?['Edge','Unused','Unused']:mode==='sphere'?['Radius','Unused','Unused']:mode==='tube'?['Outer radius','Inner radius','Length']:cylinder?['Radius','Height or average depth','Unused']:['Length','Width','Height or average depth'];
 return{labels:['Shape',...labels,'Length unit'],suffix:['select:box=Box or rectangular tank|cube=Cube|pond=Rectangular pond|pond-round=Round pond|cylinder=Cylinder or round tank|cone=Cone|sphere=Sphere|tube=Hollow tube','units','units','units','select:ft=Feet|in=Inches|cm=Centimetres|m=Metres'],calculate:()=>{
 if(!nums(b,...(labels[1]!=='Unused'?[c]:[]),...(labels[2]!=='Unused'?[d]:[]))||B<=0||(labels[1]!=='Unused'&&C<=0)||(labels[2]!=='Unused'&&D<=0)||mode==='tube'&&C>=B)return error('Use positive dimensions; the tube’s inner radius must be smaller than its outer radius.');
 const v=mode==='cube'?B**3:mode==='sphere'?4*Math.PI*B**3/3:mode==='cone'?Math.PI*B*B*C/3:mode==='tube'?Math.PI*(B*B-C*C)*D:cylinder?Math.PI*B*B*C:B*C*D,scale=({ft:.3048,in:.0254,cm:.01,m:1} as Record<string,number>)[e],litres=v*scale**3*1000;
 return[out('Geometric volume',f(v,4)+` ${e}³`,'Ponds use measured average depth. Water capacity is theoretical and excludes freeboard, displacement and irregular banks.'),out('Litres',f(litres)),out('US liquid gallons',f(litres/3.785411784)),out('Imperial gallons',f(litres/4.54609))];}};
 }
 if(slug==='productivity-calculator')return{labels:['Completed output units','Number of workers','Hours per worker','Target units per labor-hour'],suffix:['units','workers','hours','units/hour'],calculate:()=>!nums(a,b,c,d)||B<=0||C<=0||D<=0||!Number.isInteger(B)?error('Use non-negative output, whole-number workers and positive hours and target.'): [out('Labor productivity',f(A/(B*C))+' units / labor-hour','Use completed, quality-accepted output and all contributing labor hours.'),out('Total labor input',f(B*C)+' hours'),out('Output against entered target',f(A/(B*C)/D*100)+'%'),out('Hours per unit',A>0?f(B*C/A,4):'Undefined for zero output')]};
 if(slug==='time-between-calculator')return{labels:['Start date and time (UTC)','End date and time (UTC)','Unused'],suffix:['text','text',''],calculate:()=>{
 const parse=(s:string)=>/^\d{4}-\d\d-\d\dT\d\d:\d\d(?::\d\d)?$/.test(s)?(()=>{const ms=Date.parse(s+'Z');return Number.isFinite(ms)&&new Date(ms).toISOString().slice(0,s.length)===s?ms:NaN})():NaN,start=parse(a),end=parse(b),ms=end-start;
 if(!Number.isFinite(ms)||ms<0)return error('Enter valid UTC dates as YYYY-MM-DDTHH:mm with the end on or after the start.');
 return[out('Elapsed time',`${Math.floor(ms/86400000)} days ${Math.floor(ms/3600000)%24} hours ${Math.floor(ms/60000)%60} minutes`,'UTC arithmetic uses actual elapsed time; local daylight-saving times require conversion to UTC first.'),out('Total hours',f(ms/3600000,4)),out('Total minutes',f(ms/60000)),out('Total seconds',f(ms/1000))];}};
 if(slug==='blood-pressure-by-age-calculator')return{labels:['Age (adults only)','Systolic pressure','Diastolic pressure'],suffix:['years','mm Hg','mm Hg'],calculate:()=>{
 if(!nums(a,b,c)||A<18||A>120||B<=C||C<=0)return error('For adults 18–120 only. Use positive readings with systolic greater than diastolic. Children require age, sex and height-specific clinical assessment.');
 const category=B>180||C>120?'Severe hypertension range':B>=140||C>=90?'Stage 2 range':B>=130||C>=80?'Stage 1 range':B>=120?'Elevated range':'Normal range';
 return[out('Adult reading category',category,'One reading is not a diagnosis. Adult categories do not become normal just because age increases.'),out('Entered reading',`${f(B)} / ${f(C)} mm Hg`),out('Urgent guidance',B>180||C>120?'If symptoms such as chest pain, shortness of breath, weakness or vision change occur, call emergency services. Otherwise repeat after 1 minute and contact a clinician promptly.':'Discuss repeated abnormal readings with a clinician; symptoms can require urgent care even below these thresholds.')];}};
 if(slug==='interest-rate-calculator'&&['cd','fd','apy'].includes(d))return{labels:['Deposit principal','Annual nominal rate or APY','Term in years','Mode','Compounds per year (nominal mode)'],suffix:['currency','%','years','select:solve=Solve implied rate|project=Project savings|cd=CD nominal rate|fd=FD nominal rate|apy=Deposit quoted APY|simple=Simple interest','times/year'],calculate:()=>{
 if(!nums(a,b,c,e)||A<=0||C<=0||E<=0||!Number.isInteger(E))return error('Enter positive principal, term and whole-number compounding frequency.');
 const rate=B/100,v=A*Math.pow(d==='apy'?1+rate:1+rate/E,d==='apy'?C:E*C),apy=d==='apy'?B:100*(Math.pow(1+rate/E,E)-1);
 return[out('Deposit maturity value',cash(v),'No withdrawals, additions, tax, penalties or rate changes. 6 months = 0.5 years.'),out('Interest earned',cash(v-A)),out('Effective annual yield',f(apy,4)+'%'),out('Term in months',f(C*12))];}};
 if(slug==='baby-percentile-calculator')return{labels:['WHO reference sex','Age at exact monthly point','Weight','Unused'],suffix:['select:boys=Boys|girls=Girls','whole months (0–24)','kg',''],calculate:()=>{
 if(!nums(b,c)||!Number.isInteger(B)||B>24||C<=0)return error('Use an exact monthly age from 0–24 and positive weight in kg. Do not round an infant’s age to use this table.');
 const [L,M,S]=whoWeightLms[a][B],z=L===0?Math.log(C/M)/S:(Math.pow(C/M,L)-1)/(L*S);
 if(Math.abs(z)>3)return error('This simplified LMS implementation is limited to z-scores from −3 to +3. Ask a clinician to interpret extreme measurements.');
 const x=Math.abs(z)/Math.sqrt(2),t=1/(1+.3275911*x),erf=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-x*x),pct=50*(1+(z<0?-erf:erf));
 return[out('Weight-for-age percentile',f(pct,1)+'%','WHO reference at an exact monthly age; not a birthweight-for-gestational-age percentile or diagnosis.'),out('Weight z-score',f(z,3)),out('Reference median weight',f(M,4)+' kg')];}};
 return null;
};
