import type {CalculatorResolver,CalculatorResult} from './types';
const fmt=(x:number)=>Number.isFinite(x)?x.toLocaleString('en-US',{maximumFractionDigits:8}):'Undefined';
const row=(label:string,value:string,note?:string):CalculatorResult=>({label,value,note});
const bad=(note:string)=>[row('Check inputs','Enter valid values',note)];
const number=(s:string,min=-1e12,max=1e12)=>s.trim()!==''&&Number.isFinite(Number(s))&&Number(s)>=min&&Number(s)<=max;
const whole=(s:string,min=0,max=1e9)=>number(s,min,max)&&Number.isInteger(Number(s));
export function parseMatrix(text:string):number[][]{
 const rows=text.trim().split(/[\n;]+/).map(r=>r.trim().split(/[,\s]+/).map(s=>{if(!number(s))throw new Error('Use finite numeric matrix entries within ±1e12.');return Number(s);}));
 if(!text.trim()||rows.length>8||rows[0].length>8||rows.some(r=>r.length!==rows[0].length))throw new Error('Use a rectangular matrix with 1–8 rows and 1–8 columns.');return rows;
}
export function multiplyMatrices(a:number[][],b:number[][]){if(a[0].length!==b.length)throw new Error('Columns of A must equal rows of B.');return a.map(r=>b[0].map((_,j)=>r.reduce((sum,x,k)=>sum+x*b[k][j],0)));}
const gcd=(a:bigint,b:bigint):bigint=>b?gcd(b,a%b):a<BigInt(0)?-a:a;
export function decimalFraction(text:string){const m=text.trim().match(/^([+-]?)(\d{1,40})(?:\.(\d{1,18}))?$/);if(!m)throw new Error('Use a finite decimal with up to 40 whole digits and 18 decimal places, without exponents or repeating brackets.');const den=BigInt(10)**BigInt((m[3]||'').length),num=BigInt(m[2]+(m[3]||''))*(m[1]==='-'?-BigInt(1):BigInt(1)),div=gcd(num,den);return{numerator:num/div,denominator:den/div};}
const romanPairs:[number,string][]=[[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];
export function toRoman(n:number){if(!Number.isInteger(n)||n<1||n>3999)throw new Error('Use a whole number from 1 through 3999.');let out='';for(const [v,s]of romanPairs)while(n>=v){out+=s;n-=v;}return out;}
export function fromRoman(s:string){const text=s.trim().toUpperCase();if(!/^[IVXLCDM]+$/.test(text))throw new Error('Use standard Roman numerals I,V,X,L,C,D,M.');let rest=text,n=0;for(const[v,t]of romanPairs)while(rest.startsWith(t)){n+=v;rest=rest.slice(t.length);}if(rest||n<1||n>3999||toRoman(n)!==text)throw new Error('Use canonical subtractive notation, such as IV rather than IIII.');return n;}
export function eulerAffine(a:number,b:number,c:number,x:number,y:number,h:number,n:number){const steps=[{x,y}];for(let i=0;i<n;i++){y+=h*(a*x+b*y+c);x+=h;if(!Number.isFinite(y)||Math.abs(y)>1e100)throw new Error('The Euler iteration diverged beyond the supported finite range.');steps.push({x,y});}return steps;}
export const resolveRoadmap328:CalculatorResolver=({slug,a,b,c,d,e,f='0',g='0',h='0'})=>{
 const A=Number(a),B=Number(b),C=Number(c),D=Number(d),E=Number(e),F=Number(f),G=Number(g);
 if(slug==='matrix-multiplication-calculator')return{labels:['Matrix A: one row per line','Matrix B: one row per line','Unused'],suffix:['textarea','textarea',''],calculate:()=>{try{const x=parseMatrix(a),y=parseMatrix(b),product=multiplyMatrices(x,y);return[row('Matrix product A × B',product.map(r=>'['+r.map(fmt).join(', ')+']').join('; '),'Numeric matrices up to 8×8; row-by-column multiplication, not elementwise multiplication or a symbolic solver.'),row('Output dimensions',`${product.length} × ${product[0].length}`),...product.map((r,i)=>row(`Product row ${i+1}`,r.map(fmt).join(', ')))];}catch(err){return bad((err as Error).message);}}};
 if(slug==='decimal-to-fraction-calculator')return{labels:['Finite decimal written exactly','Unused','Unused'],suffix:['text','',''],calculate:()=>{try{const r=decimalFraction(a),abs=r.numerator<BigInt(0)?-r.numerator:r.numerator,wholePart=abs/r.denominator,rem=abs%r.denominator;return[row('Reduced exact fraction',`${r.numerator}/${r.denominator}`,'Exact finite-decimal conversion using integer arithmetic. Repeating decimals and scientific notation are not parsed.'),row('Mixed-number form',`${r.numerator<BigInt(0)?'-':''}${wholePart}${rem?' '+rem+'/'+r.denominator:''}`),row('Entered decimal',a.trim())];}catch(err){return bad((err as Error).message);}}};
 if(slug==='blown-insulation-calculator')return{labels:['Measured area to insulate','Label coverage per bag at selected specification','Ordering allowance','Supplied price per bag'],suffix:['ft²','ft²/bag','%','currency; 0 to omit'],calculate:()=>{if(!number(a,0)||!number(b,.000001)||!number(c,0,100)||!number(d,0))return bad('Use non-negative area/price, positive product-label coverage and allowance 0–100%.');const planned=A*(1+C/100),bags=Math.ceil(planned/B);if(!Number.isSafeInteger(bags))return bad('The whole-bag count exceeds supported safe-integer precision.');return[row('Whole insulation bags',fmt(bags)+' bags','Use coverage from the actual product label at the intended depth/R-value. No R-value, code approval or installation plan is inferred.'),row('Area including allowance',fmt(planned)+' ft²'),row('Material-only price scenario',fmt(bags*D)+' currency')];}};
 if(slug==='euler-method-calculator')return{labels:['Coefficient a in y′ = a·x + b·y + c','Coefficient b','Constant c','Initial x','Initial y','Signed step h','Number of steps'],suffix:['number','number','number','x units','y units','non-zero; |h|≤100','whole 1–1000'],calculate:()=>{if(![a,b,c,d,e].every(s=>number(s,-1e6,1e6))||!number(f,-100,100)||F===0||!whole(g,1,1000))return bad('Supply finite affine coefficients/initial values, non-zero step up to ±100 and 1–1000 whole steps.');try{const steps=eulerAffine(A,B,C,D,E,F,G),last=steps.at(-1)!;return[row('Euler final y estimate',fmt(last.y),'Affine differential equations only: y′=a·x+b·y+c. This finite-step approximation has no certified error bound.'),row('Final x',fmt(last.x)),row('Iterations',fmt(G)),...steps.slice(0,6).map((s,i)=>row(`Preview step ${i}`,`x=${fmt(s.x)}, y=${fmt(s.y)}`))];}catch(err){return bad((err as Error).message);}}};
 if(slug==='log-weight-calculator')return{labels:['Log length','Small-end diameter','Large-end diameter','Supplied bulk density'],suffix:['ft','in','in','lb/ft³'],calculate:()=>{if(!number(a,.000001)||!number(b,.000001)||!number(c,.000001)||!number(d,.000001))return bad('Supply positive length, both diameters and independently established density.');const r=B/24,R=C/24,v=Math.PI*A*(r*r+r*R+R*R)/3;return[row('Illustrative log weight',fmt(v*D)+' lb','Circular frustum with supplied density; no species, moisture, bark, load capacity or lifting recommendation is assumed.'),row('Geometric volume',fmt(v)+' ft³'),row('Mass equivalent',fmt(v*D*0.45359237)+' kg')];}};
 if(slug==='roman-numeral-converter')return{labels:['Number, Roman numeral, or ISO date','Conversion mode','Unused'],suffix:['text','select:number=Number to Roman|roman=Roman to number|date=Date YYYY-MM-DD',''],calculate:()=>{try{if(b==='number'){if(!whole(a,1,3999))throw new Error('Enter a whole number 1–3999.');return[row('Roman numeral',toRoman(A),'Standard subtractive notation, no zero, negative values or overbars.')]};if(b==='roman')return[row('Decimal number',String(fromRoman(a)),'Canonical Roman notation is checked before conversion.')];if(b!=='date'||!/^\d{4}-\d{2}-\d{2}$/.test(a)||a<'0001-01-01'||a>'3999-12-31')throw new Error('Use a real ISO date with year 0001–3999.');const date=new Date(a+'T00:00:00Z');if(!Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==a)throw new Error('Use a real Gregorian date.');const[y,m,day]=a.split('-').map(Number);return[row('Roman date: day / month / year',`${toRoman(day)} / ${toRoman(m)} / ${toRoman(y)}`,'Each date component is converted separately; this is not the ancient Roman calendar.')] }catch(err){return bad((err as Error).message);}}};
 if(slug==='prop-slip-calculator')return{labels:['Engine rotational speed','Gear reduction: engine RPM / prop RPM','Nominal propeller pitch','Measured boat speed'],suffix:['rpm','ratio','in/revolution','mph'],calculate:()=>{if(!number(a,.000001,1e6)||!number(b,.000001,100)||!number(c,.000001,200)||!number(d,0,1000))return bad('Use positive RPM, gear reduction and pitch, plus non-negative measured mph.');const theoretical=A/B*C/1056,slip=(1-D/theoretical)*100;return[row('Apparent propeller slip',fmt(slip)+' %','Negative apparent slip is preserved as a measurement/specification inconsistency; no propeller selection or safe-speed advice.'),row('Nominal no-slip speed',fmt(theoretical)+' mph'),row('Propeller speed',fmt(A/B)+' rpm')];}};
 if(slug==='rc-filter-calculator')return{labels:['Resistance','Capacitance','Frequency to evaluate','Filter output'],suffix:['Ω','nF','Hz','select:low=Low-pass|high=High-pass'],calculate:()=>{if(!number(a,.000001)||!number(b,.000001)||!number(c,0)||!['low','high'].includes(d))return bad('Use positive resistance/capacitance, non-negative frequency and an output mode.');const tau=A*B*1e-9,cutoff=1/(2*Math.PI*tau),x=2*Math.PI*C*tau,gain=d==='low'?1/Math.hypot(1,x):x/Math.hypot(1,x);return[row('Ideal RC cutoff frequency',fmt(cutoff)+' Hz','Single unloaded passive RC stage; source/load impedance, tolerances and parasitic effects are omitted.'),row('Time constant',fmt(tau*1000)+' ms'),row('Amplitude ratio at supplied frequency',fmt(gain)),row('Gain in decibels',gain===0?'−∞ dB':fmt(20*Math.log10(gain))+' dB')];}};
 if(slug==='probability-calculator')return{labels:['Probability of event A','Probability of event B','Intersection probability for supplied mode','Relationship'],suffix:['decimal 0–1','decimal 0–1','decimal 0–1','select:independent=Independent events|supplied=Supply P(A and B)'],calculate:()=>{if(!number(a,0,1)||!number(b,0,1)||!['independent','supplied'].includes(d))return bad('Use probabilities as decimals between zero and one, and select a relationship.');const intersection=d==='independent'?A*B:C,lo=Math.max(0,A+B-1),hi=Math.min(A,B);if(d==='supplied'&&(!number(c,lo,hi)))return bad('Intersection must lie between max(0,A+B−1) and min(A,B).');const union=A+B-intersection;return[row('Probability of A or B (inclusive)',fmt(union*100)+' %','Inclusive union of two events. Independence is an explicit user assumption, never inferred.'),row('Probability of A and B',fmt(intersection*100)+' %'),row('Probability of neither',fmt((1-union)*100)+' %'),row('P(A given B)',B===0?'Undefined: P(B)=0':fmt(intersection/B*100)+' %')];}};
 if(slug==='target-heart-rate-calculator')return{labels:['Adult age','Lower illustrative percentage','Upper illustrative percentage'],suffix:['whole years 18–100','% of age-predicted maximum','% of age-predicted maximum'],calculate:()=>{if(!whole(a,18,100)||!number(b,1,100)||!number(c,B,100))return bad('Use an adult age 18–100 and ordered percentages greater than zero through 100.');const max=220-A;return[row('Age-predicted maximum heart rate',fmt(max)+' bpm','220 minus age is a broad population estimate, not your measured maximum or exercise clearance. Medicines and health conditions can change interpretation.'),row('Illustrative lower reference',fmt(max*B/100)+' bpm'),row('Illustrative upper reference',fmt(max*C/100)+' bpm')];}};
 if(slug==='pension-benefit-calculator')return{labels:['Annual pensionable salary','Credited service years','Accrual denominator: 60 means 1/60 per year','Supplied benefit adjustment factor'],suffix:['currency/year','years','positive denominator','%; 100 leaves benefit unchanged'],calculate:()=>{if(!number(a,0)||!number(b,0,100)||!number(c,.000001,10000)||!number(d,0,200))return bad('Supply non-negative pensionable pay, service 0–100 years, positive accrual denominator and explicit adjustment 0–200%.');const accrued=A*B/C,annual=accrued*D/100;return[row('Illustrative annual defined benefit',fmt(annual)+' currency/year','Supplied final-salary accrual worksheet only; not a state pension, investment pot, entitlement decision or administrator quotation.'),row('Monthly equivalent',fmt(annual/12)+' currency/month'),row('Before supplied adjustment',fmt(accrued)+' currency/year')];}};
 if(slug==='grams-to-ml-converter')return{labels:['Amount to convert','Supplied material density','Input amount represents'],suffix:['g or mL by mode','g/mL','select:mass=Mass in grams|volume=Volume in milliliters'],calculate:()=>{if(!number(a,0)||!number(b,.000001)||!['mass','volume'].includes(c))return bad('Supply a non-negative amount, positive density in g/mL and an input mode.');return[row(c==='mass'?'Converted volume':'Converted mass',fmt(c==='mass'?A/B:A*B)+(c==='mass'?' mL':' g'),'Density must describe the actual material and conditions. No universal 1 g = 1 mL conversion.'),row('Supplied density',fmt(B)+' g/mL')];}};
 if(slug==='siding-course-calculator')return{labels:['Rectangular wall width','Rectangular wall height','Usable siding board length','Exposed height per course','Ordering allowance'],suffix:['ft','ft','ft','in; after overlap','%'],calculate:()=>{if(![a,b,c,d].every(s=>number(s,.000001,1e6))||!number(e,0,100))return bad('Use positive rectangular wall dimensions, board length, exposed height and allowance 0–100%.');const courses=Math.ceil(B*12/D),per=Math.ceil(A/C),base=courses*per;if(![courses,per,base,Math.ceil(base*(1+E/100))].every(Number.isSafeInteger))return bad('The whole-board count exceeds supported safe-integer precision.');return[row('Whole siding boards with allowance',fmt(Math.ceil(base*(1+E/100)))+' boards','Whole-board row layout for one rectangular wall. No opening deductions, offcut sharing, fastening, flashing or product approval.'),row('Horizontal courses',fmt(courses)),row('Whole boards per course',fmt(per)),row('Base board count',fmt(base))];}};
 if(slug==='difference-quotient-calculator')return{labels:['Quadratic coefficient a','Linear coefficient b','Constant c','Evaluation x','Non-zero increment h'],suffix:['f(x)=a·x²+b·x+c','number','number','x units','x units'],calculate:()=>{if(![a,b,c,d,e].every(s=>number(s,-1e9,1e9))||E===0)return bad('Use finite polynomial coefficients/x and a non-zero increment.');return[row('Quadratic difference quotient',fmt(2*A*D+A*E+B),'For f(x)=a·x²+b·x+c only. The simplified finite-increment expression avoids subtractive cancellation.'),row('f(x)',fmt(A*D*D+B*D+C)),row('f(x+h)',fmt(A*(D+E)**2+B*(D+E)+C)),row('Derivative limit at x',fmt(2*A*D+B))];}};
 if(slug==='odds-risk-calculator')return{labels:['Group 1: events','Group 1: non-events','Group 2: events','Group 2: non-events'],suffix:['whole count','whole count','whole count','whole count'],calculate:()=>{if(![a,b,c,d].every(s=>whole(s))||A+B===0||C+D===0)return bad('Supply non-negative whole cells and a positive total in each group.');const r1=A/(A+B),r2=C/(C+D),orDen=B*C;return[row('Observed risk ratio',r2===0?'Undefined: group 2 has no events':fmt(r1/r2),'Observed two-group counts only. No causal claim, confidence interval, significance test or clinical risk prediction. Case-control sampling does not estimate population risks.'),row('Cross-product odds ratio',orDen===0?'Undefined: zero cross-product denominator':fmt(A*D/orDen)),row('Group 1 observed proportion',fmt(r1*100)+' %'),row('Group 2 observed proportion',fmt(r2*100)+' %'),row('Observed risk difference',fmt((r1-r2)*100)+' percentage points')];}};
 if(slug==='time-lapse-calculator')return{labels:['Recording window','Interval between captures','Playback frame rate'],suffix:['minutes','seconds','fps'],calculate:()=>{if(!number(a,0,1e6)||!number(b,.001,1e9)||!number(c,.001,1000))return bad('Use a non-negative recording window, positive capture interval and positive playback frame rate.');const frames=Math.floor(A*60/B)+1;if(frames>1e9)return bad('Limit the sequence to one billion frames.');return[row('Planned capture count',fmt(frames)+' frames','Includes the first capture at t=0 and a capture at the endpoint only when the interval lands there. Camera start/end conventions can differ.'),row('Playback duration',fmt(frames/C)+' s'),row('Last planned capture time',fmt((frames-1)*B)+' s'),row('Interval speed-up factor',fmt(B*C)+' ×')];}};
 if(slug==='mileage-reimbursement-calculator')return{labels:['Starting odometer','Ending odometer','Supplied reimbursement rate','Distance unit'],suffix:['distance','distance','currency per selected unit','select:miles=Miles|km=Kilometers'],calculate:()=>{if(!number(a,0)||!number(b,A)||!number(c,0)||!['miles','km'].includes(d))return bad('Use non-negative odometers, end at least start, non-negative supplied rate and a distance unit.');const distance=B-A;return[row('Recorded trip distance',fmt(distance)+' '+d,'Odometer difference, not map routing, fuel economy or automatic tax eligibility. No 2025/2026 rate is loaded.'),row('Supplied-rate reimbursement',fmt(distance*C)+' currency'),row('Other distance unit',fmt(d==='miles'?distance*1.609344:distance/1.609344)+(d==='miles'?' km':' miles'))];}};
 if(slug==='draw-length-calculator')return{labels:['Measured nock-to-grip-pivot distance at full draw','Measurement unit','Unused'],suffix:['distance','select:in=Inches|cm=Centimeters',''],calculate:()=>{if(!number(a,.000001,200)||!['in','cm'].includes(b))return bad('Supply a positive measured distance and its unit.');const inches=b==='cm'?A/2.54:A;return[row('ATA-convention draw length',fmt(inches+1.75)+' in','Measured pivot-point distance plus 1¾ inches; not wingspan fitting, arrow-length selection, a bow setting or safety approval.'),row('Centimeter equivalent',fmt((inches+1.75)*2.54)+' cm'),row('Measured pivot distance',fmt(inches)+' in')];}};
 if(slug==='cardiac-output-calculator')return{labels:['Supplied heart rate','Independently measured stroke volume','Supplied body surface area: 0 to omit index'],suffix:['beats/min','mL/beat','m²; optional'],calculate:()=>{if(!number(a,.000001,1000)||!number(b,.000001,1000)||!number(c,0,10))return bad('Supply positive heart rate/stroke volume and a non-negative independent BSA (zero omits index).');const co=A*B/1000;return[row('Calculated cardiac output',fmt(co)+' L/min','Educational HR×SV identity only. Stroke volume is not inferred from pulse; no diagnosis, normal-range classification, treatment or emergency triage.'),row('Flow in milliliters',fmt(A*B)+' mL/min'),row('Cardiac index',C===0?'BSA omitted':fmt(co/C)+' L/min/m²')];}};
 if(slug==='option-profit-calculator')return{labels:['Option type: purchased position only','Underlying price at expiry','Strike price','Premium per underlying unit','Whole contracts','Underlying units per contract','Total supplied transaction fees'],suffix:['select:call=Long call|put=Long put','currency/unit','currency/unit','currency/unit','whole count','whole positive size','currency'],calculate:()=>{if(!['call','put'].includes(a)||![b,c,d,g].every(s=>number(s,0))||!whole(e,1,1e6)||!whole(f,1,1e6))return bad('Select a long call/put, non-negative prices/fees, and positive whole contracts/contract size.');const units=E*F,intrinsic=Math.max(0,a==='call'?B-C:C-B),cost=D*units+G,profit=intrinsic*units-cost,be=a==='call'?C+cost/units:C-cost/units;return[row('Expiry profit or loss',fmt(profit)+' currency','Purchased vanilla option at expiry only. No live valuation, volatility model, short-option margin, assignment forecast or investment recommendation.'),row('Intrinsic payoff',fmt(intrinsic*units)+' currency'),row('Premium plus supplied fees',fmt(cost)+' currency'),row('Expiry break-even underlying price',be<0?'No non-negative break-even price':fmt(be)+' currency/unit'),row('Return on supplied cost',cost===0?'Undefined: zero cost':fmt(profit/cost*100)+' %')];}};
 return null;
};
