import {resolveGlobal} from './global';
import type {CalculatorResolver,CalculatorResult} from './types';
const f=(n:number,d=4)=>n.toLocaleString('en-US',{maximumFractionDigits:d});
const row=(label:string,value:string,note?:string):CalculatorResult=>({label,value,note});
const fail=(note:string)=>[row('Check your inputs','Unable to calculate',note)];
const num=(s:string,min=0,max=1e12)=>s.trim()!==''&&Number.isFinite(Number(s))&&Number(s)>=min&&Number(s)<=max;
const date=(s:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return null;const dt=new Date(s+'T12:00:00Z');return Number.isFinite(dt.getTime())&&dt.toISOString().slice(0,10)===s&&Number(s.slice(0,4))>=1900&&Number(s.slice(0,4))<=2200?dt:null};
const after=(dt:Date,days:number)=>{const copy=new Date(dt);copy.setUTCDate(copy.getUTCDate()+days);return copy.toISOString().slice(0,10)};
const es=(t:number)=>.6108*Math.exp(17.27*t/(t+237.3));
export function simplifyRadicals(input:string):string {
 if(input.length>2000)throw Error("Expression input is limited to 2,000 characters including spaces.");
 const text=input.replace(/\s/g,'').replace(/√\((\d+)\)/g,'sqrt($1)').replace(/√(\d+)/g,'sqrt($1)');
 if(!text||text.length>1000)throw Error('Use up to 20 signed terms such as 2sqrt(72)-sqrt(8)+3, without variables, fractions or nested roots.');
 const terms=text.match(/[+-]?(?:(?:\d+\*?)?sqrt\(\d+\)|\d+)/g);
 if(!terms||terms.join('')!==text||terms.length>20||terms.slice(1).some(t=>!/^[-+]/.test(t)))throw Error('Only integer coefficients, non-negative integer square roots and addition/subtraction are supported.');
 const sums=new Map<number,number>();
 for(const term of terms){const root=term.match(/^([+-]?)(\d*)\*?sqrt\((\d+)\)$/);let coefficient:number,radicand=1;
  if(root){coefficient=(root[1]==='-'?-1:1)*Number(root[2]||1);let n=Number(root[3]),outside=1;if(n>1e9||Math.abs(coefficient)>1e6)throw Error('Radicands must be at most 1,000,000,000 and coefficients at most 1,000,000.');if(n===0)continue;
   for(let p=2;p*p<=n;p++){let count=0;while(n%p===0){n/=p;count++}outside*=p**Math.floor(count/2);if(count%2)radicand*=p}if(n>1)radicand*=n;coefficient*=outside;
  }else{coefficient=Number(term);if(Math.abs(coefficient)>1e6)throw Error('Integer constants must be within ±1,000,000.');}
  sums.set(radicand,(sums.get(radicand)||0)+coefficient);
 }
 let output='';for(const [n,k] of [...sums].sort((a,b)=>a[0]-b[0])){if(k===0)continue;const abs=Math.abs(k),body=n===1?String(abs):(abs===1?'':String(abs))+'√'+n;output+=(output?(k<0?' − ':' + '):k<0?'−':'')+body}return output||'0';
}
export const resolveRoadmap166:CalculatorResolver=({slug,a,b,c,d,e,cash})=>{
 const A=Number(a),B=Number(b),C=Number(c),D=Number(d),E=Number(e);
 if(slug==='vpd-calculator')return{labels:['Air temperature',d==='rh'?'Dew point temperature':'Measured relative humidity',d==='leaf'?'Measured leaf temperature':'Unused','Calculation mode','Unused'],suffix:['°C',d==='rh'?'°C':'%','°C','select:air=Air VPD|leaf=Leaf VPD|rh=RH from dew point',''],calculate:()=>{
  if(!['air','leaf','rh'].includes(d)||!num(a,0,50)||!num(b,0,d==='rh'?50:100)||d==='leaf'&&!num(c,0,50)||d==='rh'&&B>A)return fail('Use 0–50 °C temperatures and 0–100% RH. Dew point cannot exceed air temperature. This approximation is for liquid-water conditions.');
  const actual=d==='rh'?es(B):es(A)*B/100,rh=actual/es(A)*100,deficit=es(d==='leaf'?C:A)-actual;
  return[row(d==='rh'?'Calculated relative humidity':d==='leaf'?'Leaf vapor pressure deficit':'Air vapor pressure deficit',f(d==='rh'?rh:deficit)+(d==='rh'?'%':' kPa'),'FAO saturation-vapor-pressure approximation; no crop-specific target or climate-control instruction. Negative leaf VPD indicates the supplied leaf temperature is below the implied dew point.'),row('Air VPD',f(es(A)-actual)+' kPa'),row('Actual vapor pressure',f(actual)+' kPa'),row('Air saturation vapor pressure',f(es(A))+' kPa')];
 }};
 if(slug==='goat-gestation-calculator'||slug==='dog-pregnancy-calculator')return{labels:[slug==='goat-gestation-calculator'?'Recorded breeding date':'Recorded reproductive date',slug==='dog-pregnancy-calculator'?'Date basis':'Unused','Unused'],suffix:['date',slug==='dog-pregnancy-calculator'?'select:breeding=Breeding date (broader window)|ovulation=Veterinarian-established ovulation date':'',''],calculate:()=>{
  const start=date(a),goat=slug==='goat-gestation-calculator';if(!start||!goat&&!['breeding','ovulation'].includes(b))return fail('Use a valid Gregorian date from 1900–2200 and the correct observed date basis.');const center=goat?150:b==='ovulation'?63:65,lo=goat?145:b==='ovulation'?62:58,hi=goat?155:b==='ovulation'?64:72;
  return[row(goat?'Approximate kidding date':'Approximate whelping date',after(start,center),'Planning estimate only; breeding dates do not establish conception. A veterinarian evaluates pregnancy, fetal development and any concerns.'),row('Planning date window',after(start,lo)+' to '+after(start,hi)),row('Days used',`${center} central; ${lo}–${hi} window`)];
 }};
 if(slug==='gas-oil-mix-calculator')return{labels:['Gasoline volume before adding oil','Manufacturer gasoline:oil ratio','Gasoline volume unit'],suffix:['selected unit','parts gasoline to 1 oil','select:litre=Litres|us=US gallons|imperial=Imperial gallons'],calculate:()=>{
  if(!num(a,1e-9,10000)||!num(b,1,1000)||!['litre','us','imperial'].includes(c))return fail('Use positive gasoline volume, a verified ratio from 1:1 to 1000:1, and the correct gallon definition.');const litres=A*(c==='us'?3.785411784:c==='imperial'?4.54609:1),ml=litres/B*1000;
  return[row('Oil volume to add',f(ml)+' mL','Oil = measured gasoline volume ÷ manufacturer gasoline:oil ratio. A default 50:1 ratio is not approval for every engine or oil.'),row('Oil in US fluid ounces',f(ml/29.5735295625)+' US fl oz'),row('Oil in litres',f(ml/1000,6)+' L'),row('Gasoline equivalent',f(litres,6)+' L')];
 }};
 if(slug==='macro-calculator')return{labels:['Existing daily calorie baseline',e==='maintain'?'Unused':'User-chosen calorie adjustment','Protein share of energy','Fat share of energy','Scenario'],suffix:['kcal/day','%','%','%','select:maintain=Baseline allocation|bulk=User-chosen surplus|cut=User-chosen deficit'],calculate:()=>{
  if(!num(a,500,6000)||e!=='maintain'&&!num(b,0,50)||!num(c,0,100)||!num(d,0,100)||C+D>100||!['maintain','bulk','cut'].includes(e))return fail('Use a supplied baseline from 500–6000 kcal, adjustment 0–50%, and protein plus fat shares at most 100%. Bounds are not recommended diets.');const calories=A*(1+(e==='bulk'?B:e==='cut'?-B:0)/100),carb=100-C-D;
  return[row('Scenario daily energy',f(calories,1)+' kcal/day','Arithmetic allocation of your supplied baseline and adjustment; does not estimate your energy needs or prescribe a deficit, surplus or sex-specific diet.'),row('Protein',f(calories*C/400,1)+' g/day'),row('Fat',f(calories*D/900,1)+' g/day'),row('Carbohydrate',f(calories*carb/400,1)+' g/day')];
 }};
 if(slug==='macroeconomics-calculator')return{labels:['Personal consumption expenditure','Gross private domestic investment','Government consumption and gross investment','Exports','Imports'],suffix:['same currency and scale','same currency and scale','same currency and scale','same currency and scale','same currency and scale'],calculate:()=>{
  if(!num(a)||!num(b,-1e12,1e12)||!num(c)||!num(d)||!num(e))return fail('Use finite same-period amounts on one currency and scale; inventory-driven investment may be negative.');return[row('Expenditure GDP identity',cash(A+B+C+D-E),'C + I + G + X − M. Enter internally consistent national-account components; no live data, inflation adjustment or economic forecast.'),row('Net exports',cash(D-E)),row('Domestic expenditure subtotal',cash(A+B+C))];
 }};
 if(slug==='vinegar-carbon-dosing-calculator')return{labels:['Verified protocol vinegar quantity per stated interval','Protocol net water volume','Your measured net water volume','Protocol labeled acidity','Your labeled acidity'],suffix:['mL','L','L','g acetic acid per 100 mL','g acetic acid per 100 mL'],calculate:()=>{
  if(!num(a,0,10000)||!num(b,1e-6,1e6)||!num(c,1e-6,1e6)||!num(d,1,10)||!num(e,1,10))return fail('Supply an independently verified protocol quantity and interval, positive measured water volumes and compatible 1–10 g/100 mL labeled vinegar acidity.');return[row('Protocol-scaled vinegar quantity',f(A*C/B*D/E)+' mL per same interval','Mathematical volume/concentration equivalence only. This is not a safe-dose recommendation or an mL-per-ppm nitrate conversion. Do not apply this number without qualified aquarium protocol review.'),row('Water-volume multiplier',f(C/B)),row('Acidity multiplier',f(D/E)),row('Nitrate removal prediction','Not determined from these inputs')];
 }};
 if(slug==='radical-expression-simplifier')return{labels:['Integer square-root expression','Unused','Unused'],suffix:['text','',''],calculate:()=>{try{return[row('Simplified exact expression',simplifyRadicals(a),'Extracts square factors and combines like radicals. Supports at most 20 integer square-root terms and constants; no variables, fractions, nested roots or complex values.')] }catch(error){return fail(error instanceof Error?error.message:'Invalid expression.')}}};
 if(slug==='wedding-liquor-calculator')return{labels:['Adults included in your supplied plan','Planned total servings per included adult','Share of servings that use liquor','Liquor volume per spirit serving','Bottle volume'],suffix:['whole adults','servings/person','%','mL','mL'],calculate:()=>{
  if(!num(a,0,100000)||!Number.isInteger(A)||!num(b,0,100)||!num(c,0,100)||!num(d,1,1000)||!num(e,1,10000))return fail('Use a whole adult count, non-negative planned servings, a liquor share from 0–100% and positive mL serving/bottle volumes.');const total=A*B,spirit=total*C/100,volume=spirit*D;
  return[row('Whole spirit bottles for supplied plan',f(Math.ceil(volume/E),0)+' bottles','Purchasing arithmetic only, not a recommendation to consume the planned quantity. A poured serving is not automatically a standard drink.'),row('Spirit servings in plan',f(spirit,2)),row('Required liquor volume',f(volume/1000,3)+' L'),row('Remaining non-spirit servings',f(total-spirit,2))];
 }};
 if(slug==='abg-calculator')return{labels:['Measured arterial pH','Arterial carbon dioxide partial pressure','Bicarbonate for stated sample basis','Serum sodium','Serum chloride'],suffix:['pH','mmHg','mmol/L','mmol/L','mmol/L'],calculate:()=>{
  if(!num(a,6.5,8)||!num(b,5,200)||!num(c,1,80)||!num(d,80,200)||!num(e,40,160))return fail('Use the labeled laboratory units and accepted arithmetic bounds. Bounds do not establish clinically normal values. Do not substitute oxygen pressure for PaCO₂.');const predicted=6.1+Math.log10(C/(.03*B));return[row('Uncorrected anion gap (without potassium)',f(D-E-C,2)+' mmol/L','Educational arithmetic, not diagnosis or treatment. Electrolytes must be on the appropriate same-time chemistry-panel basis; albumin and laboratory reference intervals are not supplied.'),row('Henderson–Hasselbalch pH estimate',f(predicted,3)),row('Measured minus estimated pH',f(A-predicted,3)),row('Clinical interpretation','Requires qualified clinical assessment')];
 }};
 if(slug==='mean-standard-deviation-calculator')return{labels:['Observed values, comma separated','Variance basis','Unused'],suffix:['text','select:population=Population (divide by n)|sample=Sample (divide by n−1)','',''],calculate:()=>{
  const tokens=a.split(',').map(s=>s.trim());if(!tokens.length||tokens.length>10000||tokens.some(s=>!num(s,-1e12,1e12))||!['population','sample'].includes(b)||b==='sample'&&tokens.length<2)return fail('Use 1–10,000 finite comma-separated observations within ±10¹²; sample mode requires at least two. A mean alone cannot determine spread.');let mean=0,m2=0,count=0;for(const token of tokens){const x=Number(token),delta=x-mean;count++;mean+=delta/count;m2+=delta*(x-mean)}const sd=Math.sqrt(Math.max(0,m2)/(count-(b==='sample'?1:0))),sample=count>1?Math.sqrt(Math.max(0,m2)/(count-1)):null;
  return[row(b==='sample'?'Sample standard deviation':'Population standard deviation',f(sd,6),'Stable Welford accumulation. SD measures observation spread; standard error of the mean has a different interpretation and assumes independent observations.'),row('Arithmetic mean',f(mean,6)),row('Standard error of sample mean',sample===null?'Requires at least two observations':f(sample/Math.sqrt(count),6)),row('Observation count',String(count))];
 }};
 if(slug==='soil-calculator')return{labels:['Bed length','Bed width','Finished loam depth','Explicit volume allowance','Supplier bulk density'],suffix:['ft','ft','in','%','lb/ft³ (0 to omit weight)'],calculate:()=>{
  if(!num(a,1e-9)||!num(b,1e-9)||!num(c,1e-9)||!num(d,0,100)||!num(e,0,1000))return fail('Use positive bed dimensions, 0–100% allowance and a supplied bulk density, or zero to omit weight.');const cubic=A*B*C/12,planned=cubic*(1+D/100);return[row('Planned loam volume',f(planned/27)+' yd³','Rectangular bed volume with your explicit allowance; no hidden loam density or settlement factor.'),row('Geometric volume',f(cubic)+' ft³'),row('Planned cubic metres',f(planned*.028316846592)+' m³'),row('Weight at supplied bulk density',E===0?'No density supplied':f(planned*E)+' lb')];
 }};
 if(slug==='profit-margin-calculator-global')return{labels:['Unit cost',c==='markup'?'Markup on cost':'Selling price','Known pricing basis'],suffix:['currency',c==='markup'?'%':'currency','select:price=Known selling price|markup=Known markup percentage'],calculate:()=>{
  if(!num(a,1e-9)||!num(b,0,1e9)||!['price','markup'].includes(c))return fail('Use positive unit cost, non-negative price or markup, and the correct pricing basis.');const price=c==='markup'?A*(1+B/100):B,profit=price-A;return[row('Selling price',cash(price),'Markup divides profit by cost; margin divides profit by selling price. Taxes and omitted overhead are not included.'),row('Unit gross profit',cash(profit)),row('Markup on cost',f(profit/A*100,2)+'%'),row('Gross profit margin',price===0?'Undefined at zero selling price':f(profit/price*100,2)+'%')];
 }};
 if(slug==='car-lease-vs-buy-calculator')return{labels:['Lease upfront costs (exclude first monthly payment)','Monthly lease payment for 36 payments','Buy upfront cash costs (exclude recurring payments)','Buy monthly payment; remaining loan balance; resale value','Other lease costs; other buy costs (36-month totals)'],suffix:['currency','currency/month','currency','text','text'],calculate:()=>{
  const buy=d.split(';').map(s=>s.trim()),other=e.split(';').map(s=>s.trim());if(!num(a)||!num(b)||!num(c)||buy.length!==3||other.length!==2||[...buy,...other].some(s=>!num(s)))return fail('Use non-negative amounts. Supply buy monthly payment; remaining principal at month 36; resale value, then extra lease costs; extra buy costs.');const lease=A+36*B+Number(other[0]),purchase=C+36*Number(buy[0])+Number(buy[1])-Number(buy[2])+Number(other[1]),difference=lease-purchase;return[row(difference===0?'Equal modeled net cost':difference>0?'Buying has lower modeled net cost':'Leasing has lower modeled net cost',cash(Math.abs(difference)),'Fixed 36-month nominal cash comparison. Purchase cost includes remaining loan principal less resale; no automatic rates or contract fees.'),row('Lease net cost at 36 months',cash(lease)),row('Buy net cost at 36 months',cash(purchase)),row('Net purchase equity at month 36',cash(Number(buy[2])-Number(buy[1])))];
 }};
 if(slug==='aspect-ratio-calculator'){
  const base=resolveGlobal({slug,a,b,c,d,e,cash});if(!base)return null;
  return{...base,calculate:()=>{
   if(!num(a,1e-9)||!num(b,1e-9)||!num(c,1e-9)||!['height-from-width','width-from-height'].includes(d))return fail('Use finite positive dimensions and a valid dimension-solving mode.');
   const out=base.calculate();if(!Number.isInteger(A)||!Number.isInteger(B))out[1]=row('Original dimension ratio',f(A,6)+':'+f(B,6),'Decimal dimensions retain their supplied ratio; no rounded integer reduction is implied.');return out;
  }};
 }
 return null;
};
