import type {CalculatorResolver,CalculatorResult} from './types';
const row=(label:string,value:string,note?:string):CalculatorResult=>({label,value,note});
const bad=(note:string)=>[row('Check inputs',note)];
const fmt=(value:number)=>value.toLocaleString('en-US',{maximumFractionDigits:8});
const valid=(s:string,min=0,max=1e9)=>s.trim()!==''&&Number.isFinite(Number(s))&&Number(s)>=min&&Number(s)<=max;
const whole=(s:string,min=0,max=1e9)=>valid(s,min,max)&&Number.isInteger(Number(s));
export function pairedCorrelation(xs:string,ys:string){
 const parse=(s:string)=>{if(s.length>20000)throw Error('Limit each list to 20,000 characters.');const parts=s.trim().split(/[\s,;]+/);if(parts.some(t=>!valid(t,-1e12,1e12)))throw Error('Use finite numbers separated by spaces, commas or semicolons.');return parts.map(Number);};
 const x=parse(xs),y=parse(ys);if(x.length!==y.length||x.length<2||x.length>1000)throw Error('Supply 2–1,000 matched pairs in the same order.');
 let mx=0,my=0,sx=0,sy=0,sxy=0;x.forEach((v,i)=>{const dx=v-mx,dy=y[i]-my;mx+=dx/(i+1);my+=dy/(i+1);sx+=dx*(v-mx);sy+=dy*(y[i]-my);sxy+=dx*(y[i]-my);});if(sx<=0||sy<=0)throw Error('Both lists need non-zero variation.');return{r:Math.max(-1,Math.min(1,sxy/Math.sqrt(sx*sy))),count:x.length,mx,my};
}
export function binomialProbabilities(n:number,p:number,k:number){
 const probabilities=Array.from({length:n+1},(_,i)=>{if(p===0)return Number(i===0);if(p===1)return Number(i===n);let log=0;const smaller=Math.min(i,n-i);for(let j=1;j<=smaller;j++)log+=Math.log(n-smaller+j)-Math.log(j);return Math.exp(log+i*Math.log(p)+(n-i)*Math.log1p(-p));});
 return{exact:probabilities[k],below:Math.min(1,probabilities.slice(0,k+1).reduce((s,v)=>s+v,0)),above:Math.min(1,probabilities.slice(k).reduce((s,v)=>s+v,0))};
}
const timecodeFrames=(s:string,fps:number)=>{const m=s.match(/^(\d{2}):(\d{2}):(\d{2}):(\d{2})$/);if(!m)throw Error('Use HH:MM:SS:FF with colons and two digits per field.');const [hh,mm,ss,ff]=m.slice(1).map(Number);if(hh>23||mm>59||ss>59||ff>=fps)throw Error('Use hours 00–23, minutes/seconds 00–59 and a frame number below fps.');return((hh*60+mm)*60+ss)*fps+ff;};
const framesTimecode=(frames:number,fps:number)=>{const hh=Math.floor(frames/(3600*fps)),mm=Math.floor(frames/(60*fps))%60,ss=Math.floor(frames/fps)%60,ff=frames%fps;return[hh,mm,ss,ff].map(v=>String(v).padStart(2,'0')).join(':');};
export const resolveRoadmap268:CalculatorResolver=({slug,a,b,c,d,e,f='0',g='0',h='0'})=>{
 const A=Number(a),B=Number(b),C=Number(c),D=Number(d),E=Number(e),F=Number(f),G=Number(g),H=Number(h);
 if(slug==='drywall-calculator')return{labels:['Total wall and ceiling area','Measured openings to deduct','Panel width','Panel length','Explicit ordering allowance'],suffix:['ft²','ft²','ft','ft','%'],calculate:()=>{if(!valid(a)||!valid(b)||B>A||!valid(c,.001,100)||!valid(d,.001,100)||!valid(e,0,100))return bad('Supply non-negative areas, openings no larger than gross area, positive panel dimensions and 0–100% allowance.');const net=A-B,planned=net*(1+E/100),coverage=C*D;return[row('Estimated whole drywall panels',fmt(Math.ceil(planned/coverage))+' sheets','Area-based purchasing estimate; no cutting layout, framing, fire rating, fastener or compound specification.'),row('Net surface area',fmt(net)+' ft²'),row('Planned area including allowance',fmt(planned)+' ft²'),row('Coverage per sheet',fmt(coverage)+' ft²')];}};
 if(slug==='zero-to-sixty-calculator')return{labels:['Constant acceleration scenario','Target speed','Speed unit'],suffix:['m/s²','speed','select:mph=mph|kmh=km/h'],calculate:()=>{if(!valid(a,.000001,100)||!valid(b,.000001,1000)||!['mph','kmh'].includes(c))return bad('Use positive acceleration and target speed with a supported speed unit.');const v=B*(c==='mph'?.44704:1/3.6),t=v/A;return[row('Constant-acceleration elapsed time',fmt(t)+' s','Model from rest: not a measured 0–60 result, rollout correction, horsepower forecast or vehicle simulation.'),row('Target speed in SI units',fmt(v)+' m/s'),row('Distance under constant acceleration',fmt(v*v/(2*A))+' m'),row('Acceleration relative to standard gravity',fmt(A/9.80665)+' g')];}};
 if(slug==='watt-hour-calculator')return{labels:['Measured or supplied power','Operating duration','Unused'],suffix:['W','hours',''],calculate:()=>{if(!valid(a)||!valid(b,0,1e6))return bad('Use non-negative power in watts and time in hours.');const wh=A*B;return[row('Electrical energy',fmt(wh)+' Wh','Constant or independently established average power × duration; no battery usable capacity or automatic losses.'),row('Kilowatt-hours',fmt(wh/1000)+' kWh'),row('Joules',fmt(wh*3600)+' J')];}};
 if(slug==='kd-calculator')return{labels:['Recorded kills','Recorded deaths','Target K/D ratio'],suffix:['whole kills','whole deaths','ratio'],calculate:()=>{if(!whole(a)||!whole(b)||!valid(c,0,1e6))return bad('Use non-negative whole kills/deaths and a non-negative target ratio.');return[row('Kill/death ratio',B===0?'Undefined — zero deaths':fmt(A/B),'Kills divided by deaths; no invented zero-death denominator or game-specific elimination/assist rules.'),row('Additional kills to reach target with no more deaths',B===0?'Undefined until deaths are positive':fmt(Math.max(0,Math.ceil(C*B-A)))+' kills'),row('Recorded count basis',fmt(A)+' kills / '+fmt(B)+' deaths')];}};
 if(slug==='deck-board-calculator')return{labels:['Deck width across board rows','Deck length along boards','Actual board face width','Supplied installation gap','Stock board length','Explicit ordering allowance'],suffix:['ft','ft','in','in','ft','%'],calculate:()=>{if(!valid(a,.001,1e5)||!valid(b,.001,1e5)||!valid(c,.001,100)||!valid(d,0,10)||!valid(e,.001,1e5)||!valid(f,0,100))return bad('Use positive deck/board dimensions, a non-negative supplied gap and 0–100% allowance.');const rows=Math.ceil((A*12+D)/(C+D)),pieces=Math.ceil(B/E),base=rows*pieces;return[row('Estimated stock boards',fmt(Math.ceil(base*(1+F/100)))+' boards','Straight parallel rows, row-specific stock pieces; no shared offcut optimization, joist/support design or manufacturer gap recommendation.'),row('Board rows',fmt(rows)),row('Stock pieces per row',fmt(pieces)),row('Laid board length before allowance',fmt(rows*B)+' linear ft')];}};
 if(slug==='plate-rolling-calculator')return{labels:['Inside finished radius','Plate thickness','Neutral-axis factor supplied by fabricator','Arc angle','Separate process allowance'],suffix:['mm','mm','factor 0–1','degrees','mm'],calculate:()=>{if(!valid(a,.001,1e7)||!valid(b,.001,1e5)||!valid(c,0,1)||!valid(d,.001,360)||!valid(e,-1e7,1e7))return bad('Use positive inside radius/thickness, supplied factor 0–1, angle above zero through 360° and a signed separate allowance.');const neutral=A+C*B,arc=neutral*D*Math.PI/180;if(arc+E<=0)return bad('Developed length plus process allowance must remain positive.');return[row('Illustrative developed plate length',fmt(arc+E)+' mm','Neutral-axis arc worksheet only; factor and process allowance must be independently established. No springback, roll load or machine-setting prediction.'),row('Neutral-axis arc length before allowance',fmt(arc)+' mm'),row('Supplied neutral-axis radius',fmt(neutral)+' mm')];}};
 if(slug==='running-record-calculator')return{labels:['Words in assessed passage','Uncorrected scored errors','Self-corrections counted separately','Elapsed reading time'],suffix:['whole words','whole errors','whole corrections','seconds; 0 to omit rate'],calculate:()=>{if(!whole(a,1,1e6)||!whole(b,0,A)||!whole(c,0,A-B)||!valid(d,0,1e6))return bad('Supply positive whole words, separate whole errors/corrections whose sum does not exceed words, and non-negative elapsed seconds.');return[row('Word-reading accuracy',fmt((A-B)/A*100)+' %','Supplied running-record tallies; no comprehension score, diagnosis, grade assignment or automatic reading-level label.'),row('Error ratio',B===0?'No errors; ratio undefined':'1:'+fmt(A/B)),row('Self-correction ratio',C===0?'No self-corrections; ratio undefined':'1:'+fmt((B+C)/C)),row('Correct words per minute',D===0?'Time omitted':fmt((A-B)*60/D)+' WCPM')];}};
 if(slug==='timecode-calculator')return{labels:['First timecode HH:MM:SS:FF','Second timecode HH:MM:SS:FF','Integer frame rate','Operation'],suffix:['text','text','select:24=24 fps NDF|25=25 fps NDF|30=30 fps NDF|50=50 fps NDF|60=60 fps NDF','select:add=Add durations|subtract=First minus second'],calculate:()=>{if(![24,25,30,50,60].includes(C)||!['add','subtract'].includes(d))return bad('Select a supported integer frame rate and operation. Fractional/drop-frame rates are not supported.');try{const x=timecodeFrames(a,C),y=timecodeFrames(b,C),count=d==='add'?x+y:x-y;return[row('Timecode result',(count<0?'-':'')+framesTimecode(Math.abs(count),C),'Integer-rate non-drop-frame duration arithmetic; subtraction is signed, addition does not wrap at 24 hours. No fractional-rate or DF conversion.'),row('Signed frame count',fmt(count)+' frames'),row('Signed duration',fmt(count/C)+' s')];}catch(err){return bad((err as Error).message);}}};
 if(slug==='cow-gestation-calculator')return{labels:['Known service or insemination date','Planning gestation length','Unused'],suffix:['date','whole days',''],calculate:()=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(a)||a<'1900-01-01'||a>'2099-12-31'||!whole(b,250,310))return bad('Use a real date from 1900–2099 and an independently selected planning interval of 250–310 whole days.');const base=new Date(a+'T00:00:00Z');if(!Number.isFinite(base.getTime())||base.toISOString().slice(0,10)!==a)return bad('Enter a real Gregorian date.');const due=new Date(base);due.setUTCDate(due.getUTCDate()+B);return[row('Planning calving date',due.toISOString().slice(0,10),'Default 283-day convention is adjustable; no guaranteed due date, pregnancy diagnosis or intervention timing.'),row('Supplied planning interval',fmt(B)+' days'),row('Service-date basis',a)];}};
 if(slug==='rim-offset-calculator')return{labels:['Current wheel width','Current offset','Proposed wheel width','Proposed offset'],suffix:['in','mm','in','mm'],calculate:()=>{if(!valid(a,.001,50)||!valid(c,.001,50)||!valid(b,-200,200)||!valid(d,-200,200))return bad('Use positive wheel widths in inches and signed offsets −200 to 200 mm.');const half=(C-A)*25.4/2,inner=half+D-B,outer=half-D+B;return[row('Outer wheel-lip movement',fmt(outer)+' mm','Positive moves outward; negative retracts. Nominal-width comparison only, not tyre fitment or clearance certification.'),row('Inner wheel-edge movement toward suspension',fmt(inner)+' mm'),row('Width difference',fmt((C-A)*25.4)+' mm')];}};
 if(slug==='correlation-coefficient-calculator')return{labels:['X observations in pair order','Y observations in matching order','Unused'],suffix:['textarea','textarea',''],calculate:()=>{try{const r=pairedCorrelation(a,b);return[row('Pearson correlation coefficient',fmt(r.r),'Linear association of supplied paired numbers; no causal conclusion, p-value or predictive guarantee.'),row('Paired observations',fmt(r.count)),row('Squared correlation r²',fmt(r.r*r.r)),row('X and Y arithmetic means',fmt(r.mx)+'; '+fmt(r.my))];}catch(err){return bad((err as Error).message);}}};
 if(slug==='speed-distance-time-calculator')return{labels:['Calculation mode','Distance','Elapsed time','Speed'],suffix:['select:speed=Find speed|distance=Find distance|time=Find time','km','hours','km/h'],calculate:()=>{if(!['speed','distance','time'].includes(a))return bad('Select speed, distance or time.');let distance=B,time=C,speed=D;if(a==='speed'){if(!valid(b)||!valid(c,.000001,1e6))return bad('For speed use non-negative km and positive elapsed hours.');speed=B/C;}else if(a==='distance'){if(!valid(c)||!valid(d))return bad('For distance use non-negative hours and km/h.');distance=C*D;}else{if(!valid(b)||!valid(d,.000001))return bad('For time use non-negative km and positive km/h.');time=B/D;}const main=a==='speed'?row('Average speed',fmt(speed)+' km/h'):a==='distance'?row('Modeled distance',fmt(distance)+' km'):row('Modeled elapsed time',fmt(time)+' h');return[main,row('Speed in miles per hour',fmt(speed/1.609344)+' mph'),row('Speed in metres per second',fmt(speed/3.6)+' m/s'),row('Speed in feet per second',fmt(speed/1.09728)+' ft/s'),row('Elapsed minutes',fmt(time*60)+' min','Supplied average-speed arithmetic; no route, traffic, stop or arrival-time prediction.')];}};
 if(slug==='tv-mounting-height-calculator')return{labels:['Measured seated eye height','Measured screen height','Supplied vertical center offset from eye level','Screen-center to wall-bracket reference offset'],suffix:['cm from finished floor','cm','cm; positive upward','cm; positive bracket above center'],calculate:()=>{if(!valid(a,.001,1000)||!valid(b,.001,1000)||!valid(c,-1000,1000)||!valid(d,-1000,1000))return bad('Use positive measured eye/screen heights and signed offsets in centimetres.');const center=A+C,bottom=center-B/2;if(bottom<0||center+D<0)return bad('The supplied geometry places the screen or bracket reference below the floor.');return[row('Planned screen-center height',fmt(center)+' cm','Measured geometry only; no universal comfort angle, fixing pattern, structural capacity or wall-anchor recommendation.'),row('Screen bottom edge',fmt(bottom)+' cm'),row('Screen top edge',fmt(center+B/2)+' cm'),row('Supplied wall-bracket reference height',fmt(center+D)+' cm')];}};
 if(slug==='wire-length-calculator')return{labels:['Measured one-way route','Number of identical routes','Conductors along each route','Extra termination/slack per conductor per route','Explicit ordering allowance'],suffix:['m','whole routes','whole conductors','m','%'],calculate:()=>{if(!valid(a)||!whole(b,1,10000)||!whole(c,1,1000)||!valid(d)||!valid(e,0,100))return bad('Use non-negative route/slack, positive whole route/conductor counts and 0–100% allowance.');const route=A+D,cut=route*B,total=cut*C;return[row('Planned individual-conductor length',fmt(total*(1+E/100))+' m','Length takeoff only; not wire gauge, voltage-drop, circuit protection or electrical code approval. Cable-jacket route is listed separately.'),row('Cable-jacket route before percentage allowance',fmt(cut)+' m'),row('Individual-conductor takeoff before allowance',fmt(total)+' m'),row('Length per conductor per route',fmt(route)+' m')];}};
 if(slug==='gear-ratio-speed-calculator')return{labels:['Calculation mode','Engine rotational speed','Road speed','Transmission gear ratio','Final-drive ratio','Effective rolling tyre diameter'],suffix:['select:speed=Speed from RPM|rpm=RPM from speed','rpm','mph','ratio','ratio','in'],calculate:()=>{if(!['speed','rpm'].includes(a)||!valid(d,.000001,100)||!valid(e,.000001,100)||!valid(f,.001,1000)||(a==='speed'?!valid(b,0,1e6):!valid(c,0,10000)))return bad('Select a mode, use positive ratios/diameter and a non-negative active RPM or speed.');const factor=Math.PI*F*60/(D*E*63360),speed=a==='speed'?B*factor:C,rpm=a==='rpm'?C/factor:B;return[row(a==='speed'?'Modeled vehicle speed':'Modeled engine RPM',a==='speed'?fmt(speed)+' mph':fmt(rpm)+' rpm','Rigid gearing and supplied rolling circumference; no tyre slip, converter slip, redline limit or safe-speed prediction. Independent of TREMEC.'),row('Vehicle speed in km/h',fmt(speed*1.609344)+' km/h'),row('Combined reduction ratio',fmt(D*E)),row('Wheel rotational speed',fmt(rpm/(D*E))+' rpm')];}};
 if(slug==='christmas-tree-light-calculator')return{labels:['Tree height','Your chosen decorative light density','Lights on one product strand','Existing usable light count'],suffix:['ft','lights per ft of height','whole lights','whole lights'],calculate:()=>{if(!valid(a,.001,100)||!valid(b,.001,10000)||!whole(c,1,100000)||!whole(d))return bad('Use positive height/density, a positive whole strand count and non-negative whole existing lights.');const target=Math.ceil(A*B),needed=Math.max(0,target-D),strands=Math.ceil(needed/C);return[row('Additional light strands for supplied density',fmt(strands)+' strands','Aesthetic count worksheet only; no universal lights-per-foot rule, electrical load or permitted connection count.'),row('Scenario target lights',fmt(target)+' lights'),row('Additional lights before whole-strand rounding',fmt(needed)+' lights'),row('Available lights after purchase',fmt(D+strands*C)+' lights')];}};
 if(slug==='ops-calculator')return{labels:['Official at-bats','Hits','Walks','Hit by pitch','Sacrifice flies','Doubles','Triples','Home runs'],suffix:['whole AB','whole H','whole BB','whole HBP','whole SF','whole 2B','whole 3B','whole HR'],calculate:()=>{if(!whole(a,1,1e9)||[b,c,d,e,f,g,h].some(s=>!whole(s))||B>A||F+G+H>B)return bad('Use positive whole at-bats, non-negative whole tallies, hits no greater than AB and extra-base hits no greater than hits.');const obp=(B+C+D)/(A+C+D+E),tb=B+F+2*G+3*H,slg=tb/A;return[row('On-base plus slugging',fmt(obp+slg)+' OPS','Unadjusted MLB-style supplied-count arithmetic; not OPS+, park-adjusted value, projection or live player data.'),row('On-base percentage as decimal',fmt(obp)),row('Slugging percentage as decimal',fmt(slg)),row('Total bases from hits',fmt(tb)),row('Singles',fmt(B-F-G-H))];}};
 if(slug==='binomial-distribution-calculator')return{labels:['Independent trials','Success probability per trial','Success count of interest'],suffix:['whole n; 0–500','decimal p; 0–1','whole k; 0–n'],calculate:()=>{if(!whole(a,0,500)||!valid(b,0,1)||!whole(c,0,A))return bad('Supply whole n from 0–500, decimal probability 0–1 and whole k from 0–n.');const r=binomialProbabilities(A,B,C);return[row('Probability of exactly k successes',fmt(r.exact*100)+' %','Independent identical Bernoulli trials only; decimal inputs, not percentages. Very small displayed probabilities may round to zero.'),row('Probability of at most k successes',fmt(r.below*100)+' %'),row('Probability of at least k successes',fmt(r.above*100)+' %'),row('Expected successes',fmt(A*B)),row('Standard deviation',fmt(Math.sqrt(A*B*(1-B))))];}};
 if(slug==='octagon-calculator')return{labels:['Side length of regular octagon','Unused','Unused'],suffix:['length units','',''],calculate:()=>{if(!valid(a,.000001,1e9))return bad('Supply a positive side length of a regular octagon.');const across=A*(1+Math.SQRT2),apothem=across/2;return[row('Regular octagon area',fmt(2*(1+Math.SQRT2)*A*A)+' square units','Equal sides and equal angles; not an irregular eight-sided parcel or construction cutting plan.'),row('Perimeter',fmt(8*A)+' length units'),row('Distance across opposite parallel sides',fmt(across)+' length units'),row('Apothem',fmt(apothem)+' length units'),row('Distance across opposite vertices',fmt(A/Math.sin(Math.PI/8))+' length units')];}};
 if(slug==='winrate-calculator')return{labels:['Recorded wins','Recorded losses','Recorded draws','Draw handling','Target win rate'],suffix:['whole wins','whole losses','whole draws','select:include=Include draws in denominator|exclude=Exclude draws','%'],calculate:()=>{if([a,b,c].some(s=>!whole(s))||!['include','exclude'].includes(d)||!valid(e,0,100))return bad('Use non-negative whole outcome counts, a supported draw convention and target 0–100%.');const played=A+B+(d==='include'?C:0);if(!played)return bad('The selected denominator must contain at least one match.');const rate=A/played*100,need=E===100?(A===played?'0':'Impossible with existing non-wins'):fmt(Math.max(0,Math.ceil((E/100*played-A)/(1-E/100))));return[row('Recorded win rate',fmt(rate)+' %','Descriptive win count / chosen match denominator. Draws are not half-wins; no probability model or future performance forecast.'),row('Matches in selected denominator',fmt(played)),row('Additional consecutive wins for target',need),row('Draw count supplied',fmt(C))];}};
 return null;
};
