import type {CalculatorResolver,CalculatorResult} from './types';
import {njTax2025} from '../../lib/nj-tax-2025';
const r=(label:string,value:string,note?:string):CalculatorResult=>({label,value,note});
const bad=(message:string)=>[r('Check inputs',message)];
const valid=(s:string,min=0,max=1e12)=>s.trim()!==''&&Number.isFinite(Number(s))&&Number(s)>=min&&Number(s)<=max;
const f=(x:number,p=6)=>x.toLocaleString('en-US',{maximumFractionDigits:p});
export function basicExpression(source:string):number{
 if(/(?:\d|\.)\s+(?:\d|\.)/.test(source))throw Error('Do not separate digits within a number with spaces.');
 const text=source.replace(/[×]/g,'*').replace(/[÷]/g,'/').replace(/[−]/g,'-').replace(/\s/g,'');
 if(!text||text.length>500||!/^[\d.+*/()%\-]+$/.test(text))throw Error('Use decimal numbers, + − × ÷, percent and parentheses only; no commas, letters or exponent notation.');
 const tokens=text.match(/(?:\d+(?:\.\d*)?|\.\d+)|[+*/()%\-]/g)||[];
 if(tokens.join('')!==text||tokens.length>200)throw Error('Use a valid expression with at most 200 tokens.');
 let index=0,depth=0;const check=(v:number)=>{if(!Number.isFinite(v)||Math.abs(v)>1e15)throw Error('The result is non-finite or exceeds ±10¹⁵.');return v;};
 const atom=():number=>{if(++depth>40)throw Error('Limit nested signs and parentheses to 40 levels.');let value:number;const token=tokens[index++];if(token==='+'||token==='-')value=(token==='-'?-1:1)*atom();else if(token==='('){value=sum();if(tokens[index++]!==')')throw Error('Close each parenthesis.');}else if(token&&/^(?:\d+(?:\.\d*)?|\.\d+)$/.test(token))value=Number(token);else throw Error('A number or parenthesized expression is required.');while(tokens[index]==='%'){index++;value/=100;}depth--;return check(value);};
 const product=():number=>{let v=atom();while(['*','/'].includes(tokens[index])){const op=tokens[index++],b=atom();if(op==='/'&&b===0)throw Error('Division by zero is undefined.');v=check(op==='*'?v*b:v/b);}return v;};
 const sum=():number=>{let v=product();while(['+','-'].includes(tokens[index])){const op=tokens[index++],b=product();v=check(op==='+'?v+b:v-b);}return v;};
 const value=sum();if(index!==tokens.length)throw Error('Check operators and unmatched parentheses. Implicit multiplication is not supported.');return value;
}
export const resolveRoadmap206:CalculatorResolver=({slug,a,b,c,d,e,f:extraF='0',g='0',h='roof',cash})=>{
 const A=Number(a),B=Number(b),C=Number(c),D=Number(d),E=Number(e),F=Number(extraF),G=Number(g);
 if(slug==='gc-content-calculator')return{labels:['DNA or RNA sequence (one FASTA record allowed)','Sequence alphabet','GC denominator'],suffix:['text','select:dna=DNA: A C G T N|rna=RNA: A C G U N','select:known=Known bases only (exclude N)|all=All positions (N unresolved lower bound)'],calculate:()=>{
 if(a.length>200000||!['dna','rna'].includes(b)||!['known','all'].includes(c))return bad('Choose DNA/RNA and a denominator; limit pasted text to 200,000 characters.');const lines=a.trim().split(/\r?\n/),headers=lines.filter(s=>s.startsWith('>'));if(headers.length>1||headers.length===1&&!lines[0].startsWith('>'))return bad('Use one plain sequence or one FASTA record with the header first.');const sequence=lines.filter(s=>!s.startsWith('>')).join('').replace(/\s/g,'').toUpperCase();if(!sequence||sequence.length>100000||!(b==='dna'?/^[ACGTN]+$/:/^[ACGUN]+$/).test(sequence))return bad('Supply 1–100,000 bases in the selected alphabet; only N is supported as an unresolved base.');const counts={A:0,C:0,G:0,T:0,U:0,N:0};for(const base of sequence)counts[base as keyof typeof counts]++;const known=sequence.length-counts.N,denom=c==='known'?known:sequence.length,gc=counts.G+counts.C;return[r(c==='known'?'GC content among known bases':'Resolved G+C fraction of all positions',denom?f(100*gc/denom)+' %':'Undefined: no known bases','N is never guessed as a G, C, A, T or U. All-position mode is a lower bound, not an inferred full-sequence GC percentage.'),r('Sequence positions',String(sequence.length)),r('Known bases / unresolved N',known+' / '+counts.N),r('Base counts',Object.entries(counts).map(([key,n])=>key+': '+n).join(', ')),r('GC skew',gc?f((counts.G-counts.C)/gc):'Undefined: no G or C')];
 }};
 if(slug==='llc-tax-calculator')return{labels:['Annual net profit on supplied basis','Your supplied profit-allocation share','Combined effective reserve rate supplied by adviser','Other known tax/fee amount in this scenario','Payments already allocated to this same scenario'],suffix:['currency','%','%','currency','currency'],calculate:()=>{
 if(!valid(a)||!valid(b,0,100)||!valid(c,0,100)||!valid(d)||!valid(e))return bad('Use non-negative amounts and allocation/reserve percentages from 0–100.');const allocated=A*B/100,tax=allocated*C/100+D,remaining=tax-E;return[r('Remaining scenario reserve',cash(Math.max(0,remaining)),'User-rate cash-reserve arithmetic only, not actual federal/state LLC tax, a classification election or an estimated-payment safe-harbor check.'),r('Allocated profit',cash(allocated)),r('Modeled tax/fee reserve before payments',cash(tax)),r('Payments exceeding modeled reserve',cash(Math.max(0,-remaining))),r('Profit after modeled reserve',cash(allocated-tax))];
 }};
 if(slug==='wainscoting-calculator')return{labels:['Wall run length','Margin at each end outside end stiles','Width of each vertical stile','Number of equal clear panels'],suffix:['in','in','in','whole panels'],calculate:()=>{
 if(!valid(a,1,100000)||!valid(b,0,10000)||!valid(c,1e-6,1000)||!valid(d,1,100)||!Number.isInteger(D))return bad('Use positive wall/stile dimensions, non-negative equal end margins and 1–100 whole panels.');const clear=(A-2*B-(D+1)*C)/D;if(clear<=0)return bad('Margins and stiles leave no positive clear panel width.');return[r('Equal clear panel width',f(clear)+' in','Layout assumes N clear panels, N+1 vertical stiles and equal margins outside the end stiles; no door/window or cut-length design.'),r('Vertical stile count',String(D+1)),r('First panel begins at',f(B+C)+' in from left wall edge'),r('Panel/stile repeat distance',f(clear+C)+' in'),r('Total clear-panel width',f(D*clear)+' in')];
 }};
 if(slug==='charles-law-calculator'){
 const unused:Record<string,number>={v1:0,t1:1,v2:2,t2:3},labels=['Initial volume V₁','Initial absolute temperature T₁','Final volume V₂','Final absolute temperature T₂'];if(Object.hasOwn(unused,e))labels[unused[e]]='Unused';
 return{labels:[...labels,'Solve for'],suffix:['volume units','K','same volume units','K','select:v2=Final volume V₂|v1=Initial volume V₁|t2=Final temperature T₂|t1=Initial temperature T₁'],calculate:()=>{
 if(!Object.hasOwn(unused,e)||[a,b,c,d].some((s,i)=>i!==unused[e]&&!valid(s,1e-12,1e12)))return bad('Supply three positive known values with both temperatures in Kelvin and compatible volumes.');const value=e==='v2'?A*D/B:e==='v1'?C*B/D:e==='t2'?C*B/A:A*D/C;if(!Number.isFinite(value)||value<=0)return bad('The supplied values produce an unsupported result.');return[r('Solved '+e.toUpperCase(),f(value)+(e[0]==='t'?' K':' volume units'),'Ideal gas with fixed amount and constant pressure. Celsius must be converted by adding 273.15 before entry.'),r('Charles law relation','V₁ / T₁ = V₂ / T₂')];
 }};}
 if(slug==='crypto-conversion-calculator')return{labels:[e==='units'?'Quote-currency budget':'Token quantity','Your supplied price per token','Explicit proportional fee','Quote currency label','Conversion direction'],suffix:['number','quote currency/token','%','text','select:value=Token quantity to quote value|units=Quote budget to token quantity'],calculate:()=>{
 if(!valid(a)||!valid(b,1e-15,1e12)||!valid(c,0,99.999)||d.trim().length<1||d.length>40||!['value','units'].includes(e))return bad('Use non-negative quantity/budget, positive supplied price, a fee below 100%, a short currency label and a conversion direction.');const fee=C/100;if(e==='value'){const gross=A*B;return[r('Quote value after supplied fee',f(gross*(1-fee),10)+' '+d.trim(),'Manual quote only: no live OVO price, verified token identity, executable exchange order, spread, network fee or tax is inferred.'),r('Gross quote value',f(gross,10)+' '+d.trim()),r('Supplied proportional fee amount',f(gross*fee,10)+' '+d.trim())];}const net=A*(1-fee);return[r('Tokens from net supplied budget',f(net/B,10)+' tokens','Fee is deducted from the budget before dividing by the supplied unit price; exchange fee conventions may differ.'),r('Budget after proportional fee',f(net,10)+' '+d.trim()),r('Fee amount',f(A-net,10)+' '+d.trim())];
 }};
 if(slug==='basic-calculator')return{labels:['Arithmetic expression','Unused','Unused'],suffix:['text','',''],calculate:()=>{try{return[r('Arithmetic result',f(basicExpression(a),12),'Standard operator precedence with binary floating-point arithmetic. Percent means divide the preceding number/expression by 100; it is not a commercial add-percent key.')];}catch(error){return bad(error instanceof Error?error.message:'Invalid expression.');}}};
 if(slug==='roof-area-calculator'){
 const pitch=h==='pitch';return{labels:pitch?['Measured vertical rise','Measured horizontal run','Unused','Unused','Unused','Unused','Unused','Mode']:['Horizontal plan length incl. overhang','Horizontal plan width incl. overhang','Pitch rise per 12 horizontal units','Material waste allowance','Supplier package coverage (0 to omit packages)','Supplied unit cost per planned roof ft² (0 to omit cost)','Other project cost on same quotation basis','Mode'],suffix:pitch?['same length units','same length units','','','','','','select:roof=Roof area, packages and cost|pitch=Pitch from measured rise/run']:['ft','ft','rise / 12','%','ft²/package','currency/ft²','currency','select:roof=Roof area, packages and cost|pitch=Pitch from measured rise/run'],calculate:()=>{
 if(!['roof','pitch'].includes(h))return bad('Choose roof estimate or pitch mode.');if(pitch){if(!valid(a,0,1e6)||!valid(b,1e-9,1e6))return bad('Use non-negative rise and positive horizontal run in matching units.');return[r('Roof pitch rise per 12 run',f(12*A/B)+' / 12'),r('Pitch angle',f(Math.atan(A/B)*180/Math.PI)+' degrees'),r('Slope multiplier',f(Math.hypot(1,A/B)))];}
 if(!valid(a,1e-9,1e5)||!valid(b,1e-9,1e5)||!valid(c,0,60)||!valid(d,0,100)||!valid(e,0,1e6)||!valid(extraF,0,1e9)||!valid(g,0,1e12))return bad('Use positive plan dimensions, 0–60 rise/12, 0–100% waste and non-negative supplied coverage/prices.');const multiplier=Math.hypot(1,C/12),area=A*B*multiplier,planned=area*(1+D/100);return[r('Sloped roof area',f(area)+' ft²','Uniform-pitch rectangular footprint including overhang. Complex roofs need separate plane takeoffs; this is not structural or roof-access guidance.'),r('Coverage with waste',f(planned)+' ft²'),r('Roofing squares before waste',f(area/100)),r('Slope multiplier',f(multiplier,4)),r('Whole supplier packages',E===0?'No package coverage supplied':f(Math.ceil(planned/E),0)),r('Supplied-basis project cost',F===0?'No unit price supplied':cash(planned*F+G),'Unit rate applies to planned area including waste. Use either a complete installed rate or a material-only rate with clearly separate additional charges; no market prices are loaded.')];
 }};}
 if(slug==='linear-feet-calculator')return{labels:d==='area'?['Area to cover','Actual uniform material width','Unused','Mode']:['Feet per piece','Inches per piece','Number of pieces','Mode'],suffix:d==='area'?['ft²','in','','select:pieces=Sum piece lengths|area=Square feet to linear feet']:['ft','in','whole pieces','select:pieces=Sum piece lengths|area=Square feet to linear feet'],calculate:()=>{
 if(!['pieces','area'].includes(d))return bad('Choose a length calculation mode.');if(d==='area'){if(!valid(a,1e-9)||!valid(b,1e-9,1200))return bad('Use positive square feet and actual material width in inches.');return[r('Required linear feet',f(A/(B/12))+' ft','Area divided by uniform coverage width; no overlap, waste or installed-width adjustment is assumed.'),r('Coverage width in feet',f(B/12)+' ft'),r('Check: length × width',f(A)+' ft²')];}
 if(!valid(a)||!valid(b)||!valid(c,1,1e6)||!Number.isInteger(C)||A+B/12<=0)return bad('Use non-negative piece dimensions, positive total piece length and a whole positive quantity.');const one=A+B/12,total=one*C;return[r('Total linear feet',f(total,2)+' ft','Inches are converted to feet before multiplying.'),r('Total inches',f(total*12,2)+' in'),r('Length per piece',f(one,3)+' ft')];
 }};
 if(slug==='bank-simple-interest-days')return{labels:['Principal','Supplied annual simple rate','Accrual days','Explicit annual day-count denominator'],suffix:['currency','%','whole days','select:365=365 days|360=360 days|366=366 days'],calculate:()=>{
 if(!valid(a)||!valid(b,0,100)||!valid(c,0,100000)||!Number.isInteger(C)||!['360','365','366'].includes(d))return bad('Supply non-negative principal, rate 0–100%, whole days and an explicit 360/365/366 denominator.');const interest=A*B/100*C/D;return[r('Simple interest on supplied convention',cash(interest),'Fixed annual denominator with supplied actual accrual-day count; no date schedule, 30/360 algorithm, compounding or bank policy is inferred.'),r('Principal plus simple interest',cash(A+interest)),r('Year fraction',f(C/D))];
 }};
 if(slug==='study-assessment-weighted-total')return{labels:['Assessment percentages, comma separated','Matching weights, comma separated','Unused'],suffix:['text','text',''],calculate:()=>{
 const scores=a.split(',').map(s=>s.trim()),weights=b.split(',').map(s=>s.trim());if(!scores.length||scores.length>20||scores.length!==weights.length||scores.some(s=>!valid(s,0,100))||weights.some(s=>!valid(s,0,100)))return bad('Supply 1–20 matched score/weight pairs between 0 and 100, with positive total weight.');const total=weights.reduce((s,x)=>s+Number(x),0);if(total<=0)return bad('At least one weight must be positive.');const result=scores.reduce((s,x,i)=>s+Number(x)*Number(weights[i]),0)/total;return[r('Weighted assessment percentage',f(result)+' %','Normalizes your supplied weights. This is not a VCAA study score, moderated result, cohort percentile or scaled ATAR contribution.'),r('Total supplied weight',f(total))];
 }};
 if(slug==='new-jersey-tax-calculator')return{labels:['2025 NJ taxable income (line 42)','2025 NJ gross income (line 29)','2025 filing status','Known credits on the applicable basis','Payments/withholding on this same basis'],suffix:['USD','USD','select:single=Single|separate=Married/CU separate|joint=Married/CU joint|head=Head of household|surviving=Qualifying surviving spouse/CU partner','USD','USD'],calculate:()=>{
 if(!valid(a,0,1e9)||!valid(b,0,1e9)||A>B||!['single','separate','joint','head','surviving'].includes(c)||!valid(d,0,1e9)||!valid(e,0,1e9))return bad('Use non-negative 2025 NJ income/credits/payments, taxable income no higher than gross, and a supported full-year resident filing status.');const calculated=njTax2025(A,B,c),after=Math.max(0,calculated.tax-D),difference=after-E;return[r('2025 NJ income tax before supplied credits',f(calculated.tax,2)+' USD',calculated.method+' Full-year resident arithmetic only; no deduction preparation, refundable-credit eligibility, local/federal payroll tax or filing decision is inferred.'),r('After supplied credit amount',f(after,2)+' USD'),r('Balance before omitted return items',f(difference,2)+' USD','Negative means payments exceed this limited modeled tax; it is not a guaranteed refund.'),r('Marginal schedule rate',f(calculated.rate*100)+' %')];
 }};
 return null;
};
