import type {CalculatorResolver,CalculatorResult} from './types';
const f=(n:number,d=4)=>n.toLocaleString('en-US',{maximumFractionDigits:d});
const r=(label:string,value:string,note?:string):CalculatorResult=>({label,value,note});
const bad=(note:string)=>[r('Check your inputs','Unable to calculate',note)];
const valid=(...v:string[])=>v.every(x=>x.trim()!==''&&Number.isFinite(Number(x))&&Number(x)>=0&&Number(x)<=1e12);
const polyMul=(a:number[],b:number[])=>{const v=Array(a.length+b.length-1).fill(0);a.forEach((x,i)=>b.forEach((y,j)=>v[i+j]+=x*y));return v as number[]};
const trim=(a:number[])=>{while(a.length>1&&Math.abs(a.at(-1)!)<1e-10)a.pop();return a};
const divide=(p:number[],q:number[])=>{const rem=[...p],quot=Array(Math.max(1,p.length-q.length+1)).fill(0);for(let i=p.length-q.length;i>=0;i--){const k=rem[i+q.length-1]/q.at(-1)!;quot[i]=k;q.forEach((x,j)=>rem[i+j]-=k*x)}return{quot:trim(quot),rem:trim(rem)}};
const polyText=(p:number[])=>p.map((v,i)=>Math.abs(v)<1e-9?'':`${f(v,8)}${i?`x${i>1?'^'+i:''}`:''}`).filter(Boolean).reverse().join(' + ').replaceAll('+ -','− ')||'0';
type Term={k:number;x:number;y:number};
export function parsePolynomial(input:string):Term[]|null{
 if(input.length>1000)return null;const sides=input.replaceAll(' ','').split('=');if(sides.length>2)return null;const result:Term[]=[];
 for(let side=0;side<sides.length;side++){
 const text=sides[side];if(!text||/[^0-9xy.*^+\-]/.test(text))return null;
 const parts=text.match(/[+-]?[^+-]+/g);if(!parts||parts.join('')!==text)return null;
 for(const part of parts){if(part.endsWith('*'))return null;const m=part.match(/^([+-]?)(?:(\d+(?:\.\d*)?|\.\d+))?(.*)$/);if(!m)return null;
 let k=(m[1]==='-'?-1:1)*(m[2]?Number(m[2]):1)*(side===1?-1:1),rest=m[3],x=0,y=0;
 if(!rest&&!m[2])return null;if(rest.startsWith('*')){if(!m[2])return null;rest=rest.slice(1);}
 while(rest){const t=rest.match(/^([xy])(?:\^(\d+))?/);if(!t)return null;const exp=t[2]?Number(t[2]):1;if(exp>12)return null;if(t[1]==='x')x+=exp;else y+=exp;rest=rest.slice(t[0].length);if(rest.startsWith('*'))rest=rest.slice(1);if(!rest&&part.endsWith('*'))return null;}
 if(x+y>12||!Number.isFinite(k)||Math.abs(k)>1e12)return null;result.push({k,x,y});
 }}return result;
}
const termText=(terms:Term[])=>terms.filter(t=>t.k!==0).map(t=>`${f(t.k,8)}${t.x?'*x'+(t.x>1?'^'+t.x:''):''}${t.y?'*y'+(t.y>1?'^'+t.y:''):''}`).join(' + ').replaceAll('+ -','− ')||'0';
export const resolveRoadmap126:CalculatorResolver=({slug,a,b,c,d,e,cash})=>{
const A=Number(a),B=Number(b),C=Number(c),D=Number(d),E=Number(e);
if(slug==='calories-burned-calculator')return{labels:['Body weight','Activity minutes or steps','Activity','Duration input',d==='steps'?'Measured walking cadence':c==='custom'?'Custom activity MET':'Unused'],suffix:['kg','minutes or steps','select:walk=Walking 2.8–3.4 mph, level|brisk=Walking 3.5–3.9 mph, level|bike=Cycling under 10 mph, leisure|run=Running 5.0–5.2 mph|treadmill=Treadmill walking 3.0–3.4 mph, 0% grade|backpack=Backpacking, Compendium 17010 (7.0 MET)|daypack=Level city walking with daypack, 17011 (3.5 MET)|hikepack=Organized daypack hiking, 17012 (7.8 MET)|custom=Custom MET activity','select:minutes=Minutes|steps=Steps (walking only)','MET or steps/min'],calculate:()=>{
if(!valid(a,b)||A<=0||B<0)return bad('Enter positive kg and non-negative duration.');const preset:Record<string,number>={walk:3.8,brisk:4.8,bike:4,run:8.5,treadmill:3.8,backpack:7,daypack:3.5,hikepack:7.8};const met=c==='custom'?E:preset[c];if(!Number.isFinite(met)||met<=0||met>30)return bad('Custom MET must be above zero and at most 30.');if(d==='steps'&&(!['walk','brisk','treadmill'].includes(c)||!valid(e)||E<=0||E>300))return bad('Step mode supports walking only and requires your measured cadence, above 0 and at most 300 steps/min.');const minutes=d==='steps'?B/E:B,kcal=met*3.5*A/200*minutes;return[r('Estimated gross activity energy',f(kcal,2)+' kcal','MET estimate includes resting energy during this period; not a weight-loss prediction or measured individual expenditure.'),r('Estimated net above 1 MET',f(Math.max(0,met-1)*3.5*A/200*minutes,2)+' kcal'),r('MET used',f(met)),r('Duration used',f(minutes,2)+' min')];}};
if(slug==='pine-straw-calculator')return{labels:['Bed length','Bed width','Supplier coverage per bale at desired depth','Waste allowance'],suffix:['ft','ft','ft²/bale','%'],calculate:()=>!valid(a,b,c,d)||A<=0||B<=0||C<=0?bad('Use positive dimensions and the supplier’s stated coverage at your intended depth.'): [r('Whole pine straw bales',f(Math.ceil(A*B*(100+D)/100/C),0),'Coverage is user supplied; bale size, depth and settling differ.'),r('Bed area',f(A*B)+' ft²'),r('Coverage including allowance',f(A*B*(100+D)/100)+' ft²'),r('Unrounded bale requirement',f(A*B*(100+D)/100/C))]};
if(slug==='running-pace-calculator')return{labels:['Race distance','Target total time','Distance unit',e==='splits'?'Split interval':'Unused','Mode'],suffix:['distance','minutes','select:km=Kilometres|mi=Miles','same distance unit','select:pace=Average pace|splits=Even race splits'],calculate:()=>{
if(!valid(a,b)||A<=0||B<=0||e==='splits'&&(!valid(d)||D<=0||Math.ceil(A/D)>200))return bad('Use positive distance, time and interval; maximum 200 splits.');const pace=B/A;if(e!=='splits'){const sec=Math.round(pace*60);return[r('Average pace',`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')} per ${c}`,'Average pace; choose Even race splits to generate cumulative checkpoints.'),r('Average speed',f(A/(B/60),2)+(c==='mi'?' mph':' km/h')),r('Total time',f(B)+' min')]}const rows=[];for(let dist=D;dist<A;dist+=D)rows.push(`${f(dist)} ${c}: ${f(dist*pace,2)} min`);rows.push(`${f(A)} ${c}: ${f(B,2)} min (finish)`);return[r('Cumulative even-pace splits',rows.join(' · '),'Cumulative minutes from the start. Final partial split is included; no fatigue or terrain model.'),r('Average split time',f(pace*D,2)+' min for a full interval'),r('Average pace',f(pace,4)+' min/'+c)];}};
if(slug==='ohms-law-calculator')return{labels:['Known values',a==='ir'?'Known current':a==='code'?'Nominal resistance':'Known voltage',a==='code'?'Unused':a==='vi'?'Known current':'Known resistance',a==='code'?'Color-code tolerance':'Unused'],suffix:['select:vi=Voltage and current|vr=Voltage and resistance|ir=Current and resistance|code=Resistance to four-band color code',a==='ir'?'A':a==='code'?'Ω':'V',a==='vi'?'A':'Ω','select:gold=Gold ±5%|silver=Silver ±10%|brown=Brown ±1%|red=Red ±2%'],calculate:()=>{
if(!valid(b)||B<=0)return bad('Use positive finite values.');if(a==='code'){let exp=Math.floor(Math.log10(B))-1;const sig=B/10**exp;const colors=['black','brown','red','orange','yellow','green','blue','violet','gray','white'];if(exp< -2||exp>9||Math.abs(sig-Math.round(sig))>1e-7)return bad('Four-band code requires two significant digits and a multiplier from 0.01 to 1e9; use five-band specifications for other values.');const digits=Math.round(sig),mult=exp===-2?'silver':exp===-1?'gold':colors[exp];return[r('Four-band resistor colors',`${colors[Math.floor(digits/10)]} · ${colors[digits%10]} · ${mult} · ${d}`,'Nominal code only. Verify tolerance, power rating and component datasheet.'),r('Nominal resistance',f(B)+' Ω')];}
if(!valid(c)||C<=0)return bad('Both selected electrical values must be positive.');const V=a==='ir'?B*C:B,I=a==='vi'?C:a==='vr'?B/C:B,R=a==='vi'?B/C:C;return[r('Resistance',f(R,6)+' Ω','Ideal resistive DC relationship. Not AC impedance, mains wiring or equipment-safety design.'),r('Voltage',f(V,6)+' V'),r('Current',f(I,6)+' A'),r('Dissipated power',f(V*I,6)+' W')];}};
if(slug==='fence-post-depth-calculator')return{labels:['Post height above ground','Embedment fraction','Local required depth below grade','Gravel layer'],suffix:['ft','select:third=One third of above-ground height|half=One half of above-ground height','in','in'],calculate:()=>!valid(a,c,d)||A<=0?bad('Enter positive exposed height and non-negative local depth and gravel thickness.'): [r('Planning post embedment',f(Math.max(A*12/(b==='half'?2:3),C),2)+' in','Geometric planning guideline; local frost/code, wind, soil and gate loads may require a different design.'),r('Excavation depth with gravel',f(Math.max(A*12/(b==='half'?2:3),C)+D,2)+' in'),r('Post length before cutting allowance',f(A+Math.max(A*12/(b==='half'?2:3),C)/12,3)+' ft')]};
if(slug==='lead-time-calculator')return{labels:['Order processing','Production','Transit','Receiving and inspection'],suffix:['calendar days','calendar days','calendar days','calendar days'],calculate:()=>!valid(a,b,c,d)?bad('Use non-negative calendar-day stages.'): [r('Sequential lead time',f(A+B+C+D)+' calendar days','Adds sequential stages. Parallel stages, business calendars and variability require a different model.'),r('Before dispatch',f(A+B)+' days'),r('After production',f(C+D)+' days')]};
if(slug==='recessed-light-calculator')return{labels:['Room length','Room width','Fixture lumens','Target average illuminance','Combined utilization and maintenance factor'],suffix:['m','m','lm','lux','0–1'],calculate:()=>!valid(a,b,c,d,e)||A<=0||B<=0||C<=0||D<=0||E<=0||E>1?bad('Use positive dimensions, lumens and target lux with a factor above 0 and at most 1.'): [r('Estimated recessed-light count',f(Math.ceil(A*B*D/(C*E)),0),'Lumen-method planning estimate, not a photometric layout or electrical installation design.'),r('Room area',f(A*B)+' m²'),r('Required initial lumens',f(A*B*D/E)+' lm'),r('Average achieved illuminance',f(Math.ceil(A*B*D/(C*E))*C*E/(A*B))+' lux')]};
if(slug==='partial-fraction-calculator')return{labels:['Numerator coefficients (descending powers)','Denominator real roots (repeat for multiplicity)','Unused'],suffix:['text','text',''],calculate:()=>{
const list=(s:string)=>s.split(/[,\s]+/).filter(Boolean).map(Number);const num=list(a).reverse(),roots=list(b);if(!num.length||num.length>9||!roots.length||roots.length>6||[...num,...roots].some(x=>!Number.isFinite(x)||Math.abs(x)>1e6))return bad('Use up to 9 finite numerator coefficients and 1–6 real roots, all within ±1,000,000. Denominator leading coefficient is assumed 1.');
const denominator=roots.reduce((p,x)=>polyMul(p,[-x,1]),[1]),{quot,rem}=divide(trim(num),denominator),terms:{root:number;power:number;basis:number[]}[]=[];
for(const root of [...new Set(roots)])for(let power=1;power<=roots.filter(x=>x===root).length;power++){let removed=0;const remain=roots.filter(x=>{if(x===root&&removed<power){removed++;return false}return true});terms.push({root,power,basis:remain.reduce((p,x)=>polyMul(p,[-x,1]),[1])})}
const n=terms.length,m=Array.from({length:n},(_,i)=>[...terms.map(t=>t.basis[i]||0),rem[i]||0]);for(let i=0;i<n;i++){let pivot=i;for(let j=i+1;j<n;j++)if(Math.abs(m[j][i])>Math.abs(m[pivot][i]))pivot=j;[m[i],m[pivot]]=[m[pivot],m[i]];if(Math.abs(m[i][i])<1e-12)return bad('Root combination is numerically ill-conditioned; choose better-separated or smaller roots.');const v=m[i][i];for(let k=i;k<=n;k++)m[i][k]/=v;for(let j=0;j<n;j++)if(j!==i){const z=m[j][i];for(let k=i;k<=n;k++)m[j][k]-=z*m[i][k]}}
const answer=terms.map((t,i)=>`${f(m[i][n],8)}/(x ${t.root>=0?'−':'+'} ${f(Math.abs(t.root))})${t.power>1?'^'+t.power:''}`).join(' + ').replaceAll('+ -','− ');return[r('Partial-fraction decomposition',(polyText(quot)!=='0'?polyText(quot)+' + ':'')+answer,'Real linear factors only; decimal coefficients are rounded. Original denominator roots remain excluded.'),r('Expanded denominator',polyText(denominator)),r('Polynomial quotient',polyText(quot)),r('Excluded x values',[...new Set(roots)].map(x=>f(x)).join(', '))];}};
if(slug==='implicit-differentiation-calculator')return{labels:['Polynomial equation in x and y','Point x','Point y'],suffix:['text','x','y'],calculate:()=>{
const p=parsePolynomial(a);if(!p||!Number.isFinite(B)||!Number.isFinite(C)||!b.trim()||!c.trim()||Math.abs(B)>1e6||Math.abs(C)>1e6)return bad('Use a polynomial such as x^2+y^2=25 and finite point coordinates. No functions, parentheses, division or negative powers.');const dx=p.map(t=>({k:t.k*t.x,x:Math.max(0,t.x-1),y:t.y})),dy=p.map(t=>({k:t.k*t.y,x:t.x,y:Math.max(0,t.y-1)}));const ev=(t:Term[])=>t.reduce((s,v)=>s+v.k*B**v.x*C**v.y,0),fx=ev(dx),fy=ev(dy),res=ev(p),scale=Math.max(1,...p.map(t=>Math.abs(t.k*B**t.x*C**t.y)));return[r('Implicit derivative',`dy/dx = −(${termText(dx)}) / (${termText(dy)})`,'Valid where F_y is nonzero. Symbolic polynomial differentiation; point evaluation does not solve for y.'),r('Curve residual F(x,y)',f(res,8)),r('Slope at supplied point',Math.abs(res)>1e-8*scale?'Point is not on the entered curve':Math.abs(fy)<1e-12?'F_y = 0: derivative formula undefined':f(-fx/fy,8)),r('Partials at point',`F_x = ${f(fx,8)}; F_y = ${f(fy,8)}`)];}};
if(slug==='greek-gematria-calculator')return{labels:['Greek text','Unused','Unused'],suffix:['text','',''],calculate:()=>{
if(a.length>5000)return bad('Use at most 5,000 characters.');const map:Record<string,number>={α:1,β:2,γ:3,δ:4,ε:5,ϛ:6,ϝ:6,ζ:7,η:8,θ:9,ι:10,κ:20,λ:30,μ:40,ν:50,ξ:60,ο:70,π:80,ϟ:90,ϙ:90,ρ:100,σ:200,ς:200,τ:300,υ:400,φ:500,χ:600,ψ:700,ω:800,ϡ:900};const text=a.normalize('NFD').replace(/\p{M}/gu,'').toLowerCase(),letters=[...text].filter(x=>map[x]!==undefined),unsupported=[...text].filter(x=>map[x]===undefined&&!/[\s.,;:!?·'"\-()]/.test(x));if(!letters.length||unsupported.length)return bad('Enter Greek letters and ordinary spacing/punctuation only; no Latin transliteration, digits or numeral-sign syntax.');return[r('Greek isopsephy total',f(letters.reduce((s,l)=>s+map[l],0),0),'Letter values are added; accents and case are normalized. This is not Hebrew or English gematria, and it makes no predictive claim.'),r('Letter breakdown',letters.map(l=>`${l}=${map[l]}`).join(' · ')),r('Counted letters',f(letters.length,0))];}};
if(slug==='time-off-calculator')return{labels:['Current PTO balance','Accrual per pay period','Future pay periods','Planned leave','Policy balance cap (0 = none)'],suffix:['hours','hours/period','whole periods','hours','hours'],calculate:()=>{
if(!valid(a,b,c,d,e)||!Number.isInteger(C))return bad('Use non-negative hours and a whole-number pay-period count.');const before=A+B*C,capped=E>0?Math.min(before,E):before,balance=capped-D;return[r('Projected PTO after planned leave',f(balance)+' hours','Simplified cap-at-projection model. Earned eligibility, carryover, expiry, timing of leave and employer approval are not determined.'),r('Projected balance before leave',f(capped)+' hours'),r('Accrual before cap',f(B*C)+' hours'),r('Hours short of planned leave',f(Math.max(0,-balance))+' hours')];}};
if(slug==='interest-rate-calculator'&&d==='simple')return{labels:['Principal','Annual simple-interest rate','Term in years','Calculation mode','Unused'],suffix:['currency','%','years','select:solve=Solve implied rate|project=Project savings|cd=CD nominal rate|fd=FD nominal rate|apy=Deposit quoted APY|simple=Simple interest',''],calculate:()=>!valid(a,b,c)||A<=0?bad('Use positive principal and non-negative rate and years.'): [r('Simple-interest ending amount',cash(A*(1+B*C/100)),'Simple interest on the original principal only; no compounding, tax, fees or cash flows.'),r('Interest earned',cash(A*B*C/100)),r('Original principal',cash(A))]};
if(slug==='decimals-calculator')return{labels:['First decimal','Second decimal','Operation','Decimal places (0–30)'],suffix:['text','text','select:add=Add|subtract=Subtract|multiply=Multiply|divide=Divide','digits'],calculate:()=>{
const parse=(s:string)=>{if(s.length>150||!/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s.trim()))return null;const t=s.trim(),digits=(t.split('.')[1]||'').length;return{n:BigInt(t.replace('.','').replace(/^\+/,'')),d:BigInt(10)**BigInt(digits)}};
const x=parse(a),y=parse(b);if(!x||!y||!valid(d)||!Number.isInteger(D)||D>30)return bad('Enter plain finite decimals, each at most 150 characters, and 0–30 output places. Scientific notation is not supported.');let n=BigInt(0),den=BigInt(1);if(c==='add'){n=x.n*y.d+y.n*x.d;den=x.d*y.d}else if(c==='subtract'){n=x.n*y.d-y.n*x.d;den=x.d*y.d}else if(c==='multiply'){n=x.n*y.n;den=x.d*y.d}else{if(y.n===BigInt(0))return bad('Cannot divide by zero.');n=x.n*y.d;den=x.d*y.n}if(den<0){n=-n;den=-den}const gcd=(a:bigint,b:bigint):bigint=>b===BigInt(0)?a:gcd(b,a%b),g=gcd(n<BigInt(0)?-n:n,den);n/=g;den/=g;const abs=n<BigInt(0)?-n:n,scale=BigInt(10)**BigInt(D),q=abs*scale/den,rem=abs*scale%den,rounded=q+(rem*BigInt(2)>=den?BigInt(1):BigInt(0));let t=rounded.toString().padStart(D+1,'0');if(D)t=(t.slice(0,-D)+'.'+t.slice(-D)).replace(/0+$/,'').replace(/\.$/,'');if(n<BigInt(0)&&rounded!==BigInt(0))t='−'+t;return[r('Decimal result',t,rem===BigInt(0)?'Exact at the displayed precision.':'Rounded half away from zero to the selected decimal places.'),r('Exact reduced fraction',`${n}/${den}`),r('Operation',c)];}};
return null;
};
