import type { CalculatorResolver,CalculatorResult } from "./types";
import { numberValue as n } from "./helpers";
const fmt=(x:number,d=2)=>Number.isFinite(x)?x.toLocaleString("en-US",{maximumFractionDigits:d}):"—";
const pct=(x:number)=>`${fmt(x,2)}%`;
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a);
const fractionValue=(input:string):[number,number]|null=>{const mixed=input.trim().match(/^(-?\d+)\s+(\d+)\/(\d+)$/),simple=input.trim().match(/^(-?\d+)\/(\d+)$/),whole=input.trim().match(/^(-?\d+)$/);if(mixed){const sign=Number(mixed[1])<0?-1:1,den=Number(mixed[3]);return den?[sign*(Math.abs(Number(mixed[1]))*den+Number(mixed[2])),den]:null}if(simple){const den=Number(simple[2]);return den?[Number(simple[1]),den]:null}return whole?[Number(whole[1]),1]:null};
const formulaMasses:Record<string,number>={H:1.008,He:4.0026,Li:6.94,Be:9.0122,B:10.81,C:12.011,N:14.007,O:15.999,F:18.998403163,Ne:20.1797,Na:22.98976928,Mg:24.305,Al:26.9815385,Si:28.085,P:30.973761998,S:32.06,Cl:35.45,Ar:39.948,K:39.0983,Ca:40.078,Sc:44.955908,Ti:47.867,V:50.9415,Cr:51.9961,Mn:54.938044,Fe:55.845,Co:58.933194,Ni:58.6934,Cu:63.546,Zn:65.38,Ga:69.723,Ge:72.63,As:74.921595,Se:78.971,Br:79.904,Kr:83.798,Rb:85.4678,Sr:87.62,Y:88.90584,Zr:91.222,Nb:92.90637,Mo:95.95,Ru:101.07,Rh:102.9055,Pd:106.42,Ag:107.8682,Cd:112.414,In:114.818,Sn:118.71,Sb:121.76,Te:127.6,I:126.90447,Xe:131.293,Cs:132.90545196,Ba:137.327,La:138.90547,Ce:140.116,Pr:140.90766,Nd:144.242,Sm:150.36,Eu:151.964,Gd:157.25,Tb:158.92535,Dy:162.5,Ho:164.93033,Er:167.259,Tm:168.93422,Yb:173.045,Lu:174.9668,Hf:178.49,Ta:180.94788,W:183.84,Re:186.207,Os:190.23,Ir:192.217,Pt:195.084,Au:196.966569,Hg:200.592,Tl:204.38,Pb:207.2,Bi:208.9804,Th:232.0377,Pa:231.03588,U:238.02891};
type MolecularBreakdown={total:number;counts:Record<string,number>};
const molecularBreakdown=(raw:string):MolecularBreakdown|null=>{
  if(raw.length>4096)return null;
  const formula=raw.trim().replace(/[₀-₉]/g,d=>String("₀₁₂₃₄₅₆₇₈₉".indexOf(d))).replace(/\s+/g,"").replace(/[·•]/g,".");
  if(!formula||/[^A-Za-z0-9().]/.test(formula))return null;
  const parts=formula.split(".");
  const totals:Record<string,number>={};
  const add=(symbol:string,count:number)=>{totals[symbol]=(totals[symbol]||0)+count};
  const parsePart=(part:string):Record<string,number>|null=>{
    const lead=part.match(/^(\d+)(?=[A-Z(])/);
    const multiplier=lead?Number(lead[1]):1;
    const body=lead?part.slice(lead[1].length):part;
    const tokens=body.match(/[A-Z][a-z]?|\d+|[()]/g);
    if(!tokens||tokens.join("")!==body||!Number.isSafeInteger(multiplier)||multiplier<1)return null;
    let index=0;
    const group=(nested=false,depth=0):Record<string,number>|null=>{
      if(depth>32)return null;
      const counts:Record<string,number>={}; let found=false;
      const merge=(source:Record<string,number>,m=1)=>Object.entries(source).forEach(([k,v])=>counts[k]=(counts[k]||0)+v*m);
      while(index<tokens.length&&tokens[index]!==")"){
        if(tokens[index]==="("){
          index++; const inner=group(true,depth+1); if(!inner)return null;
          const m=/^\d+$/.test(tokens[index]||"")?Number(tokens[index++]):1;
          if(!Number.isSafeInteger(m)||m<1)return null; merge(inner,m); found=true; continue;
        }
        const symbol=tokens[index++]; if(formulaMasses[symbol]===undefined)return null;
        const count=/^\d+$/.test(tokens[index]||"")?Number(tokens[index++]):1;
        if(!Number.isSafeInteger(count)||count<1)return null;
        counts[symbol]=(counts[symbol]||0)+count; found=true;
      }
      if(nested){if(tokens[index]!==")")return null;index++}
      return found&&Object.values(counts).every(Number.isSafeInteger)?counts:null;
    };
    const counts=group(); if(!counts||index!==tokens.length)return null;
    Object.keys(counts).forEach(k=>counts[k]*=multiplier); return Object.values(counts).every(Number.isSafeInteger)?counts:null;
  };
  for(const part of parts){if(!part)return null;const counts=parsePart(part);if(!counts)return null;Object.entries(counts).forEach(([k,v])=>add(k,v))}
  const total=Object.entries(totals).reduce((sum,[el,count])=>sum+formulaMasses[el]*count,0);
  return Object.values(totals).every(Number.isSafeInteger)&&Number.isFinite(total)&&total>0?{total,counts:totals}:null;
};
const bowlingScore=(input:string):{score:number;frames:number}|null=>{const tokens=input.trim().toUpperCase().split(/[\s,;]+/).filter(Boolean);let i=0;const rolls:number[]=[],frames:number[][]=[];const pin=(t:string)=>t==="X"?10:t==="-"?0:/^\d+$/.test(t)?Number(t):NaN;for(let frame=0;frame<10;frame++){const firstToken=tokens[i++];if(!firstToken)return null;const first=pin(firstToken);if(!Number.isInteger(first)||first<0||first>10)return null;const current=[first];if(frame<9&&first===10){rolls.push(10);frames.push(current);continue}const secondToken=tokens[i++];if(!secondToken)return null;const second=secondToken==="/"?(first===10?NaN:10-first):pin(secondToken);if(!Number.isInteger(second)||second<0||second>10||(frame<9&&first+second>10))return null;current.push(second);if(frame===9&&(first===10||first+second===10)){const thirdToken=tokens[i++];if(!thirdToken)return null;const third=thirdToken==="/"?(second===10?NaN:10-second):pin(thirdToken);if(!Number.isInteger(third)||third<0||third>10||(first===10&&second<10&&second+third>10))return null;current.push(third)}else if(frame===9&&i<tokens.length)return null;rolls.push(...current);frames.push(current)}if(i!==tokens.length)return null;let total=0,index=0;for(let frame=0;frame<9;frame++){const first=rolls[index];if(first===10){const next=rolls[index+1],after=rolls[index+2];if(next===undefined||after===undefined)return null;total+=10+next+after;index++}else{const second=rolls[index+1];if(second===undefined)return null;if(first+second===10){const bonus=rolls[index+2];if(bonus===undefined)return null;total+=10+bonus}else total+=first+second;index+=2}}total+=frames[9].reduce((sum,x)=>sum+x,0);return{score:total,frames:frames.length}};
const dt=(s:string)=>new Date(`${s}T12:00:00Z`);
const dateText=(x:Date)=>Number.isNaN(x.getTime())?"Enter a valid date":x.toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric",timeZone:"UTC"});
const cfg=(labels:string[],suffix:string[],calculate:()=>CalculatorResult[])=>({labels,suffix,calculate});
export const resolveSemrushPhaseOneB:CalculatorResolver=({slug,a,b,c,d,e,cash})=>{
if(slug==="gpa-calculator")return cfg(["Grade points per course (comma-separated)","Credits per course (comma-separated)","GPA scale maximum","Unused","Unused"],["text","text","points","",""],()=>{const grades=a.split(/[,;\s]+/).filter(Boolean).map(Number),credits=b.split(/[,;\s]+/).filter(Boolean).map(Number),valid=grades.length>0&&grades.length===credits.length&&grades.every(Number.isFinite)&&credits.every(x=>Number.isFinite(x)&&x>0),sum=credits.reduce((x,y)=>x+y,0),g=valid?grades.reduce((x,y,i)=>x+y*credits[i],0)/sum:NaN;return[{label:"Credit-weighted GPA",value:valid?fmt(g,3):"Match each grade point with a positive credit value",note:"Use your school’s grade-point scale"},{label:"Total credits",value:valid?fmt(sum):"—"},{label:"Percent of selected scale",value:valid&&n(c)>0?pct(g/n(c)*100):"Enter a scale maximum"}]});
if(slug==="square-footage-calculator")return cfg(["Length","Width","Number of areas","Coverage per pack (optional)","Waste allowance"],["ft","ft","areas","ft²","%"],()=>{const one=n(a)*n(b),total=one*Math.max(1,n(c)),waste=Math.max(0,n(e))/100,order=total*(1+waste),packs=n(d)>0?Math.ceil(order/n(d)):0;return[{label:"Total floor area",value:`${fmt(total)} ft²`,note:"Rectangular area before waste"},{label:"Area with allowance",value:`${fmt(order)} ft²`},{label:"Packs required",value:n(d)>0?String(packs):"Enter pack coverage"}]});
if(slug==="bench-press-max-calculator")return cfg(["Weight lifted","Repetitions","Lift: bench press, squat, or deadlift"],["weight","reps","select:bench press=Bench press|squat=Squat|deadlift=Deadlift"],()=>{const est=n(a)*(1+n(b)/30),lift=String(c||"bench press");return[{label:`Estimated ${lift} one-rep max`,value:n(a)>0&&n(b)>0?fmt(est):"Enter a positive lifted weight and rep count",note:"Epley estimate; not a tested maximum"},{label:"90% training estimate",value:n(a)>0&&n(b)>0?fmt(est*.9):"—"},{label:"80% training estimate",value:n(a)>0&&n(b)>0?fmt(est*.8):"—"}]});
if(slug==="triangle-calculator")return cfg(["Side A","Side B","Side C or included angle (degrees)","Mode: SSS or SAS"],["units","units","units or °","text"],()=>{const A=n(a),B=n(b),mode=String(d).trim().toUpperCase();if(mode==="SAS"){const angle=n(c)*Math.PI/180,area=A>0&&B>0&&angle>0&&angle<Math.PI?.5*A*B*Math.sin(angle):NaN,C=Math.sqrt(A*A+B*B-2*A*B*Math.cos(angle));return[{label:"Triangle area",value:Number.isFinite(area)?fmt(area):"Enter two positive sides and an angle from 0° to 180°",note:"Area = ½ab sin(C)"},{label:"Third side",value:Number.isFinite(C)?fmt(C):"—"},{label:"Perimeter",value:Number.isFinite(C)?fmt(A+B+C):"—"}]}const C=n(c),s=(A+B+C)/2,valid=A>0&&B>0&&C>0&&A+B>C&&A+C>B&&B+C>A,area=valid?Math.sqrt(s*(s-A)*(s-B)*(s-C)):NaN;return[{label:"Triangle area",value:valid?fmt(area):"Check positive sides and triangle inequality",note:"Heron's formula"},{label:"Perimeter",value:valid?fmt(A+B+C):"—"},{label:"Semiperimeter",value:valid?fmt(s):"—"}]});
if(slug==="molecular-weight-calculator")return cfg(["Chemical formula","Unused","Unused"],["text","",""],()=>{const result=molecularBreakdown(a);if(!result)return[{label:"Molecular weight",value:"Enter a valid formula such as H2O, Ca(OH)2, or CuSO4·5H2O",note:"Formula symbols are case-sensitive; supported syntax includes integer subscripts, parentheses, and hydrate dots."},{label:"Formula entered",value:a||"—"},{label:"Method",value:"Sum of atomic weight × atom count"}];const rows:CalculatorResult[]=[{label:"Molar mass",value:`${fmt(result.total,4)} g/mol`,note:"Numerically equal to average molecular mass in Da for one molecule"},{label:"Molecular mass",value:`${fmt(result.total,4)} Da`,note:"Average mass based on standard atomic weights"},{label:"Formula entered",value:a.trim()}];Object.entries(result.counts).forEach(([el,count])=>{const contribution=formulaMasses[el]*count;rows.push({label:`${el} × ${count}`,value:`${fmt(contribution,4)} g/mol`,note:`Atomic weight ${fmt(formulaMasses[el],6)} · ${fmt(contribution/result.total*100,2)}% by mass`})});rows.push({label:"Calculation check",value:`${fmt(result.total,4)} g/mol`,note:"Sum of the element mass contributions shown above"});return rows});
if(slug==="bowling-score-calculator")return cfg(["Rolls in order (X strike, / spare, - miss)","Unused","Unused"],["text","",""],()=>{const result=bowlingScore(a);return[{label:"Ten-pin game score",value:result?fmt(result.score,0):"Enter a valid complete 10-frame roll sequence",note:"Strike and spare bonuses are included"},{label:"Frames scored",value:result?String(result.frames):"—"},{label:"Roll sequence",value:a||"—"}]});
if(slug==="air-force-pt-test-calculator"||slug==="air-force-pt-calculator")return cfg(["Cardiorespiratory points","Waist-to-height ratio points","Muscle strength points","Core endurance points"],["points","points","points","points"],()=>{const cardio=n(a),whtR=n(b),strength=n(c),core=n(d),values=[cardio,whtR,strength,core],max=[50,20,15,15],valid=values.every((value,i)=>Number.isFinite(value)&&value>=0&&value<=max[i]),total=values.reduce((x,y)=>x+y,0);return[{label:"Entered assessment total",value:valid?fmt(total):"Check points against each category maximum",note:"Enter points from the current official chart; no pass decision is made"},{label:"Cardiorespiratory",value:`${fmt(cardio)} / 50`},{label:"WHtR + muscular components",value:valid?`${fmt(whtR+strength+core)} / 50`:"—"}]});
if(slug==="square-root-calculator")return cfg(["Number","Unused","Unused"],["","",""],()=>{const root=Math.sqrt(n(a));return[{label:"Principal square root",value:fmt(root,8),note:"For a non-negative real number"},{label:"Original number",value:fmt(n(a),8)},{label:"Square check",value:fmt(root*root,8)}]});
if(slug==="fraction-calculator")return cfg(["Fraction or mixed number A","Fraction or mixed number B","Operation (+, −, ×, ÷)","Unused","Unused"],["text","text","text","",""],()=>{const left=fractionValue(a),right=fractionValue(b),op=String(c).trim(),A=left?.[0]||0,B=left?.[1]||1,C=right?.[0]||0,D=right?.[1]||1;let top=0,bot=1;if(!left||!right||!(["+","-","−","*","×","/","÷"].includes(op))||((op==="/"||op==="÷")&&C===0))return[{label:"Fraction result",value:"Enter valid fractions and a supported operation"}];if(op==="-"||op==="−"){top=A*D-C*B;bot=B*D}else if(op==="*"||op==="×"){top=A*C;bot=B*D}else if(op==="/"||op==="÷"){top=A*D;bot=B*C}else{top=A*D+C*B;bot=B*D}const g=gcd(Math.round(Math.abs(top)),Math.round(Math.abs(bot)))||1;return[{label:"Fraction result",value:`${Math.round(top/g)}/${Math.round(bot/g)}`,note:"Reduced exact result for integer inputs"},{label:"Decimal result",value:fmt(top/bot,8)},{label:"Operation",value:op}]});
if(slug==="how-many-years-calculator")return cfg(["Start date","End date","Unused"],["date","date",""],()=>{const x=dt(a),y=dt(b),days=Math.abs(y.getTime()-x.getTime())/86400000,years=days/365.2425;return[{label:"Elapsed years",value:fmt(years,4),note:"Decimal years using average Gregorian year"},{label:"Elapsed days",value:fmt(days,0)},{label:"Approximate months",value:fmt(years*12,2)}]});
if(slug==="cylinder-volume-calculator")return cfg(["Radius or diameter","Height","Input mode: radius or diameter"],["units","units","text"],()=>{const r=String(c).trim().toLowerCase().startsWith("diam")?n(a)/2:n(a),h=n(b),v=Math.PI*r*r*h,sa=2*Math.PI*r*(r+h);return[{label:"Cylinder volume",value:r>0&&h>0?fmt(v):"Enter positive radius/diameter and height",note:"Cubic units"},{label:"Surface area",value:fmt(sa)},{label:"Base area",value:fmt(Math.PI*r*r)}]});
if(slug==="date-calculator")return cfg(["Start date","Days to add/subtract","Direction (1 add, 0 subtract)"],["date","days","1 / 0"],()=>{const out=dt(a),days=Math.round(n(b))*(n(c)>=1?1:-1);out.setUTCDate(out.getUTCDate()+days);return[{label:"Result date",value:dateText(out),note:"Calendar-day arithmetic"},{label:"Offset",value:`${Math.abs(days)} days`},{label:"Direction",value:days>=0?"Added":"Subtracted"}]});
if(slug==="hourly-wage-and-tax-calculator")return cfg(["Hourly wage","Hours worked","Tax/deduction rate"],["currency","hours","%"],()=>{const gross=n(a)*n(b),tax=gross*n(c)/100;return[{label:"Estimated net pay",value:cash(gross-tax),note:"User-entered deduction rate"},{label:"Gross pay",value:cash(gross)},{label:"Estimated deductions",value:cash(tax)}]});
if(slug==="asphalt-calculator")return cfg(["Area","Depth","Density"],["ft²","in","lb/ft³"],()=>{const ft=n(a)*n(b)/12,lb=ft*n(c);return[{label:"Approximate asphalt tonnage",value:`${fmt(lb/2000)} US tons`,note:"Use supplier density for ordering"},{label:"Volume",value:`${fmt(ft/27)} yd³`},{label:"With 5% allowance",value:`${fmt(lb/2000*1.05)} US tons`}]});
if(slug==="ap-biology-score-calculator"||slug==="ap-chemistry-score-calculator")return cfg(["Multiple-choice score","Multiple-choice total","Free-response %"],["points","points","%"],()=>{const mc=n(b)?n(a)/n(b)*100:0,composite=mc*.5+n(c)*.5;return[{label:"Practice composite estimate",value:pct(composite),note:"Not an official 1–5 score conversion"},{label:"Multiple-choice %",value:pct(mc)},{label:"Free-response %",value:pct(n(c))}]});
if(slug==="womens-bmi-calculator")return cfg(["Weight","Height","Unused"],["kg","cm",""],()=>{const h=n(b)/100,bmi=h?n(a)/(h*h):0;return[{label:"BMI",value:fmt(bmi,1),note:"Adult screening measure; not a diagnosis"},{label:"Weight",value:`${fmt(n(a),1)} kg`},{label:"Height",value:`${fmt(n(b),1)} cm`}]});
if(slug==="concrete-calculator")return cfg(["Length or tube diameter or block length","Width or block width","Thickness or tube height or block height","Mode: slab, sonotube, or block","Price per yd³ or block count,weight per block"],["ft for slab/tube; in for block","ft for slab; in for block","in for slab; ft tube; in block","text","text"],()=>{const mode=String(d).trim().toLowerCase(),block=mode.startsWith("block"),tube=mode.startsWith("sono"),extras=String(e).split(/[,;]/).map(Number),count=Math.max(1,Math.floor(extras[0]||1)),unitWeight=extras.length>1&&Number.isFinite(extras[1])?extras[1]:null,ft=block?n(a)*n(b)*n(c)/1728:tube?Math.PI*Math.pow(n(a)/2,2)*n(c):n(a)*n(b)*n(c)/12,yd=ft/27;if(!Number.isFinite(ft)||ft<=0)return[{label:"Concrete volume",value:"Enter positive dimensions and choose slab, sonotube, or block"}];return[{label:block?"Total block volume":"Concrete volume",value:`${fmt(yd*(block?count:1))} yd³`,note:block?`Volume for ${count} block(s); excludes voids and mortar`:tube?"Cylinder: π × radius² × height":"Rectangular slab estimate"},{label:"Cubic feet",value:fmt(ft*(block?count:1))},{label:block?"Block weight estimate":n(e)>0?"Estimated material cost":"With 10% allowance",value:block?unitWeight!==null?`${fmt(unitWeight*count)} lb from entered unit weight`:`${fmt(ft*150*count)} lb solid-concrete equivalent; hollow block weight varies`:n(e)>0?`${fmt(yd*Number(e))} in the entered currency`: `${fmt(yd*1.1)} yd³`}]});
if(slug==="npv-calculator")return cfg(["Initial investment","Cash flow per period","Discount rate","Periods"],["currency","currency","%","periods"],()=>{let pv=0;for(let i=1;i<=Math.min(600,Math.round(n(d)));i++)pv+=n(b)/Math.pow(1+n(c)/100,i);return[{label:"Net present value",value:cash(pv-n(a)),note:"Equal recurring cash-flow assumption"},{label:"Present value of inflows",value:cash(pv)},{label:"Initial investment",value:cash(n(a))}]});
if(slug==="weeks-calculator")return cfg(["Duration value","Input unit: days or weeks","Convert to: weeks, days, or months"],["number","text","text"],()=>{const input=String(b).trim().toLowerCase(),target=String(c).trim().toLowerCase(),value=n(a),days=input.startsWith("week")?value*7:value,months=days/30.436875,weeks=days/7;return[{label:"Converted duration",value:target.startsWith("day")?`${fmt(days,2)} days`:target.startsWith("month")?`${fmt(months,2)} months (average calendar month)`:target.startsWith("week")?`${fmt(weeks,2)} weeks`:"Choose days, weeks, or months",note:"Calendar-month conversion uses the average Gregorian month"},{label:"Weeks and days",value:`${Math.floor(weeks)} weeks, ${Math.round(days%7)} days`},{label:"Days",value:fmt(days,2)}]});
if(slug==="half-birthday-calculator")return cfg(["Birth date","Unused","Unused"],["date","",""],()=>{const x=dt(a),day=x.getUTCDate(),out=new Date(x);out.setUTCDate(1);out.setUTCMonth(out.getUTCMonth()+6);const last=new Date(Date.UTC(out.getUTCFullYear(),out.getUTCMonth()+1,0)).getUTCDate();out.setUTCDate(Math.min(day,last));return[{label:"Half birthday",value:dateText(out),note:"Six calendar months later; month-end dates clamp to the last day"},{label:"Birth date",value:dateText(x)},{label:"Approximate day gap",value:fmt((out.getTime()-x.getTime())/86400000,0)}]});
if(slug==="paycheck-hours-calculator")return cfg(["Regular hours","Hourly rate","Overtime hours","Overtime multiplier"],["hours","currency","hours","×"],()=>{const regular=n(a)*n(b),ot=n(c)*n(b)*(n(d)||1.5);return[{label:"Estimated gross paycheck",value:cash(regular+ot),note:"Before taxes and other deductions"},{label:"Regular pay",value:cash(regular)},{label:"Overtime pay",value:cash(ot)}]});
if(slug==="dog-pregnancy-calculator")return cfg(["Breeding date","Unused","Unused"],["date","",""],()=>{const x=dt(a),center=new Date(x),early=new Date(x),late=new Date(x);center.setUTCDate(center.getUTCDate()+65);early.setUTCDate(early.getUTCDate()+58);late.setUTCDate(late.getUTCDate()+72);return[{label:"Approximate planning date",value:dateText(center),note:"From breeding date; timing varies"},{label:"Possible window from breeding",value:`${dateText(early)} – ${dateText(late)}`},{label:"Breeding date",value:dateText(x)}]});
if(slug==="binary-calculator")return cfg(["Value","Unused","Mode: binary to decimal or decimal to binary"],["text","","text"],()=>{const mode=String(c).trim().toLowerCase();if(mode.startsWith("decimal")){const raw=a.trim(),value=/^-?\d+$/.test(raw)?Number(raw):NaN,valid=Number.isSafeInteger(value);return[{label:"Binary",value:valid?`${value<0?"-":""}${Math.abs(value).toString(2)}`:"Enter a safe whole-number decimal",note:"Integer conversion; negative values use a leading sign, not two's complement"},{label:"Decimal input",value:valid?fmt(value,0):raw||"—"},{label:"Hexadecimal",value:valid?value.toString(16).toUpperCase():"—"}]}const raw=a.trim(),valid=/^[01]+$/.test(raw)&&raw.length<=52,dec=valid?parseInt(raw,2):NaN;return[{label:"Decimal value",value:valid?fmt(dec,0):"Enter 1–52 binary digits (0 or 1)",note:"Invalid characters are rejected"},{label:"Binary",value:valid?raw:"—"},{label:"Hexadecimal",value:valid?dec.toString(16).toUpperCase():"—"}]});
if(slug==="paycheck-estimator-calculator")return cfg(["Hourly rate","Hours worked","Deduction rate"],["currency","hours","%"],()=>{const gross=n(a)*n(b),ded=gross*n(c)/100;return[{label:"Estimated net paycheck",value:cash(gross-ded),note:"Uses your entered deduction percentage"},{label:"Gross paycheck",value:cash(gross)},{label:"Estimated deductions",value:cash(ded)}]});
if(slug==="pool-salt-calculator")return cfg(["Pool volume","Current salt level","Target salt level","Volume unit: litres or US gallons"],["volume","ppm","ppm","text"],()=>{const unit=String(d).trim().toLowerCase(),litres=n(a)*(unit.includes("gal")?3.785411784:1),delta=Math.max(0,n(c)-n(b)),kg=litres*delta/1_000_000;return[{label:"Approximate salt to add",value:`${fmt(kg)} kg`,note:`Assumes ${unit.includes("gal")?"US gallons converted to litres":"litres"} and ppm`},{label:"Concentration increase",value:`${fmt(delta,0)} ppm`},{label:"Approximate pounds",value:`${fmt(kg*2.20462)} lb`}]});
if(slug==="rafter-length-calculator")return cfg(["Horizontal run","Vertical rise","Overhang"],["ft","ft","ft"],()=>{const base=Math.hypot(n(a),n(b)),total=base+(n(a)?n(c)*base/n(a):0);return[{label:"Estimated rafter length",value:`${fmt(total)} ft`,note:"Straight common-rafter geometry"},{label:"Length before overhang",value:`${fmt(base)} ft`},{label:"Roof angle",value:`${fmt(Math.atan2(n(b),n(a))*180/Math.PI)}°`}]});
if(slug==="stair-calculator")return cfg(["Total rise","Target riser height","Tread depth"],["in","in","in"],()=>{const risers=Math.max(1,Math.round(n(a)/(n(b)||7.5))),actual=n(a)/risers,treads=Math.max(1,risers-1),run=treads*n(c);return[{label:"Riser count",value:String(risers),note:"Rounded to create equal risers"},{label:"Actual riser height",value:`${fmt(actual)} in`},{label:"Approximate total run",value:`${fmt(run)} in`}]});
if(slug==="scientific-notation-calculator")return cfg(["Number","Unused","Unused"],["text","",""],()=>{const x=Number(a);if(!Number.isFinite(x)||x===0)return[{label:"Scientific notation",value:x===0?"0 × 10⁰":"Enter a valid number",note:"Coefficient and base-10 exponent"},{label:"Coefficient",value:"0"},{label:"Exponent",value:"0"}];const exp=Math.floor(Math.log10(Math.abs(x))),coef=x/Math.pow(10,exp);return[{label:"Scientific notation",value:`${fmt(coef,10)} × 10^${exp}`,note:"Coefficient between 1 and 10 in magnitude"},{label:"Coefficient",value:fmt(coef,10)},{label:"Exponent",value:String(exp)}]});
if(slug==="money-counter-calculator")return cfg(["Denominations, comma-separated","Counts in matching order","Currency label (optional)"],["text","text","text"],()=>{const ds=a.split(/[,;\s]+/).filter(Boolean).map(Number),cs=b.split(/[,;\s]+/).filter(Boolean).map(Number),valid=ds.length>0&&ds.length===cs.length&&ds.every(x=>Number.isFinite(x)&&x>=0)&&cs.every(x=>Number.isInteger(x)&&x>=0),total=valid?ds.reduce((sum,x,i)=>sum+x*cs[i],0):NaN;return[{label:"Cash total",value:valid?`${String(c||"").trim()} ${fmt(total,2)}`.trim():"Enter matching non-negative denomination and count lists",note:"Counts physical notes and coins; currency conversion is not performed"},{label:"Items counted",value:valid?fmt(cs.reduce((sum,x)=>sum+x,0),0):"—"},{label:"Distinct denominations",value:valid?String(ds.length):"—"}]});
if(slug==="soil-calculator")return cfg(["Bed length","Bed width","Soil depth"],["ft","ft","in"],()=>{const ft3=n(a)*n(b)*n(c)/12;return[{label:"Topsoil volume",value:ft3>0?`${fmt(ft3/27,2)} yd³`:"Enter positive dimensions",note:"Geometric estimate before settling and waste"},{label:"Cubic feet",value:fmt(ft3)},{label:"With 10% allowance",value:`${fmt(ft3/27*1.1)} yd³`}]});
if(slug==="ffmi-calculator")return cfg(["Body weight","Body fat percentage","Height"],["kg","%","cm"],()=>{const h=n(c)/100,ffm=n(a)*(1-n(b)/100),ffmi=h>0?ffm/(h*h):NaN,valid=n(a)>0&&h>0&&n(b)>=0&&n(b)<100;return[{label:"Fat-free mass index (FFMI)",value:valid?fmt(ffmi,2):"Check positive weight and height and body-fat percentage from 0 to under 100",note:"Raw FFMI; no normalization or health category applied"},{label:"Fat-free mass",value:valid?fmt(ffm,2)+" kg":"—"},{label:"Body-fat mass",value:valid?fmt(n(a)*n(b)/100,2)+" kg":"—"}]});
if(slug==="hex-calculator")return cfg(["First integer (hex or decimal)","Second integer (for arithmetic)","Mode"],["text","text","select:hex-to-decimal=Hex to decimal|decimal-to-hex=Decimal to hex|hex-to-binary=Hex to binary|add=Add hex values|subtract=Subtract hex values|multiply=Multiply hex values|divide=Divide hex values"],()=>{const mode=String(c),radix=mode==="decimal-to-hex"?10:16,parse=(v:string)=>{const raw=v.trim(),pattern=radix===10?/^-?\d+$/:/^-?[0-9a-f]+$/i;return pattern.test(raw)?parseInt(raw,radix):NaN},x=parse(a),y=parse(b),valid=Number.isSafeInteger(x)&&(!["add","subtract","multiply","divide"].includes(mode)||Number.isSafeInteger(y)),v=mode==="add"?x+y:mode==="subtract"?x-y:mode==="multiply"?x*y:mode==="divide"?x/y:x,ok=valid&&Number.isSafeInteger(v)&&!(mode==="divide"&&y===0);return[{label:"Result",value:ok?mode==="hex-to-binary"?v.toString(2):mode==="decimal-to-hex"?v.toString(16).toUpperCase():["add","subtract","multiply","divide"].includes(mode)?v.toString(16).toUpperCase():fmt(v,0):"Enter supported whole-number values; division must be exact",note:"Hex digits are 0–9 and A–F; division returns an integer only"},{label:"Decimal value",value:ok?fmt(v,0):"—"},{label:"Binary value",value:ok?Math.abs(v).toString(2):"—"}]});
if(slug==="dunk-calculator")return cfg(["Standing reach","Vertical jump","Basketball rim height"],["in","in","in"],()=>{const reach=n(a),jump=n(b),rim=n(c),at=reach+jump,clear=at-rim,valid=reach>0&&jump>=0&&rim>0;return[{label:"Estimated rim clearance",value:valid?`${fmt(clear,1)} in`:"Enter positive reach and rim height with a non-negative jump",note:clear>=0?"Reach is at or above the entered rim height":"More vertical reach is needed to touch the rim"},{label:"Maximum touch height",value:valid?`${fmt(at/12,2)} ft`:"—"},{label:"Jump height needed to reach rim",value:valid?`${fmt(rim-reach,1)} in`:"—"}]});
if(slug==="mare-gestation-calculator")return cfg(["Breeding date","Unused","Unused"],["date","",""],()=>{const x=dt(a),mid=new Date(x),early=new Date(x),late=new Date(x);mid.setUTCDate(mid.getUTCDate()+340);early.setUTCDate(early.getUTCDate()+320);late.setUTCDate(late.getUTCDate()+360);return[{label:"Estimated foaling midpoint",value:dateText(mid),note:"Approximate planning date; individual gestation varies"},{label:"Broad reference window",value:`${dateText(early)} – ${dateText(late)}`},{label:"Gestation midpoint",value:"340 days after breeding"}]});
if(slug==="linear-feet-calculator")return cfg(["Feet per piece","Inches per piece","Number of pieces"],["ft","in","pieces"],()=>{const qty=Math.max(0,Math.floor(n(c))),one=n(a)+n(b)/12,total=one*qty;return[{label:"Total linear feet",value:one>=0&&qty>0?`${fmt(total,2)} ft`:"Enter a piece length and positive quantity",note:"Inches are converted to feet before multiplying"},{label:"Total inches",value:fmt(total*12,2)+" in"},{label:"Length per piece",value:fmt(one,3)+" ft"}]});
if(slug==="water-intake-calculator")return cfg(["Adult reference group","Daily water from drinks and food (optional)","Unused"],["select:men=Adult men|women=Adult women","L/day",""],()=>{const target=String(a)==="women"?2.7:3.7,intake=n(b),group=String(a)==="women"?"adult women":"adult men",valid=n(b)>=0;return[{label:"Adequate intake reference",value:`${fmt(target,1)} L/day total water`,note:`Population reference for ${group}; includes water in food and all beverages`},{label:"Difference from entered intake",value:n(b)>0&&valid?`${fmt(target-intake,2)} L ${intake<target?"below":"above"} reference`:valid?(target/0.236588).toFixed(1)+" US cups/day":"Enter a non-negative intake"},{label:"In US fluid ounces",value:fmt(target*33.814,1)+" fl oz/day"}]});
if(slug==="steps-to-miles-calculator")return cfg(["Steps or miles","Average step length","Conversion direction"],["text","in/step","select:steps-to-miles=Steps to miles|miles-to-steps=Miles to steps"],()=>{const stride=n(b),mode=String(c),miles=mode==="miles-to-steps"?n(a):n(a)*stride/63360,steps=mode==="miles-to-steps"?(stride>0?n(a)*63360/stride:NaN):n(a);return[{label:mode==="miles-to-steps"?"Estimated steps":"Estimated miles",value:stride>0&&n(a)>=0?(mode==="miles-to-steps"?fmt(steps,0):fmt(miles,2)):"Enter a positive step length and non-negative distance",note:"Personal step length changes the result"},{label:"Step length",value:fmt(stride,1)+" in"},{label:"Distance",value:fmt(miles,2)+" miles"}]});
if(slug==="minecraft-circle-generator")return cfg(["Circle diameter in blocks","Pattern","Unused"],["blocks","select:outline=Outline|filled=Filled",""],()=>{const r=Math.max(1,Math.floor((n(a)-1)/2)),size=2*r+1,filled=String(b)==="filled",rows:string[]=[];for(let y=-r;y<=r;y++){let row="";for(let x=-r;x<=r;x++){const d=x*x+y*y,edge=Math.max(0,r-.75),outer=r+.75;row+=((filled?d<=outer*outer:d<=outer*outer&&d>=edge*edge)?"■":"·")}rows.push(row)}return[{label:"Block pattern (top row first)",value:n(a)>=3&&n(a)<=41&&n(a)%2===1?rows.join(" / "):"Choose an odd diameter from 3 to 41 blocks",note:`${size} × ${size} grid; rows are separated by / from top to bottom`},{label:"Grid width",value:`${size} blocks`},{label:"Pattern",value:filled?"Filled disk":"Outline circle"}]});
if(slug==="density-altitude-calculator")return cfg(["Pressure altitude","Outside-air temperature","Unused"],["ft","°C",""],()=>{const pa=n(a),oat=n(b),isa=15-1.9812*pa/1000,da=pa+120*(oat-isa);return[{label:"Approximate density altitude",value:`${fmt(da,0)} ft`,note:"Rule-of-thumb estimate; use current aviation data and approved flight planning tools"},{label:"ISA temperature at altitude",value:`${fmt(isa,1)} °C`},{label:"Temperature deviation",value:`${fmt(oat-isa,1)} °C`}]});
if(slug==="height-calculator")return cfg(["Father or first parent's height","Mother or second parent's height","Estimate for"],["in","in","select:boy=Boy|girl=Girl"],()=>{const adjustment=String(c)==="girl"?-5:5,mid=(n(a)+n(b)+adjustment)/2,low=mid-2.5,high=mid+2.5;return[{label:"Mid-parental height estimate",value:`${fmt(mid,1)} in (${fmt(mid*2.54,1)} cm)`,note:"Rough family-height estimate, not the Khamis–Roche method"},{label:"Illustrative range",value:`${fmt(low,1)}–${fmt(high,1)} in`},{label:"Formula adjustment",value:`${adjustment>0?"+":""}${adjustment} in before averaging`}]});
if(slug==="weighted-mean-calculator")return cfg(["Values (comma-separated)","Weights (comma-separated)","Unused"],["text","text",""],()=>{const vs=a.split(/[,;\s]+/).filter(Boolean).map(Number),ws=b.split(/[,;\s]+/).filter(Boolean).map(Number),valid=vs.length>0&&vs.length===ws.length&&vs.every(Number.isFinite)&&ws.every(x=>Number.isFinite(x)&&x>=0)&&ws.reduce((s,x)=>s+x,0)>0,den=ws.reduce((s,x)=>s+x,0),mean=valid?vs.reduce((s,x,i)=>s+x*ws[i],0)/den:NaN;return[{label:"Weighted mean",value:valid?fmt(mean,4):"Enter equal-length value and non-negative weight lists with positive total weight",note:"Pairs are matched by their list positions"},{label:"Sum of weights",value:valid?fmt(den,3):"—"},{label:"Number of pairs",value:valid?String(vs.length):"—"}]});
if(slug==="yardage-calculator")return cfg(["Piece length","Piece width","Number of pieces","Usable fabric width","Waste allowance"],["in","in","pieces","in","%"],()=>{const l=n(a),w=n(b),qty=Math.max(0,Math.floor(n(c))),bolt=n(d),waste=Math.max(0,n(e))/100,calc=(across:number,along:number)=>{const acrossPer=Math.floor(bolt/across);return acrossPer>0?Math.ceil(qty/acrossPer)*along/36:Infinity},yards=Math.min(calc(w,l),calc(l,w))*(1+waste);return[{label:"Estimated fabric yardage",value:Number.isFinite(yards)&&qty>0?`${fmt(yards,2)} yd`:"Piece width must fit across the usable fabric width",note:"Single-size repeat layout estimate; seams, nap, pattern matching and selvedge are not included"},{label:"Without waste allowance",value:Number.isFinite(yards)?`${fmt(yards/(1+waste),2)} yd`:"—"},{label:"Cut pieces",value:String(qty)}]});
if(slug==="mean-standard-deviation-calculator")return cfg(["Values (comma-separated)","Standard deviation type","Unused"],["text","select:population=Population|sample=Sample",""],()=>{const xs=a.split(/[,;\s]+/).filter(Boolean).map(Number),valid=xs.length>0&&xs.every(Number.isFinite)&&(String(b)!=="sample"||xs.length>1),mean=valid?xs.reduce((s,x)=>s+x,0)/xs.length:NaN,ss=valid?xs.reduce((s,x)=>s+(x-mean)**2,0):NaN,sd=valid?Math.sqrt(ss/(String(b)==="sample"?xs.length-1:xs.length)):NaN;return[{label:"Mean",value:valid?fmt(mean,4):"Enter numbers; sample SD requires at least two values",note:`${xs.length} value${xs.length===1?"":"s"} supplied`},{label:String(b)==="sample"?"Sample standard deviation":"Population standard deviation",value:valid?fmt(sd,4):"—"},{label:"Count",value:valid?String(xs.length):"—"}]});
if(slug==="visceral-fat-calculator")return cfg(["Sex-specific equation","Waist circumference","Proximal thigh circumference","Age","BMI (women only)"],["select:man=Men|woman=Women","cm","cm","years","kg/m²"],()=>{const female=String(a)==="woman",vat=female?2.15*n(b)-3.63*n(c)+1.46*n(d)+6.22*n(e)-92.713:6*n(b)-4.41*n(c)+1.19*n(d)-213.65,ok=n(b)>0&&n(c)>0&&n(d)>=18&&(!female||n(e)>0);return[{label:"Estimated visceral adipose tissue area",value:ok?`${fmt(vat,1)} cm²`:"Enter adult age and positive waist/thigh measurements" ,note:"Equation estimate; not a scan or diagnosis"},{label:"Equation sex group",value:female?"Women":"Men"},{label:"Model reference",value:"Samouda et al. anthropometric model"}]});
if(slug==="body-fat-calculator")return cfg(["Sex-specific equation","Height","Waist or abdomen","Neck circumference","Hip circumference (women)"],["select:man=Men|woman=Women","in","in","in","in"],()=>{const female=String(a)==="woman",height=n(b),waist=n(c),neck=n(d),hip=n(e),measure=female?waist+hip-neck:waist-neck,valid=height>0&&neck>0&&measure>0&&(!female||hip>0),value=valid?(female?163.205*Math.log10(measure)-97.684*Math.log10(height)-78.387:86.010*Math.log10(measure)-70.041*Math.log10(height)+36.76):NaN;return[{label:"Estimated body fat percentage",value:Number.isFinite(value)?`${fmt(value,1)}%`:"Check height and circumference measurements",note:"Classic U.S. Navy circumference estimate; not an official eligibility result"},{label:"Equation group",value:female?"Women: waist + hip − neck":"Men: abdomen − neck"},{label:"Measurement unit",value:"All entries in inches"}]});
return null;
};
