import { formatPkr as money, numberValue as n } from "./helpers";
import type { CalculatorResolver } from "./types";

export const resolveVehicles: CalculatorResolver = ({ slug, a, b, c, d, cash }) => {
  if(slug==="car-fuel-average-calculator-pakistan")return{labels:["Distance travelled","Fuel consumed","Petrol price"],suffix:["km","litres","PKR/litre"],calculate:()=>{const avg=n(a)/(n(b)||1),cost=n(b)*n(c);return[{label:"Measured fuel average",value:`${avg.toFixed(2)} km/l`,note:"Use a full-tank-to-full-tank measurement for better accuracy"},{label:"Fuel cost for distance",value:money(cost)},{label:"Cost per kilometre",value:money(cost/(n(a)||1))}]}};
  if(slug==="motorcycle-fuel-cost-calculator-pakistan")return{labels:["Daily riding distance","Riding days per month","Bike fuel average","Petrol price"],suffix:["km","days","km/l","PKR/litre"],calculate:()=>{const distance=n(a)*n(b),litres=distance/(n(c)||1),cost=litres*n(d);return[{label:"Estimated monthly fuel cost",value:money(cost),note:`For ${Math.round(distance).toLocaleString("en-PK")} km per month`},{label:"Monthly petrol required",value:`${litres.toFixed(1)} litres`},{label:"Daily fuel cost",value:money(cost/(n(b)||1))}]}};
  if(slug==="petrol-vs-hybrid-savings-calculator-pakistan")return{labels:["Monthly driving distance","Petrol-car average","Hybrid-car average","Petrol price"],suffix:["km","km/l","km/l","PKR/litre"],calculate:()=>{const petrol=n(a)/(n(b)||1)*n(d),hybrid=n(a)/(n(c)||1)*n(d),saving=petrol-hybrid;return[{label:"Estimated monthly hybrid saving",value:money(saving),note:"Fuel-only comparison before purchase and battery costs"},{label:"Petrol-car fuel cost",value:money(petrol)},{label:"Hybrid fuel cost",value:money(hybrid)}]}};
  if(slug==="petrol-vs-electric-bike-savings-calculator-pakistan")return{labels:["Monthly riding distance","Petrol-bike average","Electric-bike consumption","Electricity rate"],suffix:["km","km/l","Wh/km","PKR/unit"],calculate:()=>{const petrol=n(a)/(n(b)||1)*265,electric=n(a)*n(c)/1000*n(d),saving=petrol-electric;return[{label:"Estimated monthly energy saving",value:money(saving),note:"Petrol side uses PKR 265/litre; ownership costs excluded"},{label:"Petrol-bike cost",value:money(petrol)},{label:"Electric charging cost",value:money(electric)}]}};
  if(slug==="car-ownership-cost-calculator-pakistan")return{labels:["Monthly depreciation","Monthly fuel","Maintenance reserve","Insurance, tax and parking"],suffix:["PKR","PKR","PKR","PKR"],calculate:()=>{const total=n(a)+n(b)+n(c)+n(d);return[{label:"Estimated monthly ownership cost",value:money(total),note:"Financing cost and unexpected repairs require separate allowance"},{label:"Estimated annual cost",value:money(total*12)},{label:"Cost excluding depreciation",value:money(n(b)+n(c)+n(d))}]}};
  if(slug==="used-car-depreciation-calculator-pakistan")return{labels:["Current purchase value","Annual depreciation rate","Ownership period"],suffix:["PKR","%","years"],calculate:()=>{const future=n(a)*Math.pow(1-n(b)/100,n(c)),loss=n(a)-future;return[{label:"Projected future value",value:money(future),note:"Actual resale depends on market, condition and mileage"},{label:"Estimated value loss",value:money(loss)},{label:"Value retained",value:`${n(a)?(future/n(a)*100).toFixed(1):0}%`}]}};
  if(slug==="vehicle-installment-affordability-calculator-pakistan")return{labels:["Net monthly household income","Maximum payment ratio","Existing monthly obligations","Financing term"],suffix:["PKR","%","PKR","years"],calculate:()=>{const payment=Math.max(0,n(a)*n(b)/100-n(c)),months=Math.max(1,n(d)*12),rate=.15/12,amount=payment*(1-Math.pow(1+rate,-months))/rate;return[{label:"Affordable monthly installment",value:money(payment),note:"Financing estimate assumes 15% annual rate; lender approval differs"},{label:"Approximate financed amount",value:money(amount)},{label:"Maximum total debt payments",value:money(n(a)*n(b)/100)}]}};
  if(slug==="ride-hailing-earnings-calculator-pakistan")return{labels:["Daily gross fares","Platform commission","Daily fuel cost","Other daily operating cost"],suffix:["PKR","%","PKR","PKR"],calculate:()=>{const commission=n(a)*n(b)/100,net=n(a)-commission-n(c)-n(d);return[{label:"Estimated daily net earnings",value:money(net),note:"Before tax, depreciation and major repairs"},{label:"Estimated monthly net",value:money(net*26)},{label:"Platform commission",value:money(commission)}]}};
  if(slug==="delivery-rider-earnings-calculator-pakistan")return{labels:["Deliveries completed daily","Average earning per delivery","Daily fuel cost","Other daily costs"],suffix:["deliveries","PKR","PKR","PKR"],calculate:()=>{const gross=n(a)*n(b),net=gross-n(c)-n(d);return[{label:"Estimated daily net earnings",value:money(net),note:"Monthly projection uses 26 working days"},{label:"Estimated monthly net",value:money(net*26)},{label:"Daily gross earnings",value:money(gross)}]}};
  if(slug==="motorway-toll-calculator-pakistan")return{labels:["Toll-road distance","Vehicle toll rate","Number of one-way trips"],suffix:["km","PKR/km","trips"],calculate:()=>{const toll=n(a)*n(b)*n(c);return[{label:"Estimated total motorway toll",value:money(toll),note:"Verify current plaza and vehicle-class tariffs"},{label:"Estimated toll per trip",value:money(n(a)*n(b))},{label:"Total toll-road distance",value:`${Math.round(n(a)*n(c)).toLocaleString("en-PK")} km`}]}};
  if(slug==="trip-fuel-sharing-calculator-pakistan")return{labels:["Round-trip distance","Vehicle fuel average","Fuel price","People sharing"],suffix:["km","km/l","PKR/litre","people"],calculate:()=>{const fuel=n(a)/(n(b)||1)*n(c),people=Math.max(1,Math.floor(n(d)));return[{label:"Fuel share per person",value:money(fuel/people),note:"Add tolls and parking separately if applicable"},{label:"Total trip fuel cost",value:money(fuel)},{label:"Estimated fuel required",value:`${(n(a)/(n(b)||1)).toFixed(1)} litres`}]}};
  if(slug==="tyre-size-comparison-calculator")return{labels:["Original tyre width","Original aspect ratio","New tyre width","New aspect ratio"],suffix:["mm","%","mm","%"],calculate:()=>{const rim=15*25.4,original=rim+2*n(a)*n(b)/100,replacement=rim+2*n(c)*n(d)/100,diff=(replacement/original-1)*100;return[{label:"Estimated diameter difference",value:`${diff.toFixed(2)}%`,note:"Comparison assumes both tyres use the same 15-inch rim"},{label:"Original diameter",value:`${original.toFixed(1)} mm`},{label:"Replacement diameter",value:`${replacement.toFixed(1)} mm`}]}};
  if(slug==="tyre-pressure-converter")return{labels:["Pressure in PSI","Unused","Unused"],suffix:["PSI","",""],calculate:()=>{const kpa=n(a)*6.89476;return[{label:"Pressure in bar",value:`${(kpa/100).toFixed(2)} bar`,note:"Use the vehicle placard's cold-tyre specification"},{label:"Pressure in kPa",value:`${kpa.toFixed(1)} kPa`},{label:"Pressure in kgf/cm²",value:`${(n(a)*.070307).toFixed(2)} kgf/cm²`}]}};
  if(slug==="engine-oil-change-reminder-calculator")return{labels:["Mileage at last oil change","Mileage service interval","Distance driven since change","Months since change"],suffix:["km","km","km","months"],calculate:()=>{const next=n(a)+n(b),remaining=Math.max(0,n(b)-n(c)),monthRemaining=Math.max(0,6-n(d)),due=remaining===0||monthRemaining===0;return[{label:due?"Oil change may be due":"Distance remaining",value:due?"Check service now":`${Math.round(remaining).toLocaleString("en-PK")} km`,note:"Uses the earlier of mileage or a six-month planning interval"},{label:"Next mileage target",value:`${Math.round(next).toLocaleString("en-PK")} km`},{label:"Time remaining",value:`${monthRemaining} months`}]}};
  return null;
};
