import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Calculator } from "@/components/Calculator";
import { AdSlot } from "@/components/AdSlot";
import { ToolCard } from "@/components/ToolCard";
import { getTool, tools } from "@/lib/tools";

export function generateStaticParams(){ return tools.map(({slug})=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const tool=getTool(slug);if(!tool)return{};return{title:tool.title,description:tool.description,keywords:tool.keywords,alternates:{canonical:`/pk/tools/${tool.slug}/`},openGraph:{title:tool.title,description:tool.description,url:`/pk/tools/${tool.slug}/`,type:"website"}}}

export default async function ToolPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const tool=getTool(slug);if(!tool)notFound();
  const related=tools.filter(t=>t.slug!==tool.slug).sort((a,b)=>Number(b.category===tool.category)-Number(a.category===tool.category)).slice(0,3);
  const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:tool.title,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",offers:{"@type":"Offer",price:"0",priceCurrency:"PKR"},description:tool.description,url:`https://solvepilot.com/pk/tools/${tool.slug}/`,dateModified:tool.updatedAt},{"@type":"FAQPage",mainEntity:tool.faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://solvepilot.com/"},{"@type":"ListItem",position:2,name:"Tools",item:"https://solvepilot.com/pk/tools/"},{"@type":"ListItem",position:3,name:tool.title}]}]};
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><div className="tool-hero"><div className="shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/pk/tools/">Tools</Link><span>›</span><span>{tool.shortTitle}</span></nav><div className="tool-heading"><span className={`big-tool-icon ${tool.accent}`}>{tool.icon}</span><div><span className="eyebrow">Free {tool.category} tool · Updated {tool.updatedAt}</span><h1>{tool.title}</h1><p>{tool.description}</p></div></div></div></div><article className="shell article-layout"><div className="article-main"><Calculator slug={tool.slug}/><AdSlot slot="0000000001" format="horizontal"/><section className="rich-content"><h2>How this calculator helps</h2><p>{tool.intro}</p><h2>How to use it</h2><ol className="how-to-list">{tool.howTo.map((step,index)=><li key={step}><span>{index+1}</span><p>{step}</p></li>)}</ol><div className="info-panel"><span>ƒ</span><div><h3>Formula and methodology</h3><p>{tool.formula}</p></div></div><h2>Worked calculation example</h2><p>{tool.example}</p><h2>What can affect the result?</h2><div className="consideration-grid">{tool.considerations.map(item=><div key={item.title}><h3>{item.title}</h3><p>{item.text}</p></div>)}</div><h2>Limits of this estimate</h2><p>{tool.limitations}</p><div className="accuracy-note"><b>Important:</b> SolvePilot provides planning estimates, not official invoices, tax assessments, financial advice or professional quotations. Always confirm important decisions with the relevant provider or authority.</div><h2>Frequently asked questions</h2><div className="faq-list">{tool.faqs.map(f=><details key={f.question}><summary>{f.question}<span>＋</span></summary><p>{f.answer}</p></details>)}</div></section></div><aside className="article-aside"><div className="side-card"><b>Why use SolvePilot?</b><span>✓ Free with no signup</span><span>✓ Private browser calculation</span><span>✓ Formula explained</span><span>✓ Mobile friendly</span></div><div className="side-card"><b>Editorial standard</b><span>✓ Unique practical guidance</span><span>✓ Assumptions disclosed</span><span>✓ Limitations explained</span><p>Last reviewed</p><strong>{tool.updatedAt}</strong><small>Report outdated information through our contact page.</small></div></aside></article><section className="shell related"><div className="section-heading"><div><span className="eyebrow">Continue exploring</span><h2>Related tools</h2></div></div><div className="tools-grid three">{related.map(t=><ToolCard key={t.slug} tool={t}/>)}</div></section></>;
}
